### ISSUE TITLE
consider adding

### ISSUE THREAD

**Issue by CITZ-rwk** [iptv-org/epg#1]
https://github.com/weareblahs/epg the Maylasian and astro.xml EPG info

https://raw.githubusercontent.com/DAZoneK/iptv/master/iptvDE.xml    for German channels

**Comment by freearhey** [comment]
Okay, I'll check them later.

**Comment by freearhey** [comment]
Done. The TV guides for Malaysia and Germany have been added to the [list](https://github.com/iptv-org/epg/blob/master/README.md#usage).
