### ISSUE TITLE
Fix: Belgium - telenettv

### ISSUE THREAD

**Issue by PietKonijn** [iptv-org/epg#1002]
### Describe your issue

I am getting a number code at the end of many of the epg program entries e.g. Play Sports 1 has after most program entry titles like “Premier League. S46610000E2022082242”.

**Comment by RevGear** [comment]
Your player is appending the season/episode details on to the program title. Normally this would be something like S03E02 (i.e. season 3, episode 2) but source data from telenettv sometimes has some weird values.

For example, from 2 consecutive programs on the same channel.
```
"mediaType": "Episode",
"year": "2004",
"seriesEpisodeNumber": "18",
"seriesNumber": "3",
```
```
"mediaType": "Episode",
"year": "2014",
"seriesEpisodeNumber": "2014101102",
"seriesNumber": "66040000",
```
First one gives the normal S03E18 format, the second one gives S66040000E2014101102

Seems to happen a lot with sports where they assign an episode number even though the match doesn't follow the season/episode convention.
