### ISSUE TITLE
Could these 3 different "De Pelicula" channels be added to OnTVTonight USA EPG?

### ISSUE THREAD

**Issue by Mikhel** [iptv-org/epg#1003]
### Source

ontvtonight.com

### Notes

Hi, there are three channels that I would like to see if they can be added to this USA EPG:

https://iptv-org.github.io/epg/guides/us/ontvtonight.com.epg.xml

The channels I would like added to it are the following:

De Pelicula USA
https://www.ontvtonight.com/guide/listings/channel/69029250/de-pelicula-eua-usa.html

De Pelicula Clasico
https://www.ontvtonight.com/guide/listings/channel/69024616/de-pelicula-clasico.html

De Pelicula
https://www.ontvtonight.com/guide/listings/channel/69046812/de-pelicula.html

Those three have different programming.

Cheers.

**Comment by Mikhel** [comment]
Oh ok, I'll see if I can learn how to do that, I am not sure I understant, thanks for the response :)

**Comment by nickleby** [comment]
Those three channels are already on the database: De Película Clásico (DePeliculaClasico.mx), De Película EUA (USA) (DePeliculaUS.us), De Película (DePeliculaLatinAmerica.mx). The last one shares the same guide schedule as the LATAM feed.
I can add those channels to the list.

**Comment by Mikhel** [comment]
> Those three channels are already on the database: De Película Clásico (DePeliculaClasico.mx), De Película EUA (USA) (DePeliculaUS.us), De Película (DePeliculaLatinAmerica.mx). The last one shares the same guide schedule as the LATAM feed. I can add those channels to the list.

Thank you Nickleby, much appreciated :)

**Comment by LaneSh4d0w** [comment]
Added via #1029
