### ISSUE TITLE
AccessTV.se is missing in Tv.nu xmltv guide

### ISSUE THREAD

**Issue by Jimpan81** [iptv-org/epg#1006]
### Source

Tv.nu

### Notes

No guide data for
AccessTV.se in Tv.nu xmltv guide

**Comment by PopeyeTheSai10r** [comment]
The channel requested is not part of the Database yet. You can follow [this guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) and submit a pull request to get it added to the database first. Once added contributors will be able to add the EPG for it.

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/54b789b381e96a3a0ea917f37adf008b01b47648
