### ISSUE TITLE
Fix: Digiturk EPG issue for programs over midnight 

### ISSUE THREAD

**Issue by kentherzz** [iptv-org/epg#1009]
### Describe your issue

I stumbled upon an issue with Digiturks EPG for programs long enough to go over midnight. The time gets messed up.
This is how it looks like:
![EPG](https://user-images.githubusercontent.com/40774379/186277455-941c9342-1d18-406f-90f3-5a6591ccc9f4.jpeg)

This is how it looks like in the guide:
<img width="1166" alt="Screenshot" src="https://user-images.githubusercontent.com/40774379/186277527-bd8a90f7-6a8b-47ff-9faa-7e9c3df7a67b.png">

In the TV Guide it looks correct, so it must be something in the code.

I have tried to debug it without success though, hope someone can help. :)

**Comment by kentherzz** [comment]
I think this double entry in the EPG is the issue, and it only occurs for programs which start before midnight and end after midnight.

**Comment by freearhey** [comment]
Fixed via #1033

**Comment by kentherzz** [comment]
@freearhey , thank you. Can you help me to implement such a fix? I am running epggrabber myself with Digiturk config file on this github.

**Comment by freearhey** [comment]
There was no error in the config itself. I just added a filter that removes duplicate programs from the output: https://github.com/iptv-org/epg/blob/master/scripts/commands/guides/update.js#L30

**Comment by kentherzz** [comment]
Thanks a lot for your time!

**Comment by kentherzz** [comment]
> There was no error in the config itself. I just added a filter that removes duplicate programs from the output: https://github.com/iptv-org/epg/blob/master/scripts/commands/guides/update.js#L30

I use digiturk config directly with EPG grabber myself, how can I add this filter to the digiturk directly into the digiturk config? Or should I use update.js together with digiturk config?

**Comment by freearhey** [comment]
I updated epg-grabber and now all repeating entries should be deleted in the process. So you just need to update to the latest version `0.29.2` and everything should be ok.

**Comment by kentherzz** [comment]
Thanks for your time!
