### ISSUE TITLE
Fix: DSmart Connection timeout problem

### ISSUE THREAD

**Issue by mhmtngt** [iptv-org/epg#1012]
### Describe your issue

I'm having some problems with DSmart. It sometimes work and sometimes don't. Generally its giving "Error: Connection timeout" in console. Problem occurs in all of my computers. 

![Screenshot_13](https://user-images.githubusercontent.com/105891651/186467076-e18334a0-b2ce-4c1f-ab82-05232004f57f.png)

The code i'm running is here
`npx epg-grabber --days=7 --config=sites/dsmart.com.tr/dsmart.com.tr.config.js --channels=sites/dsmart.com.tr/dsmart.com.tr_tr.channels.xml --output=dsmart.com.tr.xml`

**Comment by freearhey** [comment]
Try adding the `timeout` argument to the command:

```
npx epg-grabber --days=7 --timeout=30000 --config=sites/dsmart.com.tr/dsmart.com.tr.config.js --channels=sites/dsmart.com.tr/dsmart.com.tr_tr.channels.xml --output=dsmart.com.tr.xml
```

The value should be in milliseconds (30000ms = 30s)

**Comment by mhmtngt** [comment]
It works now, thanks a lot!

**Comment by mhmtngt** [comment]
It works now, thanks a lot!
