### ISSUE TITLE
Is there any chance to add Tivibu

### ISSUE THREAD

**Issue by mhmtngt** [iptv-org/epg#1013]
### Source

https://itveas.tmp.tivibu.com.tr/

### Notes

epg: https://itvepg10008.tmp.tivibu.com.tr/iptvepg/frame3046/sdk_getmultiprevuedata.jsp?begintime=2022.08.24+00:00:00&endtime=2022.08.24+23:59:59&channelcodelist=ch00000000000000001064,ch00000000000000001307,ch00000000000000001221,ch00000000000000001021,ch00000000000000001001,ch00000000000000001092,ch00000000000000001159,ch00000000000000001081,ch00000000000000001360,ch00000000000000001361,ch00000000000000001183,ch00000000000000001260,ch00000000000000001024,ch00000000000000001027,ch00000000000000001156,

channel list: https://itvepg10008.tmp.tivibu.com.tr/iptvepg/frame3046/sdk_getchannellist.jsp?columncode=020000&pageno=1&numperpage=500&ordertype=1&isqueryfavorite=1&isqueryprevue=1&ischecklock=1

Sadly it has geoblock, only accessible in turkey :(

**Comment by freearhey** [comment]
I'm sorry, but we can't add a source that is only available from one country. 

We use GitHub servers located all over the world to download the guides and we simply have no control over which country the request is sent from.
