### ISSUE TITLE
Impossible to download tvtv.us EPG overnight now since the EPG start time was shifted forward by 3 hours

### ISSUE THREAD

**Issue by ian10951** [iptv-org/epg#1020]
### Describe your issue

Since this was done the Grab is not finishing till late morning UK time and as you dont download more than the current day up until midnight of the next day, the EPG is often running out. Its hardly ideal to be downloading the EPG data locally during the day. The only solution is to revert the start time back to what it was or even earlier if possible? or to allow for more days worth of EPG to be grabbed each time the update runs. Perhaps grab 3 days worth instead ? You say this was done to avoid conflicts with the IPTV EPG, so why shift it forwards ? Why cant you shift it backwards to achieve the same result ?

**Comment by freearhey** [comment]
Duplicate #687

**Comment by ian10951** [comment]
You have closed this but what is the solution ?

Your grabbber still doesnt complete the updated download until very late morning UK time and doesnt have enough EPG data to last if its not downloaded locally daily. So from now on all EPG has to be downloaded locally using cron after lunchtime UK time. This stops local EPG being updated overnight or very early morning when most people update their EPG's
