### ISSUE TITLE
UK Sky epg not showing programs for any channels 

### ISSUE THREAD

**Issue by Mkaye147** [iptv-org/epg#1024]
### Describe your issue

Hi, I have been using the "https://iptv-org.github.io/epg/guides/uk/sky.com.epg.xml" epg in TiviMate IPTV player for a couple of months now and it is great.  However today I have noticed it is no longer showing any programs for any channels, instead it just shows "No information".  The channel logos are still showing correctly.

I have tried deleting it as an epg source and adding it again but this didn't resolve it.  I also checked another device running TiviMate with the same epg and it is experiencing the same issue so I am assuming this is an issue with the epg itself.

If this could be investigated it would be much appreciated.

Thanks

**Comment by RevGear** [comment]
Previously the guides were available in two version, 
uncompressed : guidename.epg.xml
compressed : guidename.epg.xml.gz

Some of the uncompressed guides were starting to hit GitHub's file size limit, so it was decided to only publish the compressed version of all guides.

If you update the link you are using to https://iptv-org.github.io/epg/guides/uk/sky.com.epg.xml.gz that will fix it. I think the uncompressed file you were using returns an old file from a couple of days ago so your player wouldn't display anything as there were no current details to display.

@freearhey are you able to delete the old *.xml files.

**Comment by Shifty0wl** [comment]
Everything is down, US Canada UK and Australia epg now loading

**Comment by Mkaye147** [comment]
@RevGear thanks for the information, that resolved the issue.

**Comment by freearhey** [comment]
@RevGear Deleted.
