### ISSUE TITLE
Fix: m.tv.sms.cz EPG showing "No information"

### ISSUE THREAD

**Issue by Dexer125** [iptv-org/epg#1026]
### Describe your issue

Hi, I'm using m.tv.sms.cz EPG on TiviMate and today it started showing "No information" for all channels. In EPG menu it shows successfully updated for 173 channels which is normal. I also checked Actions here on GitHub and build was successful with more than 30 programs for all channels in list. I'm not sure what's the issue.

**Comment by RevGear** [comment]
Previously the guides were available in two version, 
uncompressed : guidename.epg.xml
compressed : guidename.epg.xml.gz

Some of the uncompressed guides were starting to hit GitHub's file size limit, so it was decided to only publish the compressed version of all guides.

If you update the link you are using to https://iptv-org.github.io/epg/guides/cz/m.tv.sms.cz.epg.xml.gz that will fix it. I think the uncompressed file you were using returns an old file from a couple of days ago so your player wouldn't display anything as there were no current details to display.

**Comment by Dexer125** [comment]
Thanks, that helped.
