### ISSUE TITLE
Epg not working

### ISSUE THREAD

**Issue by jorgepreis** [iptv-org/epg#1027]
Hi! Guide not working for any channel I think. I checked all portuguese and Canada sportsnet

**Comment by RevGear** [comment]
Previously the guides were available in two version,
uncompressed : guidename.epg.xml
compressed : guidename.epg.xml.gz

Some of the uncompressed guides were starting to hit GitHub's file size limit, so it was decided to only publish the compressed version of all guides.

Check the URL you are using against what is shown on the homepage. If what you are using doesn't end in .gz it won't work.

**Comment by jorgepreis** [comment]
Oh, I really needed uncompressed version. Ended on xml. Is there any way to keep it?

**Comment by LaneSh4d0w** [comment]
Apart of uncompressing the file and linking it directly to your program, there's nothing much we can do.
