### ISSUE TITLE
Epg not working 

### ISSUE THREAD

**Issue by dcole819** [iptv-org/epg#1028]
Tvtv.us epg not working no information

**Comment by RevGear** [comment]
Previously the guides were available in two version,
uncompressed : guidename.epg.xml
compressed : guidename.epg.xml.gz

Some of the uncompressed guides were starting to hit GitHub's file size limit, so it was decided to only publish the compressed version of all guides.

**Comment by dcole819** [comment]
Thanks man just changed it and it worked thank you
