### ISSUE TITLE
Fix: Tivimate not getting any EPG information

### ISSUE THREAD

**Issue by TertoGordez** [iptv-org/epg#1046]
### Describe your issue

I've used the following guides for a while now in Tivimate app on Nvidia Shield Pro without any issues:
tv.nu
allente.se

But for the last week or so Tivimate is not getting any EPG information. 

I've been using the links from the front page (without the .gz extension):
https://iptv-org.github.io/epg/guides/se/tv.nu.epg.xml
https://iptv-org.github.io/epg/guides/se/allente.se.epg.xml

Please let me know what I'm doing wrong here.

**Comment by RevGear** [comment]
The uncompressed *.xml files are no longer being generated. You need to use the compressed version with the .gz extension. Edit the URL in Tivimate to add .gz on the end.

**Comment by TertoGordez** [comment]
Unfortunately, Tivimate does not accept anything other than .xml
Is there a way to bring back the feature to use generated .xml files?

I would really appreciate it! I've spent quite some time contributing to the Allente.se and tv.nu list.

**Comment by RevGear** [comment]
Tivimate works just fine with .gz files. That's what I'm using

**Comment by TertoGordez** [comment]
In my Tivimate app used on Nvidia Shield Pro, it states that only XMLTV-format is supported when adding EPG-URL. 

I just tried, and behold it worked with .gz extension!

Thanks!
