### ISSUE TITLE
[VE] Inter EPG Request

### ISSUE THREAD

**Issue by nickleby** [iptv-org/epg#1054]
### Source

https://inter.com.ve/programacion/guia.php

### Notes

Hi there. Could be possible to add the EPG from this venezuelan website? https://inter.com.ve/programacion/guia.php
The EPG engine comes from Reportv.com.ar, the mentioned website uses this url specifically for this provider (Inter) https://www.reportv.com.ar/buscador/Buscador.php?aid=2694

When you click on a channel picture, it uses this url to make a POST request https://www.reportv.com.ar/buscador/ProgXSenial.php where the options are: idSenial (channel id), Senial (name of the channel, can be omitted), Alineacion (id of the provider, in this case is always 2694), DiaDesde (start date), HoraDesde (actual time or any specific time).
If you click a tv program name, a popup window inside the same page opens with the info of the program. It uses this url to make a POST request https://www.reportv.com.ar/buscador/DetallePrograma.php where the options are: id, idc, id_alineacion=2694 (this value is fixed for this provider) and idp.

It can be encoded all in the url as this example https://www.reportv.com.ar/buscador/ProgXSenial.php?idSenial=455&Alineacion=2694&DiaDesde=2022%2F08%2F30&HoraDesde=00%3A00%3A00
It makes a GET request where you can see the guide list from the selected channel and it provides the info to use on the "DetallePrograma.php" as this example (also GET request) https://www.reportv.com.ar/buscador/DetallePrograma.php?id=490919&idc=2811086&id_alineacion=2694&idp=1433382001 (where it shows program name, description, etc.)

This is all the usefull info I could get from the website, but I don't have the knowledge to create the config.js file to grab the info from this provider. If someone is able to help, it would be nice. Thanks in advance.

**Comment by freearhey** [comment]
The guide is now available at this link:

```
https://iptv-org.github.io/epg/guides/ve/reportv.com.ar.epg.xml.gz
```

**Comment by nickleby** [comment]
I don't know why if I try to test it locally on my computer (to add more channels), always returns 0 programs...
I'm using npx epg-grabber --config=reportv.com.ar.config.js --channels=reportv.com.ar_ve.channels.xml --output=guide.xml --days=2 (like with other sites) but only this one returns 0 programs.
Any advice @freearhey ? Thank you for taking the time to develop the config for this website.

**Comment by nickleby** [comment]
Hi there! @freearhey could be possible to update the configuration for this EPG? The website changed the guide, now it's using this url https://www.reportv.com.ar/finder/index/2694.... The old config still works for some channels, but others are being updated to the new site, so it doesnt grab the epg.... Thank you.
