### ISSUE TITLE
Fix: tv24.se has no episode/season or Genre in xmltv 

### ISSUE THREAD

**Issue by Jimpan81** [iptv-org/epg#1059]
### Describe your issue

https://iptv-org.github.io/epg/guides/se/tv24.se.epg.xml.gz

has no episode/season or Genre in xmltv

**Comment by freearhey** [comment]
Season/episode number, category, subtitle, image and cast added to guide.

```
https://iptv-org.github.io/epg/guides/se/tv24.se.epg.xml.gz
```
