### ISSUE TITLE
MyKlik IPTV and Radio Channels EPG

### ISSUE THREAD

**Issue by aseanic** [iptv-org/epg#1063]
### Source

https://rtmklik.rtm.gov.my/

### Notes

There are many IPTV and radio channels from Malaysia Government Official Broadcasting

**Comment by freearhey** [comment]
The guide is now available at this link:

```
https://iptv-org.github.io/epg/guides/my/rtmklik.rtm.gov.my.epg.xml.gz
```

Thanks to @RevGear
