### ISSUE TITLE
Missing TV guides listing

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1068]
### Source

?

### Notes

One more thing. There is no EPG guides for those list:

AFV FAMILY*
AMC IFC FILMS PICKS*
AMC PRESENTS*
CONTV ANIME*
CRACKLE*
DEFY TV*
DOVE CHANNEL*
FAIL ARMY (RED BOX)*
FOX WEATHER LIVE *
HI-YAH*
REWIND TV*
THIS TV NETWORK*

**Comment by freearhey** [comment]
Duplicate #1062
