### ISSUE TITLE
MEO Portugal EPG issues

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1079]
### Source

unknown

### Notes

Meo.PT

Missing is RTP Internacional

And TVI, TVI Reality's guide schedule didn't showing up on my TV screen. All else works fine. Please check. Good work.

**Comment by guiworldtv** [comment]
for me too this not working

**Comment by spotanjo3** [comment]
For better sources. I list here:

MEO.PT EPG GUIDE:

https://github.com/Arkina1234/epg-1/blob/master/sites/meo.pt/meo.pt_pt.channels.xml

Nickeloden.

Here
https://www.nickelodeon.pt/

TVI (It is supposed to be "TVI Internacional".) (That's why it didn't showing up in TV guide screen)

Here:
https://tvi.iol.pt/internacional

TVI Reality. (It won't showing up in TV guide screen)

Here:
https://tvi.iol.pt/tvireality

RTP Internacional.

Here:
https://www.rtp.pt/rtpinternacional

Hope it helps. ^_^

**Comment by freearhey** [comment]
Closed in favor #1113
