### ISSUE TITLE
Syracuse NY Locals

### ISSUE THREAD

**Issue by Gitbone94** [iptv-org/epg#1080]
### Source

https://www.tvtv.us

### Notes

I tried to set this up myself using the GitHub desktop so I could be a contributor, but I am failing to figure it out. I found this info on tvtv.us and I hope someone can add the epg for Syracuse, NY locals

WSYR ABC  https://www.tvtv.us/ny/syracuse/luUSA-NY31593-X/stn11564
WTVH CBS  https://www.tvtv.us/ny/syracuse/luUSA-NY31593-X/stn12336
WSYT FOX  https://www.tvtv.us/ny/syracuse/luUSA-NY31593-X/stn11861
WSTM NBC https://www.tvtv.us/ny/syracuse/luUSA-NY31593-X/stn11855

**Comment by RevGear** [comment]
The relevant config.js file (sites\tvtv.us\tvtv.us.config.js) contains the code to get the URL and extract the data. Where it's just a GET you can use that to check you have the correct values for each channel.

tvttv.us uses the 5-digit number after the "stn" in the URLs you listed. Find the correct channel ID and update the relevant xml file, in this case tvtv.us_us-local.channels.xml

`<channel lang="en" xmltv_id="WSYRDT1.us" site_id="11564">WSYR ABC, Syracuse NY</channel>`
Hopefully you can work the others out from there.

**Comment by Gitbone94** [comment]
As long as I can't mess this up for the rest of the users, I will keep trying. I am a senior citizen and I find this all quite confusing to master.
