### ISSUE TITLE
Fix: missing HBO channel in mncvision.id

### ISSUE THREAD

**Issue by kraith** [iptv-org/epg#1086]
### Describe your issue

HBO channel is missing from mncvision.id epg list

**Comment by azimabid00** [comment]
Both of mncvision.id generated file id-en and id-id contains HBO channels, but the tvg-id name is different. For id-en it's **HBOSingapore.sg** and for id-id it's **HBOIndonesia.id**, both referring to the same channel.

**Comment by RevGear** [comment]
> Both of mncvision.id generated file id-en and id-id contains HBO channels, but the tvg-id name is different. For id-en it's **HBOSingapore.sg** and for id-id it's **HBOIndonesia.id**, both referring to the same channel.

I don't think are country specific channels, it's all the same HBO Asia channel. We could probably get rid of HBOHongKong.hk, HBOIndonesia.id, HBOPhilippines.ph, HBOSingapore.sg, HBOTaiwan.tw, HBOThailand.th, HBOVietnam.vn and replace them all with HBOAsia.sg. Same with Cinemax Asia
