### ISSUE TITLE
Germany EPG horizon no data 

### ISSUE THREAD

**Issue by DonnerM99** [iptv-org/epg#1094]
### Describe your issue

Hi, if you open the xml for the german epg horizontv, there seems to be no epg data. Only the channelnames.

kind regards

**Comment by RevGear** [comment]
Looks like it's a problem with the source data. Horizon's own site currently shows a blank grid - [](https://www.horizon.tv/de_de/tv/tv-programm.html)

**Comment by RevGear** [comment]
Horizon seem to have resolved whatever was the problem
