### ISSUE TITLE
Request for scanning new channels EPG for Dstv.com Nigeria and South Africa

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#1098]
Hello

By scanning their EPG sourcing, many new channels could be add

For 

http://guide.dstv.com/

https://www.dstv.com/en-za/discover/tv-guide/

https://github.com/iptv-org/epg/tree/master/sites/dstv.com

https://github.com/iptv-org/epg/tree/master/sites/guide.dstv.com

Please

**Comment by freearhey** [comment]
Please specify the name of the channels that are missing so we can help you.

**Comment by Talon555** [comment]
Movie Room
KIX
Me Channel

**Comment by freearhey** [comment]
Movie Room added in https://github.com/iptv-org/epg/commit/3fe9e39acd91f6efaf34f915cd35f2d0ca4783c2 and https://github.com/iptv-org/epg/commit/1c73a9071abb5e105bb22380f58a12f70327c9d5

KIX and Me Channel are already on the list:
https://github.com/iptv-org/epg/blob/3ef23e7033d45b099e89908ba4e05e5ccd9f8fd1/sites/guide.dstv.com/guide.dstv.com_za.channels.xml#L64
https://github.com/iptv-org/epg/blob/3ef23e7033d45b099e89908ba4e05e5ccd9f8fd1/sites/guide.dstv.com/guide.dstv.com_za.channels.xml#L70
https://github.com/iptv-org/epg/blob/3ef23e7033d45b099e89908ba4e05e5ccd9f8fd1/sites/dstv.com/dstv.com_za.channels.xml#L68
