### ISSUE TITLE
Request for scanning new channels EPG for horizon.tv Germany

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#1099]
Hello

By scanning their EPG sourcing, many new channels could be add

For

https://www.horizon.tv/de_de/tv/tv-programm.html

https://github.com/iptv-org/epg/tree/master/sites/horizon.tv

Please

**Comment by freearhey** [comment]
Please specify the name of the channels that are missing so we can help you.

**Comment by Talon555** [comment]
GEO
Sky Documentaries
Sky Replay
Sky Nature HD
Sky Schowcase

**Comment by RevGear** [comment]
GEO - GeoTV.de
Sky Documentaries  -SkyDocumentaries.de
Sky Replay - SkyReplay.de
Sky Nature HD - SkyNature.de
Already in the channels xml

Sky Showcase
New channel not in the database, but it's not listed on Horizon's own site, so if we added it there would be no data to get
https://www.horizon.tv/de_de/tv/tv-programm.html
