### ISSUE TITLE
Request for scanning new channels EPG for Sky.de Germany

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#1100]
Hello

By scanning their EPG sourcing, many new channels could be add

For

https://www.sky.de/tvguide-7599

https://github.com/iptv-org/epg/tree/master/sites/sky.de

Please

**Comment by freearhey** [comment]
Please specify the name of the channels that are missing so we can help you.

**Comment by Talon555** [comment]
Sky Sport Top Event
Sky Sport Premier League
Sky Sport Mix
Sky Sport Tennis
Sky Sport Golf
DAZN Bar 1 Or DAZN 1
DAZN Bar 2 Or DAZN 2
Sky Sport UHD
Sky Documentaries
Sky Replay
Sky Nature HD
Sky Showcase

**Comment by RevGear** [comment]
Sky.de is currently disabled as it was not working as expected, see #425 
Until that is resolved, there is no point adding any more channels
