### ISSUE TITLE
Request for scanning new channels EPG for tv.blue.ch Switzerland 

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#1101]
Hello

By scanning their EPG sourcing, many new channels could be add

For

https://tv.blue.ch/tv-guide

https://github.com/iptv-org/epg/tree/master/sites/tv.blue.ch

Please

**Comment by freearhey** [comment]
Please specify the name of the channels that are missing so we can help you.

**Comment by Talon555** [comment]
Blue Retro
Blue City
Blue Action
Blue Stars
Blue Sport 1
Blue Sport 2
Blue Event 1
Blue Event 2

**Comment by RevGear** [comment]
Blue Retro - BlueRetro.ch
Blue City - BlueCity.ch
Blue Action - BlueAction.ch
Blue Stars - BlueStars.ch
Blue Sport 1 - BlueSport1.ch
Blue Sport 2 - BlueSport2.ch
Already in the channels xml

Blue Event 1
Blue Event 2
Will need adding to database

**Comment by freearhey** [comment]
>Blue Event 1
Blue Event 2
Will need adding to database

Added in https://github.com/iptv-org/database/commit/a39aad68712ac62b559ed6d820611e60f66e8005

**Comment by Talon555** [comment]
@freearhey @RevGear I noticed that many channels from this xml are unavailable when i want to assign their EPG via IPTV Player like Tivimate by example BLUE PRIME (no epg information currently) or ....
maybe this EPG sourcing tv.blue.ch should be refreshing ?
