### ISSUE TITLE
Broken: tvtv.us_us

### ISSUE THREAD

**Issue by Arkina1234** [iptv-org/epg#1106]
### Guide

https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml.gz

### Description

Check https://www.tvtv.us/gn/d/v1.1/stations/62670/airings?startDateTime=2022-01-17T00:00:00Z&endDateTime=2022-01-18T00:00:00Z link is dead.
You may fix now.

**Comment by ian10951** [comment]
Im confused by the closing of this thread and the link to another which is also closed.

Has this been fixed because for me its still down ?

**Comment by freearhey** [comment]
No, the problem as I know it has not been solved, so this issue is still open.

**Comment by spotanjo3** [comment]
The same for Portugal meo.pt.

**Comment by WaNgEr00** [comment]
Is this still down for everyone else? Have i missed something?

**Comment by RevGear** [comment]
tvtv.us appear to have removed/changed/disabled their API, meaning there is no source data to build the guide from. I'm currently trying to get an alternative solution.

**Comment by firestickkev** [comment]
I have the same problem, is there any solution yet or is this issue still been worked on. Many thanks
