### ISSUE TITLE
dstv.com wrong times

### ISSUE THREAD

**Issue by Chris230291** [iptv-org/epg#1109]
### Guide

https://github.com/iptv-org/epg/tree/master/sites/dstv.com

### Description

The sites doesn't appear to be using UTC. The programs in the output xml are scheduled a couple hours later than there actual showtime.

Chris

**Comment by Talon555** [comment]
> ### Guide
> https://github.com/iptv-org/epg/tree/master/sites/dstv.com
> 
> ### Description
> The sites doesn't appear to be using UTC. The programs in the output xml are scheduled a couple hours later than there actual showtime.
> 
> Chris

No and No !!!
Times are correct, you should change or modify or synchro with IPTV Player

**Comment by Chris230291** [comment]
They are not correct.
I use many of the grabbers and most are correct, but DSTV is slow... which happens to be the time difference between here in the UK and ZA. I'm pretty sure the times are ZA times and not UTC.

![image](https://user-images.githubusercontent.com/5328818/190911757-88fff9ac-aaa0-4a30-9f3b-10405c5a18da.png)

**Comment by RevGear** [comment]
> Also I am grabbing manually myself. Not using the premade guides.

Can you load the pre-made guide and check if those times are also incorrect.

**Comment by Chris230291** [comment]
The premade guide shows 

```
<programme start="20220918141000 +0000" stop="20220918161500 +0000" channel="SuperSportPremierLeague.za">
<title lang="en">PL 22/23: Everton v West Ham</title>
<desc lang="en">&apos;Premier League - Matchday 8: Everton vs West Ham United&apos;. LIVE from Goodison Park - Liverpool, England.</desc>
<category lang="en">Soccer</category><category lang="en">All Sport</category>
<icon src="https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/img/289620_Everton vs West Ham United.png"/>
</programme>
```

Whereas my grab shows

```
<programme start="20220918151000 +0000" stop="20220918171500 +0000" channel="SuperSportPremierLeague.za">
<title lang="en">PL 22/23: Everton v West Ham</title>
<desc lang="en">'Premier League - Matchday 8: Everton vs West Ham United'. LIVE from Goodison Park - Liverpool, England.</desc>
<category lang="en">Soccer</category>
<category lang="en">All Sport</category>
<icon src="https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/img/289620_Everton vs West Ham United.png"/>
</programme>
```

I wonder why that is? The actual kick off time is 14:15 in UTC+1. Doesn't that mean the guide should be 13:15 for UTC 0?

This is the command I use 

```
npx epg-grabber --days=<days> --config=<conf> --channels=<channels> --output=<output>
```

**Comment by Chris230291** [comment]
Thanks guys
