### ISSUE TITLE
Request: some italian EPG for tv.blue.ch

### ISSUE THREAD

**Issue by infid0** [iptv-org/epg#1112]
### Source

https://www.tivu.tv/

### Notes

(Channel name > EPG ID)

QVC Italy > QVCItaly.it
Radio Italia TV > RadioItaliaTV.it
RDS Social TV > RDSSocialTV.it
Radio Monte Carlo TV > RadioMonteCarloTV.it
Gold TV > GoldTV.it
Rai 4K > Rai4K.it

Thank you! :3

**Comment by freearhey** [comment]
The guide from tivu.tv is now available at this link:
```
https://iptv-org.github.io/epg/guides/it/tivu.tv.epg.xml.gz
```
