### ISSUE TITLE
Missing --- Portugal - meo.pt

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1113]
### Guide

https://iptv-org.github.io/epg/guides/pt/meo.pt.epg.xml.gz

### Description

Only TVI, TVI Reality, and RTP Internacional aren't working. Missing ? Or broken? I open xml and saw TVI is there on the list. but not working.

RTP Internacional and TVI Reality aren't on the list and are missing list.

**Comment by nickleby** [comment]
> ### Guide
> https://iptv-org.github.io/epg/guides/pt/meo.pt.epg.xml.gz
> 
> ### Description
> Only TVI, TVI Reality, and RTP Internacional aren't working. Missing ? Or broken? I open xml and saw TVI is there on the list. but not working.
> 
> RTP Internacional and TVI Reality aren't on the list and are missing list.

There's not RTP Internacional and TVI Reality on the schedule of meo.pt https://www.meo.pt/tv/canais-programacao/guia-tv

TVI should be working, the schedule and tv shows are present on the XML.

**Comment by Generator** [comment]
TVI Reality have schedule https://www.meo.pt/tv/canais-programacao/guia-tv?canal=TVIR

**Comment by nickleby** [comment]
> TVI Reality have schedule https://www.meo.pt/tv/canais-programacao/guia-tv?canal=TVIR

Yoy're right, my bad. But TVIR is already on the XML EPG. Only RTP Internacional not on the meo.pt website.

**Comment by spotanjo3** [comment]
I did.. in XML said TVIR.PT. Didn't work. Should I put "tvir.meo.pt" and TVi too. Still didn't showing up.

**Comment by nickleby** [comment]
> I did.. in XML said TVIR.PT. Didn't work. Should I put "tvir.meo.pt" and TVi too? I only have TVIR.PT and TVI.PT however still didn't showing up.

IDs are TVI.pt (for TVI) and TVIReality.pt (for TVI Reality)

**Comment by spotanjo3** [comment]
I did that too.. Still didn't see the guide appearing at all.

**Comment by Generator** [comment]
Use the API to check the channels id  
https://iptv-org.github.io/?q=TVI%20Reality

TVI Reality EPG is working here

**Comment by spotanjo3** [comment]
> Use the API to check the channels id https://iptv-org.github.io/?q=TVI%20Reality
> 
> TVI Reality and TVI Ficção EPG are working here

Thanks for the link. Yes, now its working fine. Only TVIReality.pt doesnt. Strange. Grr.
