### ISSUE TITLE
Late Program

### ISSUE THREAD

**Issue by melchorphc** [iptv-org/epg#1116]
### Description

There is 24 hours delay on this EPG

https://iptv-org.github.io/epg/guides/ph/clickthecity.com.epg.xml.gz

Today is sept 19 but the programs are on sept 18, please fix.. thank you..

**Comment by freearhey** [comment]
At the moment the guide works fine:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/7253922/193837404-7262731e-9a91-4ae6-a3e0-fee32a223e00.png">
