### ISSUE TITLE
Uk BT Sport channel icons

### ISSUE THREAD

**Issue by ginjaninja456** [iptv-org/epg#1132]
### Description

Hi I’ve successfully added EPG to my IPTV, they all work perfectly, but channel icons for BT Sport don’t seem to have loaded. This issue is only with these channels, all other channel icons have loaded correctly. 

Any ideas how I could fix this?

**Comment by freearhey** [comment]
Please add more information so we can help you:

- what guide are we talking about?
- what app are you using?
- which channel are we talking about exactly? 
https://iptv-org.github.io/?q=BT%20Sport

**Comment by ginjaninja456** [comment]
Hi thanks for reply.

This applies to BT sport 1-4 channels, I have tried both Irish and UK links and both fail to load the icon. I am using Tivimate as IPTV client.

**Comment by freearhey** [comment]
These channels are in 3 different guides. Which link are you using exactly?

- `https://iptv-org.github.io/epg/guides/uk/sky.com.epg.xml.gz`
- `https://iptv-org.github.io/epg/guides/uk/virginmedia.com.epg.xml.gz`
- `https://iptv-org.github.io/epg/guides/uk/bt.com.epg.xml.gz`

**Comment by ginjaninja456** [comment]
I have tried all three of those links and same result. I’ve just gone through them all again and no icon in any of them.

**Comment by freearhey** [comment]
It's strange, because I have all the icons displayed just fine:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/7253922/192134645-d32895cb-c153-4ffa-a6bc-8492f2fcf124.png">

But maybe someone else has encountered this problem and can help you.

**Comment by RevGear** [comment]
If you are using Tivimate , try Settings > Appearance > Logos > Clear logo cache
It's possible that the icons in the cache are corrupt and won't display so this will Tivimate to get all the icons again. 

All 3 guides use the same icons so changing which guide you use won't necessarily mean that Tivimate will get the icon if it already exists in the cache.

**Comment by ginjaninja456** [comment]
I tried this and it didn’t work but thought I would unlink epg for the BT channels, tried it again and linked the epg and seems to have worked!

Thanks both for your help, my OCD can rest now!
