### ISSUE TITLE
Digiturk added new sport channel 

### ISSUE THREAD

**Issue by mhmtngt** [iptv-org/epg#1137]
### Source

https://www.digiturk.com.tr/yayin-akisi

### Channels

-beIN SPORTS 5

### Notes

Following line should be added to "digiturk.com.tr_tr.channels.xml" file
`    <channel lang="tr" xmltv_id="beINSports5Turkey.tr" site_id="506">beIN SPORTS 5 Türkiye</channel>
`
Thanks

**Comment by PopeyeTheSai10r** [comment]
beINSports5Turkey.tr is not a valid XML ID. The channel needs to be added to the the database.

The Database [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) has more information how to add entries.

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/cde0694eeebd255ef8d32f648d69792098a2c2f9
