### ISSUE TITLE
CR/LF in Windows 10 causing long read/load times

### ISSUE THREAD

**Issue by dineshalphaque** [iptv-org/epg#114]
Notice that the .xml guide files are generated with very long lines, sometimes in excess of 1,5000.000 characters. This causes slow read/parsing times in Kodi with PVR Simple Client. 

Perhaps could end with a hard CR/LF at for each <programme>...</programme> block. 

Would be happy to provide a consolidated .xml file if an example is needed, but be wary, this is large ~120MB in size.

**Comment by freearhey** [comment]
> sometimes in excess of 1,5000.000 characters

Which guide are we talking about here?

**Comment by dineshalphaque** [comment]
> > sometimes in excess of 1,5000.000 characters
> 
> Which guide are we talking about here?

Trying to isolate it. It could also be due to a Kodi add-on, IPTV Merge as well. For now, i'll close this issue until i can get much better information on what's causing this.
