### ISSUE TITLE
Parse and add icons to each program in EPG guides

### ISSUE THREAD

**Issue by elboletaire** [iptv-org/epg#1140]
### Description

I've recently discovered this awesome project and I moved all my EPG mapping to use these guides. I love having them without the need to have my own program running, but I miss a huge feature compared to when I was using webgrabplus: there are no icons parsed for the programs, so the guide shows all the programs with an empty image.

Are there any plans on adding the images/icons of the tv programs? 

The xml format I've seen in your files is like:

~~~xml
<programme start="20221003184000 +0000" stop="20221003184100 +0000" channel="France24Espanol.fr">
  <title lang="es">Rappel des titres</title>
  <category lang="es">Información</category>
</programme>
~~~

Adding the icon would require an additional `icon` tag:

~~~xml
<programme start="20221003184000 +0000" stop="20221003184100 +0000" channel="France24Espanol.fr">
  <title lang="es">Rappel des titres</title>
  <category lang="es">Información</category>
  <icon src="http://programacion-tv.elpais.com/imagenes/programas/227485.jpg" />
</programme>
~~~

And most websites where the information is grabbed have these images (it could also be a feature only for those sites having images defined ofc).

**Comment by RevGear** [comment]
Normally images/icons will be included where they were part of the source data. For programacion-tv.elpais.com, they aren't.

https://programacion-tv.elpais.com/data/parrilla_05102022.json
`{
"id": "CF161483086",
"idCanal": "3",
"iniDate": "2022-10-05 00:25:00",
"endDate": "2022-10-05 01:10:00",
"idSection": "3",
"txtSection": "Informativos",
"name": "",
"title": "Comando Actualidad",
"description": "Los consumidores somos los que más desperdicio alimentario generamos.",
"recommended": "0",
"id_programa": "CF5811787",
"idCellnex": "202210050025",
"duracion": "004500",
"rating": "3"
}`

Looking at how their website guide works, it's bring in extra details from a secondary source which contains all programs for a single channel.
https://programacion-tv.elpais.com/data/programas/3.json (replace 3 with the channel number)
`{
"id_programa": "CF5811787",
"id_section": "3",
"txt_section": "Informativos",
"title": "Comando Actualidad",
"description": "Los consumidores somos los que más desperdicio alimentario generamos.",
"duration": "45",
"artistic": "0",
"commercial": "0",
"id_genre": "09",
"txt_genre": "Informativo",
"id_subgenre": "192",
"txt_subgenre": "Reportajes",
"id_parental": "3",
"txtParental": "No recomendado para menores de 7 años (7)",
"season": "16",
"episode": "6",
"episode_title": "Más usar y menos tirar",
"episode_description": "Salsas, carnes congeladas y legumbres son los alimentos que más tiramos los españoles a la basura. Desechamos más de 28 kilos de comida por persona y año.",
"total_episodes": "0",
"country": "España",
"year": "2022",
"director": "Raúl García, César Pérez, Daniel Galindo, Silvia Sánchez",
"script": "",
"actors": "",
"producer": "",
"production": "",
"presented_by": "",
"photography": "",
"music": "",
"creator": "",
"guest_actors": "",
"image": "imagenes/programas/466248.jpg",
"poster": "imagenes/programas/466248.jpg",
"paisISO": "ESP",
"imagenPadre": "466248",
"posterPadre": "466248",
"seriado": false,
"multievento": false
}`
It picks out the relevant program details by matching the `id_programa`

There's no date/time in that second source so the only way would be to grab the two URLs and try to merge the data. That might be one for someone else to pick up as I can't get my head around how best to approach it. Looks like the second URL might show programs for more than the current day ( yesterday + today + tomorrow ?) but without dates/times it's not easy to check that

**Comment by freearhey** [comment]
Images and the cast of shows have been added to the guide.

```
https://iptv-org.github.io/epg/guides/es/programacion-tv.elpais.com.epg.xml.gz
```

**Comment by elboletaire** [comment]
They aren't for the movistar guide either, which is actually the one I'm using. Sorry I used an example image from `elpais.com` which may have caused the confusion. 

I may switch my guide source tho, now that the one from `elpais.com` has the icons properly parsed 😅
