### ISSUE TITLE
Request: fix channel on tv.blue.ch

### ISSUE THREAD

**Issue by infid0** [iptv-org/epg#1152]
### Source

https://tv.blue.ch/tv-guide

### Notes

FROM "VideoItalia.it" (deprecated)
TO "RadioItaliaTV.it" (missing)

I've see the EPG of Radio Italia TV from TV and the epg site is like epg TV, the only difference is the name "Radio/Video" Italia. Thank you!

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/2bf84e1795d504329d9e1395a906fbc94549ec98
