### ISSUE TITLE
Missing Channels 

### ISSUE THREAD

**Issue by lmnl01** [iptv-org/epg#1162]
### Source

https://www.mysky.com.ph/metromanila/tv-schedules

### Channels

These are the channels that are available in the schedule but are missing in the epg:
- Cartoon Network (PH Feed)
- TLC (PH Feed)
- TMC (TAGALIZED MOVIE CHANNEL)
- ZooMoo
- Da Vinci Kids
- A2Z
- Global Trekker (Rare Channel)
- Love Nature
- Cinema One (PH Feed)

### Notes
I think the mysky epg must be updated every 2 hours because it's not loading the whole schedule for a day all at once.
Some of these are already in the clickthecity epg but that source is becoming unreliable on schedule sometimes.
Also, the CInema One on clickthecity must be added on "Cinema1Philippines.ph" because it is the schedule for the PH feed.

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/e2085b095cf4a1cc9cf8af6cc631bbbc6209ab77
