### ISSUE TITLE
SYFY WEST guide is wrong

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1168]
### Description

Looks like SYFY WEST GUIDE is wrong. The guide said Grimm T2 - Ep 16 but on the screen showing is Twilight Zone. The twilight Zone was actually on East. Can you fix it ? Yes, its on cable for my PC. Thanks.

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/epg/issues/new?assignees=&labels=%E2%9A%A0%EF%B8%8F+broken+guide&template=---broken-guide.yml
