### ISSUE TITLE
syfy west guide is wrong

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1169]
### Guide

https://iptv-org.github.io/epg/guides/us/directv.com.epg.xml.gz

### Description

Sorry about my English. Something is really wrong with SYFY WEST. When I watched the cable on my Televizo, I saw the guides showing Grimm T2 - Ep 16 but the movie come on the screen showing Twilight Zone. I checked the TV Guide and see that the East time is actually The twilight Zone. Please fix the WEST correctly. Yes, its on cable for my PC. Thanks.

**Comment by freearhey** [comment]
There is no SyFy West in this guide, only the Eastern feed:

https://github.com/iptv-org/epg/blob/af9414b5bf3baf00c208f2d2eba550a28850aae2/sites/directv.com/directv.com_us.channels.xml#L297-L299

**Comment by spotanjo3** [comment]
> There is no SyFy West in this guide, only the Eastern feed:
> 
> https://github.com/iptv-org/epg/blob/af9414b5bf3baf00c208f2d2eba550a28850aae2/sites/directv.com/directv.com_us.channels.xml#L297-L299

My apology.. Its there in:

https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml.gz

**Comment by spotanjo3** [comment]
Can you write and add SYFY Pacific to EPG ?
