### ISSUE TITLE
tvtv.us failing

### ISSUE THREAD

**Issue by SoftwareSamurai** [iptv-org/epg#1172]
### Guide

https://iptv-org.github.io/epg/guides/us-local/tvtv.us.epg.xml.gz

### Description

It appears that tvtv.us is failing again - twice in a row now as of today (10/9/22).
(https://github.com/iptv-org/epg/actions/workflows/tvtv.us.yml)

**Comment by Kev506** [comment]
Same here, no data?

**Comment by hanke69** [comment]
FYI - Same for me...no data!

**Comment by dcole819** [comment]
Same here…been failing a lot lately

**Comment by firestickkev** [comment]
I'm in uk and lost epg sat midnight, this happend last week as well, seemed to come back Monday morning last time. Hopefully same will happen again. If anyone has a work around this issue please advise

**Comment by jamboy3** [comment]
It's failing again for me too, but it's maybe 20% of the channels with No Information instead of all of them like last time. Is there any reason behind all the issues lately?

**Comment by firestickkev** [comment]
Is there any update to this issue yet or has anyone got another solution. Many thanks

**Comment by SoftwareSamurai** [comment]
The nightly build appears to be failing with: "Error: No programs found"
I'm guessing that means the website scraping didn't work.

**Comment by Kev506** [comment]
> Is there any update to this issue yet or has anyone got another solution. Many thanks

Temporarily I'm using https://guidexl.tv4.live/ in Tivimate all seems ok at the moment.

**Comment by Generator** [comment]
There's also [epgshare01/share01](https://github.com/epgshare01/share01) with US and other countries

**Comment by Kev506** [comment]
> There's also [epgshare01/share01](https://github.com/epgshare01/share01) with US and other countries

That's unfortunately also down.

**Comment by dcole819** [comment]
Yea that’s down too

**Comment by dcole819** [comment]
> > Is there any update to this issue yet or has anyone got another solution. Many thanks
> 
> Temporarily I'm using https://guidexl.tv4.live/ in Tivimate all seems ok at the moment.

If I use this epg will I manually have to assign channels in tivimate?

**Comment by Kev506** [comment]
> > > Is there any update to this issue yet or has anyone got another solution. Many thanks
> > 
> > 
> > Temporarily I'm using https://guidexl.tv4.live/ in Tivimate all seems ok at the moment.
> 
> If I use this epg will I manually have to assign channels in tivimate?

Yes but better than no data.

**Comment by firestickkev** [comment]
> > Is there any update to this issue yet or has anyone got another solution. Many thanks
> 
> Temporarily I'm using https://guidexl.tv4.live/ in Tivimate all seems ok at the moment.

Thanks kev506, like you say better than nothing, just assigned channels to it and il see how that goes. Many thanks kev506 for you help

**Comment by dcole819** [comment]
This still not fixed?

**Comment by ac3nl** [comment]
Still not fixed

**Comment by Generator** [comment]
Please stop spamming the comments if you don't have any new information.
Keeping asking "is it fixed", "please fix" won't fox the issue, only spam everyone with useless comments

**Comment by freearhey** [comment]
A bit more about the error:

Since October 8, 2022, the tvtv.us server began to return an HTTP error 503 (Service Unavailable) on every request.

https://github.com/iptv-org/epg/actions/runs/3278905005/jobs/5397838939

```sh
...
[1/4808] tvtv.us (en) - 3ABNEnglish.us - Oct 19, 2022 (0 programs)
Request failed with status code 503
[2/4808] tvtv.us (en) - 3ABNEnglish.us - Oct 20, 2022 (0 programs)
Request failed with status code 503
...
```

This error occurs only if the request is made from GitHub servers. The same request sent from another IP works as before:

```sh
...
[1/4808] tvtv.us (en) - 3ABNEnglish.us - Oct 19, 2022 (37 programs)
[2/4808] tvtv.us (en) - 3ABNEnglish.us - Oct 20, 2022 (37 programs)
...
```

The [config](https://github.com/iptv-org/epg/blob/master/sites/tvtv.us/tvtv.us.config.js) used for parsing the guide did not change in any way and still works fine.

So the only option is blocking by tvtv.us. Since there is nothing we can do about it, we will have to remove this guide from the list.

But if something changes in the future and the guide becomes available again, we will definitely bring it back.

**Comment by ac3nl** [comment]
Is it possible to run the parser from a remote server?
This will definitely have an other ip

**Comment by freearhey** [comment]
The parser itself can be run on any computer, but in order to continue providing the guide to everyone this parser needs to be run through [GitHub Actions](https://docs.github.com/en/actions).

**Comment by SoftwareSamurai** [comment]
Could the fetches be routed through a proxy?

**Comment by freearhey** [comment]
Yes, it is possible.

**Comment by ian10951** [comment]
So for clarification, is this going to be fixed or has it now gone for good ?

**Comment by ac3nl** [comment]
Disapointing how low feedback actually is on this project.
Seems like nobody cares

**Comment by freearhey** [comment]
@ian10951 If a working solution is found the guide will be returned to the list, but until then I think the topic can be closed.

**Comment by charlieglue** [comment]
using a proxy isn't a solution?

**Comment by freearhey** [comment]
@charlieglue if you find such a proxy let us know.

**Comment by SoftwareSamurai** [comment]
Would this help?
https://github.com/TheSpeedX/PROXY-List

**Comment by freearhey** [comment]
@SoftwareSamurai Have you tested any of them?

**Comment by SoftwareSamurai** [comment]
> @SoftwareSamurai Have you tested any of them?

Scanned a few. Yeah, that list contains dead/unresponsive proxy servers. (To be fair, some do work fine. Would probably need to ping/test that list first before every run just to pick one. Bit of a PITA.)

Looking over this list (https://www.proxynova.com/proxy-server-list/elite-proxies/) maybe we can just select a few prime entries, such as Thailand, Mexico, or France?

**Comment by freearhey** [comment]
Well, in this case, the location of the proxy does not matter, so I suppose any proxy will do as long as it works reliably.

**Comment by spotanjo3** [comment]
I added WSBKDT4.us for Charge! and tv guide didnt show up at all! I have this:

https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml.gz

Whats wrong ?

**Comment by GlamoramaAttack** [comment]
> I added WSBKDT4.us for Charge! and tv guide didnt show up at all! I have this:
> 
> https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml.gz
> 
> Whats wrong ?

The link isn't working any longer. Right now you get the EPG for Charge! via

https://iptv-org.github.io/epg/guides/us.xml.gz

where it is:

#EXTINF:-1 tvg-id="Charge.us" tvg-name="Charge" tvg-logo="https://i.imgur.com/fuw0hHE.png" group-title="US",Charge!

if you use .xmltv 

But if you use .m3u then you need https://raw.githubusercontent.com/matthuisman/i.mjh.nz/master/Stirr/all.xml.gz
and find it here:

#EXTINF:-1 tvg-id="externallinearfeed-01-15-2020-201540715-01-15-2020" tvg-name="Charge" tvg-logo="https://i.mjh.nz/Stirr/.images/8b4d0a3429.png" group-title="US",Charge!

**Comment by PopeyeTheSai10r** [comment]
Do we know whether they are blocking the IPs that Github assign to the runners or whether they are rate limiting the runners?

**Comment by PopeyeTheSai10r** [comment]
I was able to get the site to response while using Github servers by changing the user-agent to Chrome and Firefox.

@freearhey Anyway to create a test config and add user-agent to it?

**Comment by freearhey** [comment]
Unfortunately, changing the user-agent to a different one did not help: https://github.com/iptv-org/epg/actions/runs/3564535799/jobs/5988608573

Test config: https://github.com/iptv-org/epg/blob/fix-tvtv.us/sites/tvtv.us/tvtv.us.config.js

**Comment by PopeyeTheSai10r** [comment]
Here's how I got it it to work.

`curl -A "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0" https://www.tvtv.us/api/v1/lineup/COUNTRY-ZIPCODE-DEFAULT/grid/DATE -X GET`

https://github.com/PopeyeTheSai10r/epg/actions/runs/3569918495/jobs/6000371378

**Comment by freearhey** [comment]
And this is the response if the request is sent from the iptv-org/epg:

https://github.com/iptv-org/epg/actions/runs/3582752373/jobs/6027348290

**Comment by PopeyeTheSai10r** [comment]
Getting the same response now. We will need a different solution.

Cloudflare protection in enable as discussed below
`https://www.reddit.com/r/webscraping/comments/qjpt8k/comment/hirn6ey/?utm_source=share&utm_medium=web2x&context=3`

**Comment by PopeyeTheSai10r** [comment]
After looking into this for a while, it seems like mimicking a browser can be the a possible solution since we only get responses from the server while doing that. This will mean adding a bunch of headers to the request to make it possible. Here is a direct call I made and was able to get the response we are looking for:
`https://github.com/PopeyeTheSai10r/epg/actions/runs/3625555510/jobs/6113723053`

There is a github project that does this but I don't think it will feasible to implement that info the current configurations and configs `https://github.com/lwthiker/curl-impersonate`. There's more information how to do this at the following links `https://stackoverflow.com/a/31597823` & `https://unix.stackexchange.com/q/703599`
