### ISSUE TITLE
clickyhecity PH epg 24 hours late..

### ISSUE THREAD

**Issue by melchorphc** [iptv-org/epg#1175]
2nd time to post but the first post unresolved.. the programs was late.. the picrture below schedule was showing yesterday
![1](https://user-images.githubusercontent.com/109189325/195263119-09b66e00-8b44-4f8f-a84b-cc00ab68da21.jpg)

**Comment by melchorphc** [comment]
checked the website the program correct.. 
![2](https://user-images.githubusercontent.com/109189325/195263847-512fc6fd-f66f-4091-b332-75241fd3c70f.jpeg)

**Comment by freearhey** [comment]
I still don't see any problems in the guide:

Time on site **01:30 pm** (Filipino time):
<img width="669" alt="image" src="https://user-images.githubusercontent.com/7253922/195331335-ef92a972-c961-4beb-ac3d-ba36d53dfbfa.png">

Time in the guide **05:30 am** (UTC: -8:00 from Filipino time):
<img width="695" alt="image" src="https://user-images.githubusercontent.com/7253922/195331700-6e71c97c-2fa4-43ca-888a-145bca9bd57f.png">

Why your app displays the guide for yesterday, I do not know. 

But maybe someone else has encountered this problem and can help you.

**Comment by melchorphc** [comment]
Still late.. today is 10/15/2022 the programs still on 14
![IMG_20221015_135115](https://user-images.githubusercontent.com/109189325/195971314-54c9bd1e-d7d1-4adf-8f74-d9d5eb4cc5d0.jpg)

**Comment by freearhey** [comment]
Each guide contains a 2-day program. The guide is updated every day from 03:00 to 09:00 UTC, so you can sometimes see yesterday's program in the file. But if you look closely you'll see that there is always a program for today as well:

![195971314-54c9bd1e-d7d1-4adf-8f74-d9d5eb4cc5d0](https://user-images.githubusercontent.com/7253922/195984800-b333376d-5ea1-4784-9c9c-d0c101185638.jpg)
