### ISSUE TITLE
The Canadian EPG has a lot of French?

### ISSUE THREAD

**Issue by Skozo** [iptv-org/epg#1178]
### Description

I am trying to use the Canadian EPG but many of the channels are in French?  Is it possible to get English only?
Thank you

**Comment by Gitbone94** [comment]
dtngfan85, that is not what skozo is referring to. He is pointing out that even some of the english language channels are populating in french. i think it is because the 'hebdo' epg is probably coming from quebec. it seems the old epg for canada has been abandoned.

**Comment by freearhey** [comment]
So far, there are no plans to add a separate English version of the Canadian guide. But since in the new version of the guide English is already in the priority over French, the problem should eventually disappear by itself.
