### ISSUE TITLE
Changing the TVG-ID for some Korean Channels

### ISSUE THREAD

**Issue by lmnl01** [iptv-org/epg#1184]
### Description

The directv epg for MBCTV.kr is supposed to be included on MBCAmerica.us and on SBSTV.kr, directv and tvtv should be removed from it because those are schedules for the USA version of SBS and not the Korean one.  The schedule is overlapping and sometimes wrong because of this.

There should be an SBSAmerica.us solely for directv and tvtv. Thank you.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/4680b996792a4835269e6e849ab3c5d0df70f15a and https://github.com/iptv-org/epg/commit/97a301ec497ca1c0e9af8ddef45d70ffbdc0b464
