### ISSUE TITLE
EPG available in .xml 

### ISSUE THREAD

**Issue by deltabatonix** [iptv-org/epg#1185]
### Description

Would it be possible to add links to EPGs that are not compressed? My player only accepts xml files 

Thanks!

**Comment by freearhey** [comment]
Unfortunately, this is not possible due to platform limitations. You can read more about it here: https://github.com/iptv-org/iptv/discussions/8255

**Comment by freearhey** [comment]
Uncompressed versions of the files are again available via the same links: https://github.com/iptv-org/epg#usage
