### ISSUE TITLE
the Netherlands ZIGGOGO is failing

### ISSUE THREAD

**Issue by ac3nl** [iptv-org/epg#1186]
### Guide

https://iptv-org.github.io/epg/guides/nl/ziggogo.tv.epg.xml.gz

### Description

Please fix this ??

**Comment by ac3nl** [comment]
Should be an easy fix right?

**Comment by ac3nl** [comment]
Does anybody actually read the issues on this project?

**Comment by freearhey** [comment]
Yes, of course.

**Comment by ac3nl** [comment]
So what is an ETA on a fix for this?

**Comment by freearhey** [comment]
I have no idea.

**Comment by freearhey** [comment]
Fixed in #1228

**Comment by ac3nl** [comment]
Thank you!
