### ISSUE TITLE
New Zealand TV guide EPG

### ISSUE THREAD

**Issue by Kamiela20100** [iptv-org/epg#1190]
### Source

https://www.skygo.co.nz/tv-guide

### Notes

Would love you to add Cable Tv channels for NZ.

Thanks in advance

**Comment by freearhey** [comment]
I get error 500 when I try to load the guide through the API:

`curl --request POST --url https://api.skyone.co.nz/exp/graph ...`

```json
{
	"error": {
		"code": "500",
		"message": "An error occurred",
		"errorId": "IGGR7BHAEA",
		"correlationId": "6NFLBWPKV4",
		"sessionId": "CSYZG43FGM"
	}
}
```

But maybe someone else will find a way.

**Comment by freearhey** [comment]
The guide for most NZ channels is now available at this link:

```
https://iptv-org.github.io/epg/guides/nz.xml
```

**Comment by Kamiela20100** [comment]
Thanks heaps
