### ISSUE TITLE
TV channels disappeared

### ISSUE THREAD

**Issue by infoagwdru** [iptv-org/epg#1193]
### Source

https://iptv-org.github.io/epg/guides/ru/tv.yandex.ru.epg.xml.gz

### Channels

СТС (sts)
2X2 (2x2)
Пятница! (pyatnitsa!)
5 Канал (5kanal)
Звезда (zvezda)

### Notes

The following channels have disappeared in the Russian TV guide: sts, 2x2, pyatnitsa, 5 kanal, zvezda

**Comment by freearhey** [comment]
Thank you for the report!

Fixed in https://github.com/iptv-org/epg/commit/ea9c07bc730f419929a37aedcd0b5cf1ccf54b0b
