### ISSUE TITLE
Request: Novasports Channels & Eurosport Channels [Greece]

### ISSUE THREAD

**Issue by johntaxmi** [iptv-org/epg#1202]
### Source

https://www.novasports.gr/tv-program/

### Channels

- Novasports Premier League
- Novasports Prime
- Novasports1HD
- Novasports2HD
- Novasports3HD
- Novasports4HD
- Novasports5HD
- Novasports6HD
- NovasportsStart
- NovasportsNews
- Novasports Extra1
- Novasports Extra2
- Novasports Extra3
- Novasports Extra4
- Eurosport 1 HD
- Eurosport 2 HD

**Comment by freearhey** [comment]
Added in #1232
