### ISSUE TITLE
Please add back images sources to tvtv.us

### ISSUE THREAD

**Issue by SmokeyBR** [iptv-org/epg#1207]
### Description

tvtv.us had to be upgraded, when it was the images were never added to channel epg.
would like to see that back if possible, thanks

**Comment by SmokeyBR** [comment]
im using my own server to get data from tvtv.us so it is working please do not remove or stop giving support to it, its one of the best sources that has good info, pictures, correct times and most of the channels around.

**Comment by charlieglue** [comment]
have you guide to set this up for my self?
its either that or setup a proxy server for to use to get the scraping

**Comment by auge8472** [comment]
This might sound like back seat moderation, but ...

> [tvtv.us] ... it is working please do not remove or stop giving support to it

["the only option is ***blocking by tvtv.us***. Since ***there is nothing we can do about it***, we will have to remove this guide from the list."](https://github.com/iptv-org/epg/issues/1172#issuecomment-1284261669)

What is misleading in this comment?

**Comment by SmokeyBR** [comment]
> This might sound like back seat moderation, but ...
> 
> > [tvtv.us] ... it is working please do not remove or stop giving support to it
> 
> ["the only option is _**blocking by tvtv.us**_. Since _**there is nothing we can do about it**_, we will have to remove this guide from the list."](https://github.com/iptv-org/epg/issues/1172#issuecomment-1284261669)
> 
> What is misleading in this comment?

the problem is tvtv.us wont accept connections from **github**, if u read the entire issue you will find...
["This error occurs only if the request is made from **GitHub servers**. The same request sent from **another IP works** as before"](https://github.com/iptv-org/epg/issues/1172#issuecomment-1284261669)
as i am using another ip, it works fine thats why im asking not to give up on it....

> have you guide to set this up for my self? its either that or setup a proxy server for to use to get the scraping

I have no guide, just git clone the project install [epg-grabber](https://github.com/freearhey/epg-grabber) and install [dependencies](https://github.com/iptv-org/epg/blob/master/package.json) search on how to do it, to run use:
```
cd "/path/to/epg-master"
npx epg-grabber --config="sites/tvtv.us/tvtv.us.config.js" --channels="sites/tvtv.us/tvtv.us_ca.channels.xml" --days=3 --output="/path/to/output.xml"
```

**Comment by auge8472** [comment]
@SmokeyBR I read your comment and I read the linked statement of @freearhey. He wrote himself "This error occurs only if the request is made from GitHub servers. The same request sent from another IP works as before". So the situation, that only connections from Github are refused, can be assumed to be known.

> as i am using another ip, it works fine thats why im asking not to give up on it....

freearhey wrote [in his comment to this issue](https://github.com/iptv-org/epg/issues/1207#issuecomment-1289074736) "*sorry but tvtv.us is no longer updated*" and in [his comment in issue 1172](https://github.com/iptv-org/epg/issues/1172#issuecomment-1284261669) "*But if something changes in the future and the guide becomes available again, we will definitely bring it back.*". So I assume, it's not generally lost but we (here especially *you*) have to _wait for a solution_. 🙂

**Comment by SmokeyBR** [comment]
yes thank you for for the response just thought id ask while i was waiting for the images to be added again but if there is no interest its all good i can always change to the other multiple sources available, thank you appreciate the attention and the project.
