### ISSUE TITLE
Fox Sports Channels

### ISSUE THREAD

**Issue by dean24freeman** [iptv-org/epg#1215]
### Source

https://www.foxtel.com.au/tv-guide.html/grid/

### Notes

Channels 501, 502, 503, 504, 505, 506
This is a general guide for Australia don't know if it helps at all.
Thanks for your EPG's

**Comment by freearhey** [comment]
The guide for 501 (Fox Cricket), 502 (Fox League), 503 (Fox Sports 503), 504 (Fox Footy), 505 (Fox Sports 505), 506 (Fox Sports 506) is now available at the link:

```
https://iptv-org.github.io/epg/guides/au.xml
```
