### ISSUE TITLE
missing channels in Swedish EPG

### ISSUE THREAD

**Issue by hehewtf** [iptv-org/epg#1224]
### Source

https://www.tv.nu/alla-tv-kanaler
https://www.allente.se/tv-guide/
https://tv24.se/

### Channels

bbc brit
bbc earth
discovery science
h2 (history 2)
E!
MTV Nordic
Fight Sports
Motorvision TV
Fuel TV

### Notes

first thanks for all your work and for merging lists

previously before merge using allente.se.xml tv.nu.xml and tv24.se.xml these channels weren't missing

mainly Allente xml for everything and tv24.se+tv.nu for just a few total that was missing in Allente (max 5 missing from it iirc)

Fuel TV was named Fule in whichever previous list it was in

**Comment by freearhey** [comment]
All listed channels are added to the guide.
