### ISSUE TITLE
Request True Folm Asia in tv.trueid.net

### ISSUE THREAD

**Issue by oldpoem** [iptv-org/epg#1225]
### Source

tv.trueid.net

### Channels

True Flm Asia HD

### Notes

Seem to be missing. It's on website and id is "film-asia-hd" . But it is missing on iptv-org site EPG.

Please fix this.

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/32040d385b073584a93e0f070dabc026516ffbde
