### ISSUE TITLE
France EPG time is not correct

### ISSUE THREAD

**Issue by Sungray** [iptv-org/epg#123]
https://iptv-org.github.io/epg/guides/programme-tv.net.guide.xml
The time is the local time without time correction. Messes up the display in any globalized software like Emby by currently 2 hours
i.e. program is shown starting at 11:05pm instead of 9:05pm :
programme start="20211001210500 +0000" stop="20211001225500 +0000" channel="TF1.fr"

**Comment by freearhey** [comment]
Please try again using this link this time: `https://iptv-org.github.io/epg/guides/fr/programme-tv.net.epg.xml`

**Comment by Sungray** [comment]
@freearhey That is much better. Thanks a lot.

**Comment by freearhey** [comment]
Glad to hear that.
