### ISSUE TITLE
TvGuide.com EPG Enhancement Request

### ISSUE THREAD

**Issue by PopeyeTheSai10r** [iptv-org/epg#1231]
### Description

Hello, I noticed the EPGs from tvguide will only grab the **title**, **start** and **stop** time. 
I noticed that the rest of the program details such as description, rating and episode are saved to a different page. Is there an easy way to collect this information and add it to the EPG?

`https://github.com/iptv-org/epg/blob/master/sites/tvguide.com/tvguide.com.config.js`

**Comment by freearhey** [comment]
Added.

**Comment by PopeyeTheSai10r** [comment]
Thank you!
