### ISSUE TITLE
France

### ISSUE THREAD

**Issue by DXZ75** [iptv-org/epg#1237]
### Guide

https://iptv-org.github.io/epg/guides/fr.xml

### Description

Hi The epg of M6 group (M6, W9...) in the French channels do not work it puts only program of the night and then no information.

**Comment by freearhey** [comment]
At the moment the guide is working fine:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/7253922/198889187-2d75a420-4ee9-4576-a673-cda25d8e45f7.png">
