### ISSUE TITLE
Combined Guides - questions / features

### ISSUE THREAD

**Issue by RevGear** [iptv-org/epg#1245]
### Description

Is it possible to add a 'source' field to the combined guide to indicate where the program details originated from? Doesn't really matter from an end-user point of view but useful when debugging to trace back any issues.

I notice that some channels are missing from the combined guide, which I assume if because we have conflicting information from different  sources. For example TringActionHD.al

From maxtvgo.mk
```
<programme start="20221030213500 +0000" stop="20221030230500 +0000" channel="TringActionHD.al">
<title lang="mk">KIDNAP</title>
<category lang="mk">Филм</category>
<icon src="https://prd-static-mkt.spectar.tv/rev-1642406883/image_transform.php/transform/1/epg_program_id/26999732/instance_id/1"/>
</programme>
```

From tv2go.t-2.net
```
<programme start="20221030170000 +0000" stop="20221031050000 +0000" channel="TringActionHD.al">
<title lang="sl">Spored trenutno ni na voljo</title>
</programme>
```

In this instance it's probably just a case of removing from the tv2go.t-2.net channel list, but there are other examples which may not be as obvious.

Is there any way of identifying which channels we have source data for but don't show in the combined guides?

**Comment by RevGear** [comment]
Supplementary question, how are we handling different languages? For example, beinsports.com and elcinema.com are available in both English and Arabic with the same channel IDs. Presumably it will be 50:50 as to which language version gets picked for the combined guide. I'm sure there are other examples where different sites use different languages for the same channel ID

**Comment by freearhey** [comment]
As for the source, it is already listed next to the name of the channel at the beginning of each guide:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/7253922/199068799-85cb96a7-d671-40e9-a5e4-887f356a66e9.png">

As for multilingual guides, the current version of the scripts solves it this way:

- downloading the program guide from all sources, regardless of language
- download the list of official languages for each country from [iptv-org/database](https://github.com/iptv-org/database/blob/master/data/countries.csv)
- select a guide for each channel in one of these languages
- if there is no suitable guide, then take the guide in English

That is, in the above example, if Arabic is spoken in the country and all other things being equal, then the Arabic version will be added to the guide. If it's not suitable, then the English version will be used.

Ideally, I would like to add all versions to each file, like so:

```
<programme start="20221101053000 +0000" stop="20221101060000 +0000" channel="AlJazeeraEnglish.qa">
    <title lang="ar">حساب التكلفة</title>
    <title lang="en">Counting the Cost</title>
</programme>
```

but as I know most programs don't allow you to choose a language and just choose it randomly. Not to mention other related problems (size of the resulting file, different program start/end times in different sources, need to debug it all somehow).

**Comment by RevGear** [comment]
Thanks. Don't normally look that closely at the channel section at the top of the guide so assumed that was the channel's URL rather than that of the EPG source.

The single multi-language guide in you example would be good, but as you say it doesn't help if many players don't support that. I guess the other option would be to split into separate files, eg qa-ar.xml and qa-en.xml, but might end up with too many combinations of country/language to be practical.

**Comment by freearhey** [comment]
> might end up with too many combinations of country/language to be practical

Exactly. And as a result, the very meaning of combined guide would be lost.
