### ISSUE TITLE
Question about Class CNBC

### ISSUE THREAD

**Issue by infid0** [iptv-org/epg#1249]
### Description

Hi, Class CNBC is a italian channel in italian language, but the id epg is `ClassCNBC.us`. Now, this ".us" prevents of showing the epg with `https://iptv-org.github.io/epg/guides/it.xml.gz`. It's possible a solution? Thank you so much! :3
Uh, other stranger thing, currently Class CNBC not is present on any epg list... 
https://iptv-org.github.io/?q=ClassCNBC.us
...But in reality is present inside `guidatv.sky.it`. Thank you again! :3

**Comment by freearhey** [comment]
Fixed.
