### ISSUE TITLE
USA CHANNEL PACIFIC

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1253]
### Source

https://www.tvpassport.com/tv-listings/stations/usa-network-pacific/2144

### Notes

Can you add it ? Only East EPG is working.

**Comment by spotanjo3** [comment]
Please check it again. Its East time. I am asking for pacific because the schedule according to tv passport.com and my tv isnt match due to your link incorrect.

**Comment by freearhey** [comment]
https://iptv-org.github.io/epg/guides/us/tvpassport.com.epg.xml.gz
<img width="641" alt="image" src="https://user-images.githubusercontent.com/7253922/200138871-8d16b5ea-dd78-465e-9465-1c42f55ab145.png">
