### ISSUE TITLE
Discovery Channel Pacific

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1255]
### Source

https://www.tvpassport.com/tv-listings/stations/discovery-channel-us-pacific-feed/1206

### Notes

Great LIVE TV GUIDE. Can you add it ?

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/ae4890357bb3761a66a481215caf21739de41150

**Comment by spotanjo3** [comment]
work
