### ISSUE TITLE
EPIX East

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1257]
### Source

https://www.tvpassport.com/tv-listings/stations/epix-hd-east/7610

**Comment by spotanjo3** [comment]
Is it on iptv-org.github.io/epg/guides/us/directv.com.epg.xml.gz ? It didnt show on my tv guide.

**Comment by freearhey** [comment]
Right now it's only in the guide from tvpassport.com.

https://iptv-org.github.io/epg/guides/us/tvpassport.com.epg.xml.gz
<img width="795" alt="image" src="https://user-images.githubusercontent.com/7253922/200139093-179caed8-5bad-4992-84de-ee061bd7bafd.png">

**Comment by spotanjo3** [comment]
Please fix it. Its not working properly.

**Comment by freearhey** [comment]
At the moment, everything is working fine:

https://iptv-org.github.io/epg/guides/us/tvpassport.com.epg.xml.gz
<img width="547" alt="image" src="https://user-images.githubusercontent.com/7253922/200450141-40caefab-b14f-41d0-a40c-0134ead5b3a9.png">

**Comment by spotanjo3** [comment]
Thank you! I forgot to added "East".
