### ISSUE TITLE
EPIX 2 East

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1258]
### Source

https://www.tvpassport.com/tv-listings/stations/epix2-east/11485

**Comment by spotanjo3** [comment]
Is it on iptv-org.github.io/epg/guides/us/directv.com.epg.xml.gz ? It didnt show on my tv guide.

**Comment by freearhey** [comment]
"Epix 2 East" renamed to "Epix 2" (#1264)

https://iptv-org.github.io/epg/guides/us/directv.com.epg.xml.gz
<img width="705" alt="image" src="https://user-images.githubusercontent.com/7253922/200137277-9ea72fc9-b129-4f75-91b0-9863cc3499a0.png">

**Comment by spotanjo3** [comment]
Please check it again and this link is correct:

https://www.tvpassport.com/tv-listings/stations/epix2-east/11485

My guide said The Amazing Spider Man 2 and its wrong because this tv showing is actually:

[Sky Captain and the World of Tomorrow](https://www.tvpassport.com/movie/sky-captain-and-the-world-of-tomorrow/13993147) (2004)

**Comment by spotanjo3** [comment]
Great. It works. Thanks!

**Comment by spotanjo3** [comment]
Please fix it. Its not working properly.

**Comment by freearhey** [comment]
At the moment, everything is working fine:

https://iptv-org.github.io/epg/guides/us/tvpassport.com.epg.xml.gz
<img width="567" alt="image" src="https://user-images.githubusercontent.com/7253922/200450393-e32994b3-0e0c-4666-bdcf-e2405c7c45b8.png">
