### ISSUE TITLE
EPIX Drive-In East

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1259]
### Source

https://www.tvpassport.com/tv-listings/stations/epix-drivein/11487

**Comment by freearhey** [comment]
https://github.com/iptv-org/epg/blob/3a27bd20edcb4454bf283b81cbc0c46935a1ed91/sites/tvpassport.com/tvpassport.com_us.channels.xml#L7

**Comment by spotanjo3** [comment]
Work!
