### ISSUE TITLE
Add Channel m.tv.sms.cz

### ISSUE THREAD

**Issue by KodiPicons** [iptv-org/epg#1266]
### Source

https://m.tv.sms.cz

### Channels

Joj 24
https://m.tv.sms.cz/mobilni/tvp/?stanice=JOJ+24

Televízia Dolný Kubín 
https://m.tv.sms.cz/?stanice=Telev%EDzia+Doln%FD+Kub%EDn&cas=

Turbo TV
https://m.tv.sms.cz/?stanice=Turbo+TV&cas=

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/3a27bd20edcb4454bf283b81cbc0c46935a1ed91
