### ISSUE TITLE
Repair Channel - m.tv.sms.cz

### ISSUE THREAD

**Issue by KodiPicons** [iptv-org/epg#1267]
### Guide

https://m.tv.sms.cz/

### Description

History Channel
https://m.tv.sms.cz/?stanice=History+Channel&cas=

Nick JR
https://m.tv.sms.cz/?stanice=Nick+Jr.&cas=

Nasa TV
https://m.tv.sms.cz/mobilni/tvp/?stanice=NASA+TV

**Comment by Dexer125** [comment]
Nick JR and NASA TV is working.

History Channel fixed by PR #1305
