### ISSUE TITLE
USA EPG Not Loading Properly

### ISSUE THREAD

**Issue by Powerfader1** [iptv-org/epg#127]
The USA playlist loaded properly from: 🇺🇸 United States  1901  https://iptv-org.github.io/iptv/countries/us.m3u

But the EPG did not load at all. So I clicked on this link: https://github.com/iptv-org/epg to find my specific country (USA) and input the 2 links that were provided: 🇺🇸 United States  https://iptv-org.github.io/epg/guides/tvtv.us.guide.xml
                                                                                       https://iptv-org.github.io/epg/guides/tvguide.com.guide.xml

Both urls loaded on my Tivimate properly, but only about 33%-40% of the EPG loaded. I know I am being very presumptuous in asking for help, but I am an old retired guy with just enough tech knowledge to really screw things up. So I would appreciate anything you can do to help me out.

Thanks,

**Comment by chamby90** [comment]
oh, i see.  For the channels that do load, how many hours of data do you have?  I guess what I am trying to confirm is whether the USA EPG xml file contains more than 24 hours of data or not.  I am only getting ~18 hours of data and trying to figure out if the issue is the epg or my program I am using having some kind of limit.

**Comment by Powerfader1** [comment]
There are 6,255 channels appearing on the playlist and about 68 channels showing any type of an EPG. Also, a significant amount of channels do not load.

Imho, even though a lot of channels are not loading. I believe the epg is corupt in some way?

**Comment by freearhey** [comment]
Please try again using this link this time: `https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml`

**Comment by freearhey** [comment]
Unable to reproduce. Tested through Kodi and GSE Smart IPTV.

```
https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml
```

![image](https://user-images.githubusercontent.com/7253922/139567609-cf6a35c9-e955-461f-ac5a-17434cac569f.png)

**Comment by Powerfader1** [comment]
I am running this on Tivimate premium. I re-loaded the code and I did gain some success.

Thanks for your time and response.
