### ISSUE TITLE
Remove Episode Number

### ISSUE THREAD

**Issue by nmeed** [iptv-org/epg#1274]
### Description

Seems episode number has been recently implemented, and while I think it might be interesting for some shows, it's a bit jarring for most. Having the episode number for a CNN "show" really doesn't work. Seeing S01E909 is kind of weird. Also, I think some have the category before the description, so it is MOVIE - Inception. Which is also kind of weird. Would appreciate it if you could revert back to how the EPG used to be, which is just the description, without any mention of number or category.

**Comment by mcastellaneta** [comment]
Are you referring to a specific guide?

**Comment by PopeyeTheSai10r** [comment]
I understand how having the Episode numbers on some channels can be a distraction but I don't think straight up removing them is the solution here. There are channels like HBO, Starz and the likes where having Episode number is really handy.
