### ISSUE TITLE
EPIX West channel was removed that still exists

### ISSUE THREAD

**Issue by GlamoramaAttack** [iptv-org/epg#1276]
### Source

https://tvpassport.com

### Channels

```
<channel id="EpixWest.us"><display-name>Epix West</display-name><icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Epix_Logo_2019.svg/512px-Epix_Logo_2019.svg.png"/><url>https://tvpassport.com</url></channel>
```

### Notes

Since the EPIX  thread ["Update directv.com_us.channels.xml #1264"](https://github.com/iptv-org/epg/pull/1264) is closed I want to mention that EPIX West/Pacific still broadcasts. 

At TVPassport:

[epix--pacific/13443](https://www.tvpassport.com/tv-listings/stations/epix-pacific/13443)

I watch both EPIX East and West.

**Comment by freearhey** [comment]
The channel has been returned to the list:

https://github.com/iptv-org/epg/blob/1d10a1df2e548d1c0d3c82a6f0283615f60b927a/sites/tvpassport.com/tvpassport.com_us.channels.xml#L17
