### ISSUE TITLE
Outermax Eastern

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1277]
### Source

https://www.tvpassport.com/tv-listings/stations/outermax-eastern/2270

**Comment by spotanjo3** [comment]
It works but the title said "Movie". There is no subject. I noticed other tv guides you added also showing "Movie" as well. Why ?

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/fec1609e33784b5c8556f23a0300deb9a3c60921

**Comment by spotanjo3** [comment]
It is showing "movie" and no title.
