### ISSUE TITLE
Bravo pacific

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1286]
### Source

https://www.tvpassport.com/tv-listings/stations/bravo-usa-hd-pacific-feed/16226

**Comment by freearhey** [comment]
Already on the list:

https://github.com/iptv-org/epg/blob/9c711bee2cc541b73d445956061d0267794d655b/sites/tvpassport.com/tvpassport.com_us.channels.xml#L9

**Comment by spotanjo3** [comment]
Ok. Wrong name. I had BravoPacific.us. I rename it to BravoWest.us now. Thanks.

**Comment by spotanjo3** [comment]
It is showing "Movie". No title at all.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/fec1609e33784b5c8556f23a0300deb9a3c60921
