### ISSUE TITLE
ION PLUS

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1288]
### Source

https://ionplustv.com/schedule

### Notes

Yours always showing "SIGN OFF" and this link have correct schedule with all titles in it.

**Comment by freearhey** [comment]
The updated guide for Ion Plus can now be found at:

```
https://iptv-org.github.io/epg/guides/us.xml
```

and

```
https://iptv-org.github.io/epg/guides/us/ionplustv.com.epg.xml.gz
```
