### ISSUE TITLE
indieplex

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1289]
### Source

https://www.tvpassport.com/tv-listings/stations/indieplex-eastern/2340

### Notes

This site have titles. Yours showing "Movie" only. No titles. This link is better.

**Comment by freearhey** [comment]
Already on the list:

https://github.com/iptv-org/epg/blob/9c711bee2cc541b73d445956061d0267794d655b/sites/tvpassport.com/tvpassport.com_us.channels.xml#L26

**Comment by spotanjo3** [comment]
It is showing "movie" and no title.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/fec1609e33784b5c8556f23a0300deb9a3c60921
