### ISSUE TITLE
Retro Crush

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1292]
### Source

https://www.retrocrush.tv/

**Comment by freearhey** [comment]
https://iptv-org.github.io/epg/guides/us.xml
<img width="601" alt="image" src="https://user-images.githubusercontent.com/7253922/200668539-4e395fb6-9eee-45a1-a5b2-695ce2e032e6.png">

**Comment by spotanjo3** [comment]
Oh... RetroCrushTV.us. Mine was RetroCrush.us. Now its working. Thanks.
