### ISSUE TITLE
Disney XD Pacific 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1313]
### Source

https://www.tvpassport.com/tv-listings/stations/disney-xd-usa-hd-pacific-feed/16228

**Comment by freearhey** [comment]
Already on the list:

https://github.com/iptv-org/epg/blob/34a25853241d5bc4068280508e91d8251d0dfb47/sites/tvpassport.com/tvpassport.com_us.channels.xml#L12

**Comment by spotanjo3** [comment]
It is correct And still didnt showing up.

**Comment by freearhey** [comment]
https://iptv-org.github.io/epg/guides/us/tvpassport.com.epg.xml
<img width="732" alt="image" src="https://user-images.githubusercontent.com/7253922/200666426-69f85045-b164-4b44-afdf-f90bbaa0c60c.png">
