### ISSUE TITLE
Disney Junior Japan not retrieved 

### ISSUE THREAD

**Issue by Danieruhuli** [iptv-org/epg#1319]
### Source

Tvguide.myjcom.jp

### Channels

The epg for Disney Junior Japan (tvd-id="DisneyJuniorJapan.jp") is not being retrieved.
The problem is that the channel is not specified in the file https://iptv-org.github.io/epg/guides/jp/tvguide.myjcom.jp.epg.xml

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/6ab963353ad3f02b5cf591ad1da83819e04a5959

**Comment by Danieruhuli** [comment]
Thanks. 
Am I using the xml link correctly? Because the EPG for Disney Junior is still not appearing for me.
I use https://iptv-org.github.io/epg/guides/jp/tvguide.myjcom.jp.epg.xml

Thanks

**Comment by freearhey** [comment]
Please check again:

https://iptv-org.github.io/epg/guides/jp/tvguide.myjcom.jp.epg.xml
<img width="684" alt="image" src="https://user-images.githubusercontent.com/7253922/200933905-a489a5d9-8297-4db4-9660-62fd45836228.png">

**Comment by Danieruhuli** [comment]
Is working now. Thanks
