### ISSUE TITLE
Wu Tang Collection 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1326]
### Source

https://watch.plex.tv/live-tv/channel/wu-tang-collection

**Comment by freearhey** [comment]
The channel is already on the list:

https://iptv-org.github.io/epg/guides/us.xml
<img width="716" alt="image" src="https://user-images.githubusercontent.com/7253922/201432547-33807030-c8a1-4d20-8489-ffa101025466.png">

**Comment by spotanjo3** [comment]
No, your EPG is wrong. The schedule didnt match your EPG. The schedule said Ninja Operation 2 but what I see is All Superheroes must die. Wrong one.. Can you fix it ? Please check this https://watch.plex.tv/live-tv/channel/wu-tang-collection

**Comment by spotanjo3** [comment]
Can't you added this schedule to plex EPG ?

**Comment by freearhey** [comment]
No.

**Comment by spotanjo3** [comment]
Isnt the link mention “plex”? Curiosity

**Comment by freearhey** [comment]
The only source of guides for Plex channels that we currently use is [i.mjh.nz](https://i.mjh.nz/Plex/) and unless some other source is added we will not be able to bring the channel back.

**Comment by spotanjo3** [comment]
Can you post i.mijh.nz link so I can added it ?

**Comment by freearhey** [comment]
The guide for the Wu Tang Collection is now available at:

```
https://iptv-org.github.io/epg/guides/us.xml
```
