### ISSUE TITLE
No Information - US EPG

### ISSUE THREAD

**Issue by nmeed** [iptv-org/epg#1331]
For the past few days the US EPG has been giving me no information for all of the channels. Other EPGs work fine. Is it just me?

**Comment by freearhey** [comment]
At the moment everything is working fine:

https://iptv-org.github.io/epg/guides/us.xml
<img width="736" alt="image" src="https://user-images.githubusercontent.com/7253922/201496360-03e38bbf-b654-43e0-bfdc-ad8866198935.png">
