### ISSUE TITLE
Guide only goes thru ~8pm ET

### ISSUE THREAD

**Issue by chamby90** [iptv-org/epg#134]
I am using xteve to load my M3u and xmltv files into Plex.  It looks like the US EPG works fine up until around 8pm each night and then my channels get dropped because there is no EPG information.  Is this expected?  If so - can the EPG be populated to at least have 24 hours worth of EPG data?  In xteve, I am pulling a copy of the XML file each morning around 6am.. so if the issue is with the time that i perform the refresh let me know.

I just have no idea where to go with this.

**Comment by freearhey** [comment]
Please try again using this link this time: `https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml`

**Comment by chamby90** [comment]
thanks @freearhey that fixed it!  I appreciate it.

**Comment by chamby90** [comment]
@freearhey I dont know if it is appropriate to re-open this ticket or to create a new one, but im going to start by reopening this one.  What I am seeing again is that all of my guides run out of information at 7pm ET.  Is this is a known issue or is it something specific happening to me?  I am using many of the different US State specific EPGs and they are all cutting off at the same time

**Comment by chamby90** [comment]
looks like the guide is showing past 7pm ET again... closing ticket.

**Comment by chamby90** [comment]
Sorry for opening this again... but my guide is cutoff at 8pm every day again.  

This it the URL im using:  https://iptv-org.github.io/epg/guides/us-local/tvtv.us.epg.xml.gz

Just want to know if this is widespread or just me.

**Comment by PopeyeTheSai10r** [comment]
Hey, @chamby90 I tried to replicate the issue on my end but couldn't. I opened the file and can see that their is program info hours past 8 pm or 2000. I can see things for the 2200 and 2300 hour.

Have you try loading the EPG using a different device, perhaps a more powerful one?
The file is almost 100K lines long and could be a local issue where the device is not able to handle all the data at once.

**Comment by chamby90** [comment]
@PopeyeTheSai10r Yeah... could be it.  Because yesterday when I looked at my guide it WAS showing past 8pm, but now its back to only showing up until 8pm today.  I don't have another device to use unfortunately, but are there settings I could adjust in Plex (what i am using) or on my computer that you would suggest?

**Comment by PopeyeTheSai10r** [comment]
> @PopeyeTheSai10r Yeah... could be it. Because yesterday when I looked at my guide it WAS showing past 8pm, but now its back to only showing up until 8pm today. I don't have another device to use unfortunately, but are there settings I could adjust in Plex (what i am using) or on my computer that you would suggest?

Sorry I have never used Plex for IPTV or EPG so not sure what options are available. Don't think I can help much with that.

> 
> I only use the guide URL above for some of the channels. For most of my channels I use Schedules Direct, and I never have issues with those EPGs being cutoff at 8pm (i join my EPGs to make a master EPG with xteve - so maybe that is also another factor at play?)

As for combining EPGs, yes, this can be causing all type of issues. The best way to troubleshoot is to use the EPG URL from the link above on its own and see if you have issues with it cutting off. If no issue, then try combining as usual and see if anything changes.

**Comment by freearhey** [comment]
Related https://github.com/iptv-org/epg/issues/1172
