### ISSUE TITLE
Discovery Theater Brazil Missing

### ISSUE THREAD

**Issue by Rferreira2k** [iptv-org/epg#1341]
### Source

https://mi.tv/br

### Channels

The Discovery Theater channel disappear from EPG

Name in previous versions of xml: DiscoveryTheaterHDLatinAmerica.us

link in mi.tv website: https://mi.tv/br/canais/discovery-theater-hd

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/42153d6b457db70faef5bd943f157a495839486c
