### ISSUE TITLE
Eurosport 1 and 2 for the Netherlands 

### ISSUE THREAD

**Issue by TheDude123456** [iptv-org/epg#1342]
### Source

https://www.tvgids.nl/gids/eurosport1

### Channels

-Eurosport 1
-Eurosport 2

**Comment by freearhey** [comment]
Both channels have been added to the guide:

```
https://iptv-org.github.io/epg/guides/nl.xml
```

**Comment by TheDude123456** [comment]
Thanks!!!send from my iPhone 13 Pro MaxOn Nov 17, 2022, at 4:07 AM, Aleksandr Statciuk ***@***.***> wrote:﻿
Both channels have been added to the guide:
https://iptv-org.github.io/epg/guides/nl.xml
