### ISSUE TITLE
Missing tag

### ISSUE THREAD

**Issue by smrtprjcts** [iptv-org/epg#1349]
### Description

Some stop tags are missing from the hu.xml programs.
E.g.
`<programme start="20221116224619 +0000" channel="M3.hu"><title lang="hu">Egymillió fontos hangjegy</title><desc lang="hu">Az Új egymillió fontos hangjegy színpadán Kovács Kati énekel.</desc></programme>
`
I think it would be better if these were filtered out in advance.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/13199c4c8a27b4581e3657e5a96058fe5def15ff
