### ISSUE TITLE
Adding EPG Guide to iptv-org?

### ISSUE THREAD

**Issue by blackhern** [iptv-org/epg#1352]
### Description

What steps would I need to take in order to add or have added an EPG Guide Source to iptv-org? I have an EPG source where I can get all US and Canada OTA Channels, Satelite, and Cable listings, I would Like to share some hard-to-find EPG Guide Listings. Here is just a sample of what I can get. I can get all available OTA Channels, satellite and cable channels in New York, Chicago, Kansas City, NW Arkansas, and many more.  Please advise.

**Comment by freearhey** [comment]
I have added a file with short instructions on how to do it: https://github.com/iptv-org/epg/blob/master/CONTRIBUTING.md#how-to-add-a-new-source-to-the-repository
