### ISSUE TITLE
Some epgs are showing in Chinese instead of English

### ISSUE THREAD

**Issue by kraith** [iptv-org/epg#1359]
### Guide

sorry wrong link
~~https://iptv-org.github.io/epg/guides/sq.xml~~
the corect one
https://iptv-org.github.io/epg/guides/sg.xml
### Description

hits
hits movies
celestial classic movies
asian food netwrok
rock entertainment
rock extreme
those channels were in English but after combined guides, only in Chinese

**Comment by freearhey** [comment]
> https://iptv-org.github.io/epg/guides/sq.xml

There is no such file in the repository.

**Comment by kraith** [comment]
oh sorry, typo 
https://iptv-org.github.io/epg/guides/sg.xml

**Comment by freearhey** [comment]
Fixed.
