### ISSUE TITLE
Wrong program times in hu.xml

### ISSUE THREAD

**Issue by smrtprjcts** [iptv-org/epg#1361]
### Description

Duplicated start, different end. Overlapping
```
<programme start="20221119090000 +0000" stop="20221119100000 +0000" channel="Hatoscsatorna.hu"><title lang="hu">Lillás reggeli</title><desc lang="hu">A műsorban Paor Lilla egy reggeli mellett beszélget vendégeivel.</desc><category lang="hu">szórakoztató műsor</category></programme>

<programme start="20221119090000 +0000" stop="20221119110000 +0000" channel="Hatoscsatorna.hu"><title lang="hu">Hatoscsatorna műsora</title></programme>

```

**Comment by smrtprjcts** [comment]
Hi @freearhey!
I'd like to know how long it takes (maximum) to update the xml file after a patch merged to the master?
It would good to be known
Thanks
SP

**Comment by freearhey** [comment]
In this case, the guide has already had time to update. 
But usually all guide updates take place between 3:00 and 9:30 UTC.

**Comment by freearhey** [comment]
Fixed.

**Comment by smrtprjcts** [comment]
> In this case, the guide has already had time to update. But usually all guide updates take place between 3:00 and 9:30 UTC.

Hi!
I downloaded the current hu.xml and "TV 2 Sef" channel name is in, which is wrong. I thought that I fixed it two days ago, but seems to be not. Where does it come from? I have not found its source.
Thanks a lot.

**Comment by freearhey** [comment]
The thing is, when generating final guides, only the name of the channel from [iptv-org/database](https://github.com/iptv-org/database) is used. Names in `*.channels.xml` are used only for debugging (https://github.com/iptv-org/epg/blob/master/CONTRIBUTING.md)
