### ISSUE TITLE
.se in musor.tv_hu

### ISSUE THREAD

**Issue by smrtprjcts** [iptv-org/epg#1371]
### Description

Is it ok? 
**.se** in Hungarian site?

```
<channel lang="hu" xmltv_id="ViasatExplore.se" site_id="VIASATEXP">Viasat Explore (HD)</channel>
<channel lang="hu" xmltv_id="ViasatHistory.se" site_id="VIASATHIST">Viasat History (HD)</channel>
<channel lang="hu" xmltv_id="ViasatNature.se" site_id="VIASATNAT">Viasat Nature (HD)</channel>
```

[here](https://github.com/smrtprjcts/iptvepg/blob/master/sites/musor.tv/musor.tv_hu.channels.xml)

**Comment by freearhey** [comment]
If the guide is really for Swedish Viasat, then yes it is ok. But if the site contains a guide for the local versions of the channels, then of course it is an error and `xmltv_id` will need to be updated.

Just in case, a complete list of channels and their IDs can be found here: https://iptv-org.github.io/?q=viasat
