### ISSUE TITLE
German guide refers to french version of arte

### ISSUE THREAD

**Issue by ingo2004** [iptv-org/epg#1380]
### Guide

https://iptv-org.github.io/epg/guides/de.xml

### Description

ARTE is available in French (ARTE.fr) and in German (ARTE.de).
The german channel list therefore lists ARTE.de, however the german epg refers to ARTE.fr and therefore does not get resolved by the player, e.g:

`<programme start="20221122001500 +0000" stop="20221122020000 +0000" channel="ARTE.fr"><title lang="de">How to Save a Dead Friend</title><desc lang="de">Marusya ist 16 und entschlossen, ihrem Leben ein Ende zu setzen. Doch dann lernt sie Kimi kennen und ist bereit, dem Leben noch eine Chance zu geben. Mehr als zehn Jahre lang dokumentierte Regisseurin Marusya Syroechkovskaya die Unruhe einer Jugend.</desc><credits><director>Marusya Syroechkovskaya</director></credits><category lang="de">Dokumentation</category></programme>
`

Fix: Change entries for arte in the German guide to channel="ARTE.de"

**Comment by PopeyeTheSai10r** [comment]
Hey @ingo2004, The solution here would be adding the German version of the channel to the [Database](https://github.com/iptv-org/database#database-) and then updating` https://iptv-org.github.io/epg/guides/de.xml` to point to the German version of the channel.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/database/pull/1284 and https://github.com/iptv-org/epg/commit/830d81a13fa4a4a959f0e8f34e358c0c39dae7b5

**Comment by ingo2004** [comment]
Works now, thanks a bunch!!!
