### ISSUE TITLE
Still wrong for SuperSport, South Africa (ZA)

### ISSUE THREAD

**Issue by hulkhaugen** [iptv-org/epg#1384]
### Guide

https://iptv-org.github.io/epg/guides/za.xml

### Description

This was changed a week ago, but checking now, it still seems to be incorrect. Could be different between indivudual channels, i dunno.  [https://github.com/iptv-org/epg/issues/1332](https://github.com/iptv-org/epg/issues/1332). Looking at the [dstv.com source](https://www.dstv.com/umbraco/api/TvGuide/GetProgrammes?d=2022-11-22&package=&country=zaf) right now for SuperSport Grandstand and SuperSport Premier League:

```
<ProgrammeItem>
    <EndTime>2022-11-22T17:00:00</EndTime>
    <Id>247ad0c5-0980-4b73-bb5c-f9ed7813a228</Id>
    <StartTime>2022-11-22T14:45:00</StartTime>
    <Title>2022 FIFA World Cup: DEN v TUN</Title>
</ProgrammeItem>
```
Here is from your source:
```
<programme start="20221122134500 +0000" stop="20221122160000 +0000" channel="SuperSportFootballPlus.za">
    <title lang="en">2022 FIFA World Cup: DEN v TUN</title>
    <desc lang="en">'2022 FIFA World Cup - Denmark vs Tunisia'. LIVE from Education City Stadium - Ar-Rayyan, Qatar.</desc>
    <category lang="en">All Sport</category>
    <category lang="en">Soccer</category>
    <icon src="https://03mcdecdnimagerepository.blob.core.windows.net/epguideimage/img/300709_Denmark vs Tunisia.png"/>
</programme>
```
I'm currently watching the game, and it's almost half time, which means the tv guide is 1 hour late.

**Comment by freearhey** [comment]
Is the time in the guide correct now?

**Comment by hulkhaugen** [comment]
Yes, looks good now, thank you so much :D
