### ISSUE TITLE
Norway EPG Disappeared?

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1385]
### Description

Norway EPG https://iptv-org.github.io/epg/guides/no.xml seems to still work on my tivimate app on one device but I added another one recently and am just getting 'No Information' for every Norwegian channel when using this EPG source. Database entries for all Norwegian channels don't seem to list any EPG source but the source is still in the list here: https://github.com/iptv-org/epg
Is there an issue that can be fixed?

**Comment by PopeyeTheSai10r** [comment]
Hello @Smark223, If I understanding this correctly, you said the Norway EPG `https://iptv-org.github.io/epg/guides/no.xml` works for one of your devices but not the other, correct?

If so, it doesn't seem like an issue with the EPG. It sounds like a local issue. You may want to start by checking whether a mobile device in the same network can load the EPG URL.

Something else to try is: Open TiviMate > settings > EPG > Clear EPG > Update EPG.

**Comment by Smark223** [comment]
I didn't really explain myself properly. I have a Norwegian playlist in tivimate that has full EPG data for all channels. I added another temporary playlist for the World Cup, which duplicates channels that are stored in country specific playlists, for all channels showing World Cup games, for quick access. I have assigned all relevant EPG sources to this playlist and all work with the exception of the Norwegian channels - the source is definintely assigned (I've double checked!)

I just thought it seemed odd that none of the Norwegian channels in the database https://iptv-org.github.io/ seem to have a valid EPG associated with them. I'm confused as to why not if there is a valid one that works ie: https://iptv-org.github.io/epg/guides/no.xml 

That's why I assumed there was an issue with the EPG itself. And was worried that this source would stop working for my main Norwegian playlist. However, it isn't a big deal if that doesn't happen as I'll only be using the WC playlist for a short period of time. 

Does that make sense?

**Comment by PopeyeTheSai10r** [comment]
> Does that make sense?

Yes, it does make more sense now. 

It sounds like your new temporary playlist and the EPG have either a **CHANNEL_NAME** or **CHANNEL_ID** mismatch or something else entirely which is why it doesn't show the information. 
You can try manually assigning the EPG to one of the affected channels which should fix the issue. We know the EPG still works since your main Playlist still loading the information.

**Comment by Smark223** [comment]
No mismatches as the info was all copied and pasted. It'll have to remain a mystery. As long as the EPG is still working, that's fine. Not sure why the database isn't showing a valid source for the Norwegian channels but I'll close this now as there doesn't seem to be a problem.

**Comment by Smark223** [comment]
So, my Norwegian playlist has now lost the EPG for all its channels, so it seems like my suspicion was right and the EPG source has stoppped working :(

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/database/commit/61cdbf6b9decdaf9baaab4f96197611b27bcb658
