### ISSUE TITLE
Local channels gone

### ISSUE THREAD

**Issue by TheDeatCrusher** [iptv-org/epg#139]
There used to be epg for local channels now it is gone can someone fix this?

**Comment by Gitbone94** [comment]
Please include the Chicago locals when you bring back locals (biggest tv market in central time zone).
WLS, WBBM, WMAQ WFLD

**Comment by freearhey** [comment]
So far, only in test mode. If all goes well I'll add links to the guides to the list and let you know about it.

**Comment by freearhey** [comment]
@TheDeatCrusher Local US and Canadian channels have been added to the list.

https://github.com/iptv-org/epg#us-states
