### ISSUE TITLE
https://iptv-org.github.io/epg/guides/us.xml is not populating with info just started to day

### ISSUE THREAD

**Issue by lilchina** [iptv-org/epg#1395]
### Guide

https://iptv-org.github.io/epg/guides/us.xml

### Description

I have multiple devices from Firestick 4k max. Mecool km1. Bluestacks running Tivimate. 4.6.1 paid for sub. and only the channels I assigned to the github epg has no information.  other channels from the IPTV services have info  I use Github to fill in the  channels that have missing info from github.  It had  info until a recent epg pull now the those same channels have no info. no error getting to URL but it seems  the UR is doing the same as the old TVTV url was doing. Anyone else?

**Comment by bark1n9** [comment]
Same here but with Turkey EPG. (https://iptv-org.github.io/epg/guides/tr.xml)

**Comment by freearhey** [comment]
At the moment both guides are working fine.

https://iptv-org.github.io/epg/guides/us.xml
<img width="537" alt="image" src="https://user-images.githubusercontent.com/7253922/203963169-8dd41ca3-3eb0-445b-ba7b-3bccbb836651.png">

https://iptv-org.github.io/epg/guides/tr.xml
<img width="541" alt="image" src="https://user-images.githubusercontent.com/7253922/203962534-62486169-aab7-4598-b326-ee60bf15e2e2.png">

**Comment by lilchina** [comment]
yes it is working now but yesterday it wasn't for a bit.
