### ISSUE TITLE
need to update icons and add remainder channels

### ISSUE THREAD

**Issue by Shawkiiz** [iptv-org/epg#1397]
### Guide

https://iptv-org.github.io/epg/guides/eg.xml

### Description

The icons has disappeared for many channels need to update it ,

also need to add all channels in ( https://elcinema.com/tvguide/ )

**Comment by freearhey** [comment]
Could you specify exactly which channels are missing?

**Comment by Shawkiiz** [comment]
90% of channels icone are missing cus of changing icone  name from the source ,, 

also If you visite (https://elcinema.com/tvguide/) you will fined alot of chanels there are missing in you xml 

e.g (all rotana channels , etc , kahera walnas 2 and more)

**Comment by freearhey** [comment]
Channel logos as I said above have already been updated and will appear in the guides tomorrow.

And the guides for the Rotana and Al Kahera Wal Nas are already available at:

```
https://iptv-org.github.io/epg/guides/sa.xml
```

and

```
https://iptv-org.github.io/epg/guides/eg.xml
```

**Comment by Shawkiiz** [comment]
Thx bro and i'll update you with chaneels name need to add ❤️
