### ISSUE TITLE
NRK1 and NRK Super missing from Norwegian EPG

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1399]
### Guide

https://iptv-org.github.io/epg/guides/no.xml

### Description

I believe there was a bug in the Norwegian EPG that has now been fixed but since the fix, channels NRK1 and NRK Super do not appear.

**Comment by hulkhaugen** [comment]
I think the Norwegian channels are mostly sourced from allente.se, but they would be better collected from allente.no, i bet the same script can be applied to the norwegian site as the sites are identical.

**Comment by PopeyeTheSai10r** [comment]
@hulkhaugen The runner is using the allente.no site for the Norwegian guide.

If you look at the config for allente, you can see how the .${country} variable is being used.

**Comment by freearhey** [comment]
The guide for NRK1 is now available at:

```
https://iptv-org.github.io/epg/guides/no.xml
```

and the guide for NRK Super at:

```
https://iptv-org.github.io/epg/guides/se.xml
```

**Comment by hulkhaugen** [comment]
> and the guide for NRK Super at:
> 
> ```
> https://iptv-org.github.io/epg/guides/se.xml
> ```

Why? It's a Norwegian channel, not swedish.

**Comment by freearhey** [comment]
The thing is that at the moment we have a guide for NRK Super only in Swedish (from tv24.se), so it was placed in the `se.xml` file. As soon as a source with the guide in Norwegian or at least English, it will be added to `no.xml` as well.

**Comment by hulkhaugen** [comment]
Well the thing is, NRK Super and NRK3 is a shared channel, so it's NRK Super during the day, and NRK3 in the evening. If you look at https://tv.nrk.no/guide, you'll see that NRK Super ends when NRK3 starts. Looking at both [allente.no](https://www.allente.no/tv-guide/) and the .se version, it seems like the content of NRK Super is included in the NRK3 columns. Don't know how it's presented in the API. From formal providers in Norway, the channel is always listed as "NRK Super / NRK3" as one single channel.
