### ISSUE TITLE
Add CableGO EPG

### ISSUE THREAD

**Issue by sguinetti** [iptv-org/epg#1400]
This EPG service is for peruvian channels.

# Source:

https://cablego.com.pe/epg

(for some peruvian channels only see: https://cablego.com.pe/epg?category=NACIONALREGIONA)

# Channels:

* BHTV.pe
* PBO.pe
* Conecta2TV.pe
* ExitosaTV.pe
* USMPTV.pe
* Nativa.pe
* CongresoTV.pe
* Karibena.pe
* OvacionTV.pe

**Comment by freearhey** [comment]
Added.
