### ISSUE TITLE
BET WEST

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1405]
### Channel ID

BETWest.us

### Source

https://www.tvpassport.com/tv-listings/stations/bet-hd-pacific-feed/6561

### Notes

BET TV Pacific (West)

**Comment by PopeyeTheSai10r** [comment]
This is already included. See `https://github.com/iptv-org/epg/blob/master/sites/tvpassport.com/tvpassport.com_us.channels.xml`

Are you having issues seeing the data?

**Comment by freearhey** [comment]
https://iptv-org.github.io/epg/guides/us.xml
<img width="648" alt="image" src="https://user-images.githubusercontent.com/7253922/204255457-5370a66c-9fd6-4fa5-84fc-0a5e76313eae.png">

**Comment by spotanjo3** [comment]
Hello. Sorry to keep you wait. Its working fine now. Thanks.
