### ISSUE TITLE
The Travel Channel EAST

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1408]
### Channel ID

TravelChannelEast.us

### Source

https://www.tvpassport.com/tv-listings/stations/travel-us-east/662

### Notes

It was already in IPTV Search engine but the schedule on my TV showing different language that I cannot understand it So its obviously wrong region or something. And not properly tv schedule.

**Comment by spotanjo3** [comment]
No, its not working. I still received weird schedule from other country that I cannot read it. I deleted epg data and reloading and still received the same problem.

**Comment by freearhey** [comment]
Fixed.

**Comment by freearhey** [comment]
I have the same guide displayed as on tvpassport.com:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/7253922/204546539-8b864d89-4f3a-4f39-a216-28df7d8e5401.png">

**Comment by spotanjo3** [comment]
What did I do wrong?

**Comment by freearhey** [comment]
I don't know.

**Comment by spotanjo3** [comment]
I reduced to some EPG links because i think I messed them up and nkw everything is working properly included this channel. Everything is clean now. Good work.
