### ISSUE TITLE
Merge Arabic channels into one file

### ISSUE THREAD

**Issue by Shawkiiz** [iptv-org/epg#1412]
### Description

Iam using iptv and its allow me to use only one epg link, so could you allow me to merge more thane source into one link

**Comment by Shawkiiz** [comment]
Thx, i found a solution to merge them 🌹

**Comment by PopeyeTheSai10r** [comment]
You should share how you are merging. Others may find it useful.

**Comment by Shawkiiz** [comment]
I contact my iptv player support , and he explane to me how to use more than on source in same time from setting ❤️
