### ISSUE TITLE
ITV1 is suddenly missing from UK channel list

### ISSUE THREAD

**Issue by GlamoramaAttack** [iptv-org/epg#1424]
### Channel ID

ITV1.uk

### Source

https://sky.com

### Notes

The unique channel id is given as ITV1.uk but sky.com and bt.com list it as ITV.uk

`<channel id="ITV.uk"><display-name>ITV</display-name><icon src="https://i.imgur.com/SsgOgRF.png"/><url>https://sky.com</url></channel>`

or

`<channel id="ITV.uk"><display-name>ITV</display-name><icon src="https://i.imgur.com/SsgOgRF.png"/><url>https://bt.com</url></channel>`

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/3c6b202dc7aa9181b93ee3ed59014ff49fb90e32

The channel will appear in the guide after the next update.

**Comment by GlamoramaAttack** [comment]
Thanks again for your work!
