### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1431]
### Channel ID

Legend.uk

### Source

https://www.sky.com/tv-guide/

**Comment by GlamoramaAttack** [comment]
Except for Sky LEGEND is still referred in other guides as HORROR CHANNEL UK (as in https://iptv-org.github.io/epg/guides/uk.xml.gz) if you want a working EPG for it right now. Just tested it and it shows the program as in your Sky source for Legend. 

`<channel id="HorrorChannelUK.uk"><display-name>Horror Channel UK</display-name><icon src="https://i.imgur.com/yku1hpX.png"/><url>https://bt.com</url></channel>`

or if you use .m3u:

`#EXTINF:-1 tvg-id="HorrorChannelUK.uk" tvg-name="Horror Channel UK" tvg-logo="https://i.ibb.co/TcjBfyw/Legend.png" group-title="UK",Legend`

**Comment by Smark223** [comment]
Ah, interesting, I'd not noticed that had changed. When Horror Channel first closed that tvg-id was giving the EPG for Horror Xtra. According to the database, there is no EPG source for Horror Xtra but strangely there is one for Horror Xtra +1. Is it possible to add the EPG for Horror Xtra from that guide?
