### ISSUE TITLE
Add CBC stations

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1438]
### Source

https://www.tvpassport.com/tv-listings

### Channels

CBC Halifax - CBHT-DT - CBHTDT.ca
CBC Ottowa - CBOT-DT - CBOTDT.ca
CBC Winnipeg - CBWT-DT - CBWTDT.ca
CBC Calgary - CBRT-DT - CBRTDT.ca
CBC Edmonton - CBXT-DT - CBXTDT.ca

### Notes

Add EPG for other CBC stations. Vancouver, Toronto and Montreal already have valid sources

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/9f7162a08bd4ca03b944904553868622cad82704
