### ISSUE TITLE
Add EPG for a few Swiss channels

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1446]
### Source

https://tv.blue.ch/tv-guide

### Channels

7+  (7plus.ch)
Nick Schweiz (NickSchweiz.ch)
Blue Zoom F (BlueZoomF.ch)
Kanal 9 (Kanal9.ch)

### Notes

7+ Guide is shared between Nick Schweiz and 7+ as they share the same channel

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/dcc87f67032d147ad16b780e86f0397ea476fc07
