### ISSUE TITLE
Add more CBC Canada Channels

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1450]
### Source

https://www.tvpassport.com/tv-listings

### Channels

CBC Fredericton - CBAT-DT - CBATDT.ca
CBC St John's - CBNT-DT - CBNTDT.ca
CBC Toronto - CBLT-DT - CBLTDT.ca
CBC Montreal - CBMT-DT - CBMTDT.ca
CBC Vancouver - CBUT-DT - CBUTDT.ca

### Notes

CBC Toronto, Montreal and Vancouver already have EPG from another source but the tvpassport one is better as it provides full programme descriptions. Can tvpassport source be prioritised in the ca EPG for these channels or possibly remove them from the other one? 
CBC Fredericton and St John's do not currently have a source.

Thanks

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/e542850f392259e2823f19b4007c3375cbae8ac4

As for the priority, the bot already automatically selects a source with the most information. If in this case it is tvpassport.com, the guide will be loaded from there.

**Comment by Smark223** [comment]
Perfect, thanks
