### ISSUE TITLE
Sky Replay is missing from German channel list

### ISSUE THREAD

**Issue by GlamoramaAttack** [iptv-org/epg#1451]
### Source

https://horizon.tv

### Channels

Sky Replay Germany isn't the same channel as Sky Replay for the UK. 

`
<channel id="SkyReplay.de"><display-name>Sky Replay HD</display-name><icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Sky_Replay_DE_Logo_2021.svg/512px-Sky_Replay_DE_Logo_2021.svg.png"/><url>https://horizon.tv</url></channel>`

I recommend to change the display-name to 'Sky Replay Deutschland' or 'Sky Replay Germany' to avoid mix up with the British one.

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/7360a6e889696e71b021a4e5c35e495dc2c142d1
