### ISSUE TITLE
Swiss Canal 9/Kanal 9

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1454]
### Guide

https://iptv-org.github.io/epg/guides/ch.xml

### Description

https://github.com/iptv-org/epg/commit/dcc87f67032d147ad16b780e86f0397ea476fc07 added some Swiss channels but there is an error with Canal 9 / Kanal 9. These are separate channels - Kanal 9 is the German language version and Canal 9 is the French one. Both have separate programming and the guides for both are available at https://tv.blue.ch/tv-guide

Both were in the database previously but I think Kanal9.ch has been deleted. 

Canal9.ch has been added to the guide but is showing the EPG for Kanal 9 (the German version). Can you correct this to the French version and re-add the tvg-id and EPG for the German channel.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/30e22ef67796361456481eea8f3ea4cf5667432e

The German version now has the ID `Kanal9.ch` and the French `Canal9.ch`.
