### ISSUE TITLE
El33 Catalunya

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1466]
### Source

https://www.movistarplus.es/canal/canal-33?id=C33

### Channels

El33.es
CanalSuper3.es

### Notes

Please add gude for El33.es 

Guide also covers CanalSuper3.es which has now rebranded to SX3 - new logo - https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/SX3_logo.svg/300px-SX3_logo.svg.png

**Comment by PopeyeTheSai10r** [comment]
For the channel rebrand please create a [Pull Request](https://github.com/iptv-org/database/pulls) or [Issue](https://github.com/iptv-org/database/issues/new/choose) to the [database](https://github.com/iptv-org/database) repository.

**Comment by Smark223** [comment]
[0308ddf](https://github.com/iptv-org/epg/pull/1604/commits/0308ddf9d4da00d3bdd644f39d475e805a754e19) raised to add
