### ISSUE TITLE
No icon for these channels

### ISSUE THREAD

**Issue by Shawkiiz** [iptv-org/epg#1470]
### Guide

https://iptv-org.github.io/epg/guides/qa.xml

### Description

No icon for these channels :

- beIN Sports Premium 1
- beIN Sports Premium 2
- beIN Sports Premium 3

**Comment by Kamiela20100** [comment]
https://assets.bein.com/mena/sites/3/2015/06/beIN_SPORTS1_PREMIUM_Digital_Mono.png
https://assets.bein.com/mena/sites/3/2015/06/beIN_SPORTS2_PREMIUM_Digital_Mono.png
https://i.goalzz.com/?i=o%2Fh%2F1%2F894%2Fbein-sports-premium-1.png

**Comment by PopeyeTheSai10r** [comment]
Hello @Shawkiiz, The logo sources were updated as part of [b81670d](https://github.com/iptv-org/database/commit/b81670da79f65feaa4e3334b6152e5483541253a). Are the logos loading now?

**Comment by Shawkiiz** [comment]
Yes thx bro
