### ISSUE TITLE
for channels without epg data

### ISSUE THREAD

**Issue by Shawkiiz** [iptv-org/epg#1471]
### Description

you can add channel in the xml file to use its icone, even if there is no epg data

**Comment by PopeyeTheSai10r** [comment]
I personally don't think there would be a lot of support for this feature request considering there are some guides that are very big as they are and nearly reaching the [Github size](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#file-size-limits) limits. Adding more logos will just make those guides even bigger.
