### ISSUE TITLE
Virgin Radio TV

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1478]
### Source

https://www.superguidatv.it/programmazione-canale/oggi/guida-programmi-tv-virgin-radio/461/

### Channels

Virgin Radio TV - VirginRadioTV.it

**Comment by PopeyeTheSai10r** [comment]
The linked source requires a new config file.

I've added the EPG info from guidatv.sky.it in the meantime - https://github.com/iptv-org/epg/pull/1587/commits/75e6b6a0a1d73a42d82c432ccec23ff77cb67b9a

**Comment by freearhey** [comment]
The guide for Virgin Radio TV is now available at this link:

```
https://iptv-org.github.io/epg/guides/it/superguidatv.it.xml
```
