### ISSUE TITLE
channel request

### ISSUE THREAD

**Issue by ientau** [iptv-org/epg#1484]
### Source

https://iptv-org.github.io/epg/guides/id-en/mncvision.id.epg.xml

### Channels

DAAI TV
RTV
K PLUS
My Cinema Asia

### Notes

Hi,

Can you add the following channels on the Indonesia (MNC Vision) EPG please?

**Comment by PopeyeTheSai10r** [comment]
The following are already included in `https://iptv-org.github.io/epg/guides/id.xml`

DAAI TV (DAAITV.id)
Rajawali TV [RTV] (RajawaliTV.id)
My Cinema Asia (MyCinemaAsia.id)


Please provide the TVG-ID for **K PLUS**.

If the channel is not in the [database ](https://github.com/iptv-org/database)yet. You can follow the [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) and create a PR for it, or you can create a [new issue](https://github.com/iptv-org/database/issues/new/choose).

**Comment by PopeyeTheSai10r** [comment]
@ientau I couldn't find any of stations requested in mncvision.id. 
Do you have the direct link to the source (mncvision.id) for the channels you are requesting? Or any other source?

For example: BBC Earth -https://mncvision.id/channel/detail/200/bbc-earth/1
