### ISSUE TITLE
Channels from Xumo.tv

### ISSUE THREAD

**Issue by oldpoem** [iptv-org/epg#1488]
### Source

xumio.tv

### Channels

Dateline 24/7
ION Mystery
ION

### Notes

A lot of channels were left out of xumo.tv epg.  I'd like to request these 3 channels I watch most.

Channel ID: 99991626   Dateline 24/7
Channel ID:  99951157 ION Mystery
Channel ID: 99951158 ION

All is working fine but is  commented out in xumotv xml. 

Thanks.

**Comment by PopeyeTheSai10r** [comment]
Hello, Do you happen to know the TVG-ID for the ION and ION Mystery channel you want added?

**Dateline 24/7** is not a channel is part of the [database ](https://github.com/iptv-org/database)yet. You can take a look at the [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) If you feel comfortable adding the channel yourself.

**Comment by oldpoem** [comment]
I just found out that ION is IONTVast.us  so its epg s already available.   ION Mystery has no other alternative and has no TVG-ID for now.

All three is already in xumotv channels config  but got omitted out.  I think it's matter of enable those in xml for scraping.
https://github.com/iptv-org/epg/blob/master/sites/xumo.tv/xumo.tv_us.channels.xml

Is there any good github client for android?  I don't have access to PC for quite some time. And not comfortable to do csv editing and create pull request with my tablet.

**Comment by PopeyeTheSai10r** [comment]
ION = IONTVEast.us
ION Mystery = WPXNDT3.us

**Comment by oldpoem** [comment]
Thank you!

What about the Dateline 24/7? It's most likely internet only channel.  I scanned other internet streams db (Pluto,Plex,Stirr etc.) but can't find alternative / existing TVG-ID.

**Comment by PopeyeTheSai10r** [comment]
We can only add EPG for channels that have been added to the [Database](https://github.com/iptv-org/database). Dateline 24/7 isn't there yet. You can use https://iptv-org.github.io/ to search the database. If you can find all the required information for Dateline 24/7, feel free to create a [new issue ](https://github.com/iptv-org/database/issues/new/choose) and one of the contributors should be able to add it to the database.

All the required information can be found at https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md

**Comment by oldpoem** [comment]
Is this ok?

https://github.com/iptv-org/database/issues/1466

**Comment by Mikhel** [comment]
> Is this ok?
> 
> [iptv-org/database#1466](https://github.com/iptv-org/database/issues/1466)

sorry for asking here but... is there a xumo.xml.gz to download the file and get the EPG? would you point me to it?

Thanks.

**Comment by oldpoem** [comment]
I believe all of them is included in us.xml

but if you really want specific xumotv epg.  here is the link

https://iptv-org.github.io/epg/guides/us/xumo.tv.epg.xml
