### ISSUE TITLE
Add TCM West EPG

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1498]
### Source

https://www.directv.com/guide

### Channels

TCMWest.us

**Comment by PopeyeTheSai10r** [comment]
> DirecTV only carries TCM East, so that site doesn't have a listing for the West feed.

Adding a bit more information to this. The schedule for "East" and "West" is the exact same schedule just 3 hours difference.

**Comment by Smark223** [comment]
Oh, I was sure I found the listing for TCM West on DirecTV. Apologies if this is incorrect. 

I realise the EPG is the same as TCM East but time shifted by 3 hours but it's an anomaly that we don't have a working guide for the west version, as the other stations in the same group (TNT, TBS, truTV, Cartoon Network) all have listings for both east and west. Do you know if there's another source available? I think tvpassport may have it, possibly?
