### ISSUE TITLE
provide a single EPG with all channel data

### ISSUE THREAD

**Issue by khimaros** [iptv-org/epg#1504]
### Description

i was not able to find any open source linux IPTV clients with support for reading EPG data from the `x-tvg-url` parameter. it would be great to have a single unified EPG file which could be added to clients like iptvnator rather than needing to manually add every single country's EPG data to the list.

**Comment by PopeyeTheSai10r** [comment]
Very unlikely to happen due to Github's [file size limitation](https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository#adding-a-file-to-a-repository-on-github).
