### ISSUE TITLE
Toonami Aftermath Schedule is Incomplete

### ISSUE THREAD

**Issue by cr0op** [iptv-org/epg#1507]
### Guide

https://iptv-org.github.io/epg/guides/us.xml

### Description

the schedule's only listed from 12pm to 7pm each day, even tho T.A. is a 24-hour station.

**Comment by MajinLugia** [comment]
The guide isn’t showing anything now and I really hope this will get fixed since I added this channel on kodi.

**Comment by RevGear** [comment]
Guide should be showing the full 24 hrs now
