### ISSUE TITLE
Dateline 24/7

### ISSUE THREAD

**Issue by oldpoem** [iptv-org/epg#1508]
### Source

https://www.xumo.tv/live-guide/dateline-24-7

### Channels

Dateline247.us

### Notes

It is already in xumo.tv.us but commentted off  because the channel was not existed in database.  It was added to database recently.  So please update xumo tv config for scraping epg.

https://iptv-org.github.io/epg/guides/us/xumo.tv.epg.xml

**Comment by PopeyeTheSai10r** [comment]
Duplicates #1488
