### ISSUE TITLE
Adding extra time for EPG list xml file to solve Unsync EPG-TV content

### ISSUE THREAD

**Issue by konrul-r10** [iptv-org/epg#151]
Hello, I am able to get EPG list but it is not sync with the TV show. There is 4 hours gap for me. But I have solved the issue adding +0400 in the XML file. Here is the example:

`<programme start="20211018234500 +0400" stop="20211019003500 +0400" channel="BBC EARTH">`

How can I add that +0400 to this list automatically? 

I will be thankful for your help. Best wishes.

**Comment by konrul-r10** [comment]
> That would need some understanding of regular expression. Using your favorite Notepad, assuming the end time of the program is always "00", use a regex that'll replace each iteration of "00" to "00 +0400"

Thank you LaneSh4d0w but which file should I edit? If the output XML file, I already did it manually. Is there any way to do it in config.js file?

**Comment by LaneSh4d0w** [comment]
> > That would need some understanding of regular expression. Using your favorite Notepad, assuming the end time of the program is always "00", use a regex that'll replace each iteration of "00" to "00 +0400"
> 
> Thank you LaneSh4d0w but which file should I edit? If the output XML file, I already did it manually. Is there any way to do it in config.js file?

The XML file, since it's there in which the program's times are shown.

There might be a possibility using Moment.js, i shall check that.

**Comment by konrul-r10** [comment]
Thank you very much for your help!

**Comment by LaneSh4d0w** [comment]
Could you tell me which EPG is concerned by the issue you're pointing ?

**Comment by konrul-r10** [comment]
this one : [https://github.com/iptv-org/epg/tree/master/sites/digiturk.com.tr](url)
I want to learn such thing as to synchronize EPG info with TV shows.
