### ISSUE TITLE
channel request

### ISSUE THREAD

**Issue by ientau** [iptv-org/epg#1512]
### Source

https://iptv-org.github.io/epg/guides/id.xml

### Channels

channel id=K-PLUSHD.Id

channel id=AsianFoodNetwork.sg

channel id=CCM.hk

channel id=MyCinemaAsia.Id

### Notes

the channel exist "channel id=MyCinemaAsia.id" not working
maybe capital "channel id=MyCinemaAsia.Id"

the channel exist "channel id="KPlus.sg"  not working
maybe "channel id="K-PLUSHD.Id"

**Comment by PopeyeTheSai10r** [comment]
`K-PLUSHD.Id` is not a valid TVG-ID - https://iptv-org.github.io/

**Comment by freearhey** [comment]
- `KPlus.sg`: https://iptv-org.github.io/?q=KPlus.sg (3 guides)
- `AsianFoodNetwork.sg`: https://iptv-org.github.io/?q=AsianFoodNetwork.sg (12 guides)
- `CCM.hk`: https://iptv-org.github.io/?q=CCM.hk (7 guides)
- `MyCinemaAsia.id`: `https://iptv-org.github.io/epg/guides/id/useetv.com.xml`
