### ISSUE TITLE
.gz or .zip compress epg .xml files?

### ISSUE THREAD

**Issue by mark-summerfield** [iptv-org/epg#1523]
### Description

Would it be possible to offer compressed files?
For example `https://iptv-org.github.io/epg/guides/uk.xml` is about 11MB but compressed with gzip goes down to 1.5MB. Wouldn't that benefit this site as well as users?

**Comment by freearhey** [comment]
> All guides also have a compressed and JSON version. To download them, simply change the extension from `.xml` to `.xml.gz` or `.json` respectively.

https://github.com/iptv-org/epg/blob/master/README.md

**Comment by mark-summerfield** [comment]
Sorry for not seeing that. I only looked down the list as far as uk.xml; didn't think to see if there was any text at the end. Thank you!
