### ISSUE TITLE
Austria XML URL

### ISSUE THREAD

**Issue by morlan** [iptv-org/epg#154]
Noticed the Austria URL isn’t listed but there are channels in the search.

**Comment by freearhey** [comment]
This channel is only in the guide from https://m.tv.sms.cz

```
https://iptv-org.github.io/epg/guides/cz/m.tv.sms.cz.epg.xml
```

but their program guide for this channel is not particularly useful at the moment

![image](https://user-images.githubusercontent.com/7253922/138389786-27841ca8-b720-4ed7-865a-8d799b6c65f0.png)
