### ISSUE TITLE
Premier Sports 1 UK

### ISSUE THREAD

**Issue by Kamiela20100** [iptv-org/epg#1542]
### Source

https://www.ontvtonight.com/uk/guide/listings/channel/69042004/premier-sports.html

### Channels

Premier Sports 1 UK

**Comment by RevGear** [comment]
Channel is now called Viaplay Sports 1 (ViaplaySports1.uk)
Available in UK and IE guides
https://iptv-org.github.io/epg/guides/ie.xml
https://iptv-org.github.io/epg/guides/uk.xml
