### ISSUE TITLE
RTL Tele Luxembourg

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1549]
### Guide

https://iptv-org.github.io/epg/guides/lu.xml

### Description

RTLTeleLuxembourg.lu is showing incorrect EPG info. It seems to be picking up EPG for RTLGermany.de

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/937447caebe4b8a189b6b0f56ceef76bfb1273e3 and https://github.com/iptv-org/epg/commit/2a66d878f997ac7bb833c22fec8ec2a798643ab7
