### ISSUE TITLE
TVCG Mne

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1550]
### Source

https://tvprofil.com/gb/tvschedule/#!kanal=tvcg-sat

### Channels

TVCGMNE.me

**Comment by PopeyeTheSai10r** [comment]
@Smark223 is this working for you now?

**Comment by Smark223** [comment]
@PopeyeTheSai10r No, like TVCG 1 and 2, it's still not working.

**Comment by RevGear** [comment]
I hadn't spotted earlier but the `tvprofil.com` grabber is currently disabled. There was an update in Feb 22 to say the server wasn't stable,

**Comment by freearhey** [comment]
The guide for TVCG Mne from tvprofil.com is now available at this link:

```
https://iptv-org.github.io/epg/guides/hr/tvprofil.com.xml
```

The rest of the guides for this channel can be found at https://iptv-org.github.io/?q=TVCG%20Mne
