### ISSUE TITLE
TVCG 1 and TVCG 2

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1551]
### Source

https://tvprofil.com/gb/tvschedule/

### Channels

TVCG1.me - https://tvprofil.com/gb/tvschedule/#!kanal=tvcg1
TVCG2.me - https://tvprofil.com/gb/tvschedule/#!kanal=tvcg2

**Comment by RevGear** [comment]
Both are already in the channel list, but are not showing in combined guide due to the language not matching.
Added PR 1567 to Database repro to resolve

**Comment by PopeyeTheSai10r** [comment]
@Smark223 is this working for you now?

**Comment by Smark223** [comment]
@PopeyeTheSai10r No, still not working

**Comment by RevGear** [comment]
I hadn't spotted earlier but the `tvprofil.com` grabber is currently disabled. There was an update in Feb 22 to say the server wasn't stable,

**Comment by Smark223** [comment]
Oh, is it possible that it's now stable and could be re-enabled?

**Comment by freearhey** [comment]
The guide for TVCG 1 and TVCG 2 is now available at:

```
https://iptv-org.github.io/epg/guides/hr/tvprofil.com.xml
```
