### ISSUE TITLE
Nitro for Germany

### ISSUE THREAD

**Issue by GlamoramaAttack** [iptv-org/epg#1556]
### Source

https://horizon.tv

### Channels

`<channel id="NitroGermany.de"><display-name>Nitro Germany</display-name><icon src="https://ocdn.eu/ptv2-images-transforms/1/VGnkrdsb2dvLW1pZ3JhdGVkL25pdHJvLmpwZ5KVAmQAwsOVAgAowsM"/><url>https://horizon.tv</url></channel>`

**Comment by PopeyeTheSai10r** [comment]
`NitroGermany.de` is not a valid TVG-ID. It has changed to `Nitro.de`
