### ISSUE TITLE
Guides keep dissappearing in KODI

### ISSUE THREAD

**Issue by juniorpainkiller** [iptv-org/epg#1557]
### Description

Not sure how many of you use these URLs in Kodi, but did someone had disappearance issues after adding URLs or xml files? Usually it's fine at the start (exc ept for some important guides missing) , but after I add more than five URLs, the old ones dissappear completely. Thanks!

**Comment by PopeyeTheSai10r** [comment]
Sounds like this is not a guide issue but a Kodi issue.

Either Kodi or the device you are using is not able to handle more than 5 EPG URLs. You should try a different  [IPTV Player](https://github.com/iptv-org/awesome-iptv#apps) to see if that helps.

**Comment by juniorpainkiller** [comment]
Yeah, I was using IPTV Extreme which has it's own EPG sources- and it downloads it instantly.It's kinda niche, but I would like to have EPG on Kodi because I'm using it for everything. YT, Films, TV, you name it.
