### ISSUE TITLE
Mbc

### ISSUE THREAD

**Issue by Shawkiiz** [iptv-org/epg#1572]
### Source

https://iptv-org.github.io/epg/guides/sa.xml

### Channels

- mbc 2
- mbc max

**Comment by PopeyeTheSai10r** [comment]
https://iptv-org.github.io/epg/guides/sa.xml should have guide for MBC 2 `MBC2.ae` & MBC Max `MBCMax.ae` as per https://iptv-org.github.io/?q=country:AE%20MBC
