### ISSUE TITLE
KION TV2 MONTEREY, KFJX PITTSBURG, KFNB CASPER

### ISSUE THREAD

**Issue by Kamiela20100** [iptv-org/epg#1574]
### Source

https://www.tvpassport.com/tv-listings/stations/fox-35-kiontv2-monterey-ca/11612  https://www.tvpassport.com/tv-listings/stations/fox-kfjx-pittsburg-ks/2426  https://www.tvpassport.com/tv-listings/stations/fox-kfnb-casper-wy/9916   

### Channels

FOX KOIN TV 2 MONTEREY
FOX KFJX PITTSBURG KANSAS
FOX KFNB CASPER WY

### Notes

Thanks in advance

**Comment by PopeyeTheSai10r** [comment]
FOX KOIN TV 2 MONTEREY needs to be added to the [database](https://github.com/iptv-org/database). 
You can take a look at the [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) and either create a pull request or an [issue](https://github.com/iptv-org/database/issues/new?assignees=&labels=&template=channels_add.yml&title=Add%3A+).

**Comment by PopeyeTheSai10r** [comment]
`KFJXDT1.us` & `KFNBDT1.us` added in https://github.com/iptv-org/epg/commit/1101d05d0218dbb8e72cd92671d7df73d2860323.

**Comment by Kamiela20100** [comment]
KFNBDT1 seems to be not working correctly

**Comment by ajanes3** [comment]
`KIONDT1.us` added with pr #1701
