### ISSUE TITLE
ARTE Channels EPG not working

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1575]
### Guide

https://iptv-org.github.io/epg/guides/de.xml

### Description

tvg-ids for ARTE Germany and ARTE France seem to have been changed in the database and no longer match what is in https://iptv-org.github.io/epg/guides/de.xml and https://iptv-org.github.io/epg/guides/fr.xml so guides are not working.

EPG for ARTE Germany available at https://www.hd-plus.de/epg/

EPG for ARTE France available at https://chaines-tv.orange.fr/

**Comment by Smark223** [comment]
Has the French version been fixed too? If not, I'll raise another issue

**Comment by PopeyeTheSai10r** [comment]
Yes, that was fixed too.

ARTE Germany - Fixed in https://github.com/iptv-org/epg/commit/beca01055d569a518dddabff9c33932d30f7cca5
ARTE France - Fixed in https://github.com/iptv-org/epg/pull/1576/commits/488cdfb81210a1961d1339ec5d3a76338285b865
