### ISSUE TITLE
tvguide.com

### ISSUE THREAD

**Issue by fachos** [iptv-org/epg#1579]
### Description

Hi..

Can you add channels without ****East.us** at the end? need ****.us** only... i try to edit but  i dont know the channel source Ids.... hope you can help me... 

thank you

**Comment by GlamoramaAttack** [comment]
If you don't know the channel IDs how do you know you NEED .us only? It makes no sense. And the US has different time zones so of course East and West need to be included.

**Comment by fachos** [comment]
9233011874 
9200000057 
9200017734 
9200020107 
9233013462 
9200009303 
9233015844 
9200020094 
9200004533 
9200018514 
9233015468 
9200000143 
9233000169 
9233001926 
9200009145 
9233008130 
9233009509 
9233007144 
9233011398 
9233011398 
9200014472 
9200011893 
9200016560 
9233003794 
9200016131 
9200006523 
9233011350 
9233005598 
9233002271 
9200009124 
9233006969 
9233003497 
9200000497 
9200009884 
9233006959 
9233013967 
9200014910 
9200019858 
9200016034 
9200004467 
9233005762 
9200020115 
9233015369 
9200000502 
9200000502 
9200009223 
9233003479 
9233006803 
9233015501 
9200004683 
9233009876 
9233011497 
9200020469 
9233008939 
9200004740 
9200012145 
9233004141 
9200018304 
9200019847 
9233002484 
9233013809 
9233001687
9200004316
9200011857
9200016249
9233000035
9233005468 
9200016258 
9233003770 
9200004247 

i try edit the config... scan is good without error but only grab abc/cnn... others empty output

**Comment by PopeyeTheSai10r** [comment]
> i try edit the config... scan is good without error but only grab abc/cnn... others empty output

Channels should be added to the site.channels.xml file. Not the config file. Check out the [Contribution Guide](https://github.com/iptv-org/epg/blob/master/CONTRIBUTING.md#contributing-guide)

**Comment by PopeyeTheSai10r** [comment]
> ...
> 9233006969
> 9233003497
> 9200000497
> ...


You are missing information here. For it to work, you will need the **ProviderId** and **ChannelID**

**Comment by freearhey** [comment]
Closed due to lack of response.
