### ISSUE TITLE
Syntax Error in AU Guide

### ISSUE THREAD

**Issue by lhvy** [iptv-org/epg#1581]
### Guide

https://iptv-org.github.io/epg/guides/au.xml

### Description

Visiting the guide's URL, or inputting it into xteve results in the following error:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/40507205/209943609-6683b929-24eb-437c-beac-bacfd9a6ea00.png">

**Comment by RevGear** [comment]
There are a couple of programmes with a rating of `B&W`.

`<programme start="20221228152000 +0000" stop="20221228170000 +0000" channel="7flix.au"><title lang="en">Obliging Young Lady</title><desc lang="en">A comedy about a young girl caught in a custody battle who finds herself the centre of attention at a mountain resort.</desc><rating system="ACB"><value>B&W</value></rating></programme>`

`<programme start="20221229163000 +0000" stop="20221229180000 +0000" channel="7flix.au"><title lang="en">The Woman On Pier 13</title><desc lang="en">A newly married shipping magnate is blackmailed into returning to the Communist Party.</desc><rating system="ACB"><value>B&W</value></rating></programme>`

I assume it's a error in the source data as that's not even a valid ACB rating

**Comment by RevGear** [comment]
@freearhey this might be easier for you to fix in the epg-grabber project. Use escapeString when writing the rating value.

**Comment by freearhey** [comment]
@RevGear fixed in [v0.29.5](https://github.com/freearhey/epg-grabber/releases/tag/v0.29.5)
