### ISSUE TITLE
Can someone crawl all these channels from this site?

### ISSUE THREAD

**Issue by kronics** [iptv-org/epg#1598]
### Source

https://www.zuragt.mn/

### Channels

https://www.zuragt.mn/channel/mnb/ | MNB.mn | МҮОНТ
https://www.zuragt.mn/channel/ubs-1/ | UBS.mn | UBS
https://www.zuragt.mn/channel/mn25/ | TV25.mn | TV25
https://www.zuragt.mn/channel/tv5/ | TV5.mn | TV5
https://www.zuragt.mn/channel/tv9/ | TV9.mn | TV9
https://www.zuragt.mn/channel/c1/ | C1.mn | C1
https://www.zuragt.mn/channel/sbn/ | SBN.mn | SBN
https://www.zuragt.mn/channel/ntv/ | NTV.mn | NTV
https://www.zuragt.mn/channel/bolovsrol/ | eduTV.mn | eduTV
https://www.zuragt.mn/channel/central_tv/ | CentralTV.mn | Central TV
https://www.zuragt.mn/channel/mongol_tv/ | MongolTV.mn | Монгол ТВ
https://www.zuragt.mn/channel/tv8/ | TV8.mn | TV8
https://www.zuragt.mn/channel/etv/ | ETV.mn | ETV HD
https://www.zuragt.mn/channel/moviebox/ | MovieBox.mn | MovieBox
https://www.zuragt.mn/channel/star-tv/ | StarTV.mn | Star TV
https://www.zuragt.mn/channel/tv7/ | TV7.mn | TV7
https://www.zuragt.mn/channel/niislel-tv/ | NiislelTV.mn | Нийслэл ТВ
https://www.zuragt.mn/channel/eco_suvag/ | EcoChannel.mn | Eco Channel
https://www.zuragt.mn/channel/dream/ | Dream.mn | Dream
https://www.zuragt.mn/channel/mnc/ | MNC.mn | MNC
https://www.zuragt.mn/channel/sps-prime/ | SPSPrime.mn | SPS Prime
https://www.zuragt.mn/channel/sps-plus/ | SPSPlus.mn | SPS Plus
https://www.zuragt.mn/channel/sps-nba/ | SPSNBATV.mn | SPS NBA TV
https://www.zuragt.mn/channel/sps-global/ | SPSGlobal.mn | SPS Global
https://www.zuragt.mn/channel/sps-national/ | SPSNational.mn | SPS National
https://www.zuragt.mn/channel/Bloomberg_TV_Mongolia/ | BloombergTVMongolia.mn | Bloomberg TV Mongolia
https://www.zuragt.mn/channel/suld_tv_mongolia/ | SuldTV.mn | Сүлд ТВ
https://www.zuragt.mn/channel/asianbox/ | AsianBox.mn | AsianBox
https://www.zuragt.mn/channel/tm/ | TMTV.mn | TM TV
https://www.zuragt.mn/channel/ntn/ | NTN.mn | NTN
https://www.zuragt.mn/channel/mnb-sport/ | MNBSport.mn | MNB Sport
https://www.zuragt.mn/channel/parlament-televiz/ | ParliamentTV.mn | Parliament TV | Парламент телевиз
https://www.zuragt.mn/channel/suvag-1/ | Suvag1.mn | Суваг 1
https://www.zuragt.mn/channel/tenger/ | TenGerTV.mn | TenGer TV

### Notes

i tested mongolian channel epgs.
https://iptv-org.github.io/iptv/countries/mn.m3u
but there wasn't any mongolian channel. all channels were wrong international channels, yet time's all wrong.
can someone remove all those wrong channels?

**Comment by kronics** [comment]
any update on this?

**Comment by freearhey** [comment]
The guide from zuragt.mn is now available at:

```
https://iptv-org.github.io/epg/guides/mn/zuragt.mn.xml
```
