### ISSUE TITLE
Add EPG from excel

### ISSUE THREAD

**Issue by NotKrma** [iptv-org/epg#1606]
### Description

I have the guide for a channel in Argentina, which they send us in excel, is it possible to add it to the rest? At the moment it is not on any website.

**Comment by LaneSh4d0w** [comment]
Some libraries exist in JavaScript to read Excel files, though we would need additional information on how the Excel looks like. Is it "Channel" on the top, and "Time" on the left, or something else ?

**Comment by NotKrma** [comment]
> 

Is there somewhere I can send it to you so you can see it?

**Comment by LaneSh4d0w** [comment]
> > 
> 
> Is there somewhere I can send it to you so you can see it?

You can send it here in a compressed file, or email it to me, available in my profile.

**Comment by NotKrma** [comment]
> > > 
> > 
> > 
> > Is there somewhere I can send it to you so you can see it?
> 
> You can send it here in a compressed file, or email it to me, available in my profile.

I sent it to you by email

Thanks.
