### ISSUE TITLE
Investigation Discovery West, Lifetime West, METV +, Great American Living, CBS KEYT

### ISSUE THREAD

**Issue by Kamiela20100** [iptv-org/epg#1608]
### Source

https://www.tvpassport.com/tv-listings/stations/investigation-discovery-usa-pacific/19949,  https://www.ontvtonight.com/guide/listings/channel/69035696/lifetime-television-west.html,  https://www.ontvtonight.com/guide/listings/channel/1716558649/kyaz-metv.html, https://www.ontvtonight.com/guide/listings/channel/1226188354/ride-tv.html,  
https://keyt.com/tv-listings/   

### Channels

Investigation Discovery West 
Lifetime Television West 
METV + 
Great American Living 
CBS KEYT Santa Barbara California

### Notes

Thanks in advance

**Comment by PopeyeTheSai10r** [comment]
The following will need to be added to the [Database](https://github.com/iptv-org/database). 

**Great American Living
CBS KEYT Santa Barbara California**

You can take a look at the [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) and either create a pull request or an [issue](https://github.com/iptv-org/database/issues/new?assignees=&labels=&template=channels_add.yml&title=Add%3A+).

**Comment by PopeyeTheSai10r** [comment]
Added Investigation Discovery West, Lifetime Television West and METV + in ad27598cb113e4ca65d6a89710056746f5ff20e6

**Comment by ajanes3** [comment]
Added KEYTDT1.us through 3 on tvpassport.com in PR #1701

**Comment by PopeyeTheSai10r** [comment]
@Kamiela20100, Please confirm which of the two below matches the program data you need?

https://www.tvpassport.com/tv-listings/stations/gac-living/16158
https://www.ontvtonight.com/guide/listings/channel/1226188354/ride-tv.html

**Comment by Kamiela20100** [comment]
https://www.tvpassport.com/tv-listings/stations/gac-living/16158

Thanks
