### ISSUE TITLE
EPG BR mi.tv

### ISSUE THREAD

**Issue by thug-thug** [iptv-org/epg#1615]
### Guide

https://iptv-org.github.io/epg/guides/br/mi.tv.epg.xml

### Description

Dont work more, 
The page is no longer accessible and also the content is no longer downloaded. I'm a little layman I tried to collect as much information as possible but I didn't get much.

IMG: https://i.imgur.com/mv9BVTm.png

**Comment by RevGear** [comment]
The old source specific guide have now been turned off. You need to use one of the combined country guide listed on the main page.

For Brazil you'll need [https://iptv-org.github.io/epg/guides/br.xml](url)
