### ISSUE TITLE
The Belgium Telenet EPG gives error 404 Page not found

### ISSUE THREAD

**Issue by david63236** [iptv-org/epg#1616]
### Guide

https://iptv-org.github.io/epg/guides/be/telenet.tv.epg.xml

### Description

Is it possible that the link for the Belgium Telenet EPG has changed?

**Comment by RevGear** [comment]
The old source specific guide have now been turned off. You need to use one of the combined country guide listed on the main page.

For Belgium you'll need [https://iptv-org.github.io/epg/guides/be.xml](url)

**Comment by boeder8** [comment]
> The old source specific guide have now been turned off. You need to use one of the combined country guide listed on the main page.
> 
> For Belgium you'll need [https://iptv-org.github.io/epg/guides/be.xml](url)

Hello,

Any chance it can be turned on?

For e.g. the specific Ivory Coast Canal+ Afrique is NOT included within the combined Ivory Coast guide

https://iptv-org.github.io/epg/guides/ci/canalplus-afrique.com.epg.xml

This is the case with most of the guides: France, Germany, Netherlands, Italy,

**Comment by orhtun01** [comment]
YES... please RE ENABLE the previous links. The combined versions are not picking correctly from the correct sources. Unless we can define to pick up which channels from which main source.

**Comment by ckgib** [comment]
I also agree- please if we can leave the previous links available. As stated, there are a number of channels that are included in the site specific xml files and not the general country ones.

**Comment by nickleby** [comment]
I agree, I beleive it's better to have links for different sites as before instead of a single one. It fails to load the EPG for some IDs and also it ends loading a XML with a bunch of channels that perhaps not eveyone needs.

**Comment by F640** [comment]
XD, i agree too. I'm also wondering why they made this change? The previous one has no problems

**Comment by david63236** [comment]
old : https://iptv-org.github.io/epg/guides/be/telenet.tv.epg.xml
new : https://iptv-org.github.io/epg/guides/be.xml

The old contained program descriptions (<desc> tag), the new (combined country guide) doesn't for most channels.
Exemple : Eén, Canvas, ...

Please add the "be/telenet.tv.epg.xml" <desc> tags to "be.xml"

**Comment by RevGear** [comment]
As of today the guides have been re-structured to split by language and provider. It became clear that the country grouping wasn't working as expected. You will need to update you player to use the new URL(s)

See https://github.com/iptv-org/epg#guides for a list of available guides.
