### ISSUE TITLE
Viasat Explore Turkish

### ISSUE THREAD

**Issue by Taru38** [iptv-org/epg#1617]
### Source

http://webgrabplus.com/epg-channels#s300

### Channels

Viasat Explore TR

**Comment by PopeyeTheSai10r** [comment]
Hello @Taru38m, It seems like the station you are requesting isn't in the Database yet. https://iptv-org.github.io/?q=Viasat%20Explore 

Viasat Explore Turkish needs to be added to the [database](https://github.com/iptv-org/database) before we can try to source the EPG.
You can take a look at the [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) and either create a pull request or an [issue](https://github.com/iptv-org/database/issues/new?assignees=&labels=&template=channels_add.yml&title=Add%3A+).

**Comment by Taru38** [comment]
Hello PopeyeTheSai0r,
Thank you for your answer.

**Comment by freearhey** [comment]
There is no EPG at the link.
