### ISSUE TITLE
UK TV EPG gone?

### ISSUE THREAD

**Issue by WarrenTho** [iptv-org/epg#1620]
### Guide

http://iptv-org.github.io/epg/guides/uk.xml

### Description

What’s happened to the uk and us epg?

**Comment by orhtun01** [comment]
The guides /epg's have been consolidated into one file per country  and the old links have been removed.

**Comment by WarrenTho** [comment]
So where do I find that?Sent from my iPhoneOn 7 Jan 2023, at 10:04, orhtun01 ***@***.***> wrote:﻿
The guides /epg's have been consolidated into one file per country  and the old links have been removed.

**Comment by WarrenTho** [comment]
Where do I find the new url?

**Comment by orhtun01** [comment]
Might be that the list is being updated or being recreated. UK was there about an hour ago.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/1786c74db97fa6e8b2e5662a823733e39d6cac04

**Comment by WarrenTho** [comment]
Thanks
