### ISSUE TITLE
new epg link is broken (Brazil EPG)

### ISSUE THREAD

**Issue by Rferreira2k** [iptv-org/epg#1621]
The new link provided (https://iptv-org.github.io/epg/guides/br.xml) is broken, returning error 404.

From what I've observed, the problem happens to many countries.

Thanks!

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/1786c74db97fa6e8b2e5662a823733e39d6cac04

**Comment by Rferreira2k** [comment]
Ultra fast solution :) 

Thanks a lot!

**Comment by thug-thug** [comment]
broken again, 
https://iptv-org.github.io/epg/guides/br.xml
i'm passing by just to signal.
