### ISSUE TITLE
new merged epg brokem

### ISSUE THREAD

**Issue by Zoom-Adr** [iptv-org/epg#1624]
### Guide

https://iptv-org.github.io/epg/guides/sg.xml

### Description

most epg channels not loading after the recent merged updates.

**Comment by Dexer125** [comment]
+1 Same for CZ

**Comment by RevGear** [comment]
As of today the guides have been re-structured to split by language and provider. You will need to update you player to use the new URL(s)

See https://github.com/iptv-org/epg#guides for a list of available guides.
