### ISSUE TITLE
Czech EPG not updated 

### ISSUE THREAD

**Issue by Dexer125** [iptv-org/epg#1631]
### Guide

https://iptv-org.github.io/epg/guides/cz.xml

### Description

Guide not updated even when workflow for m.tv.sms.cz was done successful and also update workflow was done successful.

**Comment by RevGear** [comment]
As of today the guides have been re-structured to split by language and provider. You will need to update you player to use the new URL(s)

See https://github.com/iptv-org/epg#guides for a list of available guides.
