### ISSUE TITLE
VSIN, NBC Sports Boston, World Fishing Network

### ISSUE THREAD

**Issue by Kamiela20100** [iptv-org/epg#1633]
### Source

https://flixed.io/tv-guide/channels/vsin, https://www.tvpassport.com/tv-listings/stations/nbc-sports-boston/4529,  https://www.worldfishingnetwork.com/schedule/77420

### Channels

VSIN
NBC Sports Boston 
World Fishing Network WFN

### Notes

Thanks

**Comment by PopeyeTheSai10r** [comment]
Added **NBC Sports Boston** and **World Fishing Network WFN** in ad27598cb113e4ca65d6a89710056746f5ff20e6

**Comment by freearhey** [comment]
VSiN: `https://iptv-org.github.io/epg/guides/en/flixed.io.xml`
NBC Sports Boston: `https://iptv-org.github.io/epg/guides/en/tvpassport.com.xml`
World Fishing Network: `https://iptv-org.github.io/epg/guides/en/worldfishingnetwork.com.xml`
