### ISSUE TITLE
Updated EPG links no longer include Digiturk (Turkey)

### ISSUE THREAD

**Issue by bark1n9** [iptv-org/epg#1651]
### Description

I saw the updated EPG links however the old Turkey EPG link included Digiturk as one of the sources. I can't seem to find Digiturk in the new list.

**Comment by freearhey** [comment]
The site has disappeared from the list because its API has changed and currently returns an error:

> The requested URL was rejected. Please consult with your administrator.

https://www.digiturk.com.tr/yayin-akisi/api/program/kanal/483/2023-01-11/0

**Comment by bark1n9** [comment]
Ok, thanks for the reply. Hopefully it gets resolved soon.

**Comment by s-digweed** [comment]
I think this was fixed by WebGrabber a day or so ago but I don't like to use them and prefer to support you guys.

Any chance this can checked?

**Comment by RevGear** [comment]
digiturk.com.tr guides are now available again
