### ISSUE TITLE
OSN.com Guide Missing 

### ISSUE THREAD

**Issue by boeder8** [iptv-org/epg#1654]
### Guide

osn.com

### Description

Hello,

The English + Arabic guide for OSN.com is missing.

Can it be added?

Thanks

**Comment by PopeyeTheSai10r** [comment]
The site has disappeared from the list because its currently returns an error.

> Request failed with status code 302

**Comment by boeder8** [comment]
> The site has disappeared from the list because its currently returns an error.
> 
> > Request failed with status code 302

Ah I see.

302 is a website temporarily moved, no?

The below URLs work:

Arabic EPG
https://www.osn.com/ar-sa/watch/tv-schedule/

English EPG
https://www.osn.com/en-sa/watch/tv-schedule/

Apologies if this info is not useful.

**Comment by PopeyeTheSai10r** [comment]
On Jan 05, 2023 osn.com server began to return an 302 error on every request.

https://github.com/iptv-org/epg/actions/runs/3843567638/jobs/6545935654

```
[1/404] osn.com - AlAanTV.ae - Jan 14, 2023 (0 programs)
  Error: Request failed with status code 302
[2/404] osn.com - AlAanTV.ae - Jan 15, 2023 (0 programs)
  Error: Request failed with status code 302
```

Using the same config, channel list and different IP works

```
[1/404] osn.com - AlAanTV.ae - Jan 14, 2023 (47 programs)
[2/404] osn.com - AlDafrahTV.ae - Jan 14, 2023 (24 programs)
```

**Comment by boeder8** [comment]
> On Jan 05, 2023 osn.com server began to return an 302 error on every request.
> 
> https://github.com/iptv-org/epg/actions/runs/3843567638/jobs/6545935654
> 
> ```
> [1/404] osn.com - AlAanTV.ae - Jan 14, 2023 (0 programs)
>   Error: Request failed with status code 302
> [2/404] osn.com - AlAanTV.ae - Jan 15, 2023 (0 programs)
>   Error: Request failed with status code 302
> ```
> 
> Using the same config, channel list and different IP works
> 
> ```
> [1/404] osn.com - AlAanTV.ae - Jan 14, 2023 (47 programs)
> [2/404] osn.com - AlDafrahTV.ae - Jan 14, 2023 (24 programs)
> ```

Is this a good thing lol?

**Comment by PopeyeTheSai10r** [comment]
> Is this a good thing lol?

 No.

**Comment by boeder8** [comment]
> > Is this a good thing lol?
> 
> No.

Ok. From what I understood, a different IP avoids the error and pulls the guide?

**Comment by PopeyeTheSai10r** [comment]
> Ok. From what I understood, a different IP avoids the error and pulls the guide?

Yes

**Comment by boeder8** [comment]
Hello, I just wanted to ask if a solution can be found for osn.com? Is there a chance this guide can be fixed?

**Comment by boeder8** [comment]
> > Ok. From what I understood, a different IP avoids the error and pulls the guide?
> 
> Yes

Hello, I just wanted to ask if a solution can be found for osn.com? Is there a chance this guide can be fixed?

**Comment by freearhey** [comment]
@boeder8 If a solution is found, the guide will be back on the list the very next day. In the meantime, I can only advise you to try to find some alternative source.
