### ISSUE TITLE
PLEASE STOP CHANGING URL every 90 days !

### ISSUE THREAD

**Issue by pucknbass** [iptv-org/epg#1655]
### Guide

https://github.com/iptv-org/epg

### Description

PLEASE STOP CHANGING URL every 90 days !  LEAVE it hasCOUNTRYURL FFS !

**Comment by PopeyeTheSai10r** [comment]
Thank you for your feedback. The Country URLs were more than trouble than it was originally anticipated hence why the project has gone back to the Source URLs. 

You can help us make the project better by contributing to it. 
See something that can be improved? Submit a pull request.

Thank you for investing your time in the project!
