### ISSUE TITLE
Danish EPG

### ISSUE THREAD

**Issue by joolzg** [iptv-org/epg#1666]
### Description

Just wondering what happened to this and the fact that a few days ago I could pull 
wget -q "https://iptv-org.github.io/epg/guides/dk.xml"
wget -q "https://iptv-org.github.io/epg/guides/se.xml"
wget -q "https://iptv-org.github.io/epg/guides/fi.xml"

And all was good, what happened to these merged ones?

**Comment by RevGear** [comment]
Guides are now split by language/provider, see https://github.com/iptv-org/epg#guides

**Comment by joolzg** [comment]
I see that but i cannot see any danish and if i use the swedish/finnish ones i have a few channels missing

**Comment by RevGear** [comment]
Go to https://iptv-org.github.io/ and search for the channel you are looking for.  That will tell you which guide(s) the channel is included in. 

There may some channels where the language has been wrongly identified so won't be in the correct guide. If you find any, either submit a PR with the changes or raise an issue so it can be corrected

**Comment by joolzg** [comment]
OK looking in the danish for example where would i find TV3Puls.dk as there is guide marked next to it.

**Comment by RevGear** [comment]
If there are no guides listed then there is no guide for it. Not every channel in the database currently has a guide. We either don't have a source, or don't have a working source, for that information
