### ISSUE TITLE
New program guide missing

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1668]
### Description

What is the new links??

https://iptv-org.github.io/epg/guides/us/tvtv.us.xml. isnt working anymore
https://iptv-org.github.io/epg/guides/us-local/tvtv.us.xml.gz isnt working anymore
https://iptv-org.github.io/epg/guides/us/us.xml.gz isnt working anymore

**Comment by RevGear** [comment]
See https://github.com/iptv-org/epg#guides

**Comment by spotanjo3** [comment]
I Know and thats why I am asking here. Cant finds those links from there. Am I missing?
