### ISSUE TITLE
CNBC Europe not in US EPG?

### ISSUE THREAD

**Issue by chamby90** [iptv-org/epg#167]
I see that CNBC Europe channel is listed as an available channel for the USA guide.  However, when I use it in xTeve to map the channel I only see CNBC East, West and World.  I don't see the CNBC Europe channel as an option.  What am I missing?

**Comment by freearhey** [comment]
The fact is that the US program contains only those channels that are at least one of the sources: `tvtv.us`, `tvguide.com` or `ontvtonight.com`

So if you need a program for the `CNBC Europe` you need to use one of the guides which already has it, for example: 

```
https://iptv-org.github.io/epg/guides/it/guidatv.sky.it.epg.xml
```

**Comment by chamby90** [comment]
thanks @freearhey !  Thats what i was having trouble with, finding which guide it was in.  If possible, when doing the search of what channels are available if the results returned which guide it was in that would be super helpful.  Unless there is already a way to do that that I am not aware of?

**Comment by freearhey** [comment]
I will add this info to the list later.
