### ISSUE TITLE
CNN and Nippon TV

### ISSUE THREAD

**Issue by tomifisking** [iptv-org/epg#1671]
### Guide

https://iptv-org.github.io/epg/guides/ja/tvguide.myjcom.jp.xml

### Description

In /tvguide.myjcom.jp.xml, there is CNN which the EPG is in Japanese and should be English.
In /directv.com.xml, there is Nippon TV which the EPG is in English and should be Japanese.

The tvg-name and tvg-id of these two channels are the same in both EPGs.
Could you please tell me how to display them in right languages?

It happens only in the latest update.

Thank you.

**Comment by PopeyeTheSai10r** [comment]
> I don't think Nippon TV has an English version, maybe it can be DELETED from /directv.com.xml.

The channel language may not be English but the source still provides English EPG.
