### ISSUE TITLE
EPG list needed

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1672]
### Source

Dont know which one

### Channels

I dont know which links are for those lists. I fixed many others from EPG guide mostly Cable TV. Can you help with those lists ? 

AMC Thrillers
Cartoon Network east and west
CBS NEWS BOSTON
Circle
CMT
CNN
Crackle
Dove Channel
Fail Army
Hi-YAH
ION PLUS EAST
NBC NEWS NOW
NHK WORLD
RETRO CRUSH
TBS EAST AND WEST
WEATHERSPY

**Comment by RevGear** [comment]
Have you tried searching on https://iptv-org.github.io/ ?
That will tell you if there is a guide available and what URL(s) to use.

**Comment by spotanjo3** [comment]
Yes, thank you.

One more thing.. AMC PRESENTS guide isnt there on that list. Know a off list link ?

**Comment by RevGear** [comment]
If it's not on the list then we don't have the data to produce a guide

**Comment by spotanjo3** [comment]
> If it's not on the list then we don't have the data to produce a guide

Yes, someone posted previously. You can added it. Here:

https://github.com/iptv-org/epg/issues/1062
