### ISSUE TITLE
RTL Passion Germany

### ISSUE THREAD

**Issue by GlamoramaAttack** [iptv-org/epg#1673]
### EPG

https://iptv-org.github.io/epg/guides/de/tv.blue.ch.xml

### Description

RTL Passion Deutschland is in the German language EPG for tv.blue.ch here:

`<channel id="RTLPassionCroatia.hr"><display-name>RTL Passion Croatia</display-name><icon src="https://i.imgur.com/ZAZKrOB.png"/><url>https://tv.blue.ch</url></channel>`

but the ID should be RTLPassionGermany.de as it was before. 

There is a RTL Passion in Germany and a RTL Passion in Croatia - two different channels, two different languages. 

It should be:

`<channel id="RTLPassionGermany.de"><display-name>RTL Passion Deutschland</display-name>`

for tv.blue.ch!

**Comment by PopeyeTheSai10r** [comment]
The guide is now available at `https://iptv-org.github.io/epg/guides/de/tv.blue.ch.xml`
