### ISSUE TITLE
Epg not work

### ISSUE THREAD

**Issue by Icefire26** [iptv-org/epg#1677]
### Guide

https://iptv-org.github.io/epg/guides/fr/canalplus-afrique.com.xml 

### Description

Can you fix please , and thank you for your work .

**Comment by PopeyeTheSai10r** [comment]
The link is loading for me. 
Can you try again and let us know if you are still experiencing issues?

**Comment by Icefire26** [comment]
Sorry, but don't work for me , i use tivimate , and  i use the link 
https://iptv-org.github.io/epg/guides/fr/canalplus-afrique.com.xml.gz 
For me rhe link not work.

Le 13 janv. 2023, 23:38, à 23:38, PopeyeTheSai10r ***@***.***> a écrit:

**Comment by PopeyeTheSai10r** [comment]
Can you try removing and re-adding the URL?

It is working for me using `https://iptv-org.github.io/epg/guides/fr/canalplus-afrique.com.xml`

![image](https://user-images.githubusercontent.com/107763146/212449740-7558c6f7-1ea4-41b6-9825-1818c73b6575.png)

**Comment by Icefire26** [comment]
Sorry , i have try removing and re-adding the URL and it's the same thing not work and the guide does not appear .
I do not know what to do 😔



Le 14 janv. 2023, 05:01, à 05:01, PopeyeTheSai10r ***@***.***> a écrit:

**Comment by RevGear** [comment]
In Tivimate, go to Settings > EPG > Update EPG. When it's finished updating, the 'Latest update status' at the bottom of the will show if the file was successfully loaded or not.

If status shows success, then check the Playlist > EPG Sources, and check you have linked the source with the playlist.
If status shows failure, then re-check the URL is correct (no extra spaces etc)

**Comment by Icefire26** [comment]
Hello , finally it works thank you for your answers. on the other hand many channels are missing or absent, example canal+ action, canal+ pop, canal+ they etc can you please put them back, and thank you again for your great job.

Le 14 janv. 2023, 17:52, à 17:52, RevGear ***@***.***> a écrit:

**Comment by PopeyeTheSai10r** [comment]
You can start a new [EPG Request issue](https://github.com/iptv-org/epg/issues/new?assignees=&labels=%F0%9F%97%93+epg+request&template=----epg-request.yml) requesting the missing channels.
