### ISSUE TITLE
search using the channel name

### ISSUE THREAD

**Issue by Shawkiiz** [iptv-org/epg#1679]
### Description

Can I search using the channel name? In order to know which file this channel is in

**Comment by freearhey** [comment]
Yes.

https://iptv-org.github.io/

**Comment by Shawkiiz** [comment]
I want to know in which xml file , not in which country

**Comment by freearhey** [comment]
https://iptv-org.github.io/?q=Abu%20Dhabi%20TV

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/7253922/212331033-bc709ea6-3c4e-44cc-a420-1985e6f6ce49.png">
