### ISSUE TITLE
WOI    ABC

### ISSUE THREAD

**Issue by Sjsmith72** [iptv-org/epg#1684]
### Source

https://www.ontvtonight.com/guide/

### Channels

WOI ABC 5 West Des Moines, IA. 

### Notes

Can use zip code 50003. 
Can also be found on mediacom, direct tv, dish tv. 
thank you

**Comment by PopeyeTheSai10r** [comment]
Fixed in #1701

**Comment by Sjsmith72** [comment]
Thank you for tour hard work.
