### ISSUE TITLE
EPG Germany 

### ISSUE THREAD

**Issue by olek52** [iptv-org/epg#1695]
### Description

https://github.com/iptv-org/epg I was looking for an epg for germany, uploaded magentatv.at and noticed the offer is
different than here https://web.magentatv.de/tv-guide ..w magentatv. no example DAZN 1 DAZN 2. So my question is it possible to add magentatv.de versions https://web.magentatv.de/tv-guide Thank you

**Comment by RevGear** [comment]
magentatv.de has been looked at in the past. The problem is that it uses a cookie with a constantly changing session ID, meaning it's not possible to automate

**Comment by olek52** [comment]
Thank you for your answer
