### ISSUE TITLE
Please add KOCE-DTI (PBS SoCal) to TVPassport EPG (line to include in comments)

### ISSUE THREAD

**Issue by acholder** [iptv-org/epg#1702]
### Source

https://www.tvpassport.com/tv-listings/stations/pbs-socal1-koce-huntington-beach-ca/2632

### Channels

<channel lang="en" xmltv_id="KOCEDT1.us" site_id="pbs-socal1-koce-huntington-beach-ca/2632">PBS SoCal (KCOE) Los Angeles, CA</channel>

### Notes

<channel lang="en" xmltv_id="KOCEDT1.us" site_id="pbs-socal1-koce-huntington-beach-ca/2632">PBS SoCal (KCOE) Los Angeles, CA</channel>

**Comment by acholder** [comment]
`<channel lang="en" xmltv_id="KOCEDT1.us" site_id="pbs-socal1-koce-huntington-beach-ca/2632">PBS SoCal (KCOE) Los Angeles, CA</channel>`

**Comment by ajanes3** [comment]
This will be resolved with PR #1701
