### ISSUE TITLE
Missing channels

### ISSUE THREAD

**Issue by Icefire26** [iptv-org/epg#1707]
### Source

https://iptv-org.github.io/epg/guides/fr/canalplus-afrique.com.xml

### Channels

Canal plus action ouest and centre 
Canal plus pop ouest and centre etc..

### Notes

Hello,
In https://iptvorg.github.io/epg/guides/fr/canalplus-afrique many channels are missing or absent, example canal+ action, canal+ pop, canal+ they etc can you please put them back, and thank you again for your great job.

**Comment by boeder8** [comment]
I second this request, upon checking there are many channels missing.

In the old source Canal+ Afrique, there were 242 channels, now there are only 88.

**Comment by freearhey** [comment]
All channels from the request are already in the list:

https://github.com/iptv-org/epg/blob/490287088c810c534c486b943780316ed1b623dd/sites/canalplus-afrique.com/canalplus-afrique.com.channels.xml#L41-L52

**Comment by Icefire26** [comment]
Hello , i dont know , if he can help , but i have see the new adress of canal plus afrique is : https://www.canalplus-afrique.com/ci
I hope help you .

**Comment by freearhey** [comment]
At the moment the guide is working fine:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/7253922/217794288-65a3138f-2891-4a57-84f4-963b62675b75.png">

**Comment by Icefire26** [comment]
Thank you.



Le 9 févr. 2023, 11:59, à 11:59, Aleksandr Statciuk ***@***.***> a écrit:
