### ISSUE TITLE
Changes in xml paths now us.xml is gone to where?

### ISSUE THREAD

**Issue by Rainey222** [iptv-org/epg#1709]
### Description

I have been looking for info on what changed i updated the path to a few xml files in my player but this file US.xml either gone or moved into other files or is missed. 
old path was  --   https://iptv-org.github.io/epg/guides/us.xml
But is no longer there. Is there a new path for all US guides in one file?
This file had over 1300 channels in it did that all get split up to many files now listed?

Looking for a few channels that were in that file.
to name a few
Comet.us
Charge.us
Action.us

**Comment by boeder8** [comment]
The links changed last week to reflect guide sources and language instead of country.

The updated links are in the main page.

To check the specific channels for a country and get the appropriate guide link, go to https://iptv-org.github.io/?q=country:US

For e.g. Comet and Charge EPGs can be found in https://iptv-org.github.io/epg/guides/en/i.mjh.nz.xml

**Comment by Rainey222** [comment]
Thanks, i see i am not the first to ask this question, I am reading other threads after looking harder.

You can close or delete this as i got most of my guide back and will look for the few channels missing and the old file points me to what file is the source so i have some work to do.

**Comment by boeder8** [comment]
> Thanks, i see i am not the first to ask this question, I am reading other threads after looking harder.
> 
> You can close or delete this as i got most of my guide back and will look for the few channels missing and the old file points me to what file is the source so i have some work to do.

Most welcome. I'm navigating my way the new guides, too.

Haha I'm not a mod/contributor, you can close it as the OP.

**Comment by PopeyeTheSai10r** [comment]
Duplicates #1689
