### ISSUE TITLE
alias for countries epg

### ISSUE THREAD

**Issue by dbojan** [iptv-org/epg#1716]
### Description

I see that epg guides for countries were replaced with separate providers instead of countries. Judging by the amount of questions, many people were unpleasantly surprised.  

Please provide aliases for countries epg.   
You download epg files and avail them for users to download, is that correct?  
Please add another step in which all guides for a single county would be merged to a single file (optionally gzipped), available in a single url to download/use.

One of the reasons is that many popular players, like kodi, do not allow to use more than one epg.  
Right now, one has to choose which epg guide to use, and which one to miss.  

Thank you.

**Comment by PopeyeTheSai10r** [comment]
> Please add another step in which all guides for a single county would be merged to a single file (optionally gzipped), available in a single url to download/use.

Countries URLs tried to provide a single URL with all the guides for each country. Unfortunately the logic wasn't working as expected and it prove to me more troubleshoot than it was anticipated to fix. That's why the project switched back to source URLs. Source URLs give users more flexibility.

There are some other limitations with your suggestions. For example: No every player is able to accept zipped guides.


You can help us make the project better by contributing to it.
See something that can be improved? Submit a pull request with the changes.

----
Relates to #1655

**Comment by RevGear** [comment]
> One of the reasons is that many popular players, like kodi, do not allow to use more than one epg. Right now, one has to choose which epg guide to use, and which one to miss.

I haven't tried it myself but have a look for the 'IPTV Merge' plugin. I believe that should allow you to combine multiple EPGs into a single source.

The problem with the country grouping is knowing which channels belong in which group. That may have been easier in the days of traditional broadcast TV, but with cable, satellite and IPTV we are seeing channels available (legally) across vast regions. Trying to maintain an accurate list of which countries or regions each channel is available in becomes unmanageable. The previous groupings may have seemed to be mostly correct but there were still a lot of channels that weren't being picked up correctly.

**Comment by dbojan** [comment]
>There are some other limitations with your suggestions. For example: No every player is able to accept zipped guides.

That is why I said optionally gzipped. It would be less data to download, but not mandatory gzipped.

It does not have to perfect.   
Merge can be created with biggest file size first, then the rest of files added, highest probability of correct file.  
People could choose which ever version works for them.

**Comment by dbojan** [comment]
Or if there will be no merge, how about redirection from the iptv..../country.epg to the iptv.../biggest file for the country.epg
That way people will probably won't have to reconfigure their devices, and also saves them having reconfigure urls in the future if there is a epg provider name change, etc..

**Comment by PopeyeTheSai10r** [comment]
> Or if there will be no merge, how about redirection from the iptv..../country.epg to the iptv.../biggest file for the country.epg

This will require a lot of work for very little cost-benefit ration but please feel free to submit a pull request with the changes if you are up for it.
