### ISSUE TITLE
the Telenet guide for the Dutch language does not contain all dutch channels from the old be/telenet guide

### ISSUE THREAD

**Issue by david63236** [iptv-org/epg#1722]
### Guide

https://iptv-org.github.io/epg/guides/nl/telenet.tv.xml

### Description

Seems like only the first 6 channels of the old Belgium/Telenet guide have been included in the new Dutch/Telenet guide.
(PS: the new Dutch/Telenet guide contained all channels some days ago)

**Comment by freearhey** [comment]
Ref: https://github.com/iptv-org/epg/actions/runs/3935704430/jobs/6731621597

**Comment by david63236** [comment]
I have tested today and all channels that I want are included.
So there is no issue today.

**Comment by PopeyeTheSai10r** [comment]
Marking this issue as resolved since they are all working now. Feel free to open a new issue if you continue to experience issues with the EPG URL.
