### ISSUE TITLE
beIN Entertainment EPG

### ISSUE THREAD

**Issue by boeder8** [iptv-org/epg#1726]
### Source

bein.com

### Channels

Hello,

Requesting the addition of the beIN Entertainment channels. The sports channels are added but most of the entertainment channels are not. Most of these channels are English with only a few in Arabic (noted below).

Some channels are available through El Cinema but having the EPG from the official source can be more accurate, so I'm requesting the addition of these channels to bein.com 

**Sources**

**EN:** https://www.bein.com/en/tv-guide/?c=sa

**AR:** https://www.bein.com/ar/%d8%ac%d8%af%d9%88%d9%84-%d8%a7%d9%84%d8%a8%d8%ab/?c=sa

**Channels Available on El Cinema**
beIN Movies 1
beIN Movies 2
beIN Movies 3
beIN Movies 4
beIN Series 1
beIN Series 2
beIN Gourmet (AR and EN)
beIN Drama (AR)

**Channels in Database with no Guide:**
**### UAE** 
Fatafeat (AR)
Cartoon Network Arabic (AR and EN)
Star Movies
Star World

**### UK**
BBC Earth Middle East

**### Qatar**
Jeem
Baraem
BeJunior

**Channels NOT in Database and No Guide:**
Food Network Middle East
FOX Middle East
Fox Movies Middle East
Fox Action Movies Middle East
Fox Life Middle East
HGTV
MTV 80s
MTV 90s
Club MTV
Bloomberg
National Geographic Middle East
National Geographic Wild Middle East
Discovery Channel Middle East
BBC Cbeebies
Baby TV
Cartoon Network Middle East
DreamWorks

### Notes

Thanks!

**Comment by RevGear** [comment]
Entertainment and Sports channels now available in English and Arabic
EN: https://iptv-org.github.io/epg/guides/en/bein.com.xml
AR: https://iptv-org.github.io/epg/guides/ar/bein.com.xml
