### ISSUE TITLE
Addition of Discovery+ Extra 1-8 (Sweden)

### ISSUE THREAD

**Issue by boeder8** [iptv-org/epg#1728]
### Source

allente.se and tv.nu

### Channels

Hello,

I would like to request the addition of the Discovery+ Extra 1 through 8 (Sweden/Swedish) to allente.se and/or tv.nu as these are missing from the guides after the last patch.

These were present in the old allente.se guide
https://github.com/iptv-org/epg/blob/ccacf7f121c145bd87ad3b5ae5941496dba30fb7/sites/allente.se/allente.se_se.channels.xml

The channels are:

Discovery+ Extra 1
Discovery+ Extra 2
Discovery+ Extra 3
Discovery+ Extra 4
Discovery+ Extra 5
Discovery+ Extra 6
Discovery+ Extra 7
Discovery+ Extra 8

![Screenshot_20230118-041227](https://user-images.githubusercontent.com/61802643/213044472-e4342756-d48f-49b4-9aad-ef75ea32ecd7.png)

All of the channels are in the database.

Thanks a lot!

**Comment by PopeyeTheSai10r** [comment]
I tried looking for the information on the two site listed above but can't find it.

Do you have a direct link to any of the channels' guide?

**Comment by boeder8** [comment]
> I tried looking for the information on the two site listed above but can't find it.
> 
> Do you have a direct link to any of the channels' guide?

Hi, since there are live event channels, the guides aren't listed daily.

I did some searching and there is an event on Jan 20 and 21 so the channels showed up.

Please check

https://www.allente.se/tv-guide/

Under "livesport" for Jan 20 and 21

![Screenshot_20230118-123431](https://user-images.githubusercontent.com/61802643/213123984-086a76f0-6e0e-477d-8934-3a45315d8bed.png)

Also

https://www.tv.nu/kanal/discovery-extra-1/lordag

Note that the channel guides were available on Allente SE for Sweden prior to Jan 3 changes and were working fine. If the above isn't enough, maybe the data can be extracted from the old guide?

I hope this helps

Thanks!

**Comment by RevGear** [comment]
> Hi, since there are live event channels, the guides aren't listed daily.
> 
> I did some searching and there is an event on Jan 20 and 21 so the channels showed up.

Well that's the problem. They are still listed in the allente.se channels xml config but there's no data to grab. We only create for 2 days ahead, so on Jan 18th we get programs for 18/19th. There will be no guide created as there is nothing to create.

If there is data for 20th then expect the guides to re-appear after the update on 19th

**Comment by boeder8** [comment]
> > Hi, since there are live event channels, the guides aren't listed daily.
> > I did some searching and there is an event on Jan 20 and 21 so the channels showed up.
> 
> Well that's the problem. They are still listed in the allente.se channels xml config but there's no data to grab. We only create for 2 days ahead, so on Jan 18th we get programs for 18/19th. There will be no guide created as there is nothing to create.
> 
> If there is data for 20th then expect the guides to re-appear after the update on 19th

Makes sense. Thanks you for the response.

Closing the issue.
