### ISSUE TITLE
KLCSDT3 EASTERN (CREATE TV NETWORK)

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1732]
### Source

https://www.tvpassport.com/tv-listings/stations/create-klcs3-los-angeles-ca/11230

### Channels

https://d1mxoeplf1ak5a.cloudfront.net/index.m3u8

**Comment by RevGear** [comment]
Guides are only created once per day, The change was merged after today's run. Check again tomorrow

**Comment by spotanjo3** [comment]
Thank you.
