### ISSUE TITLE
Circle.us

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1743]
### Guide

https://iptv-org.github.io/epg/guides/en/i.mjh.nz.xml

### Description

Circle.us didnt showing on my tv schedule. Can you take a look a it? The guide link above is what I have but something's wrong.

**Comment by spotanjo3** [comment]
Can you check it ? Its not working at all.

**Comment by PopeyeTheSai10r** [comment]
Hello, Can you make sure your playlist channel name and/or tvg-id matches the database?

https://iptv-org.github.io/?q=Circle.us%20guides:%3E0

**Comment by spotanjo3** [comment]
Hello. Yes, I know. Circle.us is in the list but it didnt show up somehow.. Anyway..thats ok. I deleted it because Circle channel is bored lol.
