### ISSUE TITLE
SYFY PACIFIC 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1762]
### Source

https://www.tvpassport.com/tv-listings/stations/syfy-hd-pacific-feed/5644

### Channels

https://www.directv.com/guide

**Comment by PopeyeTheSai10r** [comment]
Program data looks the same as https://www.tvpassport.com/tv-listings/stations/syfy-pacific-feed/1207 which is already included in that [tvpassport EPG URL](https://iptv-org.github.io/epg/guides/en/tvpassport.com.xml)


https://github.com/iptv-org/epg/blob/c14ab652878ae9d7f86413ad54c99041e53a0fc0/sites/tvpassport.com/tvpassport.com.channels.xml#L177

**Comment by spotanjo3** [comment]
Can you add it to directv guide also ? tvpassport link schedule is conflict with my directtv link somehow. Make sure directv guide set to 92240 in California for properly schedule in pacific. Thanks.

**Comment by spotanjo3** [comment]
Directv channel 244 (SYFYHD and SYFY)

**Comment by RevGear** [comment]
Directv channel 244 is the East coast feed (SyfyEast.us). They don't have a sperate feed for West coast.

**Comment by spotanjo3** [comment]
Oh I understand. Thanks for explaination and other epg threads too. Sorry about. I didnt know.
