### ISSUE TITLE
CBSEast.US

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1770]
### Source

https://www.tvpassport.com/tv-listings/stations/cbs-eastern/1225

and

https://www.directv.com/guide

### Channels

CBSEast

### Notes

I know that it is already in TVGUIDE epg but I woould like to ask you if you can add it to TVPASSPORT and directv also ? I dont want to use TVGUIDE epg due to conflict with other EPG link. Please ? Thanks.

**Comment by RevGear** [comment]
What channel number is it on the directv.com website?

**Comment by spotanjo3** [comment]
WBCS - 2

**Comment by ajanes3** [comment]
Added with #1776

**Comment by RevGear** [comment]
> WBCS - 2

Already in directv guide as WCBSDT1.us
