### ISSUE TITLE
Charge! Eastern

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1772]
### Source

[xumo link ](https://iptv-org.github.io/epg/guides/en/xumo.tv.xml)

and [Directv guide](https://www.directv.com/guide)

### Channels

Charge.us

### Notes

I know that it is already in (https://iptv-org.github.io/epg/guides/en/i.mjh.nz.xml) epg but I woould like to ask you if you can add to XUMO and Directv also ? I dislike i.mjh.nz epg link. Please ? Thanks.

**Comment by RevGear** [comment]
What channel number is it on the directv.com website?

**Comment by spotanjo3** [comment]
> What channel number is it on the directv.com website?

What about XUMO ??

For Directv guide - It wasnt in the service.

**Comment by RevGear** [comment]
> I woould like to ask you if you can add to XUMO and Directv also ? I dislike i.mjh.nz epg link. Please ? Thanks.

> For Directv guide - It wasnt in the service.

If it's not available from Directv, then how are we supposed to add it to the guide?

**Comment by spotanjo3** [comment]
https://www.tvpassport.com/tv-listings/stations/charge/15228

For Charge Eastern time

Charge.us
