### ISSUE TITLE
NBC East

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1773]
### Source

https://www.tvpassport.com/tv-listings/stations/nbc-network-eastern/1227

and

https://www.directv.com/guide

### Channels

NBCEast.us

### Notes

It is already in TVGUIDE EPG link but it would be nice to add to TVPASSPORT and Directv EPG LINk to prevent from conflict with other link. Can you please add them too ? I would appreciate that. Thanks.

**Comment by RevGear** [comment]
What channel number is it on the directv.com website?

**Comment by ajanes3** [comment]
Added tvpassport in #1776

**Comment by spotanjo3** [comment]
> What channel number is it on the directv.com website?

WNBC - 4

**Comment by RevGear** [comment]
> WNBC - 4

Already in directv guide as WNBCDT1.us
