### ISSUE TITLE
The Movie Channel Extra East 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1780]
### Source

https://www.tvpassport.com/tv-listings/stations/tmc-xtra-hd-eastern/7113

### Channels

TheMovieChannelXtraEast.us

### Notes

Add it to tvpassport will you ? Directv have it but added it please?

**Comment by ajanes3** [comment]
Added in #1776

**Comment by spotanjo3** [comment]
Can you double check it ? It isnt working. No EPG guide at all on my tv screen. It is only one in my list that isnt working.

> Added in #1776

Can you double check it ? It isnt working. No EPG guide at all on my tv screen. It is only one in my list that isnt working.

**Comment by spotanjo3** [comment]
Hello. Can you please check it ? EPG isnt showing here. "EPG NOT AVAILABLE".
