### ISSUE TITLE
AMC Eastern

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1782]
### Source

https://www.tvpassport.com/tv-listings/stations/amc-eastern-feed-hd/6219

### Channels

AMCEast.us

### Notes

TVPassport adding please?

**Comment by ajanes3** [comment]
Added in #1776

**Comment by spotanjo3** [comment]
Are you sure it was added ? It didnt showing up on my tv schedule. For TVPassport.

**Comment by ajanes3** [comment]
It takes about day or two for the sync to catch the new channel. Just be patient. :)

**Comment by spotanjo3** [comment]
I am patient. I didnt know for how long. :) And i added some more for tvpassports if you may? Thanks. I love your site :)

**Comment by spotanjo3** [comment]
Can you double check it ? AMC schedule didnt show up on my TV at all. Everything else works.

**Comment by ajanes3** [comment]
Yep, that's my bad.  Fixing that now.

**Comment by spotanjo3** [comment]
Thanks. Will report you if its working in two-3 days. Can you finish the requested I posted there? I finished them. No more requested and good work.

**Comment by spotanjo3** [comment]
> Yep, that's my bad. Fixing that now.

AMC schedule is working right now. Can you please finish the requested I posted in EPG list ? My requested is now complete and no more to requested. Those are all I want to finish in my tvpassport epgs. Can you do that ? Thank you kindly. And Good work.

**Comment by ajanes3** [comment]
> Can you please finish the requested I posted in EPG list ? My requested is now complete and no more to requested. Those are all I want to finish in my tvpassport epgs. Can you do that ? Thank you kindly. And Good work.

Please, please, please, if in the future you have a large number of channels to submit, put it in one request. I am happy to put it into the files for you. But opening 40 tabs to copy and paste your IDs and sources is a _nightmare_!

I can't really be mad though. You did the hard work of actually collecting all of this data. Good work. 🥇

**Comment by spotanjo3** [comment]
> > Can you please finish the requested I posted in EPG list ? My requested is now complete and no more to requested. Those are all I want to finish in my tvpassport epgs. Can you do that ? Thank you kindly. And Good work.
> 
> Please, please, please, if in the future you have a large number of channels to submit, put it in one request. I am happy to put it into the files for you. But opening 40 tabs to copy and paste your IDs and sources is a _nightmare_!
> 
> I can't really be mad though. You did the hard work of actually collecting all of this data. Good work. 🥇

I know. I feel guilt and someone told me that I can put all of it in one request for less hassle and he was right. I didnt know that it was allowed. My apology and I feel bad that you did them all with 40 tabs. My gosh. So sorry.

And I thank you for say such a things to me. I am happy to help too. Thank you and you too! 🥇

**Comment by spotanjo3** [comment]
@ajanes3 

I found two missing. And can you do them please ? TNT East and Starz Encore Action East just posted in EPG. Two are done and all are complete. I am finished. Thanks.
