### ISSUE TITLE
MoreMax East

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1797]
### Source

https://www.tvpassport.com/tv-listings/stations/moremax-eastern-hd/7097

### Channels

MoreMaxEast.us

### Notes

Adding to TVPassport please ? It was added to another links already

**Comment by ajanes3** [comment]
This already exists in tvpassport.

**Comment by spotanjo3** [comment]
> This already exists in tvpassport.

Sorry. I edited it. Its East now. You can update it now. Sorry about that.

**Comment by ajanes3** [comment]
Duplicate of #1796

**Comment by spotanjo3** [comment]
What about other epg lists that I posted and requested ? Just wonder. I will wait, of course. ^_^

**Comment by ajanes3** [comment]
@spotanjo3 please see #1819
