### ISSUE TITLE
Question rather than issue on dual EPG

### ISSUE THREAD

**Issue by devilski** [iptv-org/epg#180]
Hello,

First of all, thank you for this great EPG list.  Is there a way to merge two countries' EPG into one?  I'm trying to get IPTV pvr simple client to work with EPGs from two countries, but it only allows for one EPG URL.  Any help would be appreciated.

Thanks

**Comment by devilski** [comment]
Found out how to merge them...

**Comment by konrul-r10** [comment]
Could you please share how do you do that? Thanks.

**Comment by konrul-r10** [comment]
@devilski could you please share merge two epg into one?
