### ISSUE TITLE
beIN.com and DirecTV AR/UY Disappeared

### ISSUE THREAD

**Issue by Cosmo879** [iptv-org/epg#1816]
### Guide

bein.com (Arabic and English), DirecTV AR and UY (Spanish)

### Description

Hello,

4x guides disappeared in the last 24 hours:

- bein.com in Arabic and English
- DirecTV AR (Argentina) and UY (Uruguay) in Spanish

It would be awesome if a member of the team can check the issue with these and possibly fix them.

As always, thank you very much for the support!

**Comment by nickleby** [comment]
Yes, these guides are now missing (error 404 file not found).

**Comment by RevGear** [comment]
Looks like they are there now. There seemed to be an issue generating some guides yesterday, although I don't know why. Same issue as #1820

**Comment by Cosmo879** [comment]
> Looks like they are there now. There seemed to be an issue generating some guides yesterday, although I don't know why. Same issue as #1820

Yes, they're back up. Thank you.
