### ISSUE TITLE
Portuguese channels missing 

### ISSUE THREAD

**Issue by Thermaldude** [iptv-org/epg#1818]
### Source

https://www.nos.pt/particulares/televisao/guia-tv/pages/default.aspx

### Channels

Motorvision HD
Nos studios
Tv series
Crime+investigation
Cbs reality
Id investigation discovery
Travel channel
Casa e cozinha
24 kitchen
Food network
Nick JR
Nickelodeon (portugal) 
Canal nos 

Thks for your amazing work

### Notes

You have the nickelodeon spain in Portugal epg

**Comment by nickleby** [comment]
I think there's not a site configuration for that provider yet (nos.pt)

**Comment by Thermaldude** [comment]
I dont know, i just try help, i dont understand how epg work , i try see vídeos but i dont ubderstand

**Comment by spotanjo3** [comment]
What does that mean Eleven Sports 1-6 Portugal "closed" at https://iptv-org.github.io/?q=eleven%20sports ? 

My channels of Eleven Sports Portugal 1-6 works fine. No EPGs thought.

**Comment by freearhey** [comment]
The guide from nos.pt is now available at the link:

```
https://iptv-org.github.io/epg/guides/pt/nos.pt.xml
```

Program guide for 

Tv series
Crime+investigation
Cbs reality

is not on the website
