### ISSUE TITLE
Locals

### ISSUE THREAD

**Issue by shughes31** [iptv-org/epg#1825]
I’m pretty sure I’m missing something and maybe haven’t done enough research but I’m missing mostly US local channels but also many channels around the world.  I have managed to track down alternatives but would really like a good explanation on how to replicate what we had before the change.  Or at least a good faq or how to.  Thanks

**Comment by ajanes3** [comment]
@shughes31 what locals are you looking for? They can most likely be added to one of the many guides available.

**Comment by PopeyeTheSai10r** [comment]
Local channel will channel by region. What's local to you won't be local to others. Please let us know what channels you are looking for.

**Comment by Kamiela20100** [comment]
https://epgshare01.online/epgshare01/
Is where you'll find most US Locals channels

**Comment by shughes31** [comment]
I must be missing something but I can’t even find any decent explanations.  I used to have GitHub as an epg source in tivimate.  Now I have tried adding some of the urls listed for USA, Australia, and the epgshare listed above.  I don’t get any failure errors from the sources but when I try to assign EPG to specific channels I don’t see anything from GitHub and I don’t see anything from epgshare either

**Comment by RevGear** [comment]
@shughes31 lets start with the basics. What URL(s) are you using for the EPG source, and what channel(s) are you trying to assign? Without some specifics it's difficult to offer any help

**Comment by shughes31** [comment]
I am using https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml

im guessing that’s probably not an epg format

**Comment by ajanes3** [comment]
tvtv.us is currently malfunctioning per #1172 
If you are seeking US channel EPG, I recommend the TVPassport guide for now. `https://iptv-org.github.io/epg/guides/en/tvpassport.com.xml`
If any local channels are missing, simply post a request for the channel to be added. :)

**Comment by RevGear** [comment]
> I am using https://iptv-org.github.io/epg/guides/us/tvtv.us.epg.xml

That's one of the old country grouping that is no longer used, and tvtv.us hasn't been working for a few months.

Have a look through the [Guide List](https://github.com/iptv-org/epg#guides) for alternative. For general US channels then directv.com, flixed.io, or tvpassport.com guides are a good starting point. If you want local US channels then tvpassport.com is probably the best option. As @ajanes3 says, if there's any missing then find the page on the tvpassport.com website and post a request for the channel to be added.

**Comment by ajanes3** [comment]
I didn't even notice that the link was based on older groupings. Good catch @RevGear! 🥇

**Comment by shughes31** [comment]
I was able to pull data from the TVPassport link.  Thanks so much for the help
