### ISSUE TITLE
Bein.Net

### ISSUE THREAD

**Issue by m0hamedessam** [iptv-org/epg#185]
Can you add Bein.Net site

**Comment by freearhey** [comment]
Please provide a link to the guide page

**Comment by m0hamedessam** [comment]
https://www.bein.com/en/tv-guide/

Theres sports and entertainment

**Comment by freearhey** [comment]
The site takes too long to load.

![image](https://user-images.githubusercontent.com/7253922/140613672-c877842d-e837-40e9-bd79-425f3796c525.png)

**Comment by m0hamedessam** [comment]
example works fine try this

https://www.bein.com/ar/wp-admin/admin-ajax.php?action=epg_fetch&offset=0&category=entertainment&serviceidentity=bein.net&mins=00&cdate=2021-11-06&language=AR&postid=25344

**Comment by freearhey** [comment]
same result
![image](https://user-images.githubusercontent.com/7253922/140638085-16cbe254-d4ed-4e2a-9a31-3bf5ca356d0b.png)
