### ISSUE TITLE
tvplus.com.tr

### ISSUE THREAD

**Issue by m0hamedessam** [iptv-org/epg#187]
Can you add tvplus.com.tr site

**Comment by freearhey** [comment]
Please provide a link to the guide page

**Comment by m0hamedessam** [comment]
Post : https://izmottvsc23.tvplus.com.tr:33207/EPG/JSON/PlayBillList

post data : {"type":"2","channelid":"144","begintime":"20211104000000","endtime":"20211111235959"}

This can be found on webgrabplus site pack

**Comment by freearhey** [comment]
The link no longer works.

![image](https://user-images.githubusercontent.com/7253922/140613747-4507bae3-c75b-49f0-88ba-40564d85f732.png)

**Comment by m0hamedessam** [comment]
POST https://izmottvsc23.tvplus.com.tr:33207/EPG/JSON/Authenticate HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=UTF-8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Edg/79.0.309.71
Accept-Encoding: gzip,deflate,br
Host: izmottvsc23.tvplus.com.tr:33207
Content-Length: 227
Expect: 100-continue

{"terminaltype":"WEBTV_WIDEVINE","terminalvendor":"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","osversion":"Win32","userType":"3","utcEnable":"1","timezone":"UTC"}


**Then get session id from response to use on epg request like below**

POST https://izmottvsc23.tvplus.com.tr:33207/EPG/JSON/PlayBillList HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=UTF-8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Edg/79.0.309.71
Accept-Encoding: gzip,deflate,br
Host: izmottvsc23.tvplus.com.tr:33207
Cookie: XSESSIONID=031X1A07FPS8C1RN8GYV6HYRUZU7AE3E; JSESSIONID=031X1A07FPS8C1RN8GYV6HYRUZU7AE3E
Content-Length: 86
Expect: 100-continue

{"type":"2","channelid":"177","begintime":"20211106000000","endtime":"20211113235959"}
