### ISSUE TITLE
UPtv 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1874]
### Source

https://www.tvpassport.com/tv-listings/stations/up/5911

### Channels

UpTV.us

### Notes

Adding to TVPassport please ? It was added to another links already

**Comment by Cosmo879** [comment]
Bro, I don't get it, why open +20 seperate issues when you can put all your requests in a single issue post? 

Surely this doesn't make the contributors' life any easier.

**Comment by RevGear** [comment]
https://github.com/iptv-org/epg/blob/master/CONTRIBUTING.md

Or better still, just edit the channel.xml file with the changes and submit a pull request. TVPassport is one of the easiest to update. If you have the TVPassport URL and channel ID then you've already done all the hard work.

**Comment by PopeyeTheSai10r** [comment]
As RevGear mentioned tvpassport is one of the simplest to update. 


If you follow the [Contribution Guide](https://github.com/iptv-org/epg/blob/master/CONTRIBUTING.md#contributing-guide), you will learn that you should follow the following format.

`<channel lang="LANGUAGE_CODE" xmltv_id="CHANNEL_ID" site_id="SITE_ID">CHANNEL_NAME</channel>`

In this case, all you will need to add to the channel file is

`<channel lang="en" xmltv_id="UpTV.us" site_id="up">Up TV</channel>`


You can also take a look at [Contributing to projects](https://docs.github.com/en/get-started/quickstart/contributing-to-projects).

**Comment by RevGear** [comment]
You mean
 `<channel lang="en" xmltv_id="UpTV.us" site_id="up/5911">Up TV</channel>`

Site_id is just the last portion of the tvpassport URL

**Comment by freearhey** [comment]
@RevGear I've already corrected the `site_id` in @PopeyeTheSai10r's post, thought no one would notice)

**Comment by spotanjo3** [comment]
I am scared to try it and dont want to bother you if it messed up or didnt working. Can you at least finished them? I am done. Much appreciated . I will report only if some arent working or error. I finished posted them now for you to update the tvpassport.

**Comment by freearhey** [comment]
@spotanjo3 Don't be afraid to try. I assure you, this way you won't mess anything up.

**Comment by spotanjo3** [comment]
I understand but I am not a programming or something. I am not interested. I am just simple person enjoying my life and watched tv, lol. I am not great in English either. All I want is to finished those requested to tvpassport because I just posted in EPG list. I should asked all in one EPG list. My mistake. Anyway, can you finish them and thats all I am asking. I am not asking for more EPG requested anymore. ^_^
