### ISSUE TITLE
turksatkablo.com.tr

### ISSUE THREAD

**Issue by m0hamedessam** [iptv-org/epg#188]
https://www.turksatkablo.com.tr/userUpload/EPG/b.json?_=1636034936820

https://www.turksatkablo.com.tr/yayin-akisi-program-detay.aspx?d=4&m=11&y=2021&kID=283&eID=196444373822

This can be found on webgrabplus site pack

**Comment by freearhey** [comment]
Already on the list, but disabled due to unstable site performance.

https://github.com/iptv-org/epg/tree/master/sites/turksatkablo.com.tr
