### ISSUE TITLE
Great American Family 

### ISSUE THREAD

**Issue by Kamiela20100** [iptv-org/epg#1883]
### Source

https://www.tvpassport.com/tv-listings/stations/gac-family-east/1051

### Channels

Great American Family

please

**Comment by PopeyeTheSai10r** [comment]
The channel you are requesting needs to be added to the [Database](https://github.com/iptv-org/database) before we can grab the EPG data for it. Use iptv-org.github.io to find out what  channels are currently available. - https://iptv-org.github.io/?q=Great%20American

You can take a look at the [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) for the Database repository and either create a pull request or an [issue](https://github.com/iptv-org/database/issues/new?assignees=&labels=&template=channels_add.yml&title=Add%3A+).
