### ISSUE TITLE
Issue Labeling Inquiry

### ISSUE THREAD

**Issue by ajanes3** [iptv-org/epg#1889]
### Description

I see there is an 🗓 epg request label and a 📺 channel request label. I am trying to understand the difference between them.

#1818 is labeled as an 🗓 epg request. This makes sense because it is for a source that is currently not setup.

#1887 is labeled as an 🗓 epg request. But, in my opinion, this is actually a 📺 channel request because it is for a new channel in an existing source.

Does this make sense? Is there another way to understand it?

**Comment by freearhey** [comment]
There is no difference between the labels. "📺 channel request" is the label that was used before. 

I already deleted it.

**Comment by RevGear** [comment]
I think there is an argument for both, albeit with a change to the tag descriptions. To me `channel request` means adding a channel to an existing site/config, and `epg request` is to add an entire new provider. Maybe `provider request` would be better for the latter

**Comment by freearhey** [comment]
@ajanes3 @RevGear @PopeyeTheSai10r Well, how about I add the `channel request` label back then, and rename `epg request` to `provider request` or `source request`?

**Comment by PopeyeTheSai10r** [comment]
My take on this is. We should be using `EPG Request` when people are requesting channels to be added to an existing source's channel list. E.g: Add HBO East to tvpassport.

I don't see any value for `Channel Request` in this repository. That label should be only used in the Database and IPTV repos. `provider request` or `source request` should be what we use here going forward when requesting a new source to be added.

**Comment by freearhey** [comment]
I'll do as you all decide.

Request to add a channel to existing list:

1. `epg request`
2. `channel request`

Request to add a new source:

1. `epg request`
2. `provider request`
3.  `source request`

Just write below the combination that you like best.

**Comment by PopeyeTheSai10r** [comment]
**Request to add a channel to existing list:** epg request
**Request to add a new source:** source request

**Comment by freearhey** [comment]
Added.

I also updated the issue templates: #1899
