### ISSUE TITLE
EPG para Canales de españa en enlace moviestar

### ISSUE THREAD

**Issue by jesusgonzi** [iptv-org/epg#1897]
### Source

https://programacion-tv.elpais.com/

### Channels

Navarra TV, Onda Cadiz, Popular Tv Cantabria, La 7 de la Rioja, Super3 de tv3, RTVCeuta, TV Melilla y la 8 burgos

muchas gracias

**Comment by freearhey** [comment]
Channels "Navarra TV" and "Super 3" added in https://github.com/iptv-org/epg/commit/fd12fb48d5b2faf24d266eb06a9eca689e0f5fcc

There is no guide for Onda Cadiz, Popular Tv Cantabria, La 7 de la Rioja, RTVCeuta and TV Melilla on the site.

la 8 burgos is already on the list:

https://github.com/iptv-org/epg/blob/fd12fb48d5b2faf24d266eb06a9eca689e0f5fcc/sites/programacion-tv.elpais.com/programacion-tv.elpais.com.channels.xml#L84
