### ISSUE TITLE
EPG El pais

### ISSUE THREAD

**Issue by jesusgonzi** [iptv-org/epg#1898]
### Source

https://programacion-tv.elpais.com/

### Channels

cmm, tv canaria, cyl 7 la 8 burgos . 3/24,  super 3

### Notes

canales autonomicios de españa con la guia de el pais xfavor. gracias

**Comment by PopeyeTheSai10r** [comment]
**CyL 7 / CyL TV** needs to be added to the [Database](https://github.com/iptv-org/database). Super 3 needs to be updated.

CMM, TV Canaria, La 8 burgos and 3/24 added in PR 1904
