### ISSUE TITLE
Guide data for Dark Matter TV (third source)

### ISSUE THREAD

**Issue by markosjal** [iptv-org/epg#1903]
### Guide

https://iptv-org.github.io/epg/guides/en/xumo.tv.xml

### Description

data for Dark Matter TV from this source appears to be completely incorrect!

Please see other Dark matter Guide issues with other guide sources

**Comment by freearhey** [comment]
Unfortunately, we have no way to influence the quality of the data in the source.

The guide itself loads correctly:

https://play.xumo.com/live-guide/dark-matter-tv
<img width="1424" alt="image" src="https://github.com/iptv-org/epg/assets/7253922/11ed6192-3425-4fe9-bcd8-213a3c689714">

```sh
npx epg-grabber --config=sites/xumo.tv/xumo.tv.config.js --channels=sites/xumo.tv/xumo.tv.channels.xml --output=guide.xml
```

<img width="1372" alt="image" src="https://github.com/iptv-org/epg/assets/7253922/6b768936-1213-48f8-8347-3a67202bd6bc">
