### ISSUE TITLE
EPG question

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1908]
### Description

What does that mean Eleven Sports 1-6 Portugal "closed" at https://iptv-org.github.io/?q=eleven%20sports ?

My channels of Eleven Sports Portugal 1-6 works fine. No EPGs thought.

**Comment by RevGear** [comment]
Closed can either mean the channel is no longer broadcast, or in many cases it means it's still broadcasting under a different name. In this instance 'Eleven Sports 1 Portugal' is now 'Eleven 1 Portugal'. The channel ID in the guide config needs updating.

**Comment by spotanjo3** [comment]
> Closed can either mean the channel is no longer broadcast, or in many cases it means it's still broadcasting under a different name. In this instance 'Eleven Sports 1 Portugal' is now 'Eleven 1 Portugal'. The channel ID in the guide config needs updating.

No no.. It is fine. I found the epg guide is nos.pt and its working fine now.
