### ISSUE TITLE
digiturk.com.tr Error: Connection timeout

### ISSUE THREAD

**Issue by m0hamedessam** [iptv-org/epg#191]
digiturk.com.tr - 360.tr - Nov 4, 2021 (0 programs)
    Error: Connection timeout
  digiturk.com.tr - 360.tr - Nov 5, 2021 (0 programs)
    Error: Connection timeout
  digiturk.com.tr - 360.tr - Nov 6, 2021 (0 programs)

I face this problem not sure is it require turkish proxy or not but can you confirm its working on your side and any option to use proxy ?

**Comment by konrul-r10** [comment]
try to use this config file:

`
const dayjs = require('dayjs')
const utc = require('dayjs/plugin/utc')
const timezone = require('dayjs/plugin/timezone')
const customParseFormat = require('dayjs/plugin/customParseFormat')

dayjs.extend(utc)
dayjs.extend(timezone)
dayjs.extend(customParseFormat)

module.exports = {
    site: 'digiturk.com.tr',
    output: 'yeni_guide.xml', // path to output file (default: 'guide.xml')
    channels: 'digiturk.com.tr.channels.xml', // path to channels.xml file (required)
    lang: 'tr', // default language for all programs (default: 'en')
    days: 3, // number of days for which to grab the program (default: 1)
    delay: 3000, // delay between requests (default: 3000)
  
    url: function ({ date, channel }) {
    return `https://www.digiturk.com.tr/yayin-akisi/api/program/kanal/${
      channel.site_id
    }/${date.format('YYYY-MM-DD')}/0`
  },
  parser: function ({ content, channel }) {
    const programs = []
    const items = parseItems(content, channel)
    items.forEach(item => {
      programs.push({
        title: item.ProgramName,
        description: item.LongDescription,
        category: parseCategory(item),
        start: parseStart(item),
        stop: parseStop(item)
      })
    })

    return programs
  }
}

function parseStart(item) {
  return dayjs.tz(item.BroadcastStart, 'Europe/Istanbul')
}

function parseStop(item) {
  return dayjs.tz(item.BroadcastEnd, 'Europe/Istanbul')
}

function parseCategory(item) {
  const categories = {
    '00': 'Diğer',
    E0: 'Romantik Komedi',
    E1: 'Aksiyon',
    E4: 'Macera',
    E5: 'Dram',
    E6: 'Fantastik',
    E7: 'Komedi',
    E8: 'Korku',
    EB: 'Polisiye',
    EF: 'Western',
    FA: 'Macera',
    FB: 'Yarışma',
    FC: 'Eğlence',
    F0: 'Reality-Show',
    F2: 'Haberler',
    F4: 'Belgesel',
    F6: 'Eğitim',
    F7: 'Sanat ve Kültür',
    F9: 'Life Style'
  }

  return categories[item.Genre]
}

function parseItems(content, channel) {
  const data = JSON.parse(content)
  const items = data.listings[channel.site_id]
  if (!items.length) return []

  return items
}
`

2-3 programs can not be found. however, it will be ok soon. Problem must be related to source. Best wishes!

**Comment by m0hamedessam** [comment]
problem is digiturk.com.tr block ips you must use proxy so we need option for proxy.

**Comment by freearhey** [comment]
At the moment everything works fine without a proxy. Tested with Kodi and GSE Smart IPTV.

![image](https://user-images.githubusercontent.com/7253922/140600591-2ba4cbcb-fedf-4ea0-8c22-997d26f117d8.png)
