### ISSUE TITLE
AXN White Portugal

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1910]
### Guide

https://iptv-org.github.io/epg/guides/pt/meo.pt.xml

### Channels

AXNWhite.pt

### Notes

https://iptv-org.github.io/?q=axn%20white

You put wrong channel AXNWhite.us along with meo.pt. Please move AXNWhite.pt to meo.pt epg guide only. Thanks.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/1d41c2448220196500fb2a85abae979641d0c579

**Comment by spotanjo3** [comment]
AXNWhitePortugal.pt or AXNWhite.pt. I dont know which one -- It is not added to guide in https://iptv-org.github.io/?q=axn%20white
