### ISSUE TITLE
[vidio.com]

### ISSUE THREAD

**Issue by leakssh** [iptv-org/epg#1911]
### Guide

https://iptv-org.github.io/epg/guides/id/vidio.com.xml

### Channels

https://vidio.com/live/8241-rans-channel
https://vidio.com/live/7230-magna-tv
https://vidio.com/live/7946-tv-tempo
https://vidio.com/live/7687-sea-today
https://vidio.com/live/7150-abc-australia
https://vidio.com/live/6852-makkah-tv

### Notes

please add the channel, thank you

**Comment by freearhey** [comment]
Most of the channels have been added in https://github.com/iptv-org/epg/commit/a8a6fb6f4e85139cd0e3a9146dc4fd9b83bd423b

 Channel Magna TV is already on the list:

https://github.com/iptv-org/epg/blob/a8a6fb6f4e85139cd0e3a9146dc4fd9b83bd423b/sites/vidio.com/vidio.com.channels.xml#L42
