### ISSUE TITLE
Sat.tv for Arabic Channels

### ISSUE THREAD

**Issue by boeder8** [iptv-org/epg#1921]
### Source

https://sat.tv/ar/%d9%82%d9%86%d9%88%d8%a7%d8%aa-%d8%aa%d9%84%d9%81%d8%b2%d9%8a%d9%88%d9%86%d9%8a%d8%a9

### Notes

Hello,

Requesting the addition of Sat.tv as a source for Arabic Channels in Arabic Language EPG

To enter the guide, go to https://sat.tv/ar/%d9%82%d9%86%d9%88%d8%a7%d8%aa-%d8%aa%d9%84%d9%81%d8%b2%d9%8a%d9%88%d9%86%d9%8a%d8%a9

Select any Arab country (Saudi in this example), then select "Eutelsat/Nilsat" finally select Saudi (or any other country) to see the guide.

For reference the English guide can be found here: https://sat.tv/tv-channels

I would be grateful if the below channels are added and sourced from the above. I've split them by country (all channels are in the database):

```
**Algeria**
SamiraTV.dz
EnnaharTV.dz
EchoroukNews.dz
EchoroukTV.dz
BahiaTV.dz
ElBilad.dz
TV1.dz
TV3.dz
TV4.dz
TV5.dz
TV6.dz
TV7.dz
TV8.dz

**Egypt**
AlhayatTV.eg
AlhayatDrama.eg
AlNaharDrama.eg
AlMasriyah.eg
CBC.eg
CBCDrama.eg
CBCSofra.eg
ElMehwarChannel.eg
ERTU1.eg
DMC.eg
DMCDrama.eg
NileCinema.eg
NileComedy.eg
NileDrama.eg
NileLife.eg
PNCFood.eg
RotanaCinemaEgypt.eg
SadaElbalad.eg
SadaElbaladDrama.eg

**Iraq**
AlSharqiya.iq
AlSharqiyaNews.iq
Alsumaria.iq
DijlahTV.iq

**Jordan**
AlMamlakaTV.jo
JordanTV.jo
RoyaTV.jo
AmmanTV.jo

**Kuwait**
KTV1.kw

**Lebanon**
AlMayadeenTV.lb

**Morocco**
2M.ma
AlAoula.ma
AlMaghribia.ma
Arrabiaa.ma
Arryadia.ma
Assadissa.ma
Athaqafia.ma
Tamazight.ma

**Oman**
OmanTV.om

**Qatar**
AlRayyanTV.qa
QatarTV.qa

**Tunisia**
AlJanoubiyaTV.tn
AttessiaTV.tn
ElhiwarEttounsiTV.tn
HannibalTV.tn
NessmaElJadida.tn
TelvzaTV.tn
TunisnaTV.tn
Watania1.tn
Watania2.tn
ZitounaTV.tn

**Saudi Arabia**
AlSaudiya.sa
EkhbariyaTV.sa
SBC.sa
ThikrayatTV.sa
RotanaCinemaKSA.sa
RotanaDrama.sa
RotanaKhalijia.sa

**Sudan**
BlueNileChannel.sd
KhartoumTV.sd
SudanTV.sd

**UAE**
AbuDhabiTV.ae
AbuDhabiEmirates.ae
AbuDhabiSports1.ae
AbuDhabiSports2.ae
AlAanTV.ae
Yas.ae
SpacetoonArabic.ae
DubaiSports1.ae
DubaiSports2.ae
DubaiSports3.ae
DubaiRacing.ae
DubaiRacing2.ae
DubaiRacing3.ae
SharjahSports.ae
FujairahTV.ae
NoorDubai.ae
SharjahTV.ae
SkyNewsArabia.ae

**UK**
AlArabyTV.uk

**Yemen**
AdenTV.ye
YemenTV.ye
YemenShababChannel.ye
```

I realize this is a large request so please take your time and thanks in advance!

![Screenshot_20230131-025239](https://user-images.githubusercontent.com/61802643/215618385-7525524b-2e36-4216-a344-201a5ee27e12.png)

![Screenshot_20230130-231526_2](https://user-images.githubusercontent.com/61802643/215618468-b98e2c47-2870-4185-a21d-3133bc5dd4d1.png)

![Screenshot_20230130-231512_2](https://user-images.githubusercontent.com/61802643/215618489-e96c7471-7b94-481c-8a00-c0aa2add6393.png)

**Comment by freearhey** [comment]
The parser for `sat.tv` has been added to the repository, but I could not find some channels on the site:

```
BlueNileChannel.sd
ElBilad.dz
TV1.dz
Watania2.tn
ZitounaTV.tn
```

If you find them, feel free to add them to the list:

https://github.com/iptv-org/epg/blob/master/sites/sat.tv/sat.tv.channels.xml
