### ISSUE TITLE
Please add Nashville local broadcast channels

### ISSUE THREAD

**Issue by dwwaldrip1** [iptv-org/epg#1923]
### Guide

https://iptv-org.github.io/epg/guides/en/tvpassport.com.xml

### Channels

abcwkrn.us
cbswtvf.us 
foxwztv.us 
nbcwsmw.us

### Notes

Thank You

**Comment by PopeyeTheSai10r** [comment]
The EPG for ABC Nashville, TN can be found in `https://iptv-org.github.io/epg/guides/en/tvpassport.com.xml` under WKRNDT1.us
