### ISSUE TITLE
EPG Flixed Empty

### ISSUE THREAD

**Issue by ba2022** [iptv-org/epg#1927]
### Guide

https://iptv-org.github.io/epg/guides/en/flixed.io.xml

### Description

Epg from flixed not load

**Comment by freearhey** [comment]
At the moment the guide is working fine:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/7253922/216840110-fcd70f34-cb52-4927-a335-fad6b1ac71c5.png">
