### ISSUE TITLE
No today update

### ISSUE THREAD

**Issue by extream87** [iptv-org/epg#1929]
Germany - horizon.tv not updated today 31/01/23

**Comment by PopeyeTheSai10r** [comment]
Please provide the the EPG URL

**Comment by extream87** [comment]
https://iptv-org.github.io/epg/guides/de/horizon.tv.xml.gz

**Comment by PopeyeTheSai10r** [comment]
The regular file is loading the information for me. `https://iptv-org.github.io/epg/guides/de/horizon.tv.xml`

See the copied code below for **123tv.de** starting at 2023-01-31 00:00:00

```
<programme start="20230131000000 +0000" stop="20230131010000 +0000" channel="123tv.de">
<title lang="de">Dennis Lieblingsuhren</title>
</programme>
<programme start="20230131010000 +0000" stop="20230131020000 +0000" channel="123tv.de">
<title lang="de">Selected Deals</title>
</programme>
<programme start="20230131020000 +0000" stop="20230131030000 +0000" channel="123tv.de">
<title lang="de">Selected Deals</title>
</programme>
```

Can you try refreshing the EPG?
If that doesn't help try changing the the URL ending in .xml instead of .xml.gz and see if that helps.

**Comment by extream87** [comment]
Hmmm maybe... but check the first line.

<tv date="20230130">

Usually epg get update daily.
Thanks

**Comment by PopeyeTheSai10r** [comment]
> Hmmm maybe... but check the first line.
> date= "20230130 "

Good point.

The last run was successful - https://github.com/iptv-org/epg/actions/runs/4050391148/jobs/6967735724

**Comment by joshmackey** [comment]
https://iptv-org.github.io/epg/guides/ja/tvguide.myjcom.jp.xml is also missing an update.

**Comment by RandySaint** [comment]
I've checked 4 others and they all show a date of "20230130".  It looks like some service has stopped yesterday.
https://iptv-org.github.io/epg/guides/en/rev.bs.xml
https://iptv-org.github.io/epg/guides/en/tvpassport.com.xml
https://iptv-org.github.io/epg/guides/en/directv.com.xml
https://iptv-org.github.io/epg/guides/en/tvguide.com.xml

**Comment by PopeyeTheSai10r** [comment]
Let's wait until the next run and the next page update to see if it updates them correctly this time. 
If it doesn't, we can look further into this a bit more.

**Comment by freearhey** [comment]
The reason why the files were not updated is this error: https://github.com/iptv-org/epg/actions/runs/4052569522

And I believe it was caused by a recent failure of GitHub itself: https://www.githubstatus.com/history

At the moment, everything seems to be working fine: https://www.githubstatus.com/

**Comment by GlamoramaAttack** [comment]
https://iptv-org.github.io/epg/guides/en/directv.com.xml.gz

isn't working for me.

And in the last 24 hours (it's now almost 10h Central European Time, Feb. 1), I wasn't able to get any updated EPG for the German language channels at

https://iptv-org.github.io/epg/guides/de/hd-plus.de.xml.gz
https://iptv-org.github.io/epg/guides/de/horizon.tv.xml.gz
https://iptv-org.github.io/epg/guides/de/magentatv.at.xml.gz
https://iptv-org.github.io/epg/guides/de/tv.blue.ch.xml.gz

The EPG for British English channels and for Swedish ones

https://iptv-org.github.io/epg/guides/en/bt.com.xml.gz
https://iptv-org.github.io/epg/guides/en/sky.com.xml.gz
https://iptv-org.github.io/epg/guides/en/tv24.co.uk.xml.gz
https://iptv-org.github.io/epg/guides/sv/allente.se.xml.gz
https://iptv-org.github.io/epg/guides/sv/tv24.se.xml.gz

worked 9 hours ago but have also stopped in the meantime (maybe three hours ago).

One of the EPG links is fully working:

https://iptv-org.github.io/epg/guides/en/tvpassport.com.xml.gz

And 

https://iptv-org.github.io/epg/guides/fr/tvhebdo.com.xml.gz

gives at least still results for HBO Canada 1 but not any longer for FX+FXX Canada (which it did a few hours ago).

And this one

https://raw.githubusercontent.com/Apollo2000/TVGuide/master/utc.xml.gz

is not from this EPG department but still usable for US local channels (but less for other channels).

Maybe it helps to know which ones work and which ones don't?

**Comment by extream87** [comment]
Thanks all by your work.
Today accessing the file: https://iptv-org.github.io/epg/guides/de/horizon.tv.xml.gz or https://iptv-org.github.io/epg/guides/de/horizon.tv.xml

I get File not found

**Comment by RevGear** [comment]
horizon.tv has been retuning a 403 error for every German channel request, hence there is no data to generate the xml guide. The Slovak channels use a different URL which is still working.

I can't currently access the horizon.tv website homepage. Some of the other pages redirect back to Virgin Media Ireland. Has there been a change of ownership that was effective today?

**Comment by GlamoramaAttack** [comment]
> I get the error: File not found

Me too. But may I ask you whether you use Kodi and which PVR client? Mine is 'IPTV Simple Client'  and I  use the 'IPTV Merge' addon.

**Comment by RandySaint** [comment]
Looks like it's working for me.  I suspect the Github glitch was the cause as suggested by freearhey.

Thanks for your help!

**Comment by extream87** [comment]
@RandySaint impossible horizon.tv.xml or gz works for you lol

**Comment by RandySaint** [comment]
I'm sorry for the confusion. I did not try horizon.tv.xml.  The 4 I listed above work for me, so my channel guide is working.

**Comment by GlamoramaAttack** [comment]
It's now working for me again too. Still I'm wondering why somehow the use of multiple EPG sources seemed to be a problem... but it is now resolved. Thanks!

**Comment by joshmackey** [comment]
https://iptv-org.github.io/epg/guides/ja/tvguide.myjcom.jp.xml wasn't updated again. No more schedule data.

**Comment by extream87** [comment]
@PopeyeTheSai10r Germany - horizon.tv goes down permanently?

**Comment by RevGear** [comment]
It appears that the Horizon GO platform in Germany has now closed down and the horizon.tv data is no longer accessible.  As I mentioned above the Horizon service in [Slovakia](https://www.horizon.tv/sk_sk.html) does still work. I'll do a PR to remove the German channels
