### ISSUE TITLE
All channels showing "No information"

### ISSUE THREAD

**Issue by Mkaye147** [iptv-org/epg#1938]
### Guide

https://iptv-org.github.io/epg/guides/en/sky.com.xml

### Description

Every channel is showing "No information" in Tivimate however the channel logos seem to be showing fine.

**Comment by GaminGuys** [comment]
Also getting 'no information'

**Comment by freearhey** [comment]
At the moment the guide is working fine:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/7253922/216839794-051b17b5-b238-4faf-85ba-96f412be8365.png">

**Comment by GaminGuys** [comment]
what 2 channels? No Sky movies or anything

**Comment by freearhey** [comment]
@GaminGuys you can see the full list of channels here: https://github.com/iptv-org/epg/blob/master/sites/sky.com/sky.com.channels.xml

**Comment by GaminGuys** [comment]
Not sure whats going on here then
![20230207_212443](https://user-images.githubusercontent.com/124317601/217369161-0a9f68dd-8253-4a84-afde-35133c8cbeb0.jpg)

**Comment by freearhey** [comment]
@GaminGuys The correct link to sky.com guide:

```
https://iptv-org.github.io/epg/guides/en/sky.com.xml
```

A complete list of all available guides can always be found on the main page: https://github.com/iptv-org/epg#guides
