### ISSUE TITLE
2 day limit?

### ISSUE THREAD

**Issue by ajanes3** [iptv-org/epg#1939]
### Description

Just curious, why do we limit the grab to 2 days of data? Why not a full week?

**Comment by RevGear** [comment]
@freearhey mentioned this in #687, short answer is file size.
Github has 50Mb limit which was a problem with the old merged country guide - the USA guide had so many local channels that it was regularly hitting that limit. Less of an issue with the current language/supplier guides but I suspect it would still cause issues with the programme database used as an interim step when building the guides.

You can now set the number of days for each provider in config. Some of the Far East and Australian guides have been pushed out from 2 to 3 days as they are so far ahead of UTC that most of the first day is already in the past by the time the guides are published.

**Comment by ajanes3** [comment]
@RevGear makes sense. I suppose I should start with search in the future.

I will propose a PR.
