### ISSUE TITLE
Where's "elcinema" guide ?!

### ISSUE THREAD

**Issue by Shawkiiz** [iptv-org/epg#1943]
### Description

Where's "elcinema" guide ?!

**Comment by PopeyeTheSai10r** [comment]
elcinema.com has been disabled because the guide shows the wrong time. The guide will be back, If a solution is found.


#994 
#1918

**Comment by Shawkiiz** [comment]
No need to disaple guide for wrong time , i can edit time in my iptv player add +5 hours and its ok , plz activate guide again 🙏🏻🌹
