### ISSUE TITLE
bein sports 1 USA

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1946]
### Guide

https://flixed.io/tv-guide/channels/BEIN1HD

### Channels

??????

### Notes

It didnt existed on your list for Bein Sports 1 but can you adding it ? Thanks.

**Comment by RevGear** [comment]
It's in the flixed.io guide as beINSportsUSA.us. There isn't a beINSports1USA.us in the database so I assume that's the same thing.

**Comment by spotanjo3** [comment]
No, I am checking it right now and the schedule didnt match. It is paid programming right now but your schedule say Adana Demirspor vs Fenerbahce. And now I am looking at my tv logo said: beIN Sports HD. It didnt say USA or 1. I assume that it is beIN Sports 1 but its not. This link is correct. And its not BeinSportUSA because BeinSportsUSA schedule said Adana Demirspor vs Fenerbahce but my tv is showing aid programming schedule right now so it is actually BeinSportHD according to the logo on my tv top right corner screen. Can you do something ?

**Comment by RevGear** [comment]
If it should be beINSports1USA rather that beINSportsUSA, then that channel will need adding to the database

**Comment by spotanjo3** [comment]
Maybe you should said beINSpor1USA.us then. And use this link. Its correct schedule

**Comment by spotanjo3** [comment]
Is it fixed already?

**Comment by ajanes3** [comment]
@spotanjo3 so far as we can tell, this already exists today as beINSportsUSA.us. We cannot find a separate beINSports1USA.

If you believe this is incorrect, please submit a database update so that we can update the channels. Until then, it is impossible to fulfill this request.

**Comment by spotanjo3** [comment]
Yeah.. I do not believe this is incorrect. It is actually incorrect because it is not beINSportsUSA.us. I just checked my cable tv and it is actually correct schedule like this:

https://streamingtvguides.com/Channel/BEIN1HD

Your beINSportsUSA is actually another channel and match different tv guide schedule. So https://flixed.io/tv-guide/channels/BEIN1HD is 100 percent correct for my Cable TV schedule. 

How do submit a database update please ? ^_^

**Comment by RevGear** [comment]
From https://streamingtvguides.com/Channel/BEIN1HD
![image](https://user-images.githubusercontent.com/95308545/216692634-d667b8d0-26e3-4a06-9faa-99b1304f22f2.png)

From https://flixed.io/tv-guide/channels/BEIN1HD
![image](https://user-images.githubusercontent.com/95308545/216693228-d07e6c1b-9162-41a9-9bef-85ed2a63e36a.png)

From https://iptv-org.github.io/epg/guides/en/flixed.io.xml
![image](https://user-images.githubusercontent.com/95308545/216692772-be292b63-585c-4a30-80c7-b79fc73e5554.png)

The look exactly the same to me. One is in PST, one is in EST, and one is UTC

**Comment by spotanjo3** [comment]
Indeed, it is. That's strange. Now, it is working properly. Sorry about the confusion a bit. Thank you for your patience and understanding. 

Edit: Now EPG is disappearing. "EPG not available". Why is that ?
