### ISSUE TITLE
Bein Sports 2 USA

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1947]
### Guide

https://flixed.io/tv-guide/channels/BEIS2HD

### Channels

beINSports2USA.us

### Notes

It didnt existed on your list for Bein Sports 2 but can you adding it ? Thanks.

**Comment by RevGear** [comment]
beINSports2USA.us will need adding to the database

**Comment by freearhey** [comment]
I could not find any additional info about the channel. The link provided is an empty guide:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/7253922/217117862-8c1eeaf3-e877-4b57-97b7-03a9084b934c.png">

And the official website is silent about it: https://www.beinsports.com/us/tv-guide

**Comment by spotanjo3** [comment]
Weird. Here it is right now : 
![08FD5026-B315-4E49-9D95-2FA143F7BD89](https://user-images.githubusercontent.com/16481778/217124473-7fdef48f-3482-4ad7-b2c4-db1c36eb237d.png)

**Comment by freearhey** [comment]
Now it's working for me, too:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/7253922/217136662-5ec03c83-135b-483f-acb8-845b15426cf4.png">
