### ISSUE TITLE
FC Famalicão Portugal

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#1951]
### Guide

https://www.foxsports.com/soccer/fc-famalicao-team-schedule

### Channels

???????

### Notes

FC Famalicão is a Portuguese Soccer Schedule from Portugal. It can be found in USA link. Maybe you can adding it to "FCFamalicaoPortugal.us" or "FCFamalicaoPortugal.pt" either way. I prefer ending with .pt to avoid the confused, perhaps ? And I don t know if you have foxsports epg link. If you dont then please adding it.

**Comment by freearhey** [comment]
The link shows the football team's game schedule. This repository is for TV channel guides.

**Comment by spotanjo3** [comment]
No, its football as in America called soccer. Not Football as in Football in America. This schedule is for Portugal soccer. Can tou add his and make a new name for new channel?

**Comment by spotanjo3** [comment]
What is epg link please?

**Comment by spotanjo3** [comment]
Hello, may I have an EPG link please ? ^_^

**Comment by RevGear** [comment]
> Hello, may I have an EPG link please ? ^_^

As already explained this is a repository for TV channel guides, not for sports team schedules. The same applies regardless if it is soccer, football, or any other sport.
