### ISSUE TITLE
Wrong times in tvmusor.hu

### ISSUE THREAD

**Issue by smrtprjcts** [iptv-org/epg#1953]
### Guide

https://iptv-org.github.io/epg/guides/hu/tvmusor.hu.xml

### Description

Lots of channels' programs have wrong times.
Example: Viasat Film

**Comment by PopeyeTheSai10r** [comment]
@smrtprjcts, can you expand on this issue?

Are only some channels or all channels affected?
How far back or forward is the wrong time?

**Comment by PopeyeTheSai10r** [comment]
Can be re-open once #2017 has been implemented.
