### ISSUE TITLE
Epg for HD Plus not working 

### ISSUE THREAD

**Issue by Kenanffb** [iptv-org/epg#1963]
### Guide

https://iptv-org.github.io/epg/guides/de/hd-plus.de.xml

### Description

Epg doesnt seem to work for a couple of days now

**Comment by freearhey** [comment]
At the moment the guide is working fine:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/7253922/216839100-f41f021c-e1df-4600-b6ea-313bef6ff377.png">
