### ISSUE TITLE
Bet Her (West), Nat Geo (West)

### ISSUE THREAD

**Issue by Kamiela20100** [iptv-org/epg#1978]
### Guide

https://www.ontvtonight.com/guide/listings/channel/5353620887/bet-her-west.html,      https://www.tvpassport.com/tv-listings/stations/national-geographic-us-pacific/10314

### Channels

Bet Her West
National Geographics West

Thanks in advance

**Comment by PopeyeTheSai10r** [comment]
Nat Geo (West) added in 84e91c5a4ef0702dd0b3e4b72416dfe1b6f64f7b
