### ISSUE TITLE
Issue with Arena Sport channels

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1986]
### Guide

https://iptv-org.github.io/epg/guides/sr/mts.rs.xml

### Description

Noticed that the xml file has Arena Sport 6, 7 & 8 listed as the Croatian versions, whereas 1-5 are Serbia. I assumed this was a mistake and they should be the Serbian versions but after looking at the EPG on the website, I'm even more confused! It lists the Arena Sport channels three times with Arena Sport 1-10. However, Arena Sport's own website only shows that 1-8 exists in Serbia (they also have Arena Sport 1-3 Premium). Croatia definitely has 1-10, seemingly with no Premium channels but all three sections of listings on the website show 1-10, although one of them shows no programmes for 9 (311) and 10 (312).

Also, after checking the database, it appears that this site is not showing as a valid EPG source for any of the Arena Sport Serbia channels but Arena Sport 6, 7 and 8 Croatia do show this as a valid source but I'm still not sure if the guide is actually showing programmes for the Serbian version.

Anyway, I'm not sure why this source isn't working for all the Serbian Arena Sport channels. Any ideas?

**Comment by freearhey** [comment]
It is possible that a mistake was made during the mapping of the channels. As you noticed on the site there is no clear indication for which channel version this guide is presented.

The current version of the markup for this site that we use is stored in the file `sites/mts.rs/mts.rs.channels.xml`.

https://github.com/iptv-org/epg/blob/af32711b39b648b6fc6b9d6d950d985a4bbe4c10/sites/mts.rs/mts.rs.channels.xml#L13-L24

If you see an error in it, please feel free to fix it by changing the `xmltv_id` to the correct one from [iptv-org.github.io](https://iptv-org.github.io/?q=name:%22arena%20sport%22) and then just send us your [pull request](https://github.com/iptv-org/epg/pulls).
