### ISSUE TITLE
tatasky.com

### ISSUE THREAD

**Issue by m0hamedessam** [iptv-org/epg#199]
https://kong-tatasky.videoready.tv/portal-search/pub/api/v1/channels/schedule?date=05-11-2021&languageFilters=&genreFilters=&limit=800&offset=0

https://kong-tatasky.videoready.tv/content-detail/pub/api/v1/forwardEpg/37591904?platform=WEB

**Comment by freearhey** [comment]
Both pages are blocked.

![image](https://user-images.githubusercontent.com/7253922/140600878-475d6f05-9e6a-43e9-ba7e-e374df6bf7fb.png)

**Comment by m0hamedessam** [comment]
Both url working on my side my your ip is blocked try with bon or proxy also you can check webgrab++ i got links from them source

**Comment by m0hamedessam** [comment]
![Uploading B4289D31-69B2-4F82-9210-24195870E0CC.jpeg…]()

**Comment by m0hamedessam** [comment]
![808AAB27-E3FA-45E4-88BC-93A5F6802CD6](https://user-images.githubusercontent.com/31938002/140606737-c992e286-6d57-4bf2-847d-1c81bb8a5096.jpeg)

**Comment by freearhey** [comment]
I'm sorry, but I can't add a source to the list if it only works through a VPN, it would make it unnecessarily difficult to maintain.
