### ISSUE TITLE
Mncvision

### ISSUE THREAD

**Issue by lynxnexy** [iptv-org/epg#20]
can you add the epg from this site https://www.mncvision.id/schedule

**Comment by freearhey** [comment]
I personally do not have time for this, but if there will be PR I will add the site to the list.

**Comment by lynxnexy** [comment]
ok i will wait, thank you

**Comment by MinePlayersPE** [comment]
Semi-related to #17, as it looks like the channel IDs needs to be sent as POST data (which is currently impossible because of how the grabber is configured)

**Comment by LaneSh4d0w** [comment]
> 
> 
> Semi-related to #17, as it looks like the channel IDs needs to be sent as POST data (which is currently impossible because of how the grabber is configured)

It would mean doing the channels by hand, and letting the program do a POST by iterating at every xml_id.
