### ISSUE TITLE
https://iptv-org.github.io/epg/guides/pl/programtv.onet.pl.json not available

### ISSUE THREAD

**Issue by mgroma** [iptv-org/epg#2002]
### Guide

https://iptv-org.github.io/epg/guides/pl/programtv.onet.pl.json

### Description

I"m getting 404 when trying to get JSON version of this guide. [XML version](https://iptv-org.github.io/epg/guides/pl/programtv.onet.pl.xml) seems to work fine

**Comment by RevGear** [comment]
JSON guides have been removed, see #1979
