### ISSUE TITLE
Canal+ Afrique Disappeared

### ISSUE THREAD

**Issue by boeder8** [iptv-org/epg#2004]
### Guide

https://iptv-org.github.io/epg/guides/fr/canalplus-afrique.com.xml

### Description

Hello,

The guide for Canal+ Afrique disappeared since yesterday's bot update, it is missing with today's update as well.

Is it an error that can be fixed?

Thank you!

**Comment by BellezaEmporium** [comment]
403 due to link changes. Gonna need to check as my last personal updates do not seem to work too.

**Comment by PopeyeTheSai10r** [comment]
Closing issue as per latest update.

https://github.com/iptv-org/epg#:~:text=IMPORTANT%3A%20We%20are%20no%20longer%20able%20to%20provide%20pre%2Dmade%20guides
