### ISSUE TITLE
Insight TV is rebranded

### ISSUE THREAD

**Issue by sensodejay** [iptv-org/epg#2011]
### Guide

https://iptv-org.github.io/epg/guides/en/tv.blue.ch.xml

### Description

InsightTV.nl are rebranded to "INPLUS.nl" (site id:1029)
InsightTVUHD.nl are rebranded to INULTRA.nl (site id:667)

https://inside.insight.tv/our-rebrand
https://www.prensario.net/38775-Insight-TV-announces-rename-and-rebranding-of-its-channels.note.aspx

Other guides can also be affected

**Comment by freearhey** [comment]
The IDs you are referring to are taken from our [iptv-org/database](https://github.com/iptv-org/database).

So these changes will have no effect on the parser. At the moment everything is working fine:

```sh
npx epg-grabber --config=sites/tv.blue.ch/tv.blue.ch.config.js --channels=sites/tv.blue.ch/tv.blue.ch.channels.xml --output=guide.xml
Starting...
Loading 'sites/tv.blue.ch/tv.blue.ch.config.js'...
Loading 'sites/tv.blue.ch/tv.blue.ch.channels.xml'...
[1/4] tv.blue.ch - InsightTV.nl - Jun 19, 2023 (39 programs)
[2/4] tv.blue.ch - InsightTV.nl - Jun 20, 2023 (40 programs)
[3/4] tv.blue.ch - InsightTVUHD.nl - Jun 20, 2023 (37 programs)
[4/4] tv.blue.ch - InsightTVUHD.nl - Jun 19, 2023 (37 programs)
File 'guide.xml' successfully saved
Finish
```
