### ISSUE TITLE
telenet.tv.xml EPG is 3 weeks old

### ISSUE THREAD

**Issue by sammyke007** [iptv-org/epg#2018]
Hi

I'm kinda new in the IPTV scene.
I see that the EPG telenet.tv.xml (Belgium) is 3 weeks old.
How can I "create" this XML myself? OR are there mirrors available?

Tnx

**Comment by fjrsaracho** [comment]
Hi, this repo has been closed for 3 weeks until yesterday.

Epg files will be updated once #2017 is done

**Comment by zuleyhasultan** [comment]
hello

he doesn't work for me either, I wonder when he'll co tvplus-and.digiturk.and.dsmart no work  please, I'm waiting for news

thanks

**Comment by sammyke007** [comment]
That was fast... Seems to be fixed!

**Comment by sammyke007** [comment]
I was 100% sure that telenet.tv.xml was updated earlier today, but now it's 3 weeks old again. Strange...

**Comment by benbelgium** [comment]
grab it for a while from another site, there are multiple options, just google it
(I recommend bevy.be myself)

**Comment by sammyke007** [comment]
I'm using Webgrabplus for now to compile an EPG myself, but TNX!

**Comment by PopeyeTheSai10r** [comment]
Epg files will be updated once https://github.com/iptv-org/epg/issues/2017 is done
