### ISSUE TITLE
add Fuji TV for the Japan guide

### ISSUE THREAD

**Issue by ChiFungLam** [iptv-org/epg#2020]
### Guide

https://iptv-org.github.io/epg/guides/ja/tvguide.myjcom.jp.xml

### Channels

- Fuji TV

**Comment by oldpoem** [comment]
FujiTV is named JOCXDTV.jp in EPG.

**Comment by ChiFungLam** [comment]
> FujiTV is named JOCXDTV.jp in EPG.
Got it, thanks a lot. Do you know the GitHub issue resolved ? The EPG not updated for weeks.

**Comment by BellezaEmporium** [comment]
https://github.com/iptv-org/epg/issues/2017

**Comment by PopeyeTheSai10r** [comment]
Closing issue as per latest update.

https://github.com/iptv-org/epg#:~:text=IMPORTANT%3A%20We%20are%20no%20longer%20able%20to%20provide%20pre%2Dmade%20guides
