### ISSUE TITLE
New Hungarian Channels

### ISSUE THREAD

**Issue by sirjohn771103** [iptv-org/epg#2021]
### Guide

https://github.com/iptv-org/epg/blob/master/sites/musor.tv/musor.tv.channels.xml

### Channels

- Magyar Mozi TV: https://musor.tv/mai/tvmusor/MAGYAR_MOZI_TV
- MAX4: https://musor.tv/mai/tvmusor/MAX4

**Comment by smrtprjcts** [comment]
Started: https://github.com/iptv-org/database/pull/2764

**Comment by PopeyeTheSai10r** [comment]
Added in https://github.com/iptv-org/epg/commit/35884284011bc5d0896c863ea774df65f8d86d42
