### ISSUE TITLE
None of the EPGs for US or UK or IE seem to have actual program information

### ISSUE THREAD

**Issue by IamMikeStone** [iptv-org/epg#2027]
### Guide

https://iptv-org.github.io/epg/guides/en/virginmedia.com.xml

### Description

None of the guides for "EN" seem to have actual programming in them.  The icons load, but everything displays as "No information".

**Comment by grand8400** [comment]
Hello ,
I have the same issue. I am using Tivimate player.

**Comment by fjrsaracho** [comment]
Epg files will be updated once https://github.com/iptv-org/epg/issues/2017 is done

**Comment by Dr3sdan** [comment]
Yeah it seems to be an issue with the CI setup.

Once thats sorted then it'll be back up again working.

**Comment by BellezaEmporium** [comment]
https://github.com/iptv-org/epg/issues/2017

**Comment by eldepor** [comment]
I downloaded epg.zip you provided few days ago and used epg grabber to download the guides locally. It worked beautifully but since last days im getting connection timeout when downloading programs for "tvguide.com.xml" with directv.com.config.js and directv.com.channels.xml.

```
(1)/epg
$ npx epg-grabber --config=tvguide.com/tvguide.com.config.js --channels=tvguide.com/tvguide.com.channels.xml --output=xml/tvguide.com.xml --days=2
Starting...
Loading 'tvguide.com/tvguide.com.config.js'...
Loading 'tvguide.com/tvguide.com.channels.xml'...
[1/6] tvguide.com - ESPN.us - Mar 22, 2023 (0 programs)
  Error: Request failed with status code 500
[2/6] tvguide.com - ESPN.us - Mar 23, 2023 (0 programs)
  Error: Request failed with status code 500
...
```

**Comment by benbelgium** [comment]
> 

500 is timeout, although I just checked and tvguide.com is up and running, so it's not total failure of the site
Most likely they changed something about their API being used:

const url = `https://cmg-prod.apigee.net/v1/xapi/tvschedules/tvguide/${providerId}/web?start=${date

if they change this URL you would get a timeout, this needs investigation
same problem for directv.com....
but I don't think the guys here are doing anything until they have their new CI....
and I have limited time this week to investigate myself... maybe sunday....

**Comment by eldepor** [comment]
No problem, just to inform ;). Thanks!

**Comment by BellezaEmporium** [comment]
> > 
> 
> 500 is timeout, although I just checked and tvguide.com is up and running, so it's not total failure of the site
> Most likely they changed something about their API being used:
> 
> const url = `https://cmg-prod.apigee.net/v1/xapi/tvschedules/tvguide/${providerId}/web?start=${date
> 
> if they change this URL you would get a timeout, this needs investigation
> same problem for directv.com....
> but I don't think the guys here are doing anything until they have their new CI....
> and I have limited time this week to investigate myself... maybe sunday....

I have an up and running CI though I make specific guides only.

**Comment by benbelgium** [comment]
I checked it anyway :)
It appears they changed the URL from cmg to fandom
So by editing the tvguide.com.config.js file and changing the URL to https://fandom-prod.apigee.net it started working again
![image](https://user-images.githubusercontent.com/43570427/227517305-558c74c2-dc4e-4a12-8bd0-3a117b287638.png)

I'll launch a pull request for this... but for now you can already change it manually if you like

Take Care

Ben

**Comment by eldepor** [comment]
Awesome! Any idea on how to fix directv aswell? Thanks a lot.

**Comment by benbelgium** [comment]
> Awesome! Any idea on how to fix directv aswell? Thanks a lot.

no I don't, I already looked into that myself, but the problem is different
I would have to examine it step by step and that would take some time that I don't have right now
maybe tomorrow, but my 8 weeks old baby is really messing up my schedule :)

**Comment by benbelgium** [comment]
@eldepor : I found why directv isn't working but it's something I can't fix myself, I'm contacting the developer to try and sort it out...

**Comment by ovladuk** [comment]
> I downloaded epg.zip you provided few days ago and used epg grabber to download the guides locally. It worked beautifully but since last days im getting connection timeout when downloading programs for "tvguide.com.xml" with tvguide.com.config.js and tvguide.com.channels.xml files, it returns server error 500.
> 
> ```
> $ npx epg-grabber --config=tvguide.com/tvguide.com.config.js --channels=tvguide.com/tvguide.com.channels.xml --output=xml/tvguide.com.xml --days=2
> Starting...
> Loading 'tvguide.com/tvguide.com.config.js'...
> Loading 'tvguide.com/tvguide.com.channels.xml'...
> [1/6] tvguide.com - ESPN.us - Mar 22, 2023 (0 programs)
>   Error: Request failed with status code 500
> [2/6] tvguide.com - ESPN.us - Mar 23, 2023 (0 programs)
>   Error: Request failed with status code 500
> ...
> ```

how did you run it locally? i don't see anywhere about how to do that
