### ISSUE TITLE
Guides still not being updated?

### ISSUE THREAD

**Issue by markosjal** [iptv-org/epg#2033]
### Description

I am very confused after this repo went down and came back up.....

It seems the guides are available but in the case of TVPassport contains stale data from Feb 14th

Can someone clarify?

**Comment by F640** [comment]
Github recently removed access to Github Actions (previous CI) for this repo due to resouce abuse by Github staff, so maintainers at here are currently considering about another CI. You might want to read this #2017

**Comment by BellezaEmporium** [comment]
https://github.com/iptv-org/epg/issues/2017
