### ISSUE TITLE
KET2?

### ISSUE THREAD

**Issue by CITZ-IMB-rwk** [iptv-org/epg#2034]
### Guide

https://iptv-org.github.io/epg/guides/en/tvpassport.com.xml

### Channels

Hi , hope I am not asking something someone else has already answered... I can not locate a KET2 (Kentucky PBS) EPG in xmltv form...anyone? thx in advance

**Comment by BellezaEmporium** [comment]
Indeed, doesn't seem to be in our programs. We shall add it in our database ASAP.

**Comment by PopeyeTheSai10r** [comment]
KET2 should be WKMJDT2.us - https://en.wikipedia.org/wiki/WKMJ-TV
