### ISSUE TITLE
[meo.pt] Broken config

### ISSUE THREAD

**Issue by BellezaEmporium** [iptv-org/epg#2035]
### Guide

meo.pt.guide.xml

### Description

Now needs the "Origin" header to be set to https://www.meo.pt in order to get the programs.

**Comment by eldepor** [comment]
nos.pt it's broken too. Did they remove the guide from their site?

**Comment by LITUATUI** [comment]
> nos.pt it's broken too. Did they remove the guide from their site?

I confirm, nos.pt is broken too.
