### ISSUE TITLE
How to repair tvguide.com

### ISSUE THREAD

**Issue by benbelgium** [iptv-org/epg#2036]
### Guide

https://iptv-org.github.io/epg/guides/en/tvguide.com.xml

### Description

It appears they changed the API URL from cmg to fandom
So by editing the tvguide.com.config.js file and changing the URL to https://fandom-prod.apigee.net/ it started working again

Please change this in your online version as well

Take Care

Ben

**Comment by zuleyhasultan** [comment]
hello 

i have these, I wonder how it works help please , i used the panel xtream codec

https://iptv-org.github.io/epg/guides/tr/digiturk.com.tr.xml

https://iptv-org.github.io/epg/guides/tr/dsmart.com.tr.xml

https://iptv-org.github.io/epg/guides/tr/tvplus.com.tr.xml

**Comment by benbelgium** [comment]
> hello
> 
> i have these, I wonder how it works help please , i used the panel xtream codec
> 
> https://iptv-org.github.io/epg/guides/tr/digiturk.com.tr.xml
> 
> https://iptv-org.github.io/epg/guides/tr/dsmart.com.tr.xml
> 
> https://iptv-org.github.io/epg/guides/tr/tvplus.com.tr.xml

It looks like these files were no longer updated/created
digiturk seems broken
smart looks ok, but old file (13/02)
tvplus looks ok, but old file (13/02)

This is probably also because of the CI missing problem, the crew on this site are looking for a solution
For now, you can use another site maybe? (I recommend bevy.be)

Take Care

Ben

**Comment by zuleyhasultan** [comment]
> 
hi bro 

if you are a member, tell them to add , i would be very glad if you have any information ( bevy.be)

thanks thanks thanks

**Comment by benbelgium** [comment]
> > 
> 
> hi bro
> 
> if you are a member, tell them to add , i would be very glad if you have any information ( bevy.be)
> 
> thanks thanks thanks

done

**Comment by zuleyhasultan** [comment]
all thanks bro

**Comment by benbelgium** [comment]
> all thanks bro

ur welcome
