### ISSUE TITLE
[indihometv.com] Error: Connection timeout

### ISSUE THREAD

**Issue by leakssh** [iptv-org/epg#2037]
### Guide

https://iptv-org.github.io/epg/guides/id/indihometv.com.xml

### Description

Error: Connection timeout
![Screenshot_2023-03-25-13-25-53-134_com termux](https://user-images.githubusercontent.com/87708571/227700928-3fa65199-fa87-4eff-bf60-98c415addb2e.jpg)

**Comment by freearhey** [comment]
Try adding the `timeout` parameter to the command:

```
epg-grabber --timeout=30000 --config=indihometv.com.config.js --channels=indihometv.com.config.xml --days=2
```

https://github.com/freearhey/epg-grabber#cli
