### ISSUE TITLE
What is going on here, none the US channels seem to be working, some UK locals are missing, I've never seen this site in such a shambles

### ISSUE THREAD

**Issue by paul19920801** [iptv-org/epg#2039]
### Guide

not sure

### Description

All the US guides don't seem to want to load, channels such as BBC Two Wales across all the UK guides don't seem to  be working. 

Also I don't understand why the site had to be restructered.

I prefered it when the EPGs were grouped by country, and by provider.

**Comment by CITZ-IMB-rwk** [comment]
take into consideration a) volunteers b) GITHUB recently put the site on pause and c) a different workflow is required to prep the epg lists and that will take time

**Comment by BellezaEmporium** [comment]
Easy : #2017
