### ISSUE TITLE
MovistarPlus.es guide not updated

### ISSUE THREAD

**Issue by lmarceg** [iptv-org/epg#2042]
### Guide

https://iptv-org.github.io/epg/guides/es/movistarplus.es.xml

### Description

The EPG is blocked at 2023-02-13.
Can you check?
The source URL https://www.movistarplus.es/programacion-tv/2023-04-12?v=json is working fine

Thanks

**Comment by PopeyeTheSai10r** [comment]
EPG files will be updated once https://github.com/iptv-org/epg/issues/2017 is completed
