### ISSUE TITLE
All Swedish EPG last updated over two months ago

### ISSUE THREAD

**Issue by no-connections** [iptv-org/epg#2050]
### Guide

https://iptv-org.github.io/epg/guides/sv/tv24.se.xml

### Description

allente.se https://iptv-org.github.io/epg/guides/sv/allente.se.xml
teliatv.ee https://iptv-org.github.io/epg/guides/sv/teliatv.ee.xml
tv.nu https://iptv-org.github.io/epg/guides/sv/tv.nu.xml
tv24.se https://iptv-org.github.io/epg/guides/sv/tv24.se.xml

I spent some time troubleshooting until I figured out all of the data was from February.

**Comment by PopeyeTheSai10r** [comment]
Hello @no-connections, This is a known issue at this time and should be fixed once #2017 gets implemented.

**Comment by no-connections** [comment]
@PopeyeTheSai10r I don't see anything on the front page to indicate something would be wrong at all.

**Comment by PopeyeTheSai10r** [comment]
https://github.com/orgs/iptv-org/discussions/12 has more information.

**Comment by no-connections** [comment]
@PopeyeTheSai10r again, https://github.com/iptv-org/epg have no mention of anything being wrong, would probably be a good thing to at least add a small mention rather than saying that you should report any issue. Which won't do anything anyway except cause more work.

**Comment by PopeyeTheSai10r** [comment]
@no-connections See #2058
