### ISSUE TITLE
hd-plus.de and other German data outdated

### ISSUE THREAD

**Issue by hurzl** [iptv-org/epg#2052]
### Guide

https://iptv-org.github.io/epg/guides/de/hd-plus.de.xml

### Description

I get a file but it is of Feb 13th.

same for https://iptv-org.github.io/epg/guides/de/horizon.tv.xml
https://iptv-org.github.io/epg/guides/de/tv.blue.ch.xml
https://iptv-org.github.io/epg/guides/de/programme-tv.net.xml
etc. etc.

... everything is of Feb 13th? Why?

Can't there be a notice that everything is broken?

**Comment by PopeyeTheSai10r** [comment]
See https://github.com/iptv-org/epg/issues/2058
