### ISSUE TITLE
how to update channels.xml files

### ISSUE THREAD

**Issue by ovladuk** [iptv-org/epg#2053]
### Description

so i know how to run the grabber to scrape my own guide locally, but how can i update the channels.xml files to add more channels to scrape? i manually added a few more channels to one of the xml files by matching names and id's from the guide website but that would take so long to do!

**Comment by PopeyeTheSai10r** [comment]
Checkout the [Contributing Guide]( https://github.com/iptv-org/epg/blob/master/CONTRIBUTING.md#contributing-guide). The same applies to local edits but may as well share with the community if you find some channels that can be added.
