### ISSUE TITLE
Czech guides not updating from Fer 2023

### ISSUE THREAD

**Issue by cooltom** [iptv-org/epg#2055]
### Guide

https://iptv-org.github.io/epg/guides/cs/m.tv.sms.cz.xml

### Description

https://iptv-org.github.io/epg/guides/cs/m.tv.sms.cz.xml
https://iptv-org.github.io/epg/guides/cs/mujtvprogram.cz.xml

there is no update from february on this czech guides. Are they tsill alive?

Thnx

**Comment by BellezaEmporium** [comment]
#2017
