### ISSUE TITLE
Add Indonesian EPG Source: firstmedia.com

### ISSUE THREAD

**Issue by keystrom-laplace** [iptv-org/epg#2074]
### Source

https://www.firstmedia.com/tv-guide

### Notes

Hi, this is my first time in issues forum, and thank you for all your help.

I have been wondering if you can add the EPG source from Indonesian cable TV First Media.

If you can't, then can I have a personal tutorial on how to add site sources myself?

Thank you for your future response(s).

**Comment by PopeyeTheSai10r** [comment]
Hello, I don't think there's a tutorial out there on how to create site sources. 
You can take a look at https://github.com/freearhey/epg-grabber#site-config for more information on what's needed for the configs.

**Comment by liimee** [comment]
working on it--almost done but still got a few issues
