### ISSUE TITLE
nmp command gives error message

### ISSUE THREAD

**Issue by akdemiris** [iptv-org/epg#2094]
Gentlemen, 
I am not a programmer nor understand commands as well. In order to get the epg data I need I followed the instructions on my PC, installed the neccessary programs and run the commands as written, but I could not get what I want. The error message I get after the command: SITE=digiturk.com.tr npm run grab is as follows, please help, I do not know what I am doing wrong:
akdem@smailey MINGW64 ~/epg (master)
$ SITE=raiplay.it npm run grab

> grab
> npx epg-grabber --config=sites/${SITE}/${SITE}.config.js --channels=sites/${SITE}/${SITE}.channels.xml --output=guides/{lang}/{site}.xml

Starting...
Loading 'sites/${SITE}/${SITE}.config.js'...
node:internal/modules/cjs/loader:1075
  const err = new Error(message);
              ^

Error: Cannot find module 'C:\Users\akdem\epg\sites\${SITE}\${SITE}.config.js'
Require stack:
- C:\Users\akdem\epg\node_modules\epg-grabber\bin\epg-grabber.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at main (C:\Users\akdem\epg\node_modules\epg-grabber\bin\epg-grabber.js:54:16)
    at Object.<anonymous> (C:\Users\akdem\epg\node_modules\epg-grabber\bin\epg-grabber.js:157:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\akdem\\epg\\node_modules\\epg-grabber\\bin\\epg-grabber.js'
  ]
}

Node.js v18.16.0

**Comment by Dave1173** [comment]
Had the same issue on windows it seems to be a software issue if you have a Mac or a Linux setup it will run i been running it perfectly by running Linux as a second operating system

**Comment by Gitbone94** [comment]
Same issue. I followed all the steps and when I got to SITE=example.com npm run grab  (I chose a couple of site options)
it fails to create a Guide directory. Tried to two different computers running Win 10.

**Comment by BellezaEmporium** [comment]
> akdem@smailey MINGW64

Using Mingw, use "set SITE=*insert site*" before launching grab. From my understanding, it doesn't recognize the variable as being initiated.

**Comment by x011** [comment]
You're missing a forward slash on the path `C:\Users\akdem\epg\sites[HERE]${SITE}${SITE}.config.js`

**Comment by dheer99** [comment]
> Had the same issue on windows it seems to be a software issue if you have a Mac or a Linux setup it will run i been running it perfectly by running Linux as a second operating system

can you please assist, I am facing issue in Windows as well as Ubuntu 18.x 

=========================================================
[npm-debug.log](https://github.com/iptv-org/epg/files/11829861/npm-debug.log)
