### ISSUE TITLE
get schedules

### ISSUE THREAD

**Issue by lynxnexy** [iptv-org/epg#21]
how to get the schedule for the next 7 days from `site: vidio.com`

**Comment by freearhey** [comment]
currently, we only load the schedule from each source one day in advance

**Comment by lynxnexy** [comment]
Ok

**Comment by ksufinger** [comment]
Would it be possible to extend the schedule longer than 1 day, or generate the guide twice a day to compensate for the ~4 hour gap created in the time it takes to run each day?

**Comment by freearhey** [comment]
@ksufinger It all depends on the source, but in general it can be done.
