### ISSUE TITLE
sky.de guide broken

### ISSUE THREAD

**Issue by dimobln** [iptv-org/epg#2101]
### Guide

https://github.com/iptv-org/epg/blob/master/sites/sky.de/sky.de.config.js

### Description

sky.de code does not work anymore. Channel id's are still correct but the script does not get any EPG data.

**Comment by BellezaEmporium** [comment]
https://github.com/iptv-org/epg/issues/2058

**Comment by freearhey** [comment]
I just tested and it is working fine.

```sh
npx epg-grabber --config=sites/sky.de/sky.de.config.js --channels=sites/sky.de/sky.de.channels.xml --output=guide.xml
Starting...
Loading 'sites/sky.de/sky.de.config.js'...
Loading 'sites/sky.de/sky.de.channels.xml'...
[1/2] sky.de - 13thStreet.de - Jun 19, 2023 (29 programs)
[2/2] sky.de - 13thStreet.de - Jun 20, 2023 (31 programs)
File 'guide.xml' successfully saved
Finish
```

**Comment by dimobln** [comment]
I am getting 403 error messages...
`Loading 'sites/sky.de/sky.de.config.js'...
Loading 'sites/sky.de/sky.de.channels.xml'...
[1/158] sky.de - 13thStreet.de - Jun 19, 2023 (0 programs)
  Error: Request failed with status code 403
[2/158] sky.de - 13thStreet.de - Jun 20, 2023 (0 programs)
  Error: Request failed with status code 403
[3/158] sky.de - BeateUhseTV.de - Jun 20, 2023 (0 programs)
  Error: Request failed with status code 403
[4/158] sky.de - CartoonNetworkGermany.de - Jun 20, 2023 (0 programs)
  Error: Request failed with status code 403
`

**Comment by freearhey** [comment]
@dimobln This usually means that the site is blocked in your country. Try running the parser with VPN enabled.
