### ISSUE TITLE
Request to update "dishtv.in.channels.xml" with all latest channels 

### ISSUE THREAD

**Issue by dheer99** [iptv-org/epg#2109]
### Guide

https://github.com/iptv-org/epg/blob/master/sites/dishtv.in/dishtv.in.channels.xml

### Channels

E.g 
MTV Beats
Times Now Navbharat
etc.

### Notes

.

**Comment by PopeyeTheSai10r** [comment]
Take a look at the [How do I add a program guide for the channel?](https://github.com/iptv-org/epg/blob/master/CONTRIBUTING.md#how-do-i-add-a-program-guide-for-the-channel) guide, if would like to try adding the missing channels yourself.

**Comment by dheer99** [comment]
sorry, but I am really not sure how I an get the latest full list of channels, 
its really help, if you can update.

**Comment by dheer99** [comment]
can someone assist please

**Comment by dheer99** [comment]
Thank you

**Comment by dheer99** [comment]
thanks
