### ISSUE TITLE
canalplus-afrique.com is broken

### ISSUE THREAD

**Issue by YassineElbouchaibi** [iptv-org/epg#2120]
### Site

canalplus-afrique.com

### Description

`canalplus-afrique.com`'s API seems to have changed.

It only returns 403 error codes.

I found this Closed PR (https://github.com/iptv-org/epg/pull/2032) and wanted to try and revive it but branch seems to have been deleted from github.

Errors Example:
```
[44/484] canalplus-afrique.com - TraceMziki.fr - Jul 5, 2023 (0 programs)
  Error: Request failed with status code 403
[45/484] canalplus-afrique.com - TraceMboa.fr - Jul 6, 2023 (0 programs)
  Error: Request failed with status code 403
[46/484] canalplus-afrique.com - TraceMboa.fr - Jul 5, 2023 (0 programs)
  Error: Request failed with status code 403
[47/484] canalplus-afrique.com - TraceKitoko.fr - Jul 6, 2023 (0 programs)
  Error: Request failed with status code 403
```

**Comment by freearhey** [comment]
The guides for all African countries have been moved from `canalplus-afrique.com` to `canalplus.com` (https://github.com/iptv-org/epg/pull/2136), so you can use its config instead: https://github.com/iptv-org/epg/tree/master/sites/canalplus.com
