### ISSUE TITLE
Possible timezone conversion issue

### ISSUE THREAD

**Issue by medhursta** [iptv-org/epg#2123]
I have notice the the time of the schedules seems to be miss aligned. I'm current in the UK so my timezone is current BST (UTC +0100).

Below is just an example but I have seen this across the board but if look at the resulting guide 'guides/en/sky.com.xml' and I take an entry on the BBCOneEngland.uk channel which in this files is stored as starting at 2023-07-06 22:40:00 +0000 (year, month, day, hour, min, sec, utc offset). Title being Newscast.

![image](https://github.com/iptv-org/epg/assets/124404635/ac6b30f0-0e10-459f-828d-352e57ad4e7b)

If I find the original data from [https://epgservices.sky.com/5.2.2/api/2.0/channel/json/2076/1688684053/86400/4](https://epgservices.sky.com/5.2.2/api/2.0/channel/json/2076/1688684053/86400/4) I can see that the time of Newcast is 1688685600 unix time. Using a converter this converts to 2023-07-06 23:20:00 +0000

![image](https://github.com/iptv-org/epg/assets/124404635/877776d3-fa38-4f44-866d-339c9bc69b5f)

Sky.com is not the only site which appears to have this problem.

I am running the scripts on a windows server 2022 environment where the clock is set to BST.

**Comment by freearhey** [comment]
I have not been able to find any discrepancy in the times given in the source and in the final guide.

https://epgservices.sky.com/5.2.2/api/2.0/channel/json/2076/1689033600/86400/4

```jsonc
...
{
	"s": 1689079500,
	"t": "Wimbledon",
	"audioDescription": false,
	"m": [
		10370,
		15300,
		3,
		1,
		"--"
	],
	"rr": "S",
	"subtitleHearing": true,
	"sid": 2343,
	"d": "Live coverage of day nine from the All England Club as the quarter-finals continue at this famous Grand Slam. [S] [HD]",
	"img": "lisa/5.2.2/linear/channel/0f5b2e6c-cc1f-3904-9bbb-05b607a55169/2076"
},
...
```


_guide.xml_

```xml
<programme start="20230711124500 +0000" stop="20230711170000 +0000" channel="BBCOneEngland.uk"><title lang="en">Wimbledon</title><desc lang="en">Live coverage of day nine from the All England Club as the quarter-finals continue at this famous Grand Slam. [S] [HD]</desc><icon src="http://epgstatic.sky.com/epgdata/1.0/paimage/46/1/lisa/5.2.2/linear/channel/0f5b2e6c-cc1f-3904-9bbb-05b607a55169/2076"/></programme>
```

<img width="651" alt="image" src="https://github.com/iptv-org/epg/assets/7253922/1dcb6ba7-0a5b-4511-9b3c-a65e99f86dc3">
