### ISSUE TITLE
tvtv.us gives 429 (rate limit) errors after a while

### ISSUE THREAD

**Issue by scumola** [iptv-org/epg#2132]
### Description

Need to slow down or honor the tvtv.us rate limits.  The npm run grab command causes tvtv.us to give 429 errors when pulling the data.

**Comment by jvdillon** [comment]
FYI, I'm getting error 429 with the default delay of 500. Using 1500 seemed to work.

**Comment by brianjmurrell** [comment]
This delay doesn't seem to be working any more.  I still seem to hit 429s with `tvtv.us`:

```
info   [137/144] tvtv.us (en) - StingrayHitList.ca@SD - Jan 14, 2026 (0 programs)
info     ERR: Request failed with status code 429
```

Would be quite informational if we could get the headers from the reply that show the retry limits/try again time.

I'd even be interested in knowing of a valid API query that I could run with `curl` to see valid response headers myself.

**Comment by freearhey** [comment]
> I'd even be interested in knowing of a valid API query that I could run with curl to see valid response headers myself.

```sh
npm run grab --- --site=tvtv.us --curl
```

https://github.com/iptv-org/epg?tab=readme-ov-file#usage

**Comment by brianjmurrell** [comment]
Oh neat.  I would have checked the usage if I'd had even an inkling of an idea that you would have implemented such a useful option!

Sadly, and anti-socially, they don't report the usual 429 headers, informing of rate limits and when you can query again.

Is there any understanding of the rate limits being applied here?  I.e. how many and over how long, etc.?  I seem to just get them constantly now so I'm not even sure how long I need to wait until I can make even just one more request.
