### ISSUE TITLE
telecablesat.fr error 403

### ISSUE THREAD

**Issue by georgeTB** [iptv-org/epg#2137]
### Site

telecablesat.fr

### Description

I get "Error: Request failed with status code 403" for telecablesat.fr

**Comment by MakwaWes** [comment]
Hi,
I had the same issue on my side and was able to fix it using the same solution as here :  
https://github.com/iptv-org/epg/issues/2038

So in the `telecablesat.fr.config.js` file, I've added the `request` component just under the `delay` line.  
```
site: 'telecablesat.fr',
  days: 2,
  delay: 5000,
  request: {
    cache: {
      ttl: 60 * 60 * 1000 // 1 hour
    },
    headers: {
      'Accept-Language':'en-US,en;q=0.5',
      'Connection':'keep-alive',
      'user-Agent': 'Mozilla/5.0 (Windows NT 10.0; rv:114.0) Gecko/20100101 Firefox/114.0'
    },
  },
```

Unfortunately, the `npm run channels:parse -- --config=./sites/telecablesat.fr/telecablesat.fr.config.js --output=./sites/telecablesat.fr/telecablesat.fr.channels.xml` command still doesn't work.

**Comment by georgeTB** [comment]
Wow, amazing! It works indeed!
