### ISSUE TITLE
[Source Request] CubMu.com

### ISSUE THREAD

**Issue by devhik** [iptv-org/epg#2138]
### Source

https://www.cubmu.com

### Notes

HOME
https://www.cubmu.com

LIVE TV
https://www.cubmu.com/play/live-tv?id=4028c68574537fcd0174be292d655725&genreId=4

EPG DATA
https://servicebuss.transvision.co.id/v2/cms/getEPGData?app_id=cubmu&tvs_platform_id=standalone&schedule_date=2023-07-22&channel_id=4028c68574537fcd0174be292d655725

![Screenshot_2023-07-22-15-13-41-611_com android chrome](https://github.com/iptv-org/epg/assets/119641432/d5b64d6c-2211-4f0f-92bc-00e2f8bf5859)

**Comment by devhik** [comment]
please help me bro 😅

**Comment by freearhey** [comment]
Added in #2207. Thanks to @tohenk
