### ISSUE TITLE
telenet.tv breaks

### ISSUE THREAD

**Issue by trincowski** [iptv-org/epg#2146]
### Site

telenet.tv

### Description

For some reason, the script stops running when it gets to this point:

![image](https://github.com/iptv-org/epg/assets/33147829/76ef9937-14ab-40a3-912e-09671281a5cb)

Removing that channel from the list made it work until the end:

![image](https://github.com/iptv-org/epg/assets/33147829/f6bd91d3-491a-429b-8ebe-5384d40f46ae)

What could be the problem?

**Comment by PopeyeTheSai10r** [comment]
Working fine for me when running using the command below.

```
npx epg-grabber --config=sites/telenet.tv/telenet.tv.config.js --channels=sites/telenet.tv/telenet.tv.channels.xml --output=guide.xml --days=1

Starting...
Loading 'sites/telenet.tv/telenet.tv.config.js'...
Loading 'sites/telenet.tv/telenet.tv.channels.xml'...

[1/110] telenet.tv - 2MInternational.ma - Aug 25, 2023 (47 programs)
[2/110] telenet.tv - AB3.be - Aug 25, 2023 (34 programs)
[3/110] telenet.tv - AnimalPlanetNetherlands.nl - Aug 25, 2023 (29 programs)
[4/110] telenet.tv - BBCEntertainment.uk - Aug 25, 2023 (37 programs)
```

**Comment by freearhey** [comment]
The config works fine for me too.

If the problem is still there try to run it using this command:

```sh
npm run grab -- --site=telenet.tv
```
