### ISSUE TITLE
EPG automatic refresh?

### ISSUE THREAD

**Issue by anoo2niem** [iptv-org/epg#2148]
### Description

Hi guys, i came across this project and i want to start using it to implement epg into my jellyfin iptv.

My goal is to run this on a container on my proxmox host, so it then can serve the epg xml into my jellyfin.
I see u can adjust the amount of days in config.js, which is wonderful.

My question is, for explamle the default days is 2, do i have to manually (or cronjob) every 2 days to update the list?
Or does it do this automatically?

Thanks!

**Comment by yarafie** [comment]
Did you build a Docker container?

**Comment by anoo2niem** [comment]
> Did you build a Docker container?

No installed on debian container on proxmox host, ended up using cronjob & bash script to automate the refresh.
Why?

**Comment by yarafie** [comment]
Thought you might have a Docker file that I can use instead of me trying to start from scratch

**Comment by anoo2niem** [comment]
To automate the updating? 
I can share the simple bash script & cron entries if u want

**Comment by yarafie** [comment]
great so you went into the ziggogo.tv.conf and changed to days: 5 same with telenet.tv.conf

**Comment by anoo2niem** [comment]
Yes
