### ISSUE TITLE
firstmedia.com unable to fetch EPG data

### ISSUE THREAD

**Issue by keystrom-laplace** [iptv-org/epg#2151]
### Description

I used the command accordingly, and I have never successfully fetch the EPG data from the site. How can I resolve this?
Thank you.
![image](https://github.com/iptv-org/epg/assets/71865572/8e44f1ca-2a4c-4ecf-9300-7fe5d683b3e4)

**Comment by devhik** [comment]
Itu memang dari webnya bang.. susah di aksess.. bukan masalah script config nya.. mending ambil dari source lain
