### ISSUE TITLE
My npm server is not working

### ISSUE THREAD

**Issue by keystrom-laplace** [iptv-org/epg#2154]
### Description

I already have started the server with 'npm run serve', but it's not sending anything to either my phone or my Android TV.
![image](https://github.com/iptv-org/epg/assets/71865572/5bb67557-d70d-4aa7-bb6d-bde726da12d3)

What network settings should I change for this? Thank you

**Comment by carlosmesquita** [comment]
Hello @keystrom-laplace , what were you expecting to "receive" on your phone or Android TV?

**Comment by keystrom-laplace** [comment]
The EPG.xml files

**Comment by carlosmesquita** [comment]
How are you trying to access them? Which URL are you trying to access?

**Comment by freearhey** [comment]
If you have already generated the guide and your phone or Android TV is on the same network as your computer, it will be enough to specify the link to the guide in the app you want to use.

Example:

```
http://192.168.0.12:3000/guides/fr/example.com.xml
```

https://github.com/iptv-org/epg?tab=readme-ov-file#how-to-use
