### ISSUE TITLE
[IPKO.COM] Cannot read properties of undefined (reading 'lang')

### ISSUE THREAD

**Issue by deniscerri** [iptv-org/epg#2156]
### Site

ipko.com

### Description

ipko is an albanian guide site

**Comment by freearhey** [comment]
This config works fine for me:

```sh
npm run grab -- --site=ipko.com
```

<img width="643" alt="image" src="https://github.com/iptv-org/epg/assets/7253922/b095b065-6f38-42fc-8828-e25c90989b85">
