### ISSUE TITLE
New install - broken installer

### ISSUE THREAD

**Issue by AahzNotOz** [iptv-org/epg#2159]
### Description

Trying to set up for the first time, and there are dependency issues that need to be fixed.  here's the result of the npm audit after trying to install:

# npm audit report

json5  <1.0.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
No fix available
node_modules/json5
  babel-core  5.8.20 - 7.0.0-beta.3
  Depends on vulnerable versions of babel-register
  Depends on vulnerable versions of json5
  node_modules/babel-core
    babel-register  *
    Depends on vulnerable versions of babel-core
    node_modules/babel-register
      cross-var  *
      Depends on vulnerable versions of babel-register
      node_modules/cross-var

4 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

**Comment by alexisspencer** [comment]
Also getting the same on a new install

**Comment by AahzNotOz** [comment]
Despite this, I've been able to get it to do something, but it is not pulling good EPGs.  When I run the following command:

npm run grab -- --site=maxtvgo.mk --gzip --cron="0 0 * * *"

I get the following message back:
> grab
> node scripts/commands/epg/grab.js --site=maxtvgo.mk --gzip --cron=0 0 * * *

o staring...                                                                                                8:13:30 AM
i settings:                                                                                                 8:13:30 AM
i   gzip: true                                                                                              8:13:30 AM
i   site: maxtvgo.mk                                                                                        8:13:30 AM
i   cron: 0 0 * * *                                                                                         8:13:30 AM
i   output: C:\Users\DanMc\epg\guides\{lang}\{site}.xml                                                     8:13:30 AM
i   config: C:\Users\DanMc\epg\sites\maxtvgo.mk\maxtvgo.mk.config.js                                        8:13:30 AM
i   channels: C:\Users\DanMc\epg\sites\maxtvgo.mk\maxtvgo.mk*.channels.xml                                  8:13:30 AM
i config:                                                                                                   8:13:30 AM
i   site: maxtvgo.mk                                                                                        8:13:30 AM
i   days: 2                                                                                                 8:13:30 AM
i creating queue...                                                                                         8:13:30 AM
[Error: ENOENT: no such file or directory, open 'C:\Users\DanMc\epg\scripts\tmp\data\channels.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\DanMc\\epg\\scripts\\tmp\\data\\channels.json'
}

 ERROR  "undefined" is not valid JSON                                                                       8:13:30 AM

  at JSON.parse (<anonymous>)
  at API.load (scripts\core\api.js:13:28)
  at async createQueue (scripts\commands\epg\grab.js:123:3)
  at async main (scripts\commands\epg\grab.js:42:17)

I can find no channels.json file in the github source, so I assume the file is supposed to be generated, but where I do not know.  Maybe the source of the problem is the broken install in my first message?  I have tried to run a few different sites for the epg, and all if them generate a bad guide xml file, list only a single channel id= element and then all guide data for all channels below that.
[maxtvgo.mk.xml.gz](https://github.com/iptv-org/epg/files/12517779/maxtvgo.mk.xml.gz)

**Comment by AahzNotOz** [comment]
Issue #2161 got had information on using another puller that got me closer, but it looks like the channels I'm getting from https://iptv-org.github.io/iptv/countries/mk.m3u do not match the channels that are in the epg\sites\maxtvgo.mk\ folder. There are a few channels, which is why I'm seeing some channels with guide data, but more than half the channels in the .m3u file are not in the guide data files, and there are several channels in the guide data that are not in the .m3u file. Not sure where to go from here with this.

**Comment by freearhey** [comment]
It should work now.

**Comment by freearhey** [comment]
Fixed in #2171 

To make the error with the missing "channels.json" file disappear, you just need to run the command:

```sh
npm run api:load
```
