### ISSUE TITLE
npm run grab is not adding channel metadata to *.xml output

### ISSUE THREAD

**Issue by socphoenix** [iptv-org/epg#2161]
### Site

tvtv.us

### Description

running npm run grab -- --site=tvtv.us outputs a guide with the channel programming, but it doesn't list the channels at the top like it used to and is causing jellyfin to fail to import the guide as it only sees one channel. It is printing out the first channel, but then none of the rest and just outputting the programming data.

Running:
`npx epg-grabber --config=sites/tvtv.us/tvtv.us.config.js --channels=sites/tvtv.us/tvtv.us.channels.xml --output=guide.xml --days=2`

fixes the issue but that wasn't in the guide I found that searching through the issue tracker.

**Comment by yarafie** [comment]
I'm facing the same problem in other iptv apps so its not just jellyfin. Testing npx eog-grabber ..... as you mentioned above and will check if that works

**Comment by AahzNotOz** [comment]
I'm seeing the same and added a description to a question I posted a couple days ago.  I'm seeing the same file structure you describe and I'm using ChannelsDVR, which does not work with what it is getting back.  I'll try your command to see if that fixes the issue for me.

**Comment by AahzNotOz** [comment]
I gave it a try, and it is semi working for me.  I'm getting guide data in ChannelsDVR now for some channels, but not all.  I'll need to look into the files in more detail.  My first guess is that the "channel id" name at the top of the file is not matching up with the "channel" name with the actual guide data.

**Comment by freearhey** [comment]
Fixed in #2171
