### ISSUE TITLE
Error: Cookie not in this host's domain. Cookie:horizon.tv Request:static.spark.telenet.tv

### ISSUE THREAD

**Issue by anoo2niem** [iptv-org/epg#2163]
### Site

telenet.tv

### Description

Hi, i have a script setup to always download 2 guides (ziggotv & telenet) 2 times a week automatically.
Ziggotv guide always finishes and with 0 issues, however, the telenet guide is never complete.
I have to do it manually, and i always get the error; 

`[5/8] telenet.tv - Be1.be - Sep 8, 2023 (0 programs)
  Error: Cookie not in this host's domain. Cookie:horizon.tv Request:static.spark.telenet.tv`

As far as i understand this means the the received Set-Cookie header contains a cookie whose domain is horizon.tv;,
which mismatches the request's target domain static.spark.telenet.tv. 

Is there anybody more experienced who can tell me how to set the request target domain to horizon.tv, or how i can resolve that issue?

At this moment if keep trying manually, with changing public ips with vpn, eventually it works after ~10 tries. 

Thanks!

**Comment by freearhey** [comment]
Can't reproduce the error.

```sh
npm run grab -- --site=telenet.tv
```

Log:
<img width="728" alt="image" src="https://github.com/iptv-org/epg/assets/7253922/14e10f0f-62d1-47fa-af14-4351e2f62b66">

**Comment by anoo2niem** [comment]
Did u try it with first ziggogo.tv, then followed by telenet.tv?

I think/hope u will be able to reproduce it that way.

```
SITE=ziggogo.tv /usr/bin/npm run grab
SITE=telenet.tv /usr/bin/npm run grab
```

**Comment by freearhey** [comment]
Please try downloading the updated version of the code:

```shell
// change directory to "epg"
cd epg

// download updated code from repository 
git pull

// install dependencies
npm install
```

and then try to run the script using the new command:

```sh
npm run grab -- --site=ziggogo.tv
npm run grab -- --site=telenet.tv
```

**Comment by anoo2niem** [comment]
Hi, 

Unfortunatly updating didn't seem to have fixed the issue.

```
i   [10/168] telenet.tv (nl) - Canvas.be - Sep 24, 2023 (15 programs)                                 12:13:16 PM
i   [11/168] telenet.tv (nl) - Canvas.be - Sep 25, 2023 (0 programs)                                  12:13:19 PM
i     ERR: Cookie not in this host's domain. Cookie:horizon.tv Request:static.spark.telenet.tv        12:13:19 PM
i   [12/168] telenet.tv (nl) - Canvas.be - Sep 26, 2023 (0 programs)                                  12:13:22 PM
i     ERR: Cookie not in this host's domain. Cookie:horizon.tv Request:static.spark.telenet.tv        12:13:22 PM
i   [13/168] telenet.tv (nl) - Canvas.be - Sep 27, 2023 (0 programs)                                  12:13:26 PM
i     ERR: Cookie not in this host's domain. Cookie:horizon.tv Request:static.spark.telenet.tv        12:13:26 PM
i   [14/168] telenet.tv (nl) - Canvas.be - Sep 28, 2023 (0 programs)                                  12:13:29 PM
i     ERR: Cookie not in this host's domain. Cookie:horizon.tv Request:static.spark.telenet.tv        12:13:29 PM
i   [15/168] telenet.tv (nl) - Canvas.be - Sep 29, 2023 (0 programs)                                  12:13:32 PM
i     ERR: Cookie not in this host's domain. Cookie:horizon.tv Request:static.spark.telenet.tv        12:13:32 PM
i   [16/168] telenet.tv (nl) - Canvas.be - Sep 30, 2023 (0 programs)                                  12:13:36 PM
i     ERR: Cookie not in this host's domain. Cookie:horizon.tv Request:static.spark.telenet.tv        12:13:36 PM
```

Steps to reproduce

```
npm run grab -- --site=ziggogo.tv
npm run grab -- --site=telenet.tv
```

Some notes on this, after first updating, both worked perfectly fine (as with the older version).
Every saterday i have a script who runs this. I saw belgium was not downloaded again after updating.
I've tried manually 'npm run grab -- --site=telenet.tv' again, and got the error posted above.
Had this issue with the older version aswell. ziggogo.tv always completes, and then after belgium failed, i have to change ip with vpn on that container several times for belgium to eventually work.

If i had to take a rough guess on what could be the issue, i think there are some same channels both in ziggogo.tv & telenet.tv.
And if telenet.tv rerun same channel with same ip maybe there is the issue? Not sure though just a rough guess...

If there is any more data i can share to try to debug this issue, please let me know what data and how to obtain it.

Thanks

**Comment by freearhey** [comment]
As for the "Cookie not in this host's domain." error, it should go away (https://github.com/iptv-org/epg/pull/2177). You just need to [update](https://github.com/iptv-org/epg?tab=readme-ov-file#update) or [reinstall](https://github.com/iptv-org/epg?tab=readme-ov-file#installation) the grabber.

If you have any other problems with this guide, don't hesitate to reopen the issue.
