### ISSUE TITLE
chaines-tv.orange.fr does not generate the channels list correctly

### ISSUE THREAD

**Issue by octavioj** [iptv-org/epg#2172]
### Site

chaines-tv.orange.fr

### Description

Calling the generator with the correct parameters does generate a correct guide with 2 days' worth of programs, but when examining the XMLTV guide generated, it contains all of the correct <programme> tags correctly, but the beginning of the file where all <channel> tags were supposed to be listed only has one channel, the very first one in the list of channels to be generated. Please find attached an example of the XML generated today September 19th 2023. 
[chaines-tv.orange.fr.pdf](https://github.com/iptv-org/epg/files/12666980/chaines-tv.orange.fr.pdf)

**Comment by freearhey** [comment]
This bug has been fixed in #2171

Please re-download the code.
