### ISSUE TITLE
beIN Sports Haber TR

### ISSUE THREAD

**Issue by UzunMuhalefet** [iptv-org/epg#218]
Hi,

Could you please add beIN Sports Haber channel from digiturk.com.tr. (Row 83)
<img width="1680" alt="Screen Shot 2021-11-09 at 23 43 21" src="https://user-images.githubusercontent.com/80906858/141001663-e05d3ea9-ce56-489c-9648-e94105597f8d.png">

**Comment by freearhey** [comment]
Done.
