### ISSUE TITLE
[Bug] "Unknown file extension .ts" on Ubuntu

### ISSUE THREAD

**Issue by freearhey** [iptv-org/epg#2181]
```sh
ubuntu@jay:~/epg$ npm run grab -- --site=tvguide.com 

> grab
> ts-node scripts/commands/epg/grab.ts --site=tvguide.com

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/ubuntu/epg/scripts/commands/epg/grab.ts
    at new NodeError (node:internal/errors:406:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:99:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:142:36)
    at defaultLoad (node:internal/modules/esm/load:120:20)
    at nextLoad (node:internal/modules/esm/hooks:833:28)
    at load (/home/ubuntu/epg/node_modules/ts-node/dist/child/child-loader.js:19:122)
    at nextLoad (node:internal/modules/esm/hooks:833:28)
    at Hooks.load (node:internal/modules/esm/hooks:416:26)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:168:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

_Originally posted by @ata-star in https://github.com/iptv-org/epg/issues/2174#issuecomment-1753892565_

**Comment by freearhey** [comment]
@ata-star Please try to run the script using this command:

```
npx tsx scripts/commands/epg/grab.ts --site=tvguide.com
```

**Comment by brad925** [comment]
I ran the npx command and this is the output (Garuda Linux):

``(node:3448104) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
staring...
config:
output: guide.xml
maxConnections: 1
gzip: false
site: tvguide.com
loading channels...
found 85 channels
creating queue...
node:internal/process/promises:289
triggerUncaughtException(err, true /* fromPromise */);
^

[Error: ENOENT: no such file or directory, open 'temp/data/channels.json'] {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: 'temp/data/channels.json'
}

Node.js v20.8.0
``

**Comment by brad925** [comment]
I ran the npx command and this is the output (Garuda Linux):

```
(node:3448104) ExperimentalWarning: --experimental-loader may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
staring...
config:
output: guide.xml
maxConnections: 1
gzip: false
site: tvguide.com
loading channels...
found 85 channels
creating queue...
node:internal/process/promises:289
triggerUncaughtException(err, true /* fromPromise */);
^

[Error: ENOENT: no such file or directory, open 'temp/data/channels.json'] {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: 'temp/data/channels.json'
}

Node.js v20.8.0
```

**Comment by solibres** [comment]
> I ran the npx command and this is the output (Garuda Linux):
> 
> ```
> (node:3448104) ExperimentalWarning: --experimental-loader may be removed in the future; instead use `register()`:
> --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
> (Use `node --trace-warnings ...` to show where the warning was created)
> staring...
> config:
> output: guide.xml
> maxConnections: 1
> gzip: false
> site: tvguide.com
> loading channels...
> found 85 channels
> creating queue...
> node:internal/process/promises:289
> triggerUncaughtException(err, true /* fromPromise */);
> ^
> 
> [Error: ENOENT: no such file or directory, open 'temp/data/channels.json'] {
> errno: -2,
> code: 'ENOENT',
> syscall: 'open',
> path: 'temp/data/channels.json'
> }
> 
> Node.js v20.8.0
> ```

I also have the same problem...

**Comment by freearhey** [comment]
> I ran the npx command and this is the output (Garuda Linux):
> 
> ```
> (node:3448104) ExperimentalWarning: --experimental-loader may be removed in the future; instead use `register()`:
> --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
> (Use `node --trace-warnings ...` to show where the warning was created)
> staring...
> config:
> output: guide.xml
> maxConnections: 1
> gzip: false
> site: tvguide.com
> loading channels...
> found 85 channels
> creating queue...
> node:internal/process/promises:289
> triggerUncaughtException(err, true /* fromPromise */);
> ^
> 
> [Error: ENOENT: no such file or directory, open 'temp/data/channels.json'] {
> errno: -2,
> code: 'ENOENT',
> syscall: 'open',
> path: 'temp/data/channels.json'
> }
> 
> Node.js v20.8.0
> ```

Run the command:

```sh
npm install
```

and the error should disappear.

**Comment by weirdal3333** [comment]
[2023-10-15T02_24_45_640Z-debug-0.log](https://github.com/iptv-org/epg/files/12908447/2023-10-15T02_24_45_640Z-debug-0.log)
![image](https://github.com/iptv-org/epg/assets/3537180/04da47f2-67a7-40ec-9b4f-b29cf3b50edc)
![image](https://github.com/iptv-org/epg/assets/3537180/8295a700-12c0-4172-93f1-e94f59dc7452)

Also having this issue when running npm install for the first time.
