### ISSUE TITLE
[Bug] Channel list does not load on Windows

### ISSUE THREAD

**Issue by freearhey** [iptv-org/epg#2182]
### Discussed in https://github.com/orgs/iptv-org/discussions/1508

<div type='discussions-op-text'>

<sup>Originally posted by **Stuggy** October  9, 2023</sup>
New install on windows:

```
npm run grab -- --site=tvguide.com

> <grab>
> ts-node scripts/commands/epg/grab.ts --site=tvguide.com

> staring...
config:
  output: guide.xml
  maxConnections: 1
  gzip: false
  site: tvguide.com
loading channels...
  found 0 channels
creating queue...
  added 0 items
run #1:
  done in 00h 00m 00s
finished`
```

I can't work out what is going on.  I tried a few different sites and always get 0 results.</div>

**Comment by nomaam** [comment]
same problem on windows. udpated install. In my case I am loading from a custom channels list. Format is same as help example. 

    staring...
    config:
      output: guide.xml
      maxConnections: 1
      gzip: false
      channels: /mypath/test.channels.xml
    loading channels...
      found 0 channels
    creating queue...
      added 0 items
    run #1:
     done in 00h 00m 00s


    <?xml version="1.0" encoding="UTF-8"?>
    <channels>
	    <channel site="9tv.co.il" lang="ru" xmltv_id="Channel9.il" site_id="#">9 канал</channel>
    </channels>
