### ISSUE TITLE
Error in installing epg 

### ISSUE THREAD

**Issue by Tamburasca** [iptv-org/epg#2205]
### Describe your issue

Trying to install epg in a docker container: 

It appears freearhey/core is lacking

#17 [14/15] RUN npm run grab -- --site=hd-plus.de
#17 0.683 
#17 0.683 > grab
#17 0.683 > npx tsx scripts/commands/epg/grab.ts --site=hd-plus.de
#17 0.683 
#17 2.191 npm WARN exec The following package was not found and will be installed: tsx@3.14.0
#17 4.152 node:internal/modules/cjs/loader:1077
#17 4.152   const err = new Error(message);
#17 4.152               ^
#17 4.152 
#17 4.152 Error: Cannot find module '@freearhey/core'
#17 4.152 Require stack:
#17 4.152 - /iptv/epg/scripts/commands/epg/grab.ts
#17 4.152     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
#17 4.152     at l.default._resolveFilename (/root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/cjs/index.cjs:1:1671)
#17 4.152     at Module._load (node:internal/modules/cjs/loader:922:27)
#17 4.152     at Module.require (node:internal/modules/cjs/loader:1143:19)
#17 4.152     at require (node:internal/modules/cjs/helpers:121:18)
#17 4.152     at path (/iptv/epg/scripts/commands/epg/grab.ts:1:52)
#17 4.152     at Object.<anonymous> (/iptv/epg/scripts/commands/epg/grab.ts:98:16)
#17 4.152     at Module._compile (node:internal/modules/cjs/loader:1256:14)
#17 4.152     at Object.j (/root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/cjs/index.cjs:1:1197)
#17 4.152     at Module.load (node:internal/modules/cjs/loader:1119:32) {
#17 4.152   code: 'MODULE_NOT_FOUND',
#17 4.152   requireStack: [ '/iptv/epg/scripts/commands/epg/grab.ts' ]
#17 4.152 }
#17 4.152 
#17 4.152 Node.js v18.17.1
#17 ERROR: process "/bin/sh -c npm run grab -- --site=hd-plus.de" did not complete successfully: exit code: 1

**Comment by freearhey** [comment]
Are you sure you've installed all the dependencies?

```sh
npm install
```

https://github.com/iptv-org/epg#installation

**Comment by Tamburasca** [comment]
Yes you are right, got it to operate in Docker. BTW, port 3000 may suffer conflicts from Grafana.
