### ISSUE TITLE
BT.com Broken

### ISSUE THREAD

**Issue by kontell** [iptv-org/epg#2221]
### Site

bt.com

### Description

I get the below error when trying to grab an epg.

> ERR: Request failed with status code 400

The site is still working: https://www.player.bt.com/#/livetv/schedule

Looks like the site needs to be changed to tv.bt.com

https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/master/siteini.pack/UK/tv.bt.com.channels.GBR-ENG-london.xml

**Comment by irishj** [comment]
Seeing the same issue here, thanks for reporting it @kontell

**Comment by eldepor** [comment]
> Looks like the site needs to be changed to tv.bt.com

Not fixing the issue for me

**Comment by kontell** [comment]
The BT broadband business is being merged into EE, so this looks like the new EPG source.

https://player.ee.co.uk/#/livetv/schedule
