### ISSUE TITLE
TRT Spor 2 and TRT Spor Yildiz

### ISSUE THREAD

**Issue by UzunMuhalefet** [iptv-org/epg#223]
Hi,

TRT Spor 2 changed its name to TRT Spor Yildiz so these channels are the same. Could you please merge them?

Source: https://tr.wikipedia.org/wiki/TRT_Spor_Y%C4%B1ld%C4%B1z

<img width="997" alt="Ekran Resmi 2021-11-10 14 44 17" src="https://user-images.githubusercontent.com/80906858/141107379-7cb69851-f774-41cf-9d68-49a388debb35.png">

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/d086f1859bca9a350901073f22f6952cf7bb8214
