### ISSUE TITLE
iptv-org/epg Installation instructions doesn't seem to work

### ISSUE THREAD

**Issue by Taqras** [iptv-org/epg#2230]
### Site

https://github.com/iptv-org/epg

### Description

Following the installation instructions gives errors.

<details>
<summary>Involved software versions</summary>

```
$ uname -srm
Linux 6.6.1-arch1-1 x86_64
$ pacman -F npm
extra/nodejs 21.1.0-1 [installed]
    usr/lib/node_modules/corepack/shims/nodewin/npm
    usr/lib/node_modules/corepack/shims/npm
extra/nodejs-lts-hydrogen 18.18.2-1
    usr/lib/node_modules/corepack/shims/nodewin/npm
    usr/lib/node_modules/corepack/shims/npm
extra/npm 10.2.3-2 [installed]
    usr/bin/npm
    usr/share/bash-completion/completions/npm
$ pwd
/home/username/GIT
```
</details>

Following the guide...
```
$ git clone --depth 1 -b master https://github.com/iptv-org/epg.git
Cloning into 'epg'...
remote: Enumerating objects: 1151, done.
remote: Counting objects: 100% (1151/1151), done.
remote: Compressing objects: 100% (1006/1006), done.
remote: Total 1151 (delta 162), reused 762 (delta 106), pack-reused 0
Receiving objects: 100% (1151/1151), 8.37 MiB | 1.99 MiB/s, done.
Resolving deltas: 100% (162/162), done.
$ cd epg
$ npm install
```
...gives the following npm log:
[https://0x0.st/Hva2.txt](https://0x0.st/Hva2.txt)

To my understanding, a directory `/home/username/GIT/epg/node_modules` is supposed to be there, but isn't.

**Comment by tohenk** [comment]
It's looks like `libxmljs2` 0.32.0 does not support node v21, but 0.33.0 does. Try `npm update` instead of `npm install`.

**Comment by Taqras** [comment]
Thank you @tohenk!

The `npm update`gave more or less the same errors (let me know if you want the log), but switching to the Arch package `extra/nodejs-lts-hydrogen 18.18.2-1` fixed it :smiley:

**Comment by tohenk** [comment]
You can try using node v21 and install `libxmljs2` manually using `npm install libxmljs2@0.33.0` then do `npm update`.

**Comment by Taqras** [comment]
Thank you for taking time to explain! Let me know if you want me to do anything for testing purposes, otherwise the issue is solved for me; I find it acceptable to use nodejs v18, and will leave at that :smiley:

**Comment by freearhey** [comment]
Changed `libxmljs2` version to `0.33.0` in https://github.com/iptv-org/epg/commit/7db92ae2f70983f95db0b2272730540d78e70ce2
