### ISSUE TITLE
Win Sports+

### ISSUE THREAD

**Issue by Mauricio300808** [iptv-org/epg#2251]
### Source

https://winplay.co/epg

**Comment by BellezaEmporium** [comment]
https://next.platform.mediastre.am/graphql

{"operationName":"getLivesEpg","variables":{"page":1,"hours":24},"query":"query getLivesEpg($page: Int = 1, $hours: Int, $ids: [String]) {\n  getLives(ids: $ids) {\n    _id\n    logo\n    name\n    schedules(hours: $hours, page: {limit: 0, page: $page}) {\n      _id\n      name\n      date_start\n      date_end\n      current\n      match {\n        matchDay\n        __typename\n      }\n      show {\n        _id\n        title\n        __typename\n      }\n      live {\n        _id\n        dvr\n        type\n        purchased\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"}
