### ISSUE TITLE
Most channels return 0 programs (Dsmart)

### ISSUE THREAD

**Issue by bark1n9** [iptv-org/epg#2253]
### Site

dsmart.com.tr 

### Description

Most of the channels are returning 0 programs as I think the "site_id" of them have changed. 

I'm mainly trying to fetch programs for these: 

`<channel site="dsmart.com.tr" lang="tr" xmltv_id="TV5.tr" site_id="92#5bf6b074cfef0b7351c27d14">TV5</channel>
  <channel site="dsmart.com.tr" lang="tr" xmltv_id="TGRTBelgesel.tr" site_id="122#59dca751cfef0b4d80a47b88">TGRT Belgesel</channel>
  <channel site="dsmart.com.tr" lang="tr" xmltv_id="TGRTEU.tr" site_id="178#59dcbfb6cfef0b4d80a49748">TGRT EU</channel>
  <channel site="dsmart.com.tr" lang="tr" xmltv_id="Tivi6.tr" site_id="142#618bd28fcfef0b1593e5d42a">Tivi6</channel>
  <channel site="dsmart.com.tr" lang="tr" xmltv_id="TV52.tr" site_id="146#5db29993cfef0b4df918bc9e">TV52</channel>
  <channel site="dsmart.com.tr" lang="tr" xmltv_id="ASTV.tr" site_id="147#59dcbbf3cfef0b4d80a49622">AS TV</channel>
  <channel site="dsmart.com.tr" lang="tr" xmltv_id="EuroD.tr" site_id="179#59dcbfdccfef0b4d80a4974a">Euro D</channel>
  <channel site="dsmart.com.tr" lang="tr" xmltv_id="LineTV.tr" site_id="130#59b7c231cfef0b07291c2aa2">Line TV</channel>
  <channel site="dsmart.com.tr" lang="tr" xmltv_id="ShowMax.tr" site_id="88#59dca5fdcfef0b4d80a47b80">Show Max</channel>
  <channel site="dsmart.com.tr" lang="tr" xmltv_id="KanalB.tr" site_id="85#58d29bb0eefad3db9c606240">Kanal B</channel>
  <channel site="dsmart.com.tr" lang="tr" xmltv_id="EuroStar.tr" site_id="180#59dcc000cfef0b4d80a4974d">Euro Star</channel>
  <channel site="dsmart.com.tr" lang="tr" xmltv_id="MilyonTV.tr" site_id="121#5c9889b0cfef0b4cffc475b4">Milyon TV</channel>`

Channels other than Euro D return 0 programs.

**Comment by freearhey** [comment]
Have you checked if there is a program for these channels now on the site itself?
https://www.dsmart.com.tr/yayin-akisi
