### ISSUE TITLE
mytelly.co.uk dosen´t pull any data.

### ISSUE THREAD

**Issue by Skurken92** [iptv-org/epg#2258]
### Site

mytelly.co.uk

### Description

Mytelly dosen´t pull any data.
npm run grab -- --output ukmytelly.xml --days 7 --site=mytelly.co.uk --maxConnections=5

```
config:
  output: ukmytelly.xml
  maxConnections: 5
  gzip: false
  days: 7
  site: mytelly.co.uk
loading channels...
  found 0 channel(s)
run #1:
  done in 00h 00m 00s
```

**Comment by freearhey** [comment]
It's working fine for me:

```sh
npm run grab -- --output ukmytelly.xml --days 7 --site=mytelly.co.uk --maxConnections=5

> grab
> npx tsx scripts/commands/epg/grab.ts --output ukmytelly.xml --days 7 --site=mytelly.co.uk --maxConnections=5

staring...
config:
  output: ukmytelly.xml
  maxConnections: 5
  gzip: false
  days: 7
  site: mytelly.co.uk
loading channels...
  found 486 channel(s)
run #1:
  [1/3402] mytelly.co.uk (en) - 4Music.uk - Nov 27, 2023 (16 programs)
  [2/3402] mytelly.co.uk (en) - 4Music.uk - Nov 28, 2023 (15 programs)
  [3/3402] mytelly.co.uk (en) - 4Music.uk - Dec 1, 2023 (13 programs)
  [4/3402] mytelly.co.uk (en) - 4Music.uk - Nov 29, 2023 (18 programs)
  [5/3402] mytelly.co.uk (en) - 4Music.uk - Nov 30, 2023 (15 programs)
```

**Comment by Skurken92** [comment]
> It's working fine for me:
> 
> ```shell
> npm run grab -- --output ukmytelly.xml --days 7 --site=mytelly.co.uk --maxConnections=5
> 
> > grab
> > npx tsx scripts/commands/epg/grab.ts --output ukmytelly.xml --days 7 --site=mytelly.co.uk --maxConnections=5
> 
> staring...
> config:
>   output: ukmytelly.xml
>   maxConnections: 5
>   gzip: false
>   days: 7
>   site: mytelly.co.uk
> loading channels...
>   found 486 channel(s)
> run #1:
>   [1/3402] mytelly.co.uk (en) - 4Music.uk - Nov 27, 2023 (16 programs)
>   [2/3402] mytelly.co.uk (en) - 4Music.uk - Nov 28, 2023 (15 programs)
>   [3/3402] mytelly.co.uk (en) - 4Music.uk - Dec 1, 2023 (13 programs)
>   [4/3402] mytelly.co.uk (en) - 4Music.uk - Nov 29, 2023 (18 programs)
>   [5/3402] mytelly.co.uk (en) - 4Music.uk - Nov 30, 2023 (15 programs)
> ```

This is weird, I will try again later.
Thank you for checking!
