### ISSUE TITLE
m.tv.sms.cz add channels

### ISSUE THREAD

**Issue by zdenci22** [iptv-org/epg#226]
Hi,

Could you please add more channels from m.tv.sms.cz 
Channels are checked on screenshot. Thank you
![IMG_20211111_003450](https://user-images.githubusercontent.com/26553957/141210656-c9bac628-110c-41a2-99fe-9f769afd26cb.jpg)

**Comment by freearhey** [comment]
Missing channels added in https://github.com/iptv-org/epg/commit/cfef28b1cea97342a287be11032d8a1406a9fd8c and https://github.com/iptv-org/epg/commit/5e097620c4494fe2d8338c53b9c69b3cf6092c14
