### ISSUE TITLE
osn.com is broken

### ISSUE THREAD

**Issue by iamm3u** [iptv-org/epg#2282]
### Site

osn.com

### Description

when i run the script for osn.com in english and arabic i get a error code 500, might be because its geo-blocked but it looks like this: 
npm run grab -- --site=osn.com --lang=ar

> grab
> npx tsx scripts/commands/epg/grab.ts --site=osn.com --lang=ar

staring...
config:
  output: guide.xml
  maxConnections: 1
  gzip: false
  site: osn.com
  lang: ar
loading channels...
  found 101 channel(s)
run #1:
  [1/202] osn.com (ar) - AksyonTVInternational.ph - Dec 16, 2023 (0 programs)
    ERR: Request failed with status code 500
  [2/202] osn.com (ar) - AksyonTVInternational.ph - Dec 17, 2023 (0 programs)
    ERR: Request failed with status code 500
  [3/202] osn.com (ar) - TLCArabia.us - Dec 17, 2023 (0 programs)
    ERR: Request failed with status code 500
  [4/202] osn.com (ar) - TLCArabia.us - Dec 16, 2023 (0 programs)
    ERR: Request failed with status code 500

**Comment by PopeyeTheSai10r** [comment]
Most be geo-locked. It is working for me. 

Try to see if you can access osn.com from your IP or run the program through Proxy/VPN.

**Comment by BellezaEmporium** [comment]
On my side, I get 0 bytes responses. When I try putting a VPN on UAE, I get instant blocked by Incapsula. Any other country works fine. Seems like they make sure that if the IP doesn't correspond to UAE (and isn't a VPN IP) they won't give any answer.

+ It now seems to be this
https://www.osn.com/api/TVScheduleWebService.asmx/GetProgramDetails?countryCode=AE&prgmEPGUNIQID=AKS

**Comment by SenseiNasser** [comment]
i can access to osn no Geoblock but i still get this error :



PS C:\Users\Sensei\Desktop\EPG\epg> npm run grab -- --site=osn.com --lang=ar --days 7

> grab
> npx tsx scripts/commands/epg/grab.ts --site=osn.com --lang=ar --days 7

(node:8168) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///C%3A/Users/Sensei/Desktop/EPG/epg/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
starting...
config:
  output: guide.xml
  maxConnections: 1
  gzip: false
  site: osn.com
  lang: ar
  days: 7
loading channels...
  found 63 channel(s)
run #1:
  [1/441] osn.com (ar) - DWR - Aug 5, 2024 (0 programs)
    ERR: Request failed with status code 500
  [2/441] osn.com (ar) - DWR - Aug 6, 2024 (0 programs)
    ERR: Request failed with status code 500
  [3/441] osn.com (ar) - TLCArabia.us - Aug 11, 2024 (0 programs)
    ERR: Request failed with status code 500
  [4/441] osn.com (ar) - TLCArabia.us - Aug 10, 2024 (0 programs)
    ERR: Request failed with status code 500
  [5/441] osn.com (ar) - TLCArabia.us - Aug 9, 2024 (0 programs)
    ERR: Request failed with status code 500
  [6/441] osn.com (ar) - TLCArabia.us - Aug 8, 2024 (0 programs)
    ERR: Request failed with status code 500
  [7/441] osn.com (ar) - TLCArabia.us - Aug 7, 2024 (0 programs)
    ERR: Request failed with status code 500
