### ISSUE TITLE
Missing channels from dsmart.com.tr

### ISSUE THREAD

**Issue by UzunMuhalefet** [iptv-org/epg#231]
Hi,

Can you please add missing channels from dsmart.com.tr ? I compared the API endpoints with the current channels.xml file.

Euro D - https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=18
![eurod](https://user-images.githubusercontent.com/80906858/141312630-aaef9c17-b388-44a8-9410-8be96caf8bb1.png)

Halk TV - https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=16
![halktv](https://user-images.githubusercontent.com/80906858/141312743-b5a2169b-41d3-4da9-8ca7-62c2880f647f.png)

Lider TV - https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=10
![lidertv](https://user-images.githubusercontent.com/80906858/141312860-5c6cbc39-0e5e-47c6-8104-6124a5404f1d.png)

Tay TV - https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=7
![taytv](https://user-images.githubusercontent.com/80906858/141312927-29eb04d2-c0dc-4382-8088-028261d4b6d0.png)

TRT 4K - https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=17
![TRT4K](https://user-images.githubusercontent.com/80906858/141313011-17328c34-20f2-4825-aa87-126c37be1a68.png)

**Comment by UzunMuhalefet** [comment]
A News - https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=17
![anews](https://user-images.githubusercontent.com/80906858/141315240-381e4a83-1a06-41e5-94ae-65268b34b23d.png)

CNN Turk - https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=21
![cnnturk](https://user-images.githubusercontent.com/80906858/141315287-9d9619ec-fbbf-416f-af41-96cbca3c1930.png)

Powerturk - https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=11
![powerturk](https://user-images.githubusercontent.com/80906858/141315321-68e594b9-051e-4ce4-8245-7dd42dd4eca2.png)

TMB TV - https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=10
![tmb](https://user-images.githubusercontent.com/80906858/141315410-54f45f58-55d8-4e01-99b8-ae41507f2028.png)

TRT Kürdi - https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=17
![trtkurdi](https://user-images.githubusercontent.com/80906858/141315441-299731d7-3cee-4682-b8d2-b391d75bfc9e.png)

**Comment by freearhey** [comment]
Added via https://github.com/iptv-org/epg/commit/a1f37f5148bf70dba37bb16dbe66b1de273c8959
