### ISSUE TITLE
superguidatv.it goes over midnight

### ISSUE THREAD

**Issue by xemles** [iptv-org/epg#2315]
### Describe your issue

superguidatv.it goes over midnight.
If I sync the guide at midnight UTC, it might go as if tomorrow is actually the day after, because they switch to the next day at 4:30AM local time.

**Comment by PopeyeTheSai10r** [comment]
Does syncing the guide at an earlier/later time fix the issue?

**Comment by xemles** [comment]
That's what I'll be testing today, will let you know.

**Comment by xemles** [comment]
It seems like it does. Ran it at 7AM UTC

**Comment by xemles** [comment]
I'm not sure it's completed @PopeyeTheSai10r, it's just a workaround that we found here 🤔

**Comment by PopeyeTheSai10r** [comment]
Don't think this is a "bug". 

Are you syncing the guide from the same timezone? Have you tried using Proxy/VPN?
