### ISSUE TITLE
mts.rs not giving proper guide.xml

### ISSUE THREAD

**Issue by momchilon** [iptv-org/epg#2318]
### Describe your issue

In guide.xml there is error since for the link it generates https://mts.rs insted of https://mts.rs/tv-vodic/epg. Simple change

**Comment by PopeyeTheSai10r** [comment]
Can you please let us know what the error is? 
Add screenshot or output of grab.

**Comment by momchilon** [comment]
First image its how script outputs
![image](https://github.com/iptv-org/epg/assets/117931455/b00bc16c-a8b3-4ba5-9f04-90e8338fc2e6)
Second how it should output 
![image](https://github.com/iptv-org/epg/assets/117931455/3231d200-ad55-4e74-85bc-be0fc2215247)

**Comment by z0mbyHG** [comment]
By me that source works perfectly.
On what are you accessing the EPG if I may ask?
