### ISSUE TITLE
TVPassport Fatal Error

### ISSUE THREAD

**Issue by forrestrose** [iptv-org/epg#2328]
### Describe your issue

As soon as the run grab gets the full guide... or what looks like the full guide, it gives a fatal error. Guide.xml appears to have aggregated the data but the playthrough to plex is bunk. Nothing populates. 

Appears to only happen with TVPassport. 

I'm on Windows. This is the fatal error:

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF7B366ED9B node::SetCppgcReference+15579
 2: 00007FF7B35E6344 DSA_meth_get_flags+87860
 3: 00007FF7B40A8EC1 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF7B4092888 v8::Function::Experimental_IsNopFunction+1192
 5: 00007FF7B3EE3710 v8::StackTrace::GetFrameCount+426608
 6: 00007FF7B3EEF891 v8::StackTrace::GetFrameCount+476145
 7: 00007FF7B3EECD90 v8::StackTrace::GetFrameCount+465136
 8: 00007FF7B3EDD3C2 v8::StackTrace::GetFrameCount+401186
 9: 00007FF7B3ED8E35 v8::StackTrace::GetFrameCount+383381
10: 00007FF7B38FF37D BIO_ssl_shutdown+189

**Comment by freearhey** [comment]
This message indicates that node.js does not have enough RAM to load the entire guide. 

To avoid this error, you can either change the size of the allocated memory:

https://stackoverflow.com/a/72785305

or reduce the list of channels by removing unnecessary ones:

https://github.com/iptv-org/epg?tab=readme-ov-file#use-custom-channel-list
