### ISSUE TITLE
m.tv.sms.cz add channels

### ISSUE THREAD

**Issue by zdenci22** [iptv-org/epg#233]
Hi,

Could you please add more channels from m.tv.sms.cz
Channels are checked on screenshot. Thank you
![IMG_20211111_183325](https://user-images.githubusercontent.com/26553957/141343342-b6564675-cfc9-4162-b71b-786ad23a8fbd.jpg)

**Comment by freearhey** [comment]
TV Nova, Up Network, CNN Prima News and TV Seznam is already on the list. The rest are added via https://github.com/iptv-org/epg/commit/c74e4b864132498de9a2a3530a8ed9ea0e2ea7c5
