### ISSUE TITLE
sky.com (possible too add sky spots tennis?)

### ISSUE THREAD

**Issue by Slee42069** [iptv-org/epg#2331]
### Source

sky.com

### Notes

hi guys is there any chance you could add sky sports tennis too the epg channel list in sky.com, also if there is a way that i could do this at all then im happy to help out :)

**Comment by kontell** [comment]
Why haven't you curated and completed the repo?

**Comment by Slee42069** [comment]
> Just add the below to your channel list.
> 
> ```
> <channel lang="en" xmltv_id="SkySportsTennis.uk" site_id="1284">SkySp Tennis</channel>
> ```

thankyou mate, ill add that to the sky.com channel list my side then :D just out of curiosity how does that work, can i pull the site id for any channel and do the same to then ? and if so how do i go about that ? :P

just asking because the channel itself isnt in the sky.com channel list in the repo for sky.com, so when i update the repo it will overwrite it im assuming and id have to add that again or am i wrong there?

many thanks

**Comment by kontell** [comment]
If you're missing a channel you can get the ID from the sky guide in a web browser. Just select a program, right click the channel icon and open in a new tab. The channel ID is at the end of the URL.

The repo will be updated eventually but for now if you pull it again it will overwrite your changes.

I use a custom channel list where I only download the channels I want, to speed things up. A bonus is that when the repo is pulled from git my custom list stays the same.

**Comment by Slee42069** [comment]
> If you're missing a channel you can get the ID from the sky guide in a web browser. Just select a program, right click the channel icon and open in a new tab. The channel ID is at the end of the URL.
> 
> The repo will be updated eventually but for now if you pull it again it will overwrite your changes.
> 
> I use a custom channel list where I only download the channels I want. When the repo is pulled from git my custom list stays the same.

Thats perfect thankyou for that mate ill keep that in mind and add any that come up.

I did try to setup a custom channel list to be honest but i had some issues doing that, it seemed to not pickup any channels from the list at all, so ive ended up using the default lists.

**Comment by freearhey** [comment]
https://github.com/iptv-org/epg/blob/33c14f36da8e71c576caa321290d398c288ee845/sites/sky.com/sky.com.channels.xml#L357
