### ISSUE TITLE
404 Error on tvguide.com

### ISSUE THREAD

**Issue by Mauricio300808** [iptv-org/epg#2333]
### Describe your issue

```
  [53/170] tvguide.com (en) - ParamountNetworkEast.us - Feb 19, 2024 (0 programs)
    ERR: Request failed with status code 404
```

**Comment by HNJAMeindersma** [comment]
`SITES.md` should represent the current state of the `tvguide.com`-grabber in my opinion. Al through merging #2332 seems to be more important since it fixes the issue.
