### ISSUE TITLE
option --maxConnections not working

### ISSUE THREAD

**Issue by ewwink** [iptv-org/epg#2343]
### Describe your issue

it just run one by one
```
npm run grab -- --site=mncvision.id --lang=id  --maxConnections=10
```

**Comment by Slee42069** [comment]
the --maxconnections feature works for me definitely, i know because if you run it at 1 connection its alot slower than if you run it at 10 connections, dont think this is a bug mate.

**Comment by tohenk** [comment]
Site mncvision.id indeed use more connections to fetch program description, PR #2474 should reduces the time used to fetch the guide.
