### ISSUE TITLE
issue saving file tvpassport.com

### ISSUE THREAD

**Issue by Slee42069** [iptv-org/epg#2344]
hi guys, 

ive been trying to run tvpassport.com`s script, i used this command "npm run grab -- --site=tvpassport.com --output=USA.xml --days=3 days --maxConnections=20" everything runs fine and it completes, says its saving the file and then i get this error: 

"<--- Last few GCs --->

[935571:0x5999250]  5387035 ms: Mark-Compact 4044.7 (4137.1) -> 4030.3 (4138.6) MB, 2545.90 / 0.00 ms  (average mu = 0.111, current mu = 0.014) allocation failure; scavenge might not succeed
[935571:0x5999250]  5389567 ms: Mark-Compact 4046.2 (4138.6) -> 4031.9 (4140.3) MB, 2500.59 / 0.00 ms  (average mu = 0.064, current mu = 0.013) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xc9e850 node::Abort() [/usr/bin/node]
 2: 0xb720ff  [/usr/bin/node]
 3: 0xec1a70 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/bin/node]
 4: 0xec1d57 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/usr/bin/node]
 5: 0x10d3dc5  [/usr/bin/node]
 6: 0x10d4354 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node]
 7: 0x10eb244 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*) [/usr/bin/node]
 8: 0x10eba5c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 9: 0x10c1d61 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
10: 0x10c2ef5 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
11: 0x10a0466 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]
12: 0x14fb386 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
13: 0x7fdae6699ef6"

ive tried to have abit of a google and the javascript heap out of memory part is saying that the project would have exceeded over 1.5gb, but im assuming the .xml file wasnt going to be that big as i was attempting to pull 3 days, just wondering if you guys have an idea at all ? 

many thanks in advance

**Comment by freearhey** [comment]
Duplicate https://github.com/iptv-org/epg/issues/2175
