### ISSUE TITLE
Sbs 9 changes name to Viaplay

### ISSUE THREAD

**Issue by davidclaeysquinones** [iptv-org/epg#2347]
### Describe your issue

Adjust https://github.com/iptv-org/epg/tree/master/sites/tvgids.nl to adapt to the name change

**Comment by davidclaeysquinones** [comment]
The configuration needs to be modified to something like this
` <channel site="tvgids.nl" lang="nl" xmltv_id="ViaplayTv.nl" site_id="viaplaytv">VIAPLAY TV</channel>`

**Comment by freearhey** [comment]
https://github.com/iptv-org/epg/pull/2376#issuecomment-2151110236
