### ISSUE TITLE
Bug: Parameters issues

### ISSUE THREAD

**Issue by Aymkdn** [iptv-org/epg#2354]
### Describe your issue

Hello,

Thanks for this project!

I've just installed it on Windows 11 with Node 20 and I noticed that the command provided as an example returns an error:
  > \> npm run grab -- --site=chaines-tv.orange.fr
  > Error: One of the arguments must be presented: `--site` or `--channels`

To make it work, I have to type:
> npm run grab -- -- --site chaines-tv.orange.fr

Notice the double `--`, as well as the space between `--site` and the site name.

**Comment by tohenk** [comment]
If you use PowerShell then it should `npm run grab '--' --site=chaines-tv.orange.fr`.
