### ISSUE TITLE
mi.tv error 504

### ISSUE THREAD

**Issue by Nilbertocs** [iptv-org/epg#2384]
### Site

mi.tv

### Description

I'm having problems getting the guide from mi.tv, it's returning error 504, in the browser the site loads but very slowly...
Is there a way to make the grabber load this?
I already increased timeout and delay but it didn't solve it

![2024-06-10_02-39](https://github.com/iptv-org/epg/assets/25190827/a950fdfe-a558-4a55-a9ff-cbb62a2454d8)

**Comment by chinochao** [comment]
It seems to be an issue with mi.tv . It was working for me too a day ago and all of the sudden all my channels using mi.tv are failing with timeout. 

I get this 504.

```
% curl "https://mi.tv/ar/async/channel/amc/2024-06-25/0"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>504 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: G8bAVCxJBlILy2ifT2_6sw-0uqK_IXuQ3gZz_7RnXitDM2Hk4MWTvw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

And I tried a proxy to see if it was my ip blocked but seems the proxy also gets the 504.

I guess it is time to look for a replacement.
