### ISSUE TITLE
can you create an xml file for the algerians tv "dz" 

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/epg#24]
echorouk tv dz : https://elcinema.com/tvguide/1315

**Comment by hemzaberkane** [comment]
i will add more channels soon

**Comment by freearhey** [comment]
I personally do not have time for this, but if there will be PR I will add the site to the list.

**Comment by LaneSh4d0w** [comment]
I'm working on it.

@freearhey is there a way to see if the EPG generation works ?

**Comment by freearhey** [comment]
@LaneSh4d0w Yes, you just need to install [freearhey/epg-grabber](https://github.com/freearhey/epg-grabber):

`npm install -g epg-grabber`

And then run it by specifying the path to the config:

`epg-grabber --config=example.com.config.js`

**Comment by tilfizyawn** [comment]
@LaneSh4d0w have you looked into this https://github.com/Fazzani/grab ? The problem is most of the tvg-id don't match

**Comment by LaneSh4d0w** [comment]
> 
> 
> @LaneSh4d0w have you looked into this https://github.com/Fazzani/grab ? The problem is most of the tvg-id don't match

Yeah, I've tried with locating a few of them, it told me that program wasn't found.
