### ISSUE TITLE
Sky.de only some channels grabbed

### ISSUE THREAD

**Issue by Quotic** [iptv-org/epg#2403]
### Site

sky.de

### Description

SkyCinemaPremierenHD etc. will not be grabbed from webpage.

### Solution
Default Channellist need update

**Comment by PopeyeTheSai10r** [comment]
Did you try running the [Update channel list](https://github.com/iptv-org/epg/tree/b52ff68fd9d26e45a81c0c44c3da40cc59827bd8/sites/sky.de#update-channel-list) command locally to see if that fixes it?

**Comment by Quotic** [comment]
Yes, that will fix it.. i will try to make a pull request for new Default Channel list

**Comment by Quotic** [comment]
Oops, still Open
