### ISSUE TITLE
Mewatch.sg not pulling through Olympic channels

### ISSUE THREAD

**Issue by fnowegwoenvwoenboiwenbpewm** [iptv-org/epg#2411]
### Site

https://www.mewatch.sg/

### Description

Finds the guide for all other channels correctly but not the 18 dedicated Olympic Games channels

**Comment by fnowegwoenvwoenboiwenbpewm** [comment]
Update for anyone else wondering, I got this working by adding the following to mewatch.sg.channels.xml

  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH01.sg" site_id="469467">Paris2024 ch01</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH02.sg" site_id="469475">Paris2024 ch02</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH03.sg" site_id="469700">Paris2024 ch03</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH04.sg" site_id="471727">Paris2024 ch04</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH05.sg" site_id="471662">Paris2024 ch05</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH06.sg" site_id="471729">Paris2024 ch06</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH07.sg" site_id="471661">Paris2024 ch07</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH08.sg" site_id="471666">Paris2024 ch08</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH09.sg" site_id="471724">Paris2024 ch09</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH10.sg" site_id="471725">Paris2024 ch10</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH11.sg" site_id="471739">Paris2024 ch11</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH12.sg" site_id="471742">Paris2024 ch12</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH13.sg" site_id="471948">Paris2024 ch13</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH14.sg" site_id="471959">Paris2024 ch14</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH15.sg" site_id="471962">Paris2024 ch15</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH16.sg" site_id="472026">Paris2024 ch16</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH17.sg" site_id="472215">Paris2024 ch17</channel>
  <channel site="mewatch.sg" lang="en" xmltv_id="Paris2024CH18.sg" site_id="472216">Paris2024 ch18</channel>

I was also getting an issue with the XML file having an error, so I also removed the   image: info.images.tile from config.js as it was causing issues.

**Comment by PopeyeTheSai10r** [comment]
> Update for anyone else wondering, I got this working by adding the following to mewatch.sg.channels.xml

Feel free to add them to [channel file](https://github.com/iptv-org/epg/blob/master/sites/mewatch.sg/mewatch.sg.channels.xml) for others to enjoy. Make sure to read the [Contributing Guide](https://github.com/iptv-org/epg/blob/master/CONTRIBUTING.md).

**Comment by PopeyeTheSai10r** [comment]
This shouldn't be needed as the Olympics are done now.
