### ISSUE TITLE
Tranvision EPG

### ISSUE THREAD

**Issue by Jodi910** [iptv-org/epg#2422]
### Source

https://www.transvision.co.id/channel.html

### Notes

Another EPG from Indonesia

**Comment by keystrom-laplace** [comment]
The website doesn't have EPG source.
But, for TransVision channels, you can use cubmu.com source.

**Comment by tohenk** [comment]
Transvision.id has long gone in 57b3db1ff1cda44a4642e7c6b98f4b202cedeed6.
