### ISSUE TITLE
EPG does not comply with node.js version 22

### ISSUE THREAD

**Issue by Tamburasca** [iptv-org/epg#2426]
### Describe your issue

Trying to install EPG in docker with 
Ubuntu 22.04 and 
node.js v22 but fails with

 > [15/15] RUN npm install:
10.32 npm error code 1
10.32 npm error path /iptv/epg/node_modules/libxmljs2
10.32 npm error command failed
10.32 npm error command sh -c node-pre-gyp install --fallback-to-build --loglevel http
10.32 npm error make: Entering directory '/iptv/epg/node_modules/libxmljs2/build'
10.32 npm error   CXX(target) Release/obj.target/xmljs/src/libxmljs.o
10.32 npm error make: Leaving directory '/iptv/epg/node_modules/libxmljs2/build'

BUT node.js v21 installs alright with few warnings only...

Hence, node.js v22 is yet to be tested?

All the best.

**Comment by tohenk** [comment]
You can workaround this issue by installing latest version of `libxmljs2` (0.35.0).

```shell
npm install libxmljs2@latest
npm update
```
