### ISSUE TITLE
Upgrade channel list maxtv.hrvatskitelekom.hr

### ISSUE THREAD

**Issue by valnet17** [iptv-org/epg#243]
Hello,
I would ask you if you can upgrade the maxtv.hrvatskitelekom.hr channel list. The page https://maxtv.hrvatskitelekom.hr/#/epg shows that it contains 296 channels. Your list has 165, missing quite a few important channels.
Thanks in advance.
Val

**Comment by freearhey** [comment]
The thing is that many channels on the site actually have no information, so they were removed from the list.

![image](https://user-images.githubusercontent.com/7253922/141676343-1b746027-7d6e-4a94-8dc0-5f785c0ca8d1.png)

If you have a specific channel in mind, then write its name below.

**Comment by valnet17** [comment]
I especially miss these channels:
- RTL Adria HD
- Sport Klub 4, Sport Klub 5 and Sport Klub 6

It would be very helpful if you could grable programs from these sites:
1. https://www.tvarenasport.com/tv-program (Arena Sport programs for all countries of the former Ex-Yu)
2. https://sportklub.com/ (also Sport Klub programs for all countries of the former Ex-Yu)
3. On these sites, the programs for these channels are given exactly, both events and times. On other sites, there are inaccurate data and large discrepancies.

Thank you and best regards,
Val
