### ISSUE TITLE
Escaping characters in links

### ISSUE THREAD

**Issue by CringeArab** [iptv-org/epg#2436]
### Describe your issue

Related to [#1904](https://github.com/orgs/iptv-org/discussions/1904)
if you use some other sources like `flixed.io` then during the assembly of the EPG some symbols inside the links are not escaped, such as `&` and maybe something else. because of this the players think that this xml file is invalid.

![image](https://github.com/user-attachments/assets/ab327943-9934-4f86-8c61-8deece2694a6)

**Comment by diogotcorreia** [comment]
cc @freearhey this did not close automatically
