### ISSUE TITLE
how to get 3 different EPG source into 1 file?

### ISSUE THREAD

**Issue by konrul-r10** [iptv-org/epg#245]
Hello,

I want to grab 3 different EPG sources into 1 file.

The sources are:
tvplus.com.tr
digiturk.com.tr
dsmart.com.tr

Can we get those sources into 1 XML file? If you can help with this, I will be thankful.

**Comment by LaneSh4d0w** [comment]
In theory, it could be possible if we merged all Turkish channels in one XML file by also precising from which website they come from. (let's say a epg-website marker on the xml)

This would also mean merging config files, and make a race condition based on reading the "epg-website" marker to always get the correct list.

The only issue (@freearhey will tell) is idk if it's actually "possible" to add a website marker on channels xml file.

**Comment by freearhey** [comment]
I've added a `<url>` tag with the source to the channel list:

```
<tv>
  <channel id="ArianaAfghanistanInternationalTV.af">
    <display-name>Ariana Afghanistan International TV</display-name>
    <url>https://arianaafgtv.com</url>
  </channel>
...
</tv>
```

**Comment by LaneSh4d0w** [comment]
> I've added a `<url>` tag with the source to the channel list:
> 
> ```
> <tv>
>   <channel id="ArianaAfghanistanInternationalTV.af">
>     <display-name>Ariana Afghanistan International TV</display-name>
>     <url>https://arianaafgtv.com</url>
>   </channel>
> ...
> </tv>
> ```

Perfect, so then what we would do is merge the configuration files and make a condition that reads the url above, assuming you've made a tool that does it.

**Comment by freearhey** [comment]
This cannot be done for the reasons stated here: https://github.com/iptv-org/epg/issues/310#issuecomment-1012223913

**Comment by konrul-r10** [comment]
thank you for your reply! Best regards.
