### ISSUE TITLE
`tv.mail.ru` ERR: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by ghost** [iptv-org/epg#2450]
### Site

tv.mail.ru

### Description

The error occurs after 3-5 requests

![image](https://github.com/user-attachments/assets/339958d2-3944-4217-b9d4-8a09a08c93ee)

**Comment by BellezaEmporium** [comment]
Sounds like a rate limit is being applied. It might either need a per-request wait time.

**Comment by BellezaEmporium** [comment]
Sounds like a rate limit is being applied. It might either need a per-request wait time.
