### ISSUE TITLE
No xmltv_id for UTV (Czech) and Praha (Czech)

### ISSUE THREAD

**Issue by Rodri-06009** [iptv-org/epg#2453]
### Site

m.tv.sms.cz

### Description

I was creating my channels.xml file but i search for UTV (Czech) and Phara TV xmltv_id, but is was just this " " can you help me please ?

**Comment by freearhey** [comment]
UTV - `UTV.cz` (https://iptv-org.github.io/channels/cz/UTV)
Phara TV - missing from the [iptv-org/database](https://github.com/iptv-org/database). Here is the form through which it can be added to it: https://github.com/iptv-org/database/issues/new?assignees=&labels=channels%3Aadd&projects=&template=__channels_add.yml&title=Add%3A+
