### ISSUE TITLE
[tvpassport.com] can't download present several hours' epg data from timezone difference

### ISSUE THREAD

**Issue by gsool9988** [iptv-org/epg#2460]
### Describe your issue

site: tvpassport.com

symptom:
Can't download present 9 hours' epg data because of the timezone difference.

My local timezone : GMT+9
Downloaded tvpassport epg data's start time : my local current time(GMT+9), +0000

So, the first item of the downloaded epg is applied to player screen after 9 hours later and No epg data is seen until the time passed.

It seems to be the cause that download starting time is falsely set to the user local time. It must be set to GMT-0 time.

How can I fix it?
How can I download epg data from tvpassport.com at start time GMT-0 ? 
Is there any option to apply to the downloading command for fixing this issue?

**Comment by gsool9988** [comment]
Thanks for your comment, and I checked it now and it works fine for the site, tvpassport.com.
![EPGdownloadSUCCESS-(tvpassport com)2024-11-12_013429](https://github.com/user-attachments/assets/d35d9cc4-dd13-4a5a-b6fc-c868bec028a0)

**Comment by BellezaEmporium** [comment]
Considering the issue as solved, thank you @CringeArab
