### ISSUE TITLE
Need help with fixing jiotv.config.js

### ISSUE THREAD

**Issue by fraudiay79** [iptv-org/epg#2462]
### Source

https://www.jiotv.com/tv-guide

### Notes

I need help from a more experienced js scripter to see what I am doing incorrectly.  I have been working on a config for getting the guide from jiotv, but it returns the following error 'Request failed with status code 450'.  I cannot figure out what my script is missing.  Any guidance/assistance would be highly appreciated.  Also, if you can get it to work, please feel free to add the config to this repo.  Thank you.

[jio.tv.config.txt](https://github.com/user-attachments/files/17707030/jio.tv.config.txt)

**Comment by lavish440** [comment]
450 status code means that you are blocked by Jio's Firewall. 
Jio only allows Indian Residential IPs for their service s.

**Comment by lavish440** [comment]
450 status code means that you are blocked by Jio's Firewall.
Jio only allows Indian Residential IPs for their services.

**Comment by fraudiay79** [comment]
I don't think Indian IP is the issue. I'm able to watch Jio TV with my VPN (which should also fail if the IP was being blocked). There is something else that I'm missing.

**Comment by fraudiay79** [comment]
Not needed anymore

**Comment by Ashpro0minecraft** [comment]
How did you solved this issue please share
