### ISSUE TITLE
Pluto TV EPG (depends on proxies)

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/epg#250]
This might be interesting due to the ongrowing number of countries Pluto TV is getting in.

I have made a fork of PlutoIPTV, available here, rewrote it to ditch request since it is deprecated : https://github.com/LaneSh4d0w/PlutoIPTV. It might serve to get the EPG.

**Comment by freearhey** [comment]
Sorry, but I can't add a source to the list if it requires a proxy to access it.
