### ISSUE TITLE
Request EPG for Slovenia

### ISSUE THREAD

**Issue by valnet17** [iptv-org/epg#261]
Thank you for adding channels to maxtv.hrvatskitelekom.hr. I would also like to thank you for this great site and service!
I would ask you if you can add an EPG for the country of Slovenia because you do not have one yet. I would recommend capturing from this page: https://epg.telemach.si/ because it is the most complete epg, both with channels and content.
Thank you in advance and best regards.
Val

**Comment by freearhey** [comment]
Added via #268. 

As for epg.telemach.si, the guide cannot be added as it requires an access token to load.
