### ISSUE TITLE
Want to contribute Swedish channels

### ISSUE THREAD

**Issue by TertoGordez** [iptv-org/epg#307]
Hi,

Is there a way for me to help improve on the EPG's for the Swedish channels? 

Currently, there are 87 channels. My guess is that there should be around close to 200 to "complete" the Swedish list. 

From what I can tell by the URL the XML file pulls information from Allente.se. 

There are other sites where there are more channels available. For example:
allatvkanaler.se
dagenstv.com
ontv.se
tv.nu

Please let me know if there is anything I can do to improve on the Swedish EPG XML file!

PS. I signed up on github for this and therefore this message might be in the wrong zone.

**Comment by freearhey** [comment]
If you know JavaScript, you can add the missing sources yourself. To do this, simply add the appropriate `example.com.config.js` and `example.com.channels.xml` to the [sites/](https://github.com/iptv-org/epg/tree/master/sites) folder. More info about these files can be found here: https://github.com/freearhey/epg-grabber#quick-start

Also, if you find any errors in the channel descriptions you can correct them by editing [allente.se_se.channels.xml](https://github.com/iptv-org/epg/blob/master/sites/allente.se/allente.se_se.channels.xml).

**Comment by TertoGordez** [comment]
Hi, I did add two channels by editing allente.se_se.channels.xml.

Please have a look if the update is ok.

**Comment by TertoGordez** [comment]
@bse4792 I could try and improve the DK channels, but the changes I did to the Swedish XML have not been approved nor implemented. I have no issues updating the XML files, but I'm not able to do the config files. 

@freearhey Could you have a look at the suggested update to the Swedish XML file?

The lines I added to the Swedish XML was as follows:

    <channel lang="sv" xmltv_id="CMoreLive3.se" site_id="se#661" logo="https://images.ctfassets.net/989y85n5kcxs/6s2u83hdpmSQuysYug6q24/e5cf3fa6a85fd2b8ab60fd4c7a7039de/c_more_live_3_hd_2rows_rgb_copy.png">C More Live 3</channel>
    <channel lang="sv" xmltv_id="CMoreLive4.se" site_id="se#662" logo="https://images.ctfassets.net/989y85n5kcxs/5nFBhLm2YwoAeYEyoWwCK8/64603ba42cbcce0cf5a1e01689ebf466/c_more_live_4_hd_2rows_rgb_copy.png">C More Live 4</channel>
