### ISSUE TITLE
[Question] All-in-One EPG file

### ISSUE THREAD

**Issue by LaneSh4d0w** [iptv-org/epg#310]
I've remembered that, before you've split the EPGs into different countries, you had a one big EPG file for all channels.

Do you find it possible to reintegrate it ? I have a UWP app (downloaded from the Store) that indeed takes EPGs, but it would be very long to add all those links one by one.

Thank you in advance.

**Comment by xpsx** [comment]
any update on this? I would like to use it with Plex

**Comment by m5arish** [comment]
Any updates on this I’d love to have it too

**Comment by freearhey** [comment]
The single EPG file was removed for several reasons:

1. The size of the final file began to exceed hundreds of megabytes. And even then there were problems with downloading only part of the daily programs (https://github.com/iptv-org/epg/issues/90).
2. The program for one channel differs in different sources, which does not allow to just merge them. Often even the start and end times of the program are different.
3. Without reference to the source it is not possible to quickly find and fix the appearing errors.

And as soon as there is a solution to all these problems, the merged file will return to the repository.

**Comment by LaneSh4d0w** [comment]
1) I've seen multiple EPG sources zipping their file into a .gz, making it easier to transport.
2) This will be one of the main things in which we're going to be tackled on. I would say that the most **precise** EPG source could be privileged (ex. a program starting at 8:30 PM on one source and at 8;28:52 PM on another, better keep the second one).
3) Source, as the TV channel or something else ? This indeed can't really be easily tracked.

**Comment by freearhey** [comment]
1. This only helps to speed up downloading the file. The amount of data to be displayed in the app does not change.
3. By source I mean the site from which the program was loaded. That is, it should be clear from the final file from which site the description of a particular program is taken, so that if there are any errors it is possible to correct them quickly.

I created a file with a list of all the programs for the day in JSON format, so anyone can experiment with it and maybe end up with some solution. 

https://github.com/iptv-org/epg/actions/runs/1720957870

![image](https://user-images.githubusercontent.com/7253922/150408201-f5d727db-6d6e-44d6-9a3e-67beac35741d.png)

**Comment by PD-TheKrazy0ne** [comment]
Would it be possible to merge the US-Directv EPG with the Canadian EPG to create a North American EPG by chance??

**Comment by LaneSh4d0w** [comment]
> 1. This only helps to speed up downloading the file. The amount of data to be displayed in the app does not change.
> 
>     2. By source I mean the site from which the program was loaded. That is, it should be clear from the final file from which site the description of a particular program is taken, so that if there are any errors it is possible to correct them quickly.
> 
> 
> I created a file with a list of all the programs for the day in JSON format, so anyone can experiment with it and maybe end up with some solution.
> 
> https://github.com/iptv-org/epg/actions/runs/1720957870
> 
> ![image](https://user-images.githubusercontent.com/7253922/150408201-f5d727db-6d6e-44d6-9a3e-67beac35741d.png)

I'll have a look at that when i'll be back home.

**Comment by freearhey** [comment]
I am closing this issue for now, but if there is any solution we will open it again.
