### ISSUE TITLE
D-Smart EPG Problems

### ISSUE THREAD

**Issue by UzunMuhalefet** [iptv-org/epg#313]
Hi,
I found some problems with dsmart-com-tr file.

Wrong ID CNNTurk
<channel lang="tr" xmltv_id="CNNTurk.us" site_id="201#500">CNN Türk</channel> -> 197#500
https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=197&limit=1&day=2021-11-28

Wrong Channel Flash TV
<channel lang="tr" xmltv_id="FlashTV.tr" site_id="155#273">Flash TV</channel> ->
156#274 (But empty)
https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=156&limit=1&day=2021-11-28

Wrong Channel
<channel lang="tr" xmltv_id="TRTAvaz.tr" site_id="163#283">TRT Avaz</channel> -> 164#284
https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=164&limit=1&day=2021-11-28

New Channels:
Halk TV -> https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=154&limit=1&day=2021-11-28 (154#272)

Powertürk -> https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=102&limit=1&day=2021-11-28 (102#118)

Tay TV -> https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=70&limit=1&day=2021-11-28 (70#74)

Tele 1 -> https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=155&limit=1&day=2021-11-28 (155#273)

TRT 3 -> https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=89&limit=1&day=2021-11-28 (89#103)

TRT Spor -> https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=81&limit=1&day=2021-11-28 (81#85)

TRT Çocuk -> https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=109&limit=1&day=2021-11-28 (109#125)

TV8.5 -> https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=46&limit=1&day=2021-11-28 (46#47)

**Comment by freearhey** [comment]
Added via #386
