### ISSUE TITLE
combine multiple EPG links

### ISSUE THREAD

**Issue by m5arish** [iptv-org/epg#342]
my IPTV player only accepts one link for EPG source
I'd like to have multiple countries EPGs, is there anyway I can combine multiple links into one ?

**Comment by Marwane87** [comment]
https://iptv-org.github.io/epg/guides/fr/chaines-tv.orange.fr.epg.xml

**Comment by Marwane87** [comment]
Salut j’arrive pas a avoir les chaîne beinsport et canal+ c’est vous pouvez me donner un liens svp merci à vous

**Comment by freearhey** [comment]
This cannot be done for the reasons stated here: https://github.com/iptv-org/epg/issues/310#issuecomment-1012223913
