### ISSUE TITLE
Requesting EPG for Japan

### ISSUE THREAD

**Issue by luke-c** [iptv-org/epg#344]
Hey, thanks for the amazing work here! I noticed that over in the IPTV repository there's [quite a few](https://github.com/iptv-org/iptv/blob/0eb61bb64429219125f991b4b46c143f44003d8a/channels/jp.m3u) channels for Japan, but there's no episode guides for them at all here.

The best sources are probably these:
https://tv.yahoo.co.jp/listings
https://tvguide.myjcom.jp/

**Comment by LaneSh4d0w** [comment]
I may try a draft, based on what @freearhey did for other service, but the issue would be that channel names given from the Japanese services are written in Kanji, whilst we have the Romanised names available on the playlists.

**Comment by luke-c** [comment]
Assuming we want to keep using the Romanised names in the playlist, would we just need a mapping between the names used in the Japanese TV guide and the Romanised names (or the tvg-id)?

**Comment by LaneSh4d0w** [comment]
> Assuming we want to keep using the Romanised names in the playlist, would we just need a mapping between the names used in the Japanese TV guide and the Romanised names (or the tvg-id)?

We would need a mapping for all known channel names in the EPGs, indeed. So that, once we got the EPGs, we basically use some backend code to change the names of the channels to their romanized one.

**Comment by luke-c** [comment]
I'm happy to help with this - is there a specific format that would be preferred?

**Comment by LaneSh4d0w** [comment]
> I'm happy to help with this - is there a specific format that would be preferred?

I suppose that JSON would be the easiest way to work with, as it's basically used by every language.

**Comment by jplagden** [comment]
Any update on this?

**Comment by freearhey** [comment]
Added via #389
