### ISSUE TITLE
All epg still work..? 

### ISSUE THREAD

**Issue by NyamukClone** [iptv-org/epg#35]
I have used some epg link.. I see the channel but i cant see any info about that channel program... Why..?

**Comment by freearhey** [comment]
Could you be more specific about which link you used?

**Comment by freearhey** [comment]
At the moment, both guides are working fine.

![image](https://user-images.githubusercontent.com/7253922/130202552-c7ab0262-d40e-4e45-82d9-e8c744e2dedd.png)
![image](https://user-images.githubusercontent.com/7253922/130202594-e2c75742-c58f-4e45-9c4e-49f2d7d07355.png)
