### ISSUE TITLE
EPG for Sky Movie Channels

### ISSUE THREAD

**Issue by Gitbone94** [iptv-org/epg#359]
You have two UK epgs and one is actually for Sky showing 84 channels, but the movie channels are missing. 
I found an online epg for some of these channels:  hxxps://www.sky.com/tv-guide/20211229/4101-1/

Is it possible for iptv-org to add to the Sky epg for these movie channels:
Sky Modern Greats
Sky Disney
Sky Family
Sky Action & Adventure
Sky Comedy
Sky Crime & Thriller
Sky Movies Drama
Sky Scifi & Horror
Sky Select
Sky Movies Showcase

**Comment by RevGear** [comment]
I was going to add a request for more Sky channels but probably better if I just tack it on to this one.

<channel lang="en" xmltv_id="?????" site_id="1104">A1TV</channel>
<channel lang="en" xmltv_id="?????" site_id="3255">AAJ TAK</channel>
<channel lang="en" xmltv_id="?????" site_id="3594">Aastha</channel>
<channel lang="en" xmltv_id="?????" site_id="6765">Ahlebait TV</channel>
<channel lang="en" xmltv_id="?????" site_id="3825">alibi</channel>
<channel lang="en" xmltv_id="?????" site_id="2402">Animal Planet</channel>
<channel lang="en" xmltv_id="?????" site_id="1066">Arirang TV</channel>
<channel lang="en" xmltv_id="?????" site_id="5040">Arise News</channel>
<channel lang="en" xmltv_id="?????" site_id="4265">ARY Digital</channel>
<channel lang="en" xmltv_id="?????" site_id="6753">ATN</channel>
<channel lang="en" xmltv_id="?????" site_id="3206">Ayozat TV</channel>
<channel lang="en" xmltv_id="?????" site_id="5703">B4U Movies</channel>
<channel lang="en" xmltv_id="?????" site_id="5708">B4U Music</channel>
<channel lang="en" xmltv_id="?????" site_id="3645">Baby TV</channel>
<channel lang="en" xmltv_id="?????" site_id="2012">BBC ALBA</channel>
<channel lang="en" xmltv_id="?????" site_id="4100">Best Direct</channel>
<channel lang="en" xmltv_id="?????" site_id="5609">Boomerang</channel>
<channel lang="en" xmltv_id="?????" site_id="3417">BoxNation</channel>
<channel lang="en" xmltv_id="?????" site_id="5417">British Muslim</channel>
<channel lang="en" xmltv_id="?????" site_id="3625">BT Sport 1</channel>
<channel lang="en" xmltv_id="?????" site_id="3627">BT Sport 2</channel>
<channel lang="en" xmltv_id="?????" site_id="3629">BT Sport 3</channel>
<channel lang="en" xmltv_id="?????" site_id="1218">BT Sport Box Office 2</channel>
<channel lang="en" xmltv_id="?????" site_id="4040">BT Sport / ESPN</channel>
<channel lang="en" xmltv_id="?????" site_id="6014">BT Sport Box Office</channel>
<channel lang="en" xmltv_id="?????" site_id="4077">Cartoon Network</channel>
<channel lang="en" xmltv_id="?????" site_id="1371">Cartoonito</channel>
<channel lang="en" xmltv_id="?????" site_id="5359">Channel 44</channel>
<channel lang="en" xmltv_id="?????" site_id="3687">Channel 7</channel>
<channel lang="en" xmltv_id="?????" site_id="5520">Channels 24</channel>
<channel lang="en" xmltv_id="?????" site_id="3815">CHSTV</channel>
<channel lang="en" xmltv_id="?????" site_id="4505">Clubland TV</channel>
<channel lang="en" xmltv_id="?????" site_id="1088">CNBC</channel>
<channel lang="en" xmltv_id="?????" site_id="1019">CNN</channel>
<channel lang="en" xmltv_id="?????" site_id="1372">COLORS</channel>
<channel lang="en" xmltv_id="?????" site_id="1105">Colors Cineplex</channel>
<channel lang="en" xmltv_id="?????" site_id="1090">Colors Gujarati</channel>
<channel lang="en" xmltv_id="?????" site_id="3916">Colors Rishtey</channel>
<channel lang="en" xmltv_id="?????" site_id="4056">Comedy Central</channel>
<channel lang="en" xmltv_id="?????" site_id="1813">Comedy Central Xtra</channel>
<channel lang="en" xmltv_id="?????" site_id="1207">Court TV</channel>
<channel lang="en" xmltv_id="?????" site_id="3012">Craft Extra</channel>
<channel lang="en" xmltv_id="?????" site_id="4088">Crime+Investigation</channel>
<channel lang="en" xmltv_id="?????" site_id="3809">Dave</channel>
<channel lang="en" xmltv_id="?????" site_id="5541">DAYSTAR</channel>
<channel lang="en" xmltv_id="?????" site_id="1235">Deen TV</channel>
<channel lang="en" xmltv_id="?????" site_id="3415">Direct Store TV</channel>
<channel lang="en" xmltv_id="?????" site_id="2407">Discovery History</channel>
<channel lang="en" xmltv_id="?????" site_id="2406">Discovery Science</channel>
<channel lang="en" xmltv_id="?????" site_id="2409">Discovery Turbo</channel>
<channel lang="en" xmltv_id="?????" site_id="4003">Discovery</channel>
<channel lang="en" xmltv_id="?????" site_id="1191">Dunamis TV</channel>
<channel lang="en" xmltv_id="?????" site_id="1038">Dunya News</channel>
<channel lang="en" xmltv_id="?????" site_id="4028">E!</channel>
<channel lang="en" xmltv_id="?????" site_id="2302">Eden</channel>
<channel lang="en" xmltv_id="?????" site_id="4604">Euronews</channel>
<channel lang="en" xmltv_id="?????" site_id="4004">Eurosport 1</channel>
<channel lang="en" xmltv_id="?????" site_id="4009">Eurosport 2</channel>
<channel lang="en" xmltv_id="?????" site_id="3117">EWTN Catholic</channel>
<channel lang="en" xmltv_id="?????" site_id="5354">Faith UK</channel>
<channel lang="en" xmltv_id="?????" site_id="4404">Faith World TV</channel>
<channel lang="en" xmltv_id="?????" site_id="1227">Foodxp</channel>
<channel lang="en" xmltv_id="?????" site_id="1121">France 24</channel>
<channel lang="en" xmltv_id="?????" site_id="1196">GB News</channel>
<channel lang="en" xmltv_id="?????" site_id="1129">Gemporia Craft</channel>
<channel lang="en" xmltv_id="?????" site_id="4407">GEO News</channel>
<channel lang="en" xmltv_id="?????" site_id="4110">GEO TV</channel>
<channel lang="en" xmltv_id="?????" site_id="1830">GINXeSportsTV</channel>
<channel lang="en" xmltv_id="?????" site_id="3105">GOD Channel</channel>
<channel lang="en" xmltv_id="?????" site_id="2304">GOLD</channel>
<channel lang="en" xmltv_id="?????" site_id="1188">Good News TV</channel>
<channel lang="en" xmltv_id="?????" site_id="3708">GREAT! action</channel>
<channel lang="en" xmltv_id="?????" site_id="3643">GREAT! Classic</channel>
<channel lang="en" xmltv_id="?????" site_id="3709">GREAT! movies</channel>
<channel lang="en" xmltv_id="?????" site_id="4266">GREAT! tv</channel>
<channel lang="en" xmltv_id="?????" site_id="4549">Hidayat TV</channel>
<channel lang="en" xmltv_id="?????" site_id="3580">High Street TV 1</channel>
<channel lang="en" xmltv_id="?????" site_id="5706">High Street TV 2</channel>
<channel lang="en" xmltv_id="?????" site_id="3404">High Street TV 3</channel>
<channel lang="en" xmltv_id="?????" site_id="1130">High Street TV 4</channel>
<channel lang="en" xmltv_id="?????" site_id="1102">Hi-Impact TV</channel>
<channel lang="en" xmltv_id="?????" site_id="1004">Hillsong</channel>
<channel lang="en" xmltv_id="?????" site_id="5205">HUM EUROPE</channel>
<channel lang="en" xmltv_id="?????" site_id="1069">HUM Masala</channel>
<channel lang="en" xmltv_id="?????" site_id="2413">ID</channel>
<channel lang="en" xmltv_id="?????" site_id="3219">Inspiration TV</channel>
<channel lang="en" xmltv_id="?????" site_id="4461">iON TV</channel>
<channel lang="en" xmltv_id="?????" site_id="3914">IQRA BANGLA</channel>
<channel lang="en" xmltv_id="?????" site_id="6754">IQRA TV</channel>
<channel lang="en" xmltv_id="?????" site_id="5211">Islam Ch Urdu</channel>
<channel lang="en" xmltv_id="?????" site_id="3214">Islam Channel</channel>
<channel lang="en" xmltv_id="?????" site_id="4403">Islam TV</channel>
<channel lang="en" xmltv_id="?????" site_id="5761">JML Direct</channel>
<channel lang="en" xmltv_id="?????" site_id="1853">Kerrang!</channel>
<channel lang="en" xmltv_id="?????" site_id="3776">KICC TV</channel>
<channel lang="en" xmltv_id="?????" site_id="1858">KISS</channel>
<channel lang="en" xmltv_id="?????" site_id="1056">KTV</channel>
<channel lang="en" xmltv_id="?????" site_id="1015">LaLigaTV</channel>
<channel lang="en" xmltv_id="?????" site_id="3845">Liverpool FC TV</channel>
<channel lang="en" xmltv_id="?????" site_id="1133">Live 360</channel>
<channel lang="en" xmltv_id="?????" site_id="5536">Local TV</channel>
<channel lang="en" xmltv_id="?????" site_id="1228">LoveWorld</channel>
<channel lang="en" xmltv_id="?????" site_id="4460">Madani Chnl</channel>
<channel lang="en" xmltv_id="?????" site_id="1877">Magic</channel>
<channel lang="en" xmltv_id="?????" site_id="3401">MATV National</channel>
<channel lang="en" xmltv_id="?????" site_id="4420">Movies24</channel>
<channel lang="en" xmltv_id="?????" site_id="3201">mta-muslim tv</channel>
<channel lang="en" xmltv_id="?????" site_id="2508">MTV BASE</channel>
<channel lang="en" xmltv_id="?????" site_id="2509">MTV Classic</channel>
<channel lang="en" xmltv_id="?????" site_id="3831">MTV</channel>
<channel lang="en" xmltv_id="?????" site_id="2506">MTV HITS</channel>
<channel lang="en" xmltv_id="?????" site_id="2512">MTV MUSIC</channel>
<channel lang="en" xmltv_id="?????" site_id="2501">MTV</channel>
<channel lang="en" xmltv_id="?????" site_id="1003">MUTV</channel>
<channel lang="en" xmltv_id="?????" site_id="4031">Nat Geo</channel>
<channel lang="en" xmltv_id="?????" site_id="4025">Nat Geo Wild</channel>
<channel lang="en" xmltv_id="?????" site_id="1821">NDTV 24x7</channel>
<channel lang="en" xmltv_id="?????" site_id="3722">NEO News</channel>
<channel lang="en" xmltv_id="?????" site_id="1131">New Media</channel>
<channel lang="en" xmltv_id="?????" site_id="1026">New Vision TV</channel>
<channel lang="en" xmltv_id="?????" site_id="3147">NHK World</channel>
<channel lang="en" xmltv_id="?????" site_id="4039">Nick Jr. HD</channel>
<channel lang="en" xmltv_id="?????" site_id="4340">Nick Jr. Too</channel>
<channel lang="en" xmltv_id="?????" site_id="4069">Nickelodeon</channel>
<channel lang="en" xmltv_id="?????" site_id="1849">Nicktoons</channel>
<channel lang="en" xmltv_id="?????" site_id="3715">Noor TV</channel>
<channel lang="en" xmltv_id="?????" site_id="3403">NOW 70s</channel>
<channel lang="en" xmltv_id="?????" site_id="4541">NOW 80s</channel>
<channel lang="en" xmltv_id="?????" site_id="3682">NOW 90s</channel>
<channel lang="en" xmltv_id="?????" site_id="3731">NTD</channel>
<channel lang="en" xmltv_id="?????" site_id="4540">NTV</channel>
<channel lang="en" xmltv_id="?????" site_id="1140">PCNE Chinese</channel>
<channel lang="en" xmltv_id="?????" site_id="1260">Pitaara </channel>
<channel lang="en" xmltv_id="?????" site_id="3421">POLITICSPUNJAB</channel>
<channel lang="en" xmltv_id="?????" site_id="4262">POP Max</channel>
<channel lang="en" xmltv_id="?????" site_id="5153">Premier 1</channel>
<channel lang="en" xmltv_id="?????" site_id="1634">Premier 2</channel>
<channel lang="en" xmltv_id="?????" site_id="5715">PTC PUNJABI</channel>
<channel lang="en" xmltv_id="?????" site_id="3646">PTV Global</channel>
<channel lang="en" xmltv_id="?????" site_id="1128">Quest</channel>
<channel lang="en" xmltv_id="?????" site_id="3359">QVC Extra</channel>
<channel lang="en" xmltv_id="?????" site_id="5907">QVC</channel>
<channel lang="en" xmltv_id="?????" site_id="3116">revelation</channel>
<channel lang="en" xmltv_id="?????" site_id="3542">ROK</channel>
<channel lang="en" xmltv_id="?????" site_id="1100">Sanskar</channel>
<channel lang="en" xmltv_id="?????" site_id="3650">Sikh Channel</channel>
<channel lang="en" xmltv_id="?????" site_id="2207">Sky Crime</channel>
<channel lang="en" xmltv_id="?????" site_id="1879">Sky History2</channel>
<channel lang="en" xmltv_id="?????" site_id="4086">Sky History</channel>
<channel lang="en" xmltv_id="?????" site_id="1402">Sky Max</channel>
<channel lang="en" xmltv_id="?????" site_id="1165">Sky Nature</channel>
<channel lang="en" xmltv_id="?????" site_id="1404">Sky News</channel>
<channel lang="en" xmltv_id="?????" site_id="1833">Sky Replay</channel>
<channel lang="en" xmltv_id="?????" site_id="1807">Sky Cinema Scifi & Horror</channel>
<channel lang="en" xmltv_id="?????" site_id="2201">Sky Witness</channel>
<channel lang="en" xmltv_id="?????" site_id="1136">Sky Documentaries</channel>
<channel lang="en" xmltv_id="?????" site_id="3940">Sky Sports Arena</channel>
<channel lang="en" xmltv_id="?????" site_id="3835">Sky Sports F1</channel>
<channel lang="en" xmltv_id="?????" site_id="3939">Sky Sports Football</channel>
<channel lang="en" xmltv_id="?????" site_id="4026">Sky Sports Golf</channel>
<channel lang="en" xmltv_id="?????" site_id="4090">Sky Sports Mix</channel>
<channel lang="en" xmltv_id="?????" site_id="4049">Sky Sports News</channel>
<channel lang="en" xmltv_id="?????" site_id="4022">Sky Sports NFL</channel>
<channel lang="en" xmltv_id="?????" site_id="4010">Sky Sports Premier League</channel>
<channel lang="en" xmltv_id="?????" site_id="4032">Sky Sports Racing</channel>
<channel lang="en" xmltv_id="?????" site_id="1034">Sky Sports Box Office</channel>
<channel lang="en" xmltv_id="?????" site_id="4081">Sky Sports Cricket</channel>
<channel lang="en" xmltv_id="?????" site_id="4002">Sky Sports Main Event</channel>
<channel lang="en" xmltv_id="?????" site_id="3392">SonLife</channel>
<channel lang="en" xmltv_id="?????" site_id="5431">Sony MAX 2</channel>
<channel lang="en" xmltv_id="?????" site_id="2603">Sony MAX</channel>
<channel lang="en" xmltv_id="?????" site_id="3631">Sony SAB</channel>
<channel lang="en" xmltv_id="?????" site_id="4045">Sony TV</channel>
<channel lang="en" xmltv_id="?????" site_id="1223">SportyStuff</channel>
<channel lang="en" xmltv_id="?????" site_id="4074">SYFY</channel>
<channel lang="en" xmltv_id="?????" site_id="4408">Takbeer TV</channel>
<channel lang="en" xmltv_id="?????" site_id="5605">TCM Movies</channel>
<channel lang="en" xmltv_id="?????" site_id="3805">Thane</channel>
<channel lang="en" xmltv_id="?????" site_id="1017">That's TV</channel>
<channel lang="en" xmltv_id="?????" site_id="1802">The Box</channel>
<channel lang="en" xmltv_id="?????" site_id="3357">The Craft Store</channel>
<channel lang="en" xmltv_id="?????" site_id="5212">TJC Beauty</channel>
<channel lang="en" xmltv_id="?????" site_id="1113">TJC</channel>
<channel lang="en" xmltv_id="?????" site_id="3812">TLC</channel>
<channel lang="en" xmltv_id="?????" site_id="3505">Trace Hits</channel>
<channel lang="en" xmltv_id="?????" site_id="3935">Trace Vault</channel>
<channel lang="en" xmltv_id="?????" site_id="1226">Travelxp</channel>
<channel lang="en" xmltv_id="?????" site_id="5237">TRT World</channel>
<channel lang="en" xmltv_id="?????" site_id="5426">TV One</channel>
<channel lang="en" xmltv_id="?????" site_id="3632">TV Warehouse</channel>
<channel lang="en" xmltv_id="?????" site_id="5882">TVC News</channel>
<channel lang="en" xmltv_id="?????" site_id="3608">Utsav Bharat</channel>
<channel lang="en" xmltv_id="?????" site_id="4047">Utsav Gold</channel>
<channel lang="en" xmltv_id="?????" site_id="5300">Utsav Plus</channel>
<channel lang="en" xmltv_id="?????" site_id="3720">Venus TV</channel>
<channel lang="en" xmltv_id="?????" site_id="3108">Vox Africa</channel>
<channel lang="en" xmltv_id="?????" site_id="3810">W</channel>
<channel lang="en" xmltv_id="?????" site_id="1084">WION</channel>
<channel lang="en" xmltv_id="?????" site_id="3205">Word Network</channel>
<channel lang="en" xmltv_id="?????" site_id="2608">Zee Cinema</channel>
<channel lang="en" xmltv_id="?????" site_id="1016">Zee TV</channel>

**Comment by freearhey** [comment]
@RevGear You can add these channels to the list yourself: https://github.com/iptv-org/epg/blob/master/sites/sky.com/sky.com_uk.channels.xml. The correct channel names and xmltv_id can be found here: https://iptv-org.github.io/epg/index.html

**Comment by RevGear** [comment]
@freearhey I didn't realise I had access to update. I've updated some where you already had the xmltv_id from another source. I'll try to pick up the others later.

**Comment by freearhey** [comment]
@Gitbone94 Most channels are already on the list.

Sky Modern Greats https://github.com/iptv-org/epg/blob/abdc974c716d381e6a54c99c2eca1c588e6b5233/sites/sky.com/sky.com_uk.channels.xml#L117
Sky Family
https://github.com/iptv-org/epg/blob/abdc974c716d381e6a54c99c2eca1c588e6b5233/sites/sky.com/sky.com_uk.channels.xml#L115
Sky Action & Adventure
https://github.com/iptv-org/epg/blob/abdc974c716d381e6a54c99c2eca1c588e6b5233/sites/sky.com/sky.com_uk.channels.xml#L111
Sky Comedy
https://github.com/iptv-org/epg/blob/abdc974c716d381e6a54c99c2eca1c588e6b5233/sites/sky.com/sky.com_uk.channels.xml#L113
Sky Crime & Thriller
https://github.com/iptv-org/epg/blob/abdc974c716d381e6a54c99c2eca1c588e6b5233/sites/sky.com/sky.com_uk.channels.xml#L123
Sky Movies Drama
https://github.com/iptv-org/epg/blob/abdc974c716d381e6a54c99c2eca1c588e6b5233/sites/sky.com/sky.com_uk.channels.xml#L114
Sky Scifi & Horror
https://github.com/iptv-org/epg/blob/abdc974c716d381e6a54c99c2eca1c588e6b5233/sites/sky.com/sky.com_uk.channels.xml#L122
Sky Movies Showcase
https://github.com/iptv-org/epg/blob/abdc974c716d381e6a54c99c2eca1c588e6b5233/sites/sky.com/sky.com_uk.channels.xml#L131

As for Sky Disney & Sky Select, I could not find their program on sky.com.

**Comment by Gitbone94** [comment]
Many thanks!
