### ISSUE TITLE
TMB.tr and TMBTV.tr

### ISSUE THREAD

**Issue by UzunMuhalefet** [iptv-org/epg#388]
These two channels are the same.
![image](https://user-images.githubusercontent.com/80906858/149421292-475b2b2a-9edb-44c2-a777-52aba6da8a06.png)

**Comment by LaneSh4d0w** [comment]
Notice the EPG URLs, those are simply from 2 different sources. One might indicate TMB, the other might indicate TMBTV.

Clearly not an issue from the program, but is linked to the EPG source.

**Comment by UzunMuhalefet** [comment]
I checked both websites (dsmart and tvplus). They are the same channel. D-Smart is using previous logo and branding of the TMB (Turkic Music Union) 

Old [website](https://web.archive.org/web/20121115083051/https://www.tmb.tv/) and logo:
![image](https://user-images.githubusercontent.com/80906858/149643983-8c8aa3de-5bfb-4a42-953b-52f26008ed80.png)
[D-Smart](https://www.dsmart.com.tr/kanallar) Channel List:
![image](https://user-images.githubusercontent.com/80906858/149643997-6b1849bf-b35a-4d0d-a66f-ccde20ba2bb3.png)

New [website](https://www.tmb.tv/canli-yayin/) and logo: 
https://www.tmb.tv/wp-content/uploads/2022/01/unnamed-5.png

[TV+ channel list](https://tvplus.com.tr/canli-tv):
![image](https://user-images.githubusercontent.com/80906858/149644017-c8eb5463-dfb8-4d65-88f5-86a284641c2b.png)

**Comment by freearhey** [comment]
Fixed via https://github.com/iptv-org/epg/commit/e31d185ccc073d2f0cdd995767ded93c19242f95
