### ISSUE TITLE
No EPG 

### ISSUE THREAD

**Issue by Shifty0wl** [iptv-org/epg#391]
So no info from UK, USA and Canada now?

**Comment by ian10951** [comment]
Same here, no new EPG from USA and Canada

**Comment by freearhey** [comment]
Thanks for the report! I'm already working on it.

**Comment by dcole819** [comment]
Yep same issue no US epg working at all

**Comment by Shifty0wl** [comment]
Any eta on a fix? All my devices still have no EPG as well as my families

**Comment by freearhey** [comment]
Should be working by now.

**Comment by Shifty0wl** [comment]
Awesome thank you

**Comment by ian10951** [comment]
No EPG again Today for USA and Canada.

The downloaded xml is just 0 bytes.

**Comment by Shifty0wl** [comment]
No EPG yet again....no Canada, no USA

**Comment by freearhey** [comment]
Programs for both countries have disappeared due to changes on tvtv.us: https://github.com/iptv-org/epg/issues/403
