### ISSUE TITLE
EPG Switzerland Final Usage Link Missed after successful added

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#409]
Hello 
Its not a real problem but 
I saw that you added with success Switzerland EPG from https://tv.blue.ch/tv-guide
But i dont see Switzerland Country EPG LINK among Usage EPG Countries List
MANY THANKS for Everything
You are the BEST

**Comment by Talon555** [comment]
Please, could you give the final usage epg.xml link for this new add for Switzerland channels from https://tv.blue.ch/tv-guide

**Comment by freearhey** [comment]
The link should appear on the list tomorrow after 06:00 UTC.

**Comment by Talon555** [comment]
MANY THANKS !!!
Please, delete my post question because following your response it looks like stupid my question !
