### ISSUE TITLE
Switzerland 🇨🇭 EPG Link clicked = Page not Found 

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#420]
Hello Guys,
Switzerland 🇨🇭 EPG Link has been successfully added in Usage Countries EPG link
But apparently there's a bug because no information provided and I clicked directly on the link I got PAGE NOT FOUND.
I'll recheck it again later if the error page persist. 
Big kudos to you for your amazing work. 
Many thanks for Everything!

**Comment by Talon555** [comment]
Everything works like a charm this morning
Big kudos to you because it's the Switzerland 🇨🇭 EPG is the most complete that I know WOW ❤️

**Comment by freearhey** [comment]
Glad to hear it!
