### ISSUE TITLE
Requesting for EPG Belgium Additionnal Complete Source

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#422]
Hello
Here Some Belgium EPG Source with all Belgian channels
Here the URLs
https://tv.telepro.be/programmes-tele/
https://www.proximus.be/pickx/fr/television/programme-tv

**Comment by freearhey** [comment]
The guide from `proximusmwc.be` is available at:

```
https://iptv-org.github.io/epg/guides/be/proximusmwc.be.epg.xml
```

**Comment by Talon555** [comment]
> The guide from `proximusmwc.be` is available at:
> 
> ```
> https://iptv-org.github.io/epg/guides/be/proximusmwc.be.epg.xml
> ```

YES THANKS

**Comment by freearhey** [comment]
The site has been down for days.
<img width="354" alt="image" src="https://user-images.githubusercontent.com/7253922/158266755-c800261e-61c4-4468-bd68-d9c6f9e08ff2.png">

**Comment by lamko648** [comment]
The site is working again but npm run grab -- --site=proximusmwc.be gives :
[304/414] proximusmwc.be (nl) - Play7.be - Nov 6, 2023 (0 programs)
    ERR: Request failed with status code 400
for al channels.
can you have a look at it
