### ISSUE TITLE
Requesting for EPG France Additionnal Complete Source

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#423]
Hello
Here Some French EPG Source with all French channels
Here the URLs

https://tv-programme.telecablesat.fr/programmes-tele/
https://www.canalplus.com/programme-tv/

**Comment by RevGear** [comment]
Canal+
https://hodor.canalplus.pro/api/v2/mycanal/channels/f55e5c7ddf0afba59d1c64581358910d/${channel}/broadcasts/day/${day}

day = -1, 0, 1, 2 ,3, 4, 5, 6, 7, 8 (0 = today, 1 = tomorrow, etc)

Response has a start time but doesn't appear to have either an end time or duration, which might be a problem.

**channels**
26 | FRANCE 2
30 | CNN INT.
47 | BLOOMBERG TV
64 | CNBC
100 | TEST3
101 | EUROSPORT 1
142 | USHUAIA TV
154 | ARTE
165 | CLASSICA
167 | PENTHOUSE
185 | DORA TV
202 | TEST4
252 | ARIRANG TV
259 | CANAL+KIDS
268 | MEZZO LIVE
274 | DISNEY JUNIOR
282 | DISNEY CHANNEL
289 | CHAINE EVENEMENT
290 | NATIONAL GEOGRAPHIC  WILD
292 | TEVA
294 | PARIS PREMIERE
296 | W9
302 | NATIONAL GEO
310 | FRANCE 24
311 | FRANCE 24 ENG
312 | TF1
313 | M6
324 | EURONEWS
352 | M6 MUSIC
356 | SERIE CLUB
362 | I24 NEWS
372 | OCS MAX
374 | TCM CINEMA
378 | GOLF+
381 | BEIN SPORTS 1
384 | BEIN SPORTS 2
407 | DJAZZ
436 | EUROSPORT 2
440 | CHERIE 25
451 | L'EQUIPE
466 | OCS CHOC
467 | OCS CITY
468 | OCS GEANTS
470 | MTV
479 | RT FRANCE
480 | CNEWS
484 | J-ONE
487 | PARAMOUNT CHANNEL
502 | CARTOON NETWORK
503 | ANIMAUX
504 | ACTION
505 | RTL9
513 | CSTAR
516 | BEIN SPORTS 3
518 | NICKELODEON TEEN
520 | TV5 MONDE
521 | 6TER
525 | CANAL J
526 | TF1 SERIES FILMS
527 | NOLLYWOOD TV
529 | BOING
530 | BOOMERANG
535 | DISNEY CHANNEL+1
536 | DORCEL TV
537 | DORCEL XXX
540 | EQUIDIA
542 | FOOT+ 24/24
543 | FRANCE 3
544 | FRANCE 4
545 | FRANCE 5
547 | VIXEN
549 | GULLI
550 | HISTOIRE TV
551 | INFOSPORT+
552 | LA CHAINE METEO
553 | LCI
554 | LCP
556 | MCM
557 | RFM TV
560 | MEZZO
562 | MULTISPORTS 1
563 | MULTISPORTS 2
564 | MULTISPORTS 3
565 | MULTISPORTS 4
566 | MULTISPORTS 5
567 | MULTISPORTS 6
568 | NRJ 12
569 | NRJ HITS
570 | TFX
571 | RMC STORY
575 | PINK X
580 | MELODY
582 | TELETOON+1
583 | TIJI
584 | TMC
585 | TRACE URBAN
586 | TV BREIZH
589 | BBC WORLD NEWS
591 | NICKELODEON
592 | GAME ONE
593 | NICKELODEON JUNIOR
595 | RMC DECOUVERTE
596 | BEIN SPORTS MAX 4
597 | BEIN SPORTS MAX 5
598 | BEIN SPORTS MAX 6
599 | BEIN SPORTS MAX 7
603 | BEIN SPORTS MAX 8
604 | BEIN SPORTS MAX 9
605 | BEIN SPORTS MAX 10
611 | AB1
612 | AUTOMOTO LA CHAINE
613 | MANGAS
614 | SCIENCE ET VIE TV
616 | XXL
620 | TOUTE L'HISTOIRE
628 | BET
629 | MTV HITS
632 | ASTROCENTER TV
633 | BFM TV
635 | EUROSPORT 360 1
636 | EUROSPORT 360 2
637 | EUROSPORT 360 3
638 | EUROSPORT 360 4
639 | LL EVENT UHD
643 | COLMAX TV
645 | BFM BUSINESS
650 | EUROSPORT 360 5
651 | EUROSPORT 360 6
652 | EUROSPORT 360 7
653 | EUROSPORT 360 8
654 | NHK WORLD-JAPAN
665 | CLIQUE TV
670 | FRANCEINFO:
672 | MAN X
674 | TRACE AFRICA
675 | AL JAZEERA ENG
678 | MUSEUM
681 | CHASSE ET PECHE
683 | TOONAMI
686 | PENTHOUSE BLACK
693 | NOVELAS TV
694 | WARNER TV
696 | EURONEWS ALL
723 | CSTAR HITS FRANCE
726 | EVENEMENT SPORT 4K UHD
768 | CANAL 9
770 | RTS 1
771 | RTS 2
772 | CANAL ALPHA NE
773 | LA TELE
774 | LEMAN BLEU
775 | TELEBIELINGUE
776 | RSI 1
777 | RSI 2
778 | SRF 1
779 | SRF 2
784 | TRACE LATINA
787 | OCS MAX (CH)
788 | OCS CHOC (CH)
789 | OCS GEANTS (CH)
790 | OCS CITY (CH)
806 | COMEDY CENTRAL
813 | OLYMPIA TV
815 | CANAL+PREMIER LEAGUE
816 | CANAL+TOP14
819 | ES1
820 | ALTICE STUDIO
823 | CANAL+MOTOGP
824 | CANAL+FORMULA1
832 | CSTAR (CH)
849 | BSMART TV
850 | JACQUIE & MICHEL TV
861 | CANAL+ SPORT 2 (CH)
872 | EVENEMENT SPORT 4K UHD
874 | CANAL+ UHD (CH)
876 | TEST1
877 | TEST2
878 | ROUGE TV
879 | LFM TV
880 | ONE TV
882 | EVENEMENT A LA CARTE
893 | BLUE ZOOM
899 | CANAL+DOCS
900 | CANAL+GRAND ECRAN
920 | F3 PICARDIE
921 | F3 FRANCHE COMTE
922 | F3 AQUITAINE
923 | F3 BNORMANDIE
924 | F3 AUVERGNE
925 | F3 BOURGOGNE
926 | F3 ALPES
927 | F3 NORD PDC
928 | F3 LIMOUSIN
929 | F3 RHONE ALPES
930 | F3 PROV ALPES
931 | F3 LANGUEDOCROU
932 | F3 LORRAINE
933 | F3 PAYS DE LA LOIRE
934 | F3 COTE D'AZUR
935 | F3 CENTRE
936 | F3 PARIS IDF
937 | F3 POITOUCHAR
938 | F3 CHAMP ARDENNE
939 | F3 BRETAGNE
940 | F3 HNORMANDIE
941 | F3 ALSACE
942 | F3 MIDI PYRENEES
943 | F3 CORSEVIASTELLA
977 | BEIN SPORTS 1
978 | BEIN SPORTS 2
979 | BEIN SPORTS 3
980 | BEIN SPORTS MAX 4
981 | BEIN SPORTS MAX 5
982 | BEIN SPORTS MAX 6
983 | BEIN SPORTS MAX 7
984 | CANAL+
985 | EUROSPORT 3
986 | EUROSPORT 4
987 | EUROSPORT 5
992 | CANAL+SPORT
993 | CANAL+ UHD
998 | F3 NOUVELLE AQUITAINE
21120 | ARTE ALLEMAND
184 | DIEGO TV
196 | BOB TV
340 | DISNEY CINEMA
434 | NON STOP PEOPLE
477 | VOYAGE
656 | MY ZEN TV
677 | VICE TV
732 | RMC SPORT 1
733 | RMC SPORT 2
734 | RMC SPORT 3
735 | RMC SPORT 4
756 | RMC SPORT LIVE 5
757 | RMC SPORT LIVE 6
758 | RMC SPORT LIVE 7
759 | RMC SPORT LIVE 8
760 | RMC SPORT LIVE 9
761 | RMC SPORT LIVE 10
762 | RMC SPORT LIVE 11
763 | RMC SPORT LIVE 12
764 | RMC SPORT LIVE 13
765 | RMC SPORT LIVE 14
766 | RMC SPORT LIVE 3
767 | RMC SPORT LIVE 4
780 | CHAINE: 780
781 | CHAINE: 781
782 | CHAINE: 782
783 | CHAINE: 783
894 | CANAL+ LIGUE1
970 | CHAINE : 970
971 | CHAINE : 971
972 | CHAINE : 972
973 | CHAINE : 973
974 | CHAINE : 974
975 | CHAINE : 975
988 | EUROSPORT 6
989 | EUROSPORT 7
990 | EUROSPORT 8
991 | EUROSPORT 9
177 | CANAL+SPORT
198 | CANAL+CINEMA
257 | CANAL+DECALE
270 | PLANETE+
301 | CANAL+
322 | CINE+ PREMIER
396 | CINE+ EMOTION
398 | CINE+ FRISSON
450 | C8
481 | CANAL+SERIES
531 | CINE+ CLASSIC
532 | CINE+ CLUB
533 | CINE+ FAMIZ
534 | COMEDIE+
576 | PIWI+
577 | SEASONS
581 | TELETOON+
587 | PLANETE+CRIME
588 | PLANETE+AVENTURE
601 | CANAL+
692 | POLAR+
728 | CANAL+ UHD
825 | CANAL+ (CH)
826 | CANAL+ DECALE (CH)
827 | CANAL+ CINEMA (CH)
829 | CINE+ PREMIER (CH)
830 | CINE+ FRISSON (CH)
831 | C8 (CH)
873 | CANAL+ SPORT (CH)

**Comment by Talon555** [comment]
Hi Guys,
I hope one these complete EPG sourcing for FRANCE will add very soon
Please

**Comment by freearhey** [comment]
Guide from canalplus.com:

```
https://iptv-org.github.io/epg/guides/fr/canalplus.com.epg.xml
```

**Comment by Talon555** [comment]
And this EPG sourcing https://tv-programme.telecablesat.fr/programmes-tele/ could be added ???

**Comment by Talon555** [comment]
> And this EPG sourcing https://tv-programme.telecablesat.fr/programmes-tele/ could be added ???

Please add this link Because it's one the most complete epg sourcing for all French and Belgian channels

**Comment by freearhey** [comment]
Guide from telecablesat.fr is now also available:

```
https://iptv-org.github.io/epg/guides/fr/telecablesat.fr.epg.xml
```

**Comment by Talon555** [comment]
RMC SPORT 3
RMC SPORT 4
RMC SPORT LIVE 5
RMC SPORT LIVE 6
EPG missed for theses channels from telecablesat.net and canalplus.com

@freearhey please

**Comment by freearhey** [comment]
@Talon555 Feel free to add the channels yourself. In this case it is enough to edit the file [sites/telecablesat.fr/telecablesat.fr_fr.channels.xml](https://github.com/iptv-org/epg/blob/master/sites/telecablesat.fr/telecablesat.fr_fr.channels.xml) and [sites/canalplus.com/canalplus.com_fr.channels.xml](https://github.com/iptv-org/epg/blob/master/sites/canalplus.com/canalplus.com_fr.channels.xml).

If you can't do it yourself, it's better to create a separate issue so more people will see your request.

**Comment by Talon555** [comment]
@freearhey xml link of canalplus.com missed
Just a reminder
