### ISSUE TITLE
Requesting for EPG Germany Additionnal Complete Source 

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#425]
Hello
Here Some German EPG Source with all German channels
Here the URLs

Germany

https://www.sky.de/tvguide-7599
https://web.magentatv.de/tv-programm
https://www.horizon.tv/de_de/tv/tv-programm.html

Austria

https://www.magentatv.at/de/tv/tv-guide.html

**Comment by RevGear** [comment]
I wouldn't know where to start writing a script for this but sky.de can be obtained as follows. 
POST to https://www.sky.de/sgtvg/service/getBroadcastsForGrid with this data
`{
	"d": ttttttttttttt,
    "cil": [ccc]
}`
where ttttttttttttt is the timestamp in milliseconds and ccc is the channel ID.

Response will be an array of details something like this:
`                {
                    "ei": 121966308,
                    "bsdt": 1644103800000,
                    "bst": "00:30",
                    "bedt": 1644105900000,
                    "len": 35,
                    "et": "Quatsch Comedy Club",
                    "ec": "Show",
                    "ish": true,
                    "cop": "D",
                    "yop": 2022,
                    "fsk": "ab 12 Jahren",
                    "epit": "Staffel 5, Episode 2",
                    "sn": "5",
                    "en": "2",
                    "pu": "/static/img/program_guide/29122_sea_s.jpg"
                }`

**bsdt**/**bedt** are the start/end timestamps
**et** is the title
 **ec** is the category
 **epit** is the episode description
  **sn**/**en** are the season/episode numbers (if given)

**Channel ID List**
116 | 13th Street HD
690 | Beate Uhse HD
761 | Boomerang
95 | Cartoon Network
99 | Classica
451 | Crime + Investigation
659 | DAZN 1 HD
900 | DAZN 2 HD
83 | Discovery HD
117 | E! Entertainm. HD
596 | Eurosport 1 HD
161 | Eurosport 2 HD
163 | Eurosport360HD 1
164 | Eurosport360HD 2
165 | Eurosport360HD 3
166 | Eurosport360HD 4
167 | Eurosport360HD 5
168 | Eurosport360HD 6
169 | Eurosport360HD 7
170 | Eurosport360HD 8
171 | Eurosport360HD 9
72 | Heimatkanal
86 | HISTORY Channel HD
452 | Jukebox
96 | Junior
70 | Kinowelt TV
52 | Motorvision TV
81 | NatGeo HD
88 | NatGeo Wild HD
783 | Nick.Jr.
798 | Nicktoons
16 | Romance TV
2 | Sky Atlantic HD
59 | Sky Cinema Action
60 | Sky Cinema Action HD
790 | Sky Cinema Best Of
792 | Sky Cinema Best Of HD
794 | Sky Cinema Classics
532 | Sky Cinema Family
533 | Sky Cinema Family HD
793 | Sky Cinema Fun
787 | Sky Cinema Premieren
789 | Sky Cinema Premieren +24
791 | Sky Cinema Premieren +24 HD
788 | Sky Cinema Premieren HD
890 | Sky Cinema Special HD
784 | Sky Cinema Thriller HD
854 | Sky Comedy HD
855 | Sky Crime HD
876 | Sky Documentaries HD
753 | Sky Krimi HD
875 | Sky Nature HD
535 | Sky One HD
888 | Sky Replay HD
149 | Sky Sport  1
158 | Sky Sport  10
159 | Sky Sport  11
150 | Sky Sport  2
151 | Sky Sport  3
152 | Sky Sport  4
153 | Sky Sport  5
154 | Sky Sport  6
155 | Sky Sport  7
156 | Sky Sport  8
157 | Sky Sport  9
128 | Sky Sport 1 HD
137 | Sky Sport 10 HD
138 | Sky Sport 11 HD
129 | Sky Sport 2 HD
130 | Sky Sport 3 HD
131 | Sky Sport 4 HD
132 | Sky Sport 5 HD
133 | Sky Sport 6 HD
134 | Sky Sport 7 HD
135 | Sky Sport 8 HD
136 | Sky Sport 9 HD
492 | Sky Sport Austria 1 HD
729 | Sky Sport Austria 2 HD
730 | Sky Sport Austria 3 HD
898 | Sky Sport Austria 4 HD
883 | Sky Sport Austria 5 HD
884 | Sky Sport Austria 6 HD
885 | Sky Sport Austria 7 HD
139 | Sky Sport Bundesliga 1
118 | Sky Sport Bundesliga 1 HD
148 | Sky Sport Bundesliga 10
127 | Sky Sport Bundesliga 10 HD
140 | Sky Sport Bundesliga 2
119 | Sky Sport Bundesliga 2 HD
141 | Sky Sport Bundesliga 3
120 | Sky Sport Bundesliga 3 HD
142 | Sky Sport Bundesliga 4
121 | Sky Sport Bundesliga 4 HD
143 | Sky Sport Bundesliga 5
122 | Sky Sport Bundesliga 5 HD
144 | Sky Sport Bundesliga 6
123 | Sky Sport Bundesliga 6 HD
145 | Sky Sport Bundesliga 7
124 | Sky Sport Bundesliga 7 HD
146 | Sky Sport Bundesliga 8
125 | Sky Sport Bundesliga 8 HD
147 | Sky Sport Bundesliga 9
126 | Sky Sport Bundesliga 9 HD
531 | Sky Sport Bundesliga UHD
853 | Sky Sport F1 HD
17 | Sky Sport News HD
526 | Sky Sport UHD
84 | Spiegel Geschichte
388 | Spiegel Geschichte HD
658 | Spiegel TV Wissen
114 | SPORTDIGITAL FUSSBALL HD
115 | SYFY HD
172 | Universal TV HD
674 | Warner TV Comedy
522 | Warner TV Comedy HD
762 | Warner TV Film
689 | Warner TV Film HD
6 | Warner TV Serie HD

**Comment by freearhey** [comment]
@RevGear The scripts for all sites are in the [/sites](https://github.com/iptv-org/epg/tree/master/sites) folder.

**Comment by Talon555** [comment]
> I wouldn't know where to start writing a script for this but sky.de can be obtained as follows. POST to https://www.sky.de/sgtvg/service/getBroadcastsForGrid with this data `{ "d": ttttttttttttt, "cil": [ccc] }` where ttttttttttttt is the timestamp in milliseconds and ccc is the channel ID.
> 
> Response will be an array of details something like this: ` { "ei": 121966308, "bsdt": 1644103800000, "bst": "00:30", "bedt": 1644105900000, "len": 35, "et": "Quatsch Comedy Club", "ec": "Show", "ish": true, "cop": "D", "yop": 2022, "fsk": "ab 12 Jahren", "epit": "Staffel 5, Episode 2", "sn": "5", "en": "2", "pu": "/static/img/program_guide/29122_sea_s.jpg" }`
> 
> **bsdt**/**bedt** are the start/end timestamps **et** is the title **ec** is the category **epit** is the episode description **sn**/**en** are the season/episode numbers (if given)
> 
> **Channel ID List** 116 | 13th Street HD 690 | Beate Uhse HD 761 | Boomerang 95 | Cartoon Network 99 | Classica 451 | Crime + Investigation 659 | DAZN 1 HD 900 | DAZN 2 HD 83 | Discovery HD 117 | E! Entertainm. HD 596 | Eurosport 1 HD 161 | Eurosport 2 HD 163 | Eurosport360HD 1 164 | Eurosport360HD 2 165 | Eurosport360HD 3 166 | Eurosport360HD 4 167 | Eurosport360HD 5 168 | Eurosport360HD 6 169 | Eurosport360HD 7 170 | Eurosport360HD 8 171 | Eurosport360HD 9 72 | Heimatkanal 86 | HISTORY Channel HD 452 | Jukebox 96 | Junior 70 | Kinowelt TV 52 | Motorvision TV 81 | NatGeo HD 88 | NatGeo Wild HD 783 | Nick.Jr. 798 | Nicktoons 16 | Romance TV 2 | Sky Atlantic HD 59 | Sky Cinema Action 60 | Sky Cinema Action HD 790 | Sky Cinema Best Of 792 | Sky Cinema Best Of HD 794 | Sky Cinema Classics 532 | Sky Cinema Family 533 | Sky Cinema Family HD 793 | Sky Cinema Fun 787 | Sky Cinema Premieren 789 | Sky Cinema Premieren +24 791 | Sky Cinema Premieren +24 HD 788 | Sky Cinema Premieren HD 890 | Sky Cinema Special HD 784 | Sky Cinema Thriller HD 854 | Sky Comedy HD 855 | Sky Crime HD 876 | Sky Documentaries HD 753 | Sky Krimi HD 875 | Sky Nature HD 535 | Sky One HD 888 | Sky Replay HD 149 | Sky Sport  1 158 | Sky Sport  10 159 | Sky Sport  11 150 | Sky Sport  2 151 | Sky Sport  3 152 | Sky Sport  4 153 | Sky Sport  5 154 | Sky Sport  6 155 | Sky Sport  7 156 | Sky Sport  8 157 | Sky Sport  9 128 | Sky Sport 1 HD 137 | Sky Sport 10 HD 138 | Sky Sport 11 HD 129 | Sky Sport 2 HD 130 | Sky Sport 3 HD 131 | Sky Sport 4 HD 132 | Sky Sport 5 HD 133 | Sky Sport 6 HD 134 | Sky Sport 7 HD 135 | Sky Sport 8 HD 136 | Sky Sport 9 HD 492 | Sky Sport Austria 1 HD 729 | Sky Sport Austria 2 HD 730 | Sky Sport Austria 3 HD 898 | Sky Sport Austria 4 HD 883 | Sky Sport Austria 5 HD 884 | Sky Sport Austria 6 HD 885 | Sky Sport Austria 7 HD 139 | Sky Sport Bundesliga 1 118 | Sky Sport Bundesliga 1 HD 148 | Sky Sport Bundesliga 10 127 | Sky Sport Bundesliga 10 HD 140 | Sky Sport Bundesliga 2 119 | Sky Sport Bundesliga 2 HD 141 | Sky Sport Bundesliga 3 120 | Sky Sport Bundesliga 3 HD 142 | Sky Sport Bundesliga 4 121 | Sky Sport Bundesliga 4 HD 143 | Sky Sport Bundesliga 5 122 | Sky Sport Bundesliga 5 HD 144 | Sky Sport Bundesliga 6 123 | Sky Sport Bundesliga 6 HD 145 | Sky Sport Bundesliga 7 124 | Sky Sport Bundesliga 7 HD 146 | Sky Sport Bundesliga 8 125 | Sky Sport Bundesliga 8 HD 147 | Sky Sport Bundesliga 9 126 | Sky Sport Bundesliga 9 HD 531 | Sky Sport Bundesliga UHD 853 | Sky Sport F1 HD 17 | Sky Sport News HD 526 | Sky Sport UHD 84 | Spiegel Geschichte 388 | Spiegel Geschichte HD 658 | Spiegel TV Wissen 114 | SPORTDIGITAL FUSSBALL HD 115 | SYFY HD 172 | Universal TV HD 674 | Warner TV Comedy 522 | Warner TV Comedy HD 762 | Warner TV Film 689 | Warner TV Film HD 6 | Warner TV Serie HD

Please @freearhey  Please add them or add this EPG sourcing for Germany 🇩🇪
Of course when you have some time for it
Many thanks for your efforts 🙏🏾

**Comment by RevGear** [comment]
> @RevGear The scripts for all sites are in the [/sites](https://github.com/iptv-org/epg/tree/master/sites) folder.

@freearhey  I know where the scripts are. The problem is that I'm not  proficient enough in javascript workflows to be able to write one. If you or someone else can create the script with a couple of channels I don't mind spending time adding the remaining channels.

**Comment by Talon555** [comment]
> Hello Here Some German EPG Source with all German channels Here the URLs
> 
> Germany
> 
> https://www.sky.de/tvguide-7599 https://web.magentatv.de/tv-programm https://www.horizon.tv/de_de/tv/tv-programm.html
> 
> Austria
> 
> https://www.magentatv.at/de/tv/tv-guide.html

These EPG Germany 🇩🇪 sourcing provide all EPG German channels 🙏🏾

**Comment by Talon555** [comment]
Hi Guys,
I hope that one these complete EPG sourcing for GERMANY will add very soon
Please

**Comment by freearhey** [comment]
The [horizon.tv](https://www.horizon.tv/de_de/tv/tv-programm.html) guide is now available here:

```
https://iptv-org.github.io/epg/guides/de/horizon.tv.epg.xml
```

Thanks to @RevGear a parser for [sky.de](https://www.sky.de/tvguide-7599) was also added to the repository, but unfortunately at the moment the server returns only a 403 error ((https://github.com/iptv-org/epg/runs/5435899744?check_suite_focus=true)) so this site had to be disabled.

Parser for [magentatv.de](https://web.magentatv.de/tv-programm) site was also added but we can't use it because for access to the guide it require constantly changing session ID.

**Comment by RevGear** [comment]
@freearhey I had started to look at magentatv.de hadn't got very far when saw you had already done a pull request. I think it is very similar to tvplus.com.tr - same URL and largely the same data format. That does a  call to /EPG/JSON/Authenticate to get an updated cookie. Possibly the same would work with magentatv.de

**Comment by Talon555** [comment]
@freearhey magentatv.de has been well added but the link xml is unavailable...

**Comment by freearhey** [comment]
@Talon555 magentatv.de has been removed from the queue because the current version of the parser is not working as expected. As soon as it is fixed, we will put it back.

**Comment by Talon555** [comment]
> @Talon555 magentatv.de has been removed from the queue because the current version of the parser is not working as expected. As soon as it is fixed, we will put it back.

Just UP the request about magentatv.de xml link if possible

**Comment by wiscel** [comment]
Any news on this? I'd really appreciate a working .xml link for Magentatv
