### ISSUE TITLE
Requesting for South Africa and Nigeria DSTV EPG

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#426]
Hello
Here Some South Africa and Nigeria EPG Source with all their channels
Here the URLs

http://guide.dstv.com/
https://www.dstv.com/en-za/discover/tv-guide/
https://www.dstv.com/en-ng/discover/tv-guide/

Yes, Supporting the projet with some dollars already sent ❤️

**Comment by freearhey** [comment]
Thank you for your support!

**Comment by freearhey** [comment]
The Nigerian guide is already on the list

```
https://iptv-org.github.io/epg/guides/ng/dstv.com.epg.xml
```

The South African guide has been added in #442

**Comment by Talon555** [comment]
its possible to add description program in their EPG for DSTV South Africa and Nigeria PLEASE @freearhey

**Comment by Talon555** [comment]
> its possible to add description program in their EPG for DSTV South Africa and Nigeria PLEASE @freearhey

If it's possible add Description Program for their DStv EPG Nigeria and South Africa

And many thanks for your daily hardworking @freearhey I just send another some dollars THANKS YOU AGAIN

**Comment by freearhey** [comment]
Both guides now include a description of the programs.

```
https://iptv-org.github.io/epg/guides/ng/dstv.com.epg.xml
https://iptv-org.github.io/epg/guides/za/dstv.com.epg.xml
```

**Comment by paul19920801** [comment]
still possible?

**Comment by IamDwag** [comment]
Please I need both the m3u too
