### ISSUE TITLE
Many Channels No Longer Available in State Specific EPG Guides

### ISSUE THREAD

**Issue by chamby90** [iptv-org/epg#437]
Not sure if work is underway for this or not... and also not sure how many examples are needed but thought I would provide a couple examples that I use:
- Indiana Guide - Missing TruReal and Defy (and CBS, Fox, ABC, etc...)
- It also seems all state guides are missing CBS, Fox, ABC, etc..  among many other examples

Let me know if any other specific examples are needed or if this is all just a known thing where channels need to be remapped. thanks,

**Comment by MichaelRPowell** [comment]
I think this issue is related to #403 

It seems it will just take time to remap all the channels.

**Comment by freearhey** [comment]
Closed in favor #403
