### ISSUE TITLE
Requesting for Japanese EPG

### ISSUE THREAD

**Issue by luongz** [iptv-org/epg#438]
Hello there . I'm looking for Japanese EPG . I have some good source here.

https://www.cablegate.tv/pc/epg.php?catvid=OGPZLItd&si=3&type=epg
https://www.tvkingdom.jp/sp/chart/23.action

**Comment by freearhey** [comment]
There is already a Japanese program on the list:

```
https://iptv-org.github.io/epg/guides/jp/tvguide.myjcom.jp.epg.xml
```

**Comment by luongz** [comment]
> There is already a Japanese program on the list:
> 
> ```
> https://iptv-org.github.io/epg/guides/jp/tvguide.myjcom.jp.epg.xml
> ```

Thanks for your information!
