### ISSUE TITLE
requesting for israeli epg 

### ISSUE THREAD

**Issue by hemzaberkane** [iptv-org/epg#448]
kan11 " need vpn in some countries "
https://www.kan.org.il/tv-guide/#stations_kan11
other link
https://www.isramedia.net/%D7%9C%D7%95%D7%97-%D7%A9%D7%99%D7%93%D7%95%D7%A8%D7%99%D7%9D/1/%D7%A2%D7%A8%D7%95%D7%A5-11-%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99
makan33
https://www.makan.org.il/tv-guide/#stations_kan33
other link
https://www.isramedia.net/%D7%9C%D7%95%D7%97-%D7%A9%D7%99%D7%93%D7%95%D7%A8%D7%99%D7%9D/5628/%D7%A2%D7%A8%D7%95%D7%A5-33-%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99
kan 23
https://www.kankids.org.il/tv-guide/
other link
https://www.isramedia.net/%D7%9C%D7%95%D7%97-%D7%A9%D7%99%D7%93%D7%95%D7%A8%D7%99%D7%9D/326/%D7%97%D7%99%D7%A0%D7%95%D7%9B%D7%99%D7%AA-23-%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99
reshet 13
https://13tv.co.il/tv-guide/
other link
https://www.isramedia.net/%D7%9C%D7%95%D7%97-%D7%A9%D7%99%D7%93%D7%95%D7%A8%D7%99%D7%9D/13/%D7%A2%D7%A8%D7%95%D7%A5-13-%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99
keshet 12
https://www.mako.co.il/tv?partner=SecondNav
other link 
https://www.isramedia.net/%D7%9C%D7%95%D7%97-%D7%A9%D7%99%D7%93%D7%95%D7%A8%D7%99%D7%9D/12/%D7%A2%D7%A8%D7%95%D7%A5-12-%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99
i24 arabic
https://www.i24news.tv/ar/%D8%AC%D8%AF%D8%A7%D9%88%D9%84/%D8%A7%D9%84%D8%A3%D8%AD%D8%AF
i24 french
https://www.i24news.tv/fr/grille-des-programmes/dimanche
i24 english
https://www.i24news.tv/en/schedules/sunday
channel 9
https://www.9tv.co.il/BroadcastSchedule
music 24
https://www.isramedia.net/%D7%9C%D7%95%D7%97-%D7%A9%D7%99%D7%93%D7%95%D7%A8%D7%99%D7%9D/24/%D7%A2%D7%A8%D7%95%D7%A5-24-%D7%91%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99
now 14
https://www.isramedia.net/%D7%9C%D7%95%D7%97-%D7%A9%D7%99%D7%93%D7%95%D7%A8%D7%99%D7%9D/14/%D7%A2%D7%A8%D7%95%D7%A5-14-%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99
knesset tv
https://www.isramedia.net/%D7%9C%D7%95%D7%97-%D7%A9%D7%99%D7%93%D7%95%D7%A8%D7%99%D7%9D/4/%D7%A2%D7%A8%D7%95%D7%A5-%D7%94%D7%9B%D7%A0%D7%A1%D7%AA-%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99

**Comment by freearhey** [comment]
kan11, makan33 and kan 23

```
https://iptv-org.github.io/epg/guides/il/kan.org.il.epg.xml
```

keshet 12

```
https://iptv-org.github.io/epg/guides/il/mako.co.il.epg.xml
```

i24 arabic, i24 french and i24 english

```
https://iptv-org.github.io/epg/guides/il/i24news.tv.epg.xml
```

channel 9

```
https://iptv-org.github.io/epg/guides/il/9tv.co.il.epg.xml
```

https://13tv.co.il/tv-guide/ - displays the same guide for any day

https://www.isramedia.net/ - cannot be added to the list due to geo-blocking
