### ISSUE TITLE
elcinema.com and osn.com

### ISSUE THREAD

**Issue by RevGear** [iptv-org/epg#456]
Has something happened to the elcinema.com and osn.com feeds. Both no longer show on the index page but are shown in the channel list page.

It appears the xml files are being updated albeit not correctly. Both the Arabic and English versions contain the same Arabic output.
eg
https://iptv-org.github.io/epg/guides/eg-en/elcinema.com.epg.xml
https://iptv-org.github.io/epg/guides/eg-ar/elcinema.com.epg.xml

https://iptv-org.github.io/epg/guides/ae-en/osn.com.epg.xml
https://iptv-org.github.io/epg/guides/ae-ar/osn.com.epg.xml

The osn.com was working correctly when it was split into 2 languages a couple of weeks ago

**Comment by freearhey** [comment]
Is everything working properly now?

**Comment by RevGear** [comment]
Looks good, thanks
