### ISSUE TITLE
Wrong timezone in United Kingdom EPG

### ISSUE THREAD

**Issue by willnwhite** [iptv-org/epg#46]
For example, from today's EPG:
```xml
<programme start="20210822134000 +0000" stop="20210822155000 +0000" channel="ITV.uk"><title lang="en">Goldfinger</title></programme>
```
This programme actually started at 13:40 +0100, not 13:40 +0000.

**Comment by SmokeyBR** [comment]
i think all channels are +0000 its prob meant to be time shifted on whatever app u use to the right timezone, problem is some apps do not have the timezone offset for epg xml i myself encounter this problem. correct me if im wrong.

**Comment by freearhey** [comment]
In this case, the problem was really that the time was saved without taking into account the timezone.

**Comment by SmokeyBR** [comment]
could you take a look on the brazilian epg it seems to be off 3 hours (utc -3) also it seems to be it using same sources as some latin americas channels like argentina and chile which im sure are not same timezone

**Comment by SmokeyBR** [comment]
ive tried the lastest changes and it is still giving me wrong times
my understanding is very limited what i did that started giving me correct results was changing this line 
`return `https://mi.tv/${country}/async/channel/${id}/${date.format('YYYY-MM-DD')}/180``
to
`return `https://mi.tv/${country}/async/channel/${id}/${date.format('YYYY-MM-DD')}/-180``
