### ISSUE TITLE
The CCTV EPG is missing..

### ISSUE THREAD

**Issue by rxrw** [iptv-org/epg#470]
Thanks for your project first!

 I used iptv and epg on emby very well before. Recently I found the epg of china's channels is missing.. 

I'm wondering what happened and is it possible to recover them again? If you need some help, I can try my best on it.

Thanks for this awesome project again!

**Comment by Talon555** [comment]
one Chinese EPG sourcing :

http://epg.i-cable.com/

**Comment by rxrw** [comment]
> one Chinese EPG sourcing :
> 
> http://epg.i-cable.com/

Those are channels for Hong Kong, not China mainland...

**Comment by freearhey** [comment]
@rxrw Have you tried this one?

```
https://iptv-org.github.io/epg/guides/cn/tv.cctv.com.epg.xml
```

**Comment by rxrw** [comment]
It appeared after this issue, but only cctv for one day.. the previous version of this has about all programs for a week in China mainland😅

发自我的iPhone
