### ISSUE TITLE
Suggestion: High Quality TV Channel Logo's

### ISSUE THREAD

**Issue by orhtun01** [iptv-org/epg#479]
As a suggestion ... Tapiosin has a great free resource of very high quality TV Channel logo's. Maybe we can use these logo's instead of the default ones provided by the source (these are generally of poor quality). I guess it is a simple replacement of the logo url within the xml files based on channel id.
See: github.com/tapiosinn/tv-logos

**Comment by Talon555** [comment]
Good suggestion but in general the logo are by default provided by EPG sourcing. Technically it's complicated I think. Anyway I am very happy for sharing because I could use it as with IPTV player

**Comment by freearhey** [comment]
Now all channel info (including logo) are loaded from a separate repository: [iptv-org/api](https://github.com/iptv-org/api). So if you want to update links to any logos you can do it there.
