### ISSUE TITLE
Swedish channels without programs today, the first ones are tomorrow

### ISSUE THREAD

**Issue by knallpulver71** [iptv-org/epg#481]
Hi, tonight I noticed that some Swedish channels don't have any programs for today (feb 1st) - examples: SVT2 and TV4. The first programs for those channels are tomorrow (feb 2nd). Is this normal?

**Comment by freearhey** [comment]
Does the problem still exist?

**Comment by knallpulver71** [comment]
The problem existed on the evening (CET) of the 1st of february, but the same time on the 2nd, it seems that all channels had programming for the current date.

**Comment by freearhey** [comment]
Okay, then I'll close this issue for now. But if the program disappears again, I will reopen it.
