### ISSUE TITLE
Broken EPG 

### ISSUE THREAD

**Issue by Shifty0wl** [iptv-org/epg#485]
Canada epg missing most channels, us has tons of channels with wrong info and now UK is down

**Comment by freearhey** [comment]
The UK guide should be working by now. What do you mean by wrong information in the US guide? The Canadian channels are missing for the reason stated here: https://github.com/iptv-org/epg/issues/403#issuecomment-1014861969

**Comment by Shifty0wl** [comment]
Like west EPG is actually east or that it's a completely different language or completely wrong info. Many channels are like this. Most of the US EPG is just a mess

**Comment by freearhey** [comment]
I'm sorry, but I can't help you without a list of specific channels. But if you want you can fix it yourself just by editing the channel list: https://github.com/iptv-org/epg/blob/master/sites/tvtv.us/tvtv.us_us.channels.xml
