### ISSUE TITLE
Please add Philippines EPG

### ISSUE THREAD

**Issue by mg8297819** [iptv-org/epg#487]
can you add epg from these sites
Thanks

https://skyepg.mysky.com.ph/
https://www.clickthecity.com/tv-networks/

**Comment by freearhey** [comment]
The guide from `clickthecity.com` is available at:

```
https://iptv-org.github.io/epg/guides/ph/clickthecity.com.epg.xml
```

And the guide from https://skyepg.mysky.com.ph/ unfortunately can not be added as it only contains a program for a few hours in advance.
