### ISSUE TITLE
DSTV m3u

### ISSUE THREAD

**Issue by GPGuy** [iptv-org/epg#488]
Hi, please assist, I’ve tried loading the DSTV playlist from GitHub on OTT but it says file not supported, please help me with the correct playlist, thank you

**Comment by Talon555** [comment]
> Hi, please assist, I’ve tried loading the DSTV playlist from GitHub on OTT but it says file not supported, please help me with the correct playlist, thank you

Which DSTV Package do you use ? 

South Africa : 
https://iptv-org.github.io/epg/guides/za/dstv.com.epg.xml
Nigeria :  
https://iptv-org.github.io/epg/guides/ng/dstv.com.epg.xml
--

**Comment by GPGuy** [comment]
Thanks it says playlist loaded however it doesn’t play, see pic
![89A2158C-8F71-4E48-A463-E71DDF44DBAB](https://user-images.githubusercontent.com/99087253/152656358-4fa26dd3-f875-4b87-b234-5ba1532d8d23.jpeg)

**Comment by GPGuy** [comment]
Using the South African one

**Comment by Talon555** [comment]
> Using the South African one, am i doing something wrong

yes you should assign EPG for each channel because channel name here and your playlist channel name dont match....
in depend your iptv player and iptv manager editor for assigning EPG

**Comment by GPGuy** [comment]
Thanks Talon, this is way too technical for me, oh my. I thought just loading the playlist onto the OTT app would give me the DSTV channels😬 how do I do all this😫

**Comment by GPGuy** [comment]
I only need the Supersport channels🥺

**Comment by Talon555** [comment]
> Thanks Talon, this is way too technical for me, oh my. I thought just loading the playlist onto the OTT app would give me the DSTV channels😬 how do I do all this😫

apparently you dont know what you need but your information here its ONLY EPG information and NO STREAMING CHANNELS !!!
