### ISSUE TITLE
UK epg logos

### ISSUE THREAD

**Issue by Brunob2020** [iptv-org/epg#489]
Hi the logos where perfect last week.. these last few days some channels have either got no
Logo like sky showcase hd, some have lost the original good quality like bbc one hd and some have changed to the old logos such as some sky sports channels.

**Comment by freearhey** [comment]
All logos are now loaded from a separate repository: [iptv-org/api](https://github.com/iptv-org/api). If you want you can add missing logos by updating this file: https://github.com/iptv-org/api/blob/master/database/channels.csv

**Comment by Brunob2020** [comment]
Ok mate just don't get why they have changed they looked amazing before To be honest
