### ISSUE TITLE
New EPG sources for Hungary

### ISSUE THREAD

**Issue by sirjohn771103** [iptv-org/epg#490]
Hello!

Can you get EPG from these sites?
https://musor.tv/
https://tvepg.eu/hu/hungary

They have more channels.
Thank you.

**Comment by freearhey** [comment]
The guide from `musor.tv` is available at:

```
https://iptv-org.github.io/epg/guides/hu/musor.tv.epg.xml
```

https://tvepg.eu/hu/hungary - cannot be added to the list because of [CAPTCHA](https://en.wikipedia.org/wiki/CAPTCHA)
