### ISSUE TITLE
albepg.com

### ISSUE THREAD

**Issue by albepg** [iptv-org/epg#5]
Albepg non è per l'uso libero. Vi consiglio di togliere dal iptv-org. 
Posso farvi redirect a un contenuto non piacevole in xmltv! Grazie in anticipo.

**Comment by freearhey** [comment]
If you own the rights to any of the data in this guide, please send us the DMCA notice link and we'll delete everything within one business day.

**Comment by albepg** [comment]
Grazie lo stesso. Sei stato avvisato.
