### ISSUE TITLE
Help required with meo.pt channels

### ISSUE THREAD

**Issue by RevGear** [iptv-org/epg#515]
I'm trying to update the channel list for meo.pt but there are a few channels that I don't recognise and can't find in the database.

num | site_id | channel
-- | -- | --
10 | GLOB | GLOBO
110 | ADVNCE | ADVNCE
129 | SMAISHD | S+
139 | ALMALUS | ALMA LUSA
142 | BOMSOM | BOMSOM TV
183 | TVVERHD | TV Verdade
263 | ARD | ARD
283 | UKR1 | Ukraine 1
284 | UKR2 | Ukraine 2
285 | NLOTV2 | NLO TV2
289 | RYBALKA | Rybalka TV
663 | LVTV | LOCALVISÃO   TV

Can anyone identify these, and supply the correct name / TVG ID? The num shown is the MEO channel number.

**Comment by freearhey** [comment]
You can add missing channels here: https://github.com/iptv-org/database/blob/master/data/channels.csv 

The main thing is to make sure that the channel has the right name (in most cases the name from [lyngsat](https://www.lyngsat.com/search.html) or [wikipedia](https://en.wikipedia.org/wiki/TV_Globo) will work). And the id is formed by removing spaces and adding a source country code with a dot.

In this case it would be:

num | site_id | channel | xmltv_id
-- | -- | -- | --
10 | GLOB | GLOBO | RedeGlobo.br
110 | ADVNCE | ADVNCE | ADVNCE.pt
129 | SMAISHD | S+ | SPlus.pt
139 | ALMALUS | ALMA LUSA | AlmaLusa.pt
142 | BOMSOM | BOMSOM TV | BomSomTV.ao
183 | TVVERHD | TV Verdade | TVVerdade.br
263 | ARD | ARD | DasErste.de
283 | UKR1 | Ukraine 1 | Ukraine1.ua
284 | UKR2 | Ukraine 2 | Ukraine2.ua
285 | NLOTV2 | NLO TV2 | NLOTV2.ua
289 | RYBALKA | Rybalka TV | RybalkaTelekanal.ua
663 | LVTV | LOCALVISÃO   TV | LocalvisaoTV.pt

After the channel appears in the database, this check #513 can be run again.

**Comment by RevGear** [comment]
Thanks, I'll update them later

**Comment by spotanjo3** [comment]
I am looking for an accurate MEO.PT canals for an example:

I found that Meo.PT rename a few:

NATIONAL GEOGRAPHIC WILD HD (regular) - Nat_Geo_Wild_HD (meo named it)

RTP ACORES HD - RTP_AC_HD (meo named it.. Yes they didnt used full ACORES but instead RTP_AC_HD)

So I want to find meo'pt's accurate canals like those. Do you know ?

**Comment by spotanjo3** [comment]
Nobody knows for sure?
