### ISSUE TITLE
Directv US epg no information 

### ISSUE THREAD

**Issue by dcole819** [iptv-org/epg#519]
Is the US directv epg working? I’ve been getting no information on epg

**Comment by freearhey** [comment]
At the moment the guide is working fine.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/7253922/154402344-48deab5b-9620-48ef-8ec7-fc4f50b58b88.png">

**Comment by dcole819** [comment]
What app are u using? That’s a nice guide

**Comment by freearhey** [comment]
GSE SMART IPTV LITE: https://apps.apple.com/us/app/gse-smart-iptv-lite/id1293450217
