### ISSUE TITLE
Indonesia EPG

### ISSUE THREAD

**Issue by gambitx20** [iptv-org/epg#522]
Hi, 

Can you add the following channels on the Indonesia (MNC Vision) EPG please?

- Galaxy
- Galaxy Premium
- imc
- cinemaworld 

Thank you!

**Comment by F640** [comment]
Some other channels on MNCVision not in your EPG
- MNC Sports 2
- MNC Sports 3
- SPOTV
- SPOTV 2
- BeIN Sports 3
- FOX News Channel
- Al Quran Al Kareem

~~And remove these channels (no longer in their schedule)~~
- ~~Star Chinese Movies~~
- ~~BeIN Sports 2~~

**Comment by ientau** [comment]
Hi,

Can you add the following channels on the Indonesia (MNC Vision) EPG please?

DAAI TV
RTV
K PLUS
My Cinema Asia

**Comment by freearhey** [comment]
@ientau It would be better to create a separate [issue](https://github.com/iptv-org/epg/issues/new?assignees=&labels=%F0%9F%97%93+epg+request&template=----epg-request.yml) so that your request does not get lost.
