### ISSUE TITLE
EPG  Portugal 100 ? How is that possible ? 

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#531]
<!DOCTYPE html>

🇵🇹 Portugal | 110 | https://iptv-org.github.io/epg/guides/pt/meo.pt.epg.xml
-- | -- | --

<br class="Apple-interchange-newline">

Portugal channel is only 55 but EPG has 100 ? Confused.

**Comment by freearhey** [comment]
The channel list is taken from the [meo.pt](https://www.meo.pt/tv/canais-programacao/guia-tv) website and does not only contain Portuguese channels.
