### ISSUE TITLE
Not able to commit, suggestion to add BR channels mi.tv

### ISSUE THREAD

**Issue by kimbrasil** [iptv-org/epg#537]
in the file epg/sites/mi.tv/mi.tv_br.channels.xml

add to lines
    `<channel lang="pt" xmltv_id="ESPN3Brasil.us" site_id="br#espn-plus">ESPN 3 Brasil</channel>`
    `<channel lang="pt" xmltv_id="SmithsonianBrasil.us" site_id="br#smithsonian">Smithsonian Brasil</channel>`

**Comment by freearhey** [comment]
Both channels have the wrong `xmltv_id`.

The correct IDs can be found here: https://iptv-org.github.io/

**Comment by freearhey** [comment]
`ESPN 3 Brazil` added via https://github.com/iptv-org/epg/commit/e54dab83a3b1894f21216487186428af7d3e2399
`Smithsonian Brasil` I could not find on the site (there is no more page with id `smithsonian`)

**Comment by kimbrasil** [comment]
> `ESPN 3 Brazil` added via [e54dab8](https://github.com/iptv-org/epg/commit/e54dab83a3b1894f21216487186428af7d3e2399) `Smithsonian Brasil` I could not find on the site (there is no more page with id `smithsonian`)

This is the Smithsonian Brasil guide in mi.tv https://mi.tv/br/canais/canal-smithsonian-hd
