### ISSUE TITLE
English version of mncvision.id

### ISSUE THREAD

**Issue by F640** [iptv-org/epg#544]
Hello, i have just found that mncvision.id has english version of it in language switcher.

**Comment by freearhey** [comment]
But this switch has no effect on the program language.

**Comment by F640** [comment]
True, but the synopsis on some channels is.

Pada tanggal Sen, 28 Feb 2022 04.32, Aleksandr Statciuk <
***@***.***> menulis:

**Comment by freearhey** [comment]
Could you be more specific about which channels we are talking about?

**Comment by RevGear** [comment]
Language switcher only effects the program description. The majority of program titles are already in English.
See AXM (Channel 154) as an example.

I assume it is using cookies to control this behaviour as the URL used to get the description is the same regardless of language.

**Comment by freearhey** [comment]
The English version has been added to the list. It is available at:

```
https://iptv-org.github.io/epg/guides/id-en/mncvision.id.epg.xml
```

and the Indonesian version at:

```
https://iptv-org.github.io/epg/guides/id-id/mncvision.id.epg.xml
```
