### ISSUE TITLE
KODI not loading EPG data.

### ISSUE THREAD

**Issue by Prajwal-Koirala** [iptv-org/epg#550]
Hello,
I am using KODI as a client and using the simple IPTV plugin and I have the global list loading but EPG data isn't being loaded, tested this on multiple devices, and it's the same issue.
- prajwal

**Comment by LaneSh4d0w** [comment]
Please precise "global". The full EPG file doesn't exist since some time ago.

**Comment by Prajwal-Koirala** [comment]
> Please precise "global". The full EPG file doesn't exist since it was removed some time ago.

How would I get the data if I am using the main list?

**Comment by LaneSh4d0w** [comment]
> > Please precise "global". The full EPG file doesn't exist since it was removed some time ago.
> 
> How would I get the data if I am using the main list? 

You don't. If it doesn't exist, it doesn't get any data.

However if you use only a specific set of channel, just look at the README to get the EPG link dedicated to your set.

**Comment by Prajwal-Koirala** [comment]
> > > Please precise "global". The full EPG file doesn't exist since it was removed some time ago.
> > 
> > 
> > How would I get the data if I am using the main list?
> 
> You don't. If it doesn't exist, it doesn't get any data.
> 
> However if you use only a specific set of channel, just look at the README to get the EPG link dedicated to your set.

Why was it removed?

Also any plans to create a new global list?

**Comment by LaneSh4d0w** [comment]
> > > > Please precise "global". The full EPG file doesn't exist since it was removed some time ago.
> > > 
> > > 
> > > How would I get the data if I am using the main list?
> > 
> > 
> > You don't. If it doesn't exist, it doesn't get any data.
> > However if you use only a specific set of channel, just look at the README to get the EPG link dedicated to your set.
> 
> Why was it removed?
> 
> Also any plans to create a new global list?

Many difficulties due to certain sources having the same channels (so it's basically a choice), EPG size being too big.

No plans are known as of today concerning a global list creation.

**Comment by freearhey** [comment]
Closed in favor #310
