### ISSUE TITLE
Italian EPG(it/guidatv.sky.it.epg.xml) is missing massive chunks of data for the second time this week.

### ISSUE THREAD

**Issue by Nostradamus1973** [iptv-org/epg#559]
Good Morning,

The Italian EPG(it/guidatv.sky.it.epg.xml) is severely incomplete for the second time in just a few days.+

Is this normal and should be expected?

Thank y ou

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/b63686e086da5f1faec225125390c963bafb7eb6
