### ISSUE TITLE
Italian Channels(it/guidatv.sky.it.epg.xml) IT Science Discovery is not mapped.

### ISSUE THREAD

**Issue by Nostradamus1973** [iptv-org/epg#564]
Good morning Everyone,

It looks like the Italian EPG is having issues once again, this is starting to become a daily venture with this EPG. LOL
Discovery Science(IT) isn't mapped at all, and the guide is only showing about 24 hours of data.

Is this EPG becoming deprecated from lack of support? 

I asked yesterday if this is normal and whether or not I should expect this sort of thing on a regular basis and I received NO RESPONSE; I know that we depend on volunteers to do things that can be under-appreciated at times by others, that is NOT my point of view; I'm grateful for everything that's done here, I would just like to know what to expect.
My questions are:
What sort of EGP time-frame can be expected? 14 hours? 24hours? One week?
How often does the EPG go down? Is it daily? bi-weekly? Or weekly?
Are you looking for assistance in maintaining this EPG? I may be able to help or know someone who will.
I'm only asking because I would like to know what to expect and see if I can help as well.
Thank you for your time and patience.
-Pete

**Comment by freearhey** [comment]
- The program is loaded daily for 2 days ahead.
- According to the [logs](https://github.com/iptv-org/epg/actions/workflows/guidatv.sky.it.yml) there were no errors with the loading guide from `guidatv.sky.it` during the last month. But if you find some let us know and either I or someone else will try to fix it.
- As @LaneSh4d0w said, any help is welcome.
