### ISSUE TITLE
TVE channel EPG of Brazil TV guide is loading the information of TVE channel from Spain

### ISSUE THREAD

**Issue by dgimortal** [iptv-org/epg#566]
Hello, I noticed a bug when loading TVE channel information in the guide for Brazil (https://iptv-org.github.io/epg/guides/br/mi.tv.epg.xml).  It is loading the information from the TVE channel in Spain, the two have similar names and I think I know why the error is happening.  The site "mi.tv" which is the source of epg information, I assigned the term "TVE" in the URI of its site [https://mi.tv/br/canais/tve](url) to the Spanish channel, and in the In the case of the Brazilian channel of the same name, the site uses the expression "TVE-1" [https://mi.tv/br/canais/tve-1](url) in its URI.  As the TVG-ID of TVE do Brasil in the xml file points to "TVE.br", it ends up erroneously getting the information from TVE of Spain.  I believe replacing the TVG-ID to "TVE-1.br" in the xml file should solve the problem. @freearhey @m-p-3 @amynkvirani @Dum4G @aarubui

**Comment by freearhey** [comment]
Thank you for pointing out this error!

Fixed via https://github.com/iptv-org/epg/commit/b0a8002b78227dae385483ff6eaa7faec6341ca1

**Comment by felipeurashima** [comment]
Put HBO plus in the epg please, thanks.
