### ISSUE TITLE
Mediaklikk.hu

### ISSUE THREAD

**Issue by sirjohn771103** [iptv-org/epg#590]
Hello, please add mediaklikk.hu EPG to Hungary.
I would like M3 channel from here. Thank you.
https://mediaklikk.hu/musorujsag/
http://www.webgrabplus.com/sites/default/files/download/ini/info/zip/Hungary_mediaklikk.hu..zip

Thank you.

**Comment by freearhey** [comment]
Added.

```
https://iptv-org.github.io/epg/guides/hu/mediaklikk.hu.epg.xml
```

**Comment by sirjohn771103** [comment]
Thank you :)
