### ISSUE TITLE
Hundreds of tvtv.ca Channels Still Missing Since API Change

### ISSUE THREAD

**Issue by magic-ian** [iptv-org/epg#604]
There used to be a fairly thorough, but incomplete list of 710 total Canadian channels ([national & provincial](https://web.archive.org/web/20220107182011/https://github.com/iptv-org/epg)) pulling from tvtv.ca available through the EPG here. Ever since the tvtv API changed, only 89 have managed to be restored.

A previous attempt to track this separately was opened ([#439](https://github.com/iptv-org/epg/issues/439)) by [Shifty0wl](https://github.com/Shifty0wl), but it was marked as a duplicate of [#403](https://github.com/iptv-org/epg/issues/403#issuecomment-1063567841) so I & others thought it included the scope of [Canadian tvtv content](https://tvtv.ca/). Since [#403](https://github.com/iptv-org/epg/issues/403#issuecomment-1063567841) was closed without a resolution to the Canadian content, I have opened an issue to track them separately.

**Comment by MichaelRPowell** [comment]
Well, I have a question. Should those 710 channels be added back or should there be separate files for different regions/provinces/states like before?

I can see the benefit of splitting them. It is less data to download and process. This means shorter delays for updates.

On the other hand, a single file/source is the limit for most TV clients. In those cases, a giant combined EPG would be better.

**Comment by magic-ian** [comment]
I think if it can't be justified for the US channels, then it can't for the Canadian ones. That being said, here are the reasons for I can think of:
- It is nice to be able to have a variety of ways to have granular control to craft the experience you want, similar to the various IPTV playlists which provide both a _consolidated_ version, and various ways to do _smaller subsets_ (genre, language, region, etc); similarly this requires duplication of efforts to achieve
- Even when this is not provided and when programs don't have native functionality for multiple EPGs, sometimes there are ways to achieve this, like with [IPTV Merge for Kodi](https://github.com/playonmonkey/service.iptv.merge)
- For those that don't have fast speeds and/or have data-limit caps, it can make it unfeasible to have one unified file

**Comment by MichaelRPowell** [comment]
> If a consolidated version is not available and when programs don't have native functionality for multiple EPGs, sometimes there are ways to achieve this, like with [IPTV Merge for Kodi](https://github.com/playonmonkey/service.iptv.merge)

My issue there is not everyone is on Kodi. For other devices, there are services online that allow you to merge multiple EPGs to create your own. Those are paid services normally.

> For those that don't have fast speeds and/or have data-limit caps (e.g countryside, or mobile user), it can make it unfeasible to have one unified file

I would argue it is rarely a necessity to update your EPG more than once daily. I would be curious what the file size difference is between those files, combined versus split. If we are talking 50 megabytes then for most users that shouldn't make or break their data cap. This is definitely true of users that are using IPTV services which can easily use hundreds of megabytes an hour. I would assume for anyone using IPTV services the data usage difference would be minimal.

I personally think generating three levels of EPGs would be ideal, and leave it to users to fine tune from there.

1. National Channels by Service Provider (US DirectTV / US Spectrum) - US has four right now
2. Regional Channels (state/province/region) - This would be 50 files again for the US
3. Combined National Channels with Regional Channels for a Country - Ideally one file of all channels within a country if this does not generate conflicts *

_* I have never done great research, but I guess it is possible that different providers could have different content on the same national channels possibly, which would cause a conflict of duplicate names in the EPG and trying to decipher which data is correct._

I have not dived into the code to know the difficulty this kind of change would require, or if @freearhey would entertain the idea. The benefit for users needing data, for whatever their purpose is, would be that they could grab just the EPG based on their exact needs, or combine files as needed while minimizing data usage. The last option would, one combined file of everything in a country, which would be for people without data restriction/cap concerns not wanting to manually add 54 different EPGs for the United States as an example.

I am also curious what other users think about.

**Comment by MichaelRPowell** [comment]
#625 and #632 seem to be related to this discussion.

**Comment by magic-ian** [comment]
I think in the meantime, it may be best just to do the same as what was done with the US channels, and then discuss having different categories, states, etc under a different tracking #.

**Comment by freearhey** [comment]
Closing this for now.

If any channel you need is still not in the guide feel free to add it to the list: https://github.com/iptv-org/epg/blob/master/sites/tvtv.us/tvtv.us_ca.channels.xml
