### ISSUE TITLE
mncvision.id not updating

### ISSUE THREAD

**Issue by mishima1992** [iptv-org/epg#605]
[it's](https://iptv-org.github.io/epg/guides/id/mncvision.id.epg.xml) not update since last night

**Comment by freearhey** [comment]
The guide from mncvision.id has been split into two versions:

English

```
https://iptv-org.github.io/epg/guides/id-en/mncvision.id.epg.xml
```

Indonesian

```
https://iptv-org.github.io/epg/guides/id-id/mncvision.id.epg.xml
```

**Comment by mishima1992** [comment]
> The guide from mncvision.id has been split into two versions:
> 
> English
> 
> ```
> https://iptv-org.github.io/epg/guides/id-en/mncvision.id.epg.xml
> ```
> 
> Indonesian
> 
> ```
> https://iptv-org.github.io/epg/guides/id-id/mncvision.id.epg.xml
> ```

it's not updating again

**Comment by freearhey** [comment]
I'm looking into it
