### ISSUE TITLE
[Bug?]Kodi Can't Load EPG

### ISSUE THREAD

**Issue by Central302** [iptv-org/epg#619]
Using tvtv.us EPG, and Happning Only Morning. Error Happend From Decades Channel.
No Issue in GSE Smart TV.

Error Log : https://ghostbin.com/PK9Ib

**Comment by freearhey** [comment]
I have the guide working in both GSE Smart TV and Kodi.

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/7253922/158037703-aa5c5a0e-a41f-4e37-a629-87c08ff2bc95.png">
