### ISSUE TITLE
Can't Load EPG For Portugal and United States

### ISSUE THREAD

**Issue by spotanjo3** [iptv-org/epg#620]
I am using TELEVIZO. EPG unavailable for both. I don't understand.

**Comment by freearhey** [comment]
Which exact link to the EPG did you use?

**Comment by streamas** [comment]
Из трхё  ссылок на EPG USA работает всего одна! В остальных двух при проверке  ошибка  404?

https://iptv-org.github.io/epg/guides/us/directv.com.epg.xml	directv.com  404?

	https://iptv-org.github.io/epg/guides/us/tvguide.com.epg.xml	tvguide.com  404?
_____________
https://iptv-org.github.io/epg/guides/us/gatotv.com.epg.xml

**Comment by PopeyeTheSai10r** [comment]
> I am using TELEVIZO. EPG unavailable for both. I don't understand.

Are you still having issues with this?

**Comment by spotanjo3** [comment]
I tried but seems not working properly. Which link is the right one ? And if I edit rename m3u8 file in notepad and it would effect EPG too ? Please response, thanks.

**Comment by PopeyeTheSai10r** [comment]
>I tried but seems not working properly.

You will need to provide more information on what exactly isn't working properly.

> And if I edit rename m3u8 file in notepad and it would effect EPG too ?

Do you mean if you rename the station/channel names? If so, no.
Modifying the m3u8 file doesn't affect the EPG. Those are two different files and both will need to be modified for it to work.
