### ISSUE TITLE
Missing Philadelphia Channels

### ISSUE THREAD

**Issue by FpFan65** [iptv-org/epg#625]
<channel lang="en" xmltv_id="WFPACD1.us" site_id="96657">UniMás (WFPA-CD1) Philadelphia, PA</channel>
<channel lang="en" xmltv_id="WFPACD2.us" site_id="96658">GetTV (WFPA-CD2) Philadelphia, PA</channel>
<channel lang="en" xmltv_id="WFPACD3.us" site_id="107435">Quest (WFPA-CD3) Philadelphia, PA</channel>
<channel lang="en" xmltv_id="WFPACD4.us" site_id="119301">Twist (WFPA-CD4) Philadelphia, PA</channel>
<channel lang="en" xmltv_id="WPSGDT1.us" site_id="34628">CW (WPSG-DT1) Philadelphia, PA</channel>
<channel lang="en" xmltv_id="WPSGDT2.us" site_id="109469">Charge (WPSG-DT2) Philadelphia, PA</channel>
<channel lang="en" xmltv_id="WPSGDT3.us" site_id="109470">Comet (WPSG-DT3) Philadelphia, PA</channel>
<channel lang="en" xmltv_id="WPSGDT4.us" site_id="110654">TBD (WPSG-DT4) Philadelphia, PA</channel>
<channel lang="en" xmltv_id="WPSGDT5.us" site_id="113745">Circle (WPSG-DT5) Philadelphia, PA</channel>
<channel lang="en" xmltv_id="WWSIDT1.us" site_id="32578">Telemundo (WWSI-DT1) Philadelphia, PA</channel>
<channel lang="en" xmltv_id="WWSIDT2.us" site_id="34628">TeleXitos (WWSI-DT2) Philadelphia, PA</channel>

**Comment by Central302** [comment]
OK, I'll Do Later.

**Comment by Central302** [comment]
(Help) EPG of WFPA and WWSI Missing.

**Comment by Central302** [comment]
[Help Wanted] WFPA-DT2,3,4 is Missing.
