### ISSUE TITLE
[To-Do]Missing channel ID List (tvtvus)

### ISSUE THREAD

**Issue by Central302** [iptv-org/epg#627]
[National Broadcast]
DW English, (Not DW Plus, Full English Version That Available in selected Market OTA).
beIN Sports Xtra en Espanol,
Newsnet (If Possible, Want to Add National Feed [Available in Sling])

[Philadelphia]
WFPA-DT2 (GetTV) - WFPA-DT3 (Quest) - WFPA-DT4 (Twist)  - (Requested at #625)

**Comment by MichaelRPowell** [comment]
> Newsnet (If Posibble)

You'll probably need to identify the specific station:
https://www.yournewsnet.com/story/43547093/where-to-watch-newsnet
