### ISSUE TITLE
[Fatal  Bug?] Deployment Error : Failed Auth

### ISSUE THREAD

**Issue by Central302** [iptv-org/epg#647]
First Self-Launched Download Process. (tvtv.us) - https://github.com/iptv-org/epg/actions/runs/1997667670

fatal: Authentication failed for 'https://github.com/iptv-org/epg.git/'
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/juhi55dla
Reset branch 'github-pages-deploy-action/juhi55dla'
/usr/bin/chmod -R 777 github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌

**Comment by ian10951** [comment]
You could try

change uses: actions/checkout@v2 to uses: actions/checkout@v2.3.4 
or even downgrade to actions/checkout@v1

Worth a try anyway.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/7cef74b5865a0a21d99b3d7bc1d98994619759f6
