### ISSUE TITLE
epg addition request for useetv.com

### ISSUE THREAD

**Issue by baydewey** [iptv-org/epg#657]
[useetv.com_id.channels.xml.txt](https://github.com/iptv-org/epg/files/8314381/useetv.com_id.channels.xml.txt)

**Comment by baydewey** [comment]
[useetv.com_id.channels.xml.txt](https://github.com/iptv-org/epg/files/8315706/useetv.com_id.channels.xml.txt)

Update with logo

**Comment by RyanRiz** [comment]
> [useetv.com_id.channels.xml.txt](https://github.com/iptv-org/epg/files/8315706/useetv.com_id.channels.xml.txt)
> 
> Update with logo

Can you describe how to use it? I'm new at this

**Comment by baydewey** [comment]
just wait admin added epg for useetv.com

**Comment by freearhey** [comment]
maybe I'm missing something, but all I could find on the website was a programme for today and the previous few days

<img width="312" alt="image" src="https://user-images.githubusercontent.com/7253922/167880080-82e4f739-0bbb-4fe0-a2af-b8d8f529c035.png">

**Comment by F640** [comment]
> maybe I'm missing something, but all I could find on the website was a programme for today and the previous few days
> 
> <img alt="image" width="312" src="https://user-images.githubusercontent.com/7253922/167880080-82e4f739-0bbb-4fe0-a2af-b8d8f529c035.png">

True, ~i already know that. It has no next day schedule, only today and past days, and (likely) no exposed API for their schedule, so it's hardcoded in their page.~
I've written that script before this request actually and it should work.
[useetv.com.config.js.txt](https://github.com/iptv-org/epg/files/8675201/useetv.com.config.js.txt)
You might want to adjust its timezone if programme time is incorrect. Its list can be found [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

> just wait admin added epg for useetv.com


I'm not admin here, but we'll see if Admin (repo maintainer) approves this config (script).

**Comment by freearhey** [comment]
> True, i already know that. It has no next day schedule, only today and past days, and (likely) no exposed API for their schedule, so it's hardcoded in their page.

In this case I don't think there's any point in adding a parser for this site to the repository. 

But if in the future someone finds a way to retrieve a programme from this site feel free to make a [pull request](https://github.com/iptv-org/epg/pulls).
