### ISSUE TITLE
Add: CMC TV and CMC USA

### ISSUE THREAD

**Issue by rrjanbiah** [iptv-org/epg#659]
Both of them seems to be available in:

https://www.ontvtonight.com/guide/listings/channel/1700812761/k16iw-cmc-tv.html

and

https://www.ontvtonight.com/guide/listings/channel/1700805265/k16iw-cmc-usa.html

**Comment by freearhey** [comment]
Added.

```
https://iptv-org.github.io/epg/guides/us/ontvtonight.com.epg.xml
```

**Comment by rrjanbiah** [comment]
Thank you
