### ISSUE TITLE
IPTV USA - problems with "prefix"

### ISSUE THREAD

**Issue by cirojr82** [iptv-org/epg#662]
Hey!

I got an issue with my iptv list. Some channels have "USL" prefixes. For instace: USL - Fox Sports, USL - NBC, USL - Cartoon Network.

Probaby, because of this USL prefix, the EPG doesn't load. Is there a workaround here?

Thanks!

**Comment by freearhey** [comment]
For the program to load you only need to specify the correct `tvg-id` for the channel in the playlist. The title can be left as it is.

#EXTINF:-1 **tvg-id="FoxSports.us"**,USL - Fox Sports
https://example.com/playlist.m3u

You can find the proper ID for each channel here: https://iptv-org.github.io/
