### ISSUE TITLE
Bein sports qatar

### ISSUE THREAD

**Issue by Lihsah1** [iptv-org/epg#664]
Bein sports source in Qatar not working

**Comment by freearhey** [comment]
Thanks for the report. Unfortunately, there is no current program on the website

https://www.beinsports.com/ar/%D8%AC%D8%AF%D9%88%D9%84-%D8%A7%D9%84%D8%A8%D8%AB
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/7253922/159657832-22e02c40-83c6-44e3-bab3-59dde357b121.png">
