### ISSUE TITLE
Missed channels EPG from Canalplus.com and Telecablesat.fr 

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#670]
Hello Guys, 

Firstly thanks you so much for your amazing work
!!! 

EPG missed for theses channels from file : 

https://github.com/iptv-org/epg/blob/master/sites/telecablesat.fr/telecablesat.fr_fr.channels.xml 

and 

https://github.com/iptv-org/epg/blob/master/sites/canalplus.com/canalplus.com_fr.channels.xml 

RMC SPORT 3
RMC SPORT 4
RMC SPORT LIVE 5
RMC SPORT LIVE 6

Especially RMC SPORT channels, we could re-add or refresh the EPG for the channels RMC SPORT 1 to RMC SPORT 15

Thanks in advance for your daily hardworking for our satisfaction

**Comment by freearhey** [comment]
**telecablesat.fr**

RMC SPORT LIVE 5
RMC SPORT LIVE 6

is already on the list:

https://github.com/iptv-org/epg/blob/069b8db723beea9e804d82c7f0593dc5d841179a/sites/telecablesat.fr/telecablesat.fr_fr.channels.xml#L211-L212

Programmes for RMC SPORT 3 and RMC SPORT 4 are not on the site

**canalplus.com**

Missing channels are added via https://github.com/iptv-org/epg/commit/71be477a919441531a553d4b51b00368096cb2b8

**Comment by Talon555** [comment]
Many thanks @freearhey
Really appreciated your work and keep supporting this open-source project with some dollars...
Apparently the xml link Canal.com FR don't display in the global table? Something wrong?

**Comment by Talon555** [comment]
@freearhey apparently all 14 EPG guide for the channels RMC SPORT dont display on Telecablesat.fr and canalplus.com
Besides, canalplus.com xml link is available

**Comment by freearhey** [comment]
The guide from canalplus.com is available again at the link:

```
https://iptv-org.github.io/epg/guides/fr/canalplus.com.epg.xml
```

The programme for the RMC Sport channels can be found in the telecablesat.fr guide:

```
https://iptv-org.github.io/epg/guides/fr/telecablesat.fr.epg.xml
```

<img width="758" alt="image" src="https://user-images.githubusercontent.com/7253922/167608519-cea0cb19-66e3-4110-8414-1afbcaf2bf71.png">

And the canalplus.com guide does not include the RMC Sport channel programme as it is no longer available on the website: https://www.canalplus.com/programme-tv/
