### ISSUE TITLE
Magentatv.de 🇩🇪 has been added many days ago but xml missed 

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#671]
Hello Guys
Here the link that magentatv.de has been added with success 
https://github.com/iptv-org/epg/blob/master/sites/magentatv.de/magentatv.de_de.channels.xml

But xml link unavailable or missed 

Thanks in advance for your daily hardworking for our satisfaction

**Comment by freearhey** [comment]
`magentatv.de` has been removed from the queue because the current version of the parser is not working as expected

As soon as it is fixed, we will put it back

**Comment by freearhey** [comment]
Closing for now. 

If anyone does find a solution in the future feel free to make a [pull request](https://github.com/iptv-org/epg/pulls).
