### ISSUE TITLE
NO description program like requested for EPG DSTV Nigeria and South Africa 

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#672]
Hello Guys, 

I had requested if its possible to add description program in EPG for DSTV South Africa and Nigeria. 

I got the response that it's available via the xml below but unfortunately there's NO description in the program guide like requested. 

https://iptv-org.github.io/epg/guides/ng/dstv.com.epg.xml
https://iptv-org.github.io/epg/guides/za/dstv.com.epg.xml

If it's possible, fix them of course when you're available for

Thanks in advance for your daily hardworking for our satisfaction

**Comment by freearhey** [comment]
We can't upload the description because the site just crashes every time and the guide will be completely lost 

Once we find a workaround, we will include a description in the guide

**Comment by freearhey** [comment]
Program descriptions have been added to both guides again (https://github.com/iptv-org/epg/commit/b2c1debc0343cee7b2c856e65a7e90e901ba3d28)
