### ISSUE TITLE
EPG outdated

### ISSUE THREAD

**Issue by willnwhite** [iptv-org/epg#68]
The UK EPG is for 31 Aug when it should be for 1 Sep. E.g.
```xml
<programme start="20210831143000 +0000" stop="20210831151000 +0000" channel="ITVBe.uk"><title lang="en">The Only Way Is Essex</title></programme>
```

**Comment by freearhey** [comment]
Thanks for the report, I already found the bug and tomorrow everything should be back to normal.

**Comment by willnwhite** [comment]
Good to know, thanks. I guess tonight I'll just have to flick through the old TV guide, lol!

**Comment by freearhey** [comment]
Fixed.
