### ISSUE TITLE
Missing EPG information pertaining to Italy(/it/guidatv.sky.it.epg.xml)

### ISSUE THREAD

**Issue by Nostradamus1973** [iptv-org/epg#680]
Good morning everyone,

Discovery Science(IT), LA 7, Rai 1, Rai 2, Rai 3, and Rai Scuola haven't had EPG(/it/guidatv.sky.it.epg.xml) information for a few days now. I know resources have been limited, so, I didn't want to file a report until I was absolutely sure there was a problem that didn't resolve on its' own.

On a side note, many of the images related to the guide are missing, I would be willing to  help crowd-source some of those images if someone would like to contact me.

Thank you

**Comment by mcastellaneta** [comment]
Hey, i was having the same issue, so i am working on a fix. I was able to find the new channel numbers for La7.it, Rai1.it, Rai2.it and Rai3.it. Unfortunately, Rai Scuola is not present on Sky website, and  Discovery Science Italia, as of 1 March, it is no longer visible on Sky and has moved to Discovery+.

**Comment by Nostradamus1973** [comment]
Thank you Michele.
Yes, I noticed that Discovery Science IT has been empty for some time now, thx for explaining why it isn't attainable currently; I can certainly live without Rai Scuola as well, although my OCD may inspire me to remove it completely off my guide because gaps make me crazy. LOL!
As far as the Images pertaining to the individual shows, some have images, some do not, is there a way to update them? Is there a process where we can submit them for review and implementation?

Thx again Michele

**Comment by mcastellaneta** [comment]
Unfortunately I can't help you with images. I am taking my first steps in contributing to this project, and as far as I know, in the xml we will have the information that the sky website has. So if there are no images in the site we can't easily add them in the generated xml. I can suggest you to use other xml files which provide more images, like tv.blue.ch.epg.xml.

**Comment by Nostradamus1973** [comment]
I understand Michele, thank you for taking the time to respond and explain things to me.
The IT EPG is down again, I'm assuming that I should file a new bug report, instead of augmenting this one.

Thx again Michele

**Comment by Nostradamus1973** [comment]
Good morning Michele,

I tried looking for tv.blue.ch.epg.xml, however, all I could find was an old xml file from October 2021 from WebGrab. Does a regularly updated version exist?

If I would like to contribute to this project, what would it entail?

Thx again

**Comment by mcastellaneta** [comment]
Hi @Nostradamus1973.
1. I am using the XML available at the link https://iptv-org.github.io/epg/guides/ch/tv.blue.ch.epg.xml
Can you access the link and view the updated file?
2. I can't help you with that, unfortunately. I am creating pull requests to improve the guide with more information, but at the moment my contribution is limited to this.
