### ISSUE TITLE
Wrong diacritic for Czech EPG

### ISSUE THREAD

**Issue by Dexer125** [iptv-org/epg#682]
Today I loaded EPG for Czech language, m.tv.sms.cz. There is an issue with diacritic. It's shown wrong and it's unreadable. Looks like problem of diacritic parsing. 
Here is photo of that. https://ibb.co/Bthjh21

**Comment by Dexer125** [comment]
Note, there was no issue yesterday. I guess it has something to do with last few commits.

**Comment by freearhey** [comment]
Thanks for report!

Fixed in https://github.com/iptv-org/epg/commit/1466bba79f31d68247213db9a489ace574e2633b
