### ISSUE TITLE
Global alternative Europa Multi EPG sourcing 

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#684]
Hello Guys
It could be great if this EPG sourcing be added, of course if it's possible. 
Here an alternative Multi Europa EPG sourcing
https://tvepg.eu/en/
Many thanks for Everything

**Comment by freearhey** [comment]
Unfortunately, we cannot use this site because it has a [CAPTCHA](https://en.wikipedia.org/wiki/CAPTCHA)
