### ISSUE TITLE
EPG time-frame of more than 2 days

### ISSUE THREAD

**Issue by mcastellaneta** [iptv-org/epg#687]
I noticed that the API for guidatv.sky.it.epg.xml could retrieve schedule of the following 6 days:

1. Is the parameter of 2 days in the XML file creation a standard parameter, or it can be increased on the basis of the offered time-frame of the API?

If 1. were possible, 

2. Would the XML file be too big to handle?
3. Would it be feasible to cluster the programmes in days for easier use?

I am not familiar with GitHub Actions and the process of creating XML files, but I would be happy to try and help if needed.

**Comment by kdzayac** [comment]
If you’re to far out things change and 2 days in the future is max you probably want to go.

**Comment by freearhey** [comment]
@mcastellaneta We can specify the number of days for each source separately. And yes, 2 days was chosen precisely to reduce the size of the final file. But I am not talking about bytes, but about the number of items in the list. For example, in the case of `guidatv.sky.it` each additional day is plus 5000 programs with all descriptions. In the case of `tvtv.us` we are already talking about tens of thousands. Some apps just can't handle such large files.

You can see for yourself what the result will be by using the command:

```
npx epg-grabber --days=7 --config=sites/guidatv.sky.it/guidatv.sky.it.config.js --channels=sites/guidatv.sky.it/guidatv.sky.it_it.channels.xml --output=guide.xml
```

> 3. Would it be feasible to cluster the programmes in days for easier use?

Do you mean create a separate file for each day?

**Comment by mcastellaneta** [comment]
@freearhey Thank you. I am developing my own web app for a TV guide for fun, so I hadn't thought about the impact it might have on existing apps. My original idea was to allow the search for a programme in the following days, but I can understand that this is an operation that is not done by many people. 

> Do you mean create a separate file for each day?

Exactly, I was thinking of creating separate files for each 2-3 days.

However, my question was more of a curiosity than a real request. It would be a nice additional feature, but I don't think it's indispensable.

**Comment by freearhey** [comment]
The number of days can now be specified for each source separately through config.js (#1637), so if the source allows it and the final size of the guide does not exceed [50Mb](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#file-size-limits) the time frame can now be more than 2 days.
