### ISSUE TITLE
Arte and ARD Alpha without EPG information in horizon.tv list for germany

### ISSUE THREAD

**Issue by linesquarecube** [iptv-org/epg#688]
Hi,
recently switched from the hd-plus.de.epg.xml to the more complete horizon.tv.epg.xml for german tv channels. Both lists include the channels `channel id="ARDAlpha.de"` and `channel id="ARTEDeutsch.fr"` but only the hd-plus.xml shows EPG information for them.

Is there any possibility to transfer the available information from hd-plus to horizon.tv to have one really complete EPG file?

Thanks :)

**Comment by Talon555** [comment]
It's different German EPG sourcing. 
I think that your request is not possible
Used one than the other!
