### ISSUE TITLE
[Feature Request] Add support for sub-category

### ISSUE THREAD

**Issue by mcastellaneta** [iptv-org/epg#690]
I think it would be useful to add a tag in the XML files that allows you to specify the sub-category.
e.g. in the case of films, you could have: 
- category: film, 
- sub-category: comedy. 

Other sub-category may also be present.

**Comment by freearhey** [comment]
As I know there is no separate tag for subcategories in the [XMLTV standard](https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd). That is, even if we add it to the files, none of the players will use it.

**Comment by mcastellaneta** [comment]
Thanks for your answer. What do you think would be the best way to include both information? Adding a new category or appending the subcategory to the existing category tag?

**Comment by freearhey** [comment]
I think the second option makes more sense.
