### ISSUE TITLE
BeIN Sports (Qatar) 

### ISSUE THREAD

**Issue by Dr3sdan** [iptv-org/epg#691]
Issues with this epg no longer working.

It's still accessible via Google search but not being directed to by specific apps.

**Comment by freearhey** [comment]
The guide has been removed from the list because there is no current program on the site: https://www.beinsports.com/en/tv-guide

**Comment by Dr3sdan** [comment]
It's here? 

https://www.bein.com/en/tv-guide/?c=gb

**Comment by Dr3sdan** [comment]
Still waiting for this. It's been almost a month without a fix.
