### ISSUE TITLE
tvhebdo.com Canadian epg request

### ISSUE THREAD

**Issue by m0hamedessam** [iptv-org/epg#693]
tvhebdo.com Canadian epg request

**Comment by freearhey** [comment]
The guide from tvhebdo.com is now available at this link:

```
https://iptv-org.github.io/epg/guides/ca/tvhebdo.com.epg.xml
```

**Comment by m0hamedessam** [comment]
source need ca proxy so how to use proxy with epg-grabber ??

**Comment by m0hamedessam** [comment]
fixed by using http_proxy env before execution.
