### ISSUE TITLE
Korea EPG

### ISSUE THREAD

**Issue by lmnl01** [iptv-org/epg#695]
Hello, is it possible to use these sources for EPG?

https://m.seezntv.com/liveTV?ch_no=285&category_id=1&channel_type=epg
https://www.wavve.com/live/index.html

**Comment by freearhey** [comment]
**wavve.com**

```
https://iptv-org.github.io/epg/guides/kr/wavve.com.epg.xml
```

**Comment by freearhey** [comment]
**seezntv.com**

```
https://iptv-org.github.io/epg/guides/kr/seezntv.com.epg.xml
```
