### ISSUE TITLE
Hong Kong Now Sports - 

### ISSUE THREAD

**Issue by Dr3sdan** [iptv-org/epg#702]
The issue is the Now Sports Premier epg is no longer in English.

**Comment by freearhey** [comment]
Which link to the guide are you using?

**Comment by Dr3sdan** [comment]
Yeah, sorry.

This one : https://iptv-org.github.io/epg/guides/hk-en/nowplayer.now.com.epg.xml

**Comment by freearhey** [comment]
Fixed.

**Comment by Dr3sdan** [comment]
Thank you.
