### ISSUE TITLE
Australia EPG not loading 

### ISSUE THREAD

**Issue by Shifty0wl** [iptv-org/epg#705]
Shows Australia as passing but no guide info is showing up on every channel

**Comment by Talon555** [comment]
Another Australian EPG Sourcing : 

https://i.mjh.nz/Stirr/
https://i.mjh.nz/SkySportNow/
https://i.mjh.nz/SkyGo/
https://i.mjh.nz/Singtel/
https://i.mjh.nz/Foxtel/

And also DSTV South Africa EPG

https://i.mjh.nz/DStv/

**Comment by Shifty0wl** [comment]
Was working, down again

**Comment by Shifty0wl** [comment]
Was working, down again 

> Another Australian EPG Sourcing :
> 
> https://i.mjh.nz/Stirr/ https://i.mjh.nz/SkySportNow/ https://i.mjh.nz/SkyGo/ https://i.mjh.nz/Singtel/ https://i.mjh.nz/Foxtel/
> 
> And also DSTV South Africa EPG
> 
> https://i.mjh.nz/DStv/

Cool thanks!

**Comment by freearhey** [comment]
@Shifty0wl Is the EPG currently working properly?

```
https://iptv-org.github.io/epg/guides/au/ontvtonight.com.epg.xml
```

**Comment by Shifty0wl** [comment]
At this exact moment it is working. Seems to work for a day, then down a day then work a day

**Comment by Shifty0wl** [comment]
Yeah so the Australian EPG is down again

**Comment by freearhey** [comment]
Strange, it works fine for me:

<img width="776" alt="image" src="https://user-images.githubusercontent.com/7253922/163717619-ef6f10c1-f468-4b15-ac3f-4a6191dc8f46.png">
