### ISSUE TITLE
Missing <credits> category

### ISSUE THREAD

**Issue by MLBStream** [iptv-org/epg#728]
Thanks for your hard work!

Is it possible to add "**credits**" category?  like that we can get tags like "**actor**", "**director**" etc.

Thanks again!

### **UPD:** _others categories and tags missing:_

```
<sub-title />
<date />
<rating />
```
Of course if it's possible. Thanks!

**Comment by mcastellaneta** [comment]
@freearhey I could work on that, because I would also like to add other features such as the programme link. Do we have to edit only scripts/commands/programs/save.js file?

**Comment by freearhey** [comment]
@mcastellaneta [convertToXMLTV()](https://github.com/freearhey/epg-grabber/blob/16d02ce1fa0df77a48a9bbd3d68be054d6a6cdfa/src/utils.js#L152-L234) function in `epg-grabber`, which is used to generate the resulting XML, should also be updated. That seems to be all there is to do.

**Comment by MLBStream** [comment]
@mcastellaneta TVM for pull your commit, can you add tag `<date />`?

Thanks!

**Comment by mcastellaneta** [comment]
@MLBStream Do you mean the creation date of the programme?
