### ISSUE TITLE
How often do ID's change?

### ISSUE THREAD

**Issue by Chris230291** [iptv-org/epg#735]
I noticed myself that some of the ID's seem a little off and changing them to be correct is only a good thing. However every time ID's change, channel mappings break for us that are using only the EPG part of iptv-org.

Thanks,
Chris

**Comment by freearhey** [comment]
In general, the channel ID should be updated only when you change the channel name or its country. And the latest updates are related to the fact that many international channels need to have their country code updated: https://github.com/iptv-org/iptv/discussions/6764

As for [@iptv-org/epg](https://github.com/iptv-org/epg), after updating the database you can run these commands:

```
npm run api:load
npm run channels:validate -- sites/**/*.xml
```

and get a list of all files that should also be updated to keep the EPG working.

**Comment by Chris230291** [comment]
I understand why ID's are changing and its a good thing. I just wanted to make sure they wont keep changing. Each time an ID changes, I have to manually map the new ID to my channels in TVHeadend. I don't use your IPTV lists.

Also I have made an app that lets you mix and match channels across guides and combine them... I am using the ID's to keep track of which channels are wanted.
