### ISSUE TITLE
how to run npx epg-grabber?

### ISSUE THREAD

**Issue by MLBStream** [iptv-org/epg#737]
Hi!

when I try to run this command:
` npx epg-grabber --days=1 --config=sites/guidatv.sky.it/guidatv.sky.it.config.js --channels=sites/guidatv.sky.it/guidatv.sky.it_it.channels.xml --output=guide.xml`

always end with "_Error: Cannot find module 'dayjs'_" doesn't matter if install dayjs module globally.
I had been set windows environment variable to  "_C:\Users\user\node_modules or C:\Users\user\AppData\Roaming\npm\node_modules_" with same results.

what I'm missing or doing wrong? any help or advices will be appreciate it.

Thanks!

**Comment by MLBStream** [comment]
Fixed it!

**Comment by Chris230291** [comment]
Did you ever figure this out?

**Comment by freearhey** [comment]
You just need to install all the dependencies before running the grabber:

```
npm install
```

**Comment by Chris230291** [comment]
Thanks for the reply. I figured it out.
