### ISSUE TITLE
Supersports South Africa

### ISSUE THREAD

**Issue by Dr3sdan** [iptv-org/epg#739]
The epg for Supersport (SA) no longer loads and hasn't been loading for a few weeks.

[Here](https://iptv-org.github.io/epg/guides/za/dstv.com.epg.xml)

**Comment by LaneSh4d0w** [comment]
Seems to work for me

![image](https://user-images.githubusercontent.com/30985701/165153270-c85b5f1b-a45f-4586-aadd-8ffe02c09588.png)

**Comment by Dr3sdan** [comment]
> Seems to work for me
> 
> ![image](https://user-images.githubusercontent.com/30985701/165153270-c85b5f1b-a45f-4586-aadd-8ffe02c09588.png)
> 

I can do the same on my browser but it won't load on my shield and firetv.

**Comment by tinuva** [comment]
@Dr3sdan what app on your shield and firetv are you using?

**Comment by Dr3sdan** [comment]
> @Dr3sdan what app on your shield and firetv are you using?
> 

Tivimate. Was working a few weeks back but just stopped. Haven't changed anything from my side either.

**Comment by tinuva** [comment]
> > @Dr3sdan what app on your shield and firetv are you using?
> 
> Tivimate. Was working a few weeks back but just stopped. Haven't changed anything from my side either.

ok. Perhaps you were using guides.dstv.com which is now dead. you need to remove that config and config using dstv.com guide. The guide.dstv.com stopped working for 13-14 days now.

**Comment by Dr3sdan** [comment]
> > > @Dr3sdan what app on your shield and firetv are you using?
> > 
> > Tivimate. Was working a few weeks back but just stopped. Haven't changed anything from my side either.
> 
> ok. Perhaps you were using guides.dstv.com which is now dead. you need to remove that config and config using dstv.com guide. The guide.dstv.com stopped working for 13-14 days now.

Yeah I tried that the first time around. It still wouldn't load.

**Comment by freearhey** [comment]
The guide for the SuperSport channels is again available at this link:

```
https://iptv-org.github.io/epg/guides/za/dstv.com.epg.xml
```

<img width="832" alt="image" src="https://user-images.githubusercontent.com/7253922/167595823-8a71eca8-9b68-490a-a8fc-75f3b45f9a3a.png">

**Comment by Dr3sdan** [comment]
> The guide for the SuperSport channels is again available at this link:
> 
> ```
> https://iptv-org.github.io/epg/guides/za/dstv.com.epg.xml
> ```
> 
> <img width="832" alt="image" src="https://user-images.githubusercontent.com/7253922/167595823-8a71eca8-9b68-490a-a8fc-75f3b45f9a3a.png">
> 

Thank you.
