### ISSUE TITLE
No new tvtv.us EPG again

### ISSUE THREAD

**Issue by ian10951** [iptv-org/epg#745]
Has the grabber ran today ?

**Comment by freearhey** [comment]
Yes. https://github.com/iptv-org/epg/actions/runs/2214088635

At the moment it's loading fine:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/7253922/164973612-59d5a8a5-1925-4fc7-9891-8d1b5d2c03f1.png">

**Comment by ian10951** [comment]
Well I'm still downloading yesterdays file, and EPG is still present because it doesnt run out until midnight tonight UK time.

**Comment by ian10951** [comment]
Ok fresh EPG has downloaded again this morning so whatever the issue was its been resolved so this matter can now be closed. There was deffo no new EPG yesterday though for whatever reason.
