### ISSUE TITLE
Madani TV Channel ID

### ISSUE THREAD

**Issue by F640** [iptv-org/epg#760]
I have just noticed that Madani TV (`MadaniTV.id`) EPG placed somewhat incorrect with [osn.com](https://osn.com/) EPG provider for unknown reason. Can someone correct it? I don't know where is another Madani TV from.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/7ea6ace12993f793bee5b5cf866bdf8cb1e46b02
