### ISSUE TITLE
Channel request

### ISSUE THREAD

**Issue by Mikhel** [iptv-org/epg#766]
Hi, I noticed there are a few channels missing from México but I am interested in one in particular which is De Pelicula HD found in mi.tv:

https://mi.tv/mx/canales/de-pelicula-hd

But it is not found in:
https://iptv-org.github.io/epg/guides/mx/mi.tv.epg.xml

Thanks in advance.

**Comment by LaneSh4d0w** [comment]
Has been added in recent PR, should be OK.

**Comment by Mikhel** [comment]
Thanks I will wait for it to update, it is still showing the other De Pelicula which has different programing compared to the De Pelicula HD.

:)
