### ISSUE TITLE
ESPN Channels removed from Brazil EPG

### ISSUE THREAD

**Issue by Rferreira2k** [iptv-org/epg#775]
Hi

ESPN 1, 2 and 3 were removed from Brazil EPG

Thanks!

**Comment by Rferreira2k** [comment]
Channel Links:

ESPN 1 (name in mi.tv "ESPN Brasil") https://mi.tv/br/canais/espn
ESPN 2 (name in mi.tv "ESPN") https://mi.tv/br/canais/espn-2
ESPN 3 (name in mi.tv "ESPN Extra") https://mi.tv/br/canais/espn-plus 

The name of the channels changed in Brazil, but on mi.tv there are the old names.

Thanks!

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/2b4474505676ecb3c03fa9984ca36c33a6cecabe
