### ISSUE TITLE
Please, Support them with some symbolic dollars 

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#791]
Hello Guys, 

Like almost each month,  i just sent them some US dollars for supporting them for their hardworking for improving this EPG Sourcing

Please, support them with dollars by anonymous by using this website below

https://opencollective.com/iptv-org

**Comment by freearhey** [comment]
Thanks for your support, but there is already a link to OpenCollective on the home page for those who would like to support the project financially.
