### ISSUE TITLE
D-Smart EPG  Error: Connection timeout

### ISSUE THREAD

**Issue by m0hamedessam** [iptv-org/epg#807]
curl "https://www.dsmart.com.tr/api/v1/public/epg/schedules?page=1&limit=500&day=2022-05-21" -X GET -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Edg/79.0.309.71"
[3/315] dsmart.com.tr - 24KitchenTurkey.us - May 21, 2022 (0 programs)
  Error: Connection timeout

I tried with proxy and without api url works but when i start epg-grabber its shown Error: Connection timeout any idea ?

**Comment by freearhey** [comment]
Try adding the `--timeout` argument as shown here (value in milliseconds):

https://github.com/iptv-org/epg/blob/2e58a9a8ebd8dd3878bd8f2fba1bc3d16c01632b/sites/dsmart.com.tr/dsmart.com.tr.test.js#L1-L2

**Comment by m0hamedessam** [comment]
I think this solve it.
