### ISSUE TITLE
KAZT-CD2 change to KAZT-DT2

### ISSUE THREAD

**Issue by Gitbone94** [iptv-org/epg#811]
h t t p s ://iptv-org.github.io/epg/guides/us-local/tvtv.us.epg.xml
The EPG for KAZT-CD2 does not provide any data. I believe it needs to be KAZT-DT2 as shown below in the pic.
![image](https://user-images.githubusercontent.com/68349959/169535786-ab831d89-b964-4d7d-9018-066ea12e19b4.png)

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/2be77de350b49bcb3a3e47e19024978ea1bd8cdd

**Comment by Gitbone94** [comment]
Aleksandr, hello.
Thanks for making this change. However, this channel continues to show
"SIGN OFF" at all times on the epg. I replied in the forum but the issue
was closed so I don't know if you saw it.
When IPTV-ORG used to publish epg by US states, I found a proxy
at KMOH (Kingman, Arizona) that showed the programs showing on KAZT..
However, since IPTV-ORG stopped publishing the epg by US states I don't
see KMOH any more.
If it is impossible to get the epg for KAZT-DT2 maybe you could bring back
KMOH.
If it is too much work then don't bother.
[image: image.png]

**Comment by freearhey** [comment]
The thing is that the epg for this channel is loaded directly from tvtv.us and at the moment that's all it shows: https://www.tvtv.us/stations/stn31303

If you find a more accurate guide for the channel you can add it to the list yourself via a [pull request](https://github.com/iptv-org/epg/pulls), or ask other users for help via [issue](https://github.com/iptv-org/epg/issues).

**Comment by Gitbone94** [comment]
Thank you. As you can tell, I am a novice at this. I know the epg for KMOH
worked in the past so now I have to figure out how a pull request works.
