### ISSUE TITLE
Guide Information for EPG for the Youtoo America

### ISSUE THREAD

**Issue by blackhern** [iptv-org/epg#815]
I have no idea how to create the XML EPG Guide for any channel but the following link has the entire schedule for Youtoo America.
https://ytatv.com/schedule/ if someone wants to add the information to an existing EPG Guide.

**Comment by PopeyeTheSai10r** [comment]
@blackhern, It seems as if this information is already available from other sources. Check the [ontvtonightlink here](https://www.ontvtonight.com/guide/listings/channel/1717081645/youtoo-america.html) and let us know if this information looks correct.

Also, the channel is not in the database. You can follow [this guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) and submit a pull request to get it added.

**Comment by freearhey** [comment]
The EPG for Youtoo America is now available at this link:

```
https://iptv-org.github.io/epg/guides/us/tvpassport.com.epg.xml.gz
```
