### ISSUE TITLE
Alot of channels don't map to the US iptv-org iptv m3u.

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [iptv-org/epg#82]
I noticed that alot of channels aren't being mapped.

I am using ```https://iptv-org.github.io/iptv/countries/us.m3u``` with ```https://iptv-org.github.io/epg/guides/tvtv.us.guide.xml```

Any way to fix this?

Edit: I noticed this pull request for the iptv repo. https://github.com/iptv-org/iptv/pull/4375 I assuming it's getting updated? Any way I could help?

**Comment by freearhey** [comment]
To make the program work, you just need to edit the playlist [channels/us.m3u](https://github.com/iptv-org/iptv/blob/master/channels/us.m3u) and copy the channel `tvg-id` from [iptv-org/epg](https://iptv-org.github.io/epg/index.html) into it. As you can see there are a lot of channels, so any help will come in handy.

**Comment by jkemp814** [comment]
I had started mapping out a plan for this. One issue is without a call sign, the other channels have to be researched, then choose the best selection. Another issue is east vs. west time zone wise. Some streams have 15 listings. So you have to monitor the channel for a period of time. We can do it, but it will take some persistence.

**Comment by golfzulu1** [comment]
I just found this post.  Hey guys, why didn't you put the updated m3u list somewhere accessible to others?  By closing and deleting, anyone else who would like to use a synched m3u list will have to "re-invent" the wheel.

Any chance of getting you to post it somewhere on github, so the rest of us don't have to slog through the painful edit cycle that you did?  

Thanks in advance

**Comment by Cookie-Monster-Coder** [comment]
It sill doesn't work for me. When I add the m3u and xml files to Jellyfin only like 5ish channels get mapped correctly.

Even mapping manually wasn't possible. I did find https://github.com/epgshare01/share01 which I manually mapped from Jellyfin but noticed that some of the channels like fox are on repeat news since that's what comes from directly from fox m3u, so I'm guessing those are going to be hard to map.

**Comment by freearhey** [comment]
@Cookie-Monster-Coder It's strange, I have a lot of channels with a program guide.
![image](https://user-images.githubusercontent.com/7253922/133583014-31bb6a00-d327-4f3f-ad46-0079f113b5a3.png)

**Comment by freearhey** [comment]
@golfzulu1 We already have an entire repository with all the playlists for which this guide was created. 

https://github.com/iptv-org/iptv

**Comment by golfzulu1** [comment]
Maybe I'm missing something here.  You are saying that "https://github.com/iptv-org/iptv" has the updated .m3u file which has TV-ID modified to match the tvtv.us.guide?  Did I get that right?  Because the old one I already have and as you guys discovered, it's not worth a hill of beans!

Have any of you been able to download the guide and save it to a file?  I keep trying to do that, and it's so big it crashes whatever app I try to open it with.

Let me know about the .m3u file.  I have some ideas that might make it work!

**Comment by golfzulu1** [comment]
I just did a quick check.  The files at  "https://github.com/iptv-org/iptv"  are not synched on TVG-ID to the Channel-ID in tvtv.guide.xml .   How about making the synched .m3u file that you guys edited about 9 days ago, available for download?

I'd like to try some things that may make it work with the EPG guide.xml url.

**Comment by freearhey** [comment]
I use `https://iptv-org.github.io/iptv/countries/us.m3u` with `https://iptv-org.github.io/epg/guides/tvtv.us.guide.xml` and it works fine for me.

If you find any inconsistencies then feel free to correct them just read the [guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md) before you do it.
