### ISSUE TITLE
Please rename "SKAÏ" to "SKAI" in the greek epg

### ISSUE THREAD

**Issue by pitsi** [iptv-org/epg#827]
As the title suggests, I would like the greek channel Skai to lose those two dots over "I" (I think they are called umlauts) for its name.
Its greek name is ΣΚΑΪ, is it pronounced as the englih word "sky" (α+ι=αι=ε in greek, so the umlauts are needed for the name in greek, so it is not pronounced "ske"), but in english there is no reason for them.
It's on line 75 on `cosmote.gr_gr.channels.xml`.

My main reason for the change is a bit different. I maintain a small m3u file locally for the 10 channels that transmit nationwide (8 of them work, 2 do not because their web tv maintainers are idiots). All those 10 channels are practically cherry picked from the 120+ channels your m3u offers.
When I first started with my m3u, and with another epg back then, the matching between the epg xml and the channels in the m3u was done through their names (tvg-name parameter). When I moved to your epg, I had to change to ids (tvg-id parameter) because of that channel only. How would I type that "I" on a terminal based editor (nano), on a system that supports only the posix "locale"?

Plus, the last couple of weeks, there have been a lot of changes on the forementioned tvg-ids of the epg, so I had to change them again on my m3u. Thus, I think that moving back to tvg-names will keep things stable for longer.

Thank you in advance.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/d91f82f0e239e097a41b818fa0f687c196abc144
