### ISSUE TITLE
TapGo (Philippines) EPG

### ISSUE THREAD

**Issue by lmnl01** [iptv-org/epg#831]
http://www.tapdmv.com/schedule.html

**Comment by PopeyeTheSai10r** [comment]
Hello @lmnl01, The link provided has other Tap Channels but I can't see TapGo.

Can you provide the channel id? 
You can get that information from https://iptv-org.github.io or https://github.com/iptv-org/database

**Comment by lmnl01** [comment]
TapGo is the streaming service name.

**Comment by PopeyeTheSai10r** [comment]
@lmnl01 I will be more than happy to assist with adding the EPG for some channels. I just need to know the name of the Channel/s or channel ids you are after.

**Comment by lmnl01** [comment]
Sure, here are the channels:
- Tap TV
- Tap Edge
- Tap Movies
- Tap Action Flix
- Tap Sports
- Premier Sports
- Premier Sports 2
- Premier Football

**Comment by PopeyeTheSai10r** [comment]
Tap TV, Tap Edge, Tap Sports and Premier Football are the only channels that are in the database at this time.

You can follow [this guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) and submit a pull request to get Tap Movies, Tap Action Flix, Premier Sports and Premier Sports 2 added to the database. Once added contributors should be able to help get the EPG for them.

**Comment by freearhey** [comment]
The rest of the channels have also been added to the database.

**Comment by LaneSh4d0w** [comment]
This thing is different than the others, due to the fact that it doesn't have a straight EPG, simply data for all the days, and each channel has got its different way of presenting them. (like every monday you have this, every tuesday you have this (seen from TAP Edge as an example)). This means that we need to generate the date and time from the existent data except for the ones that do have a correct EPG (for example, TAP Movies has a correct way of presenting the schedules, Premier Sports doesn't)

**Comment by PopeyeTheSai10r** [comment]
I found this site that has the info for the stations request. If anyone want to try to create a config file for it.

[skyepg.mysky.com.ph](https://skyepg.mysky.com.ph/Main/getEventsbyType?counter=48)



> id":"324","name":"TAP TV
> id":"325","name":"TAP EDGE
> id":"55","name":"TAP MOVIES
> id":"318","name":"TAP SPORTS
> id":"140","name":"PREMIER SPORTS
> id":"326","name":"PREMIER SPORTS 2 HD
> id":"322","name":"PREMIER FOOTBALL HD

**Comment by freearhey** [comment]
Guide from tapdmv.com is now available here:

```
https://iptv-org.github.io/epg/guides/ph/tapdmv.com.epg.xml.gz
```

The guide for all of the above channels is also available at this link:

```
https://iptv-org.github.io/epg/guides/ph/mysky.com.ph.epg.xml.gz
```
