### ISSUE TITLE
Hungary - Yettel TV EPG

### ISSUE THREAD

**Issue by sirjohn771103** [iptv-org/epg#835]
Hello, can you get EPG from Yettel TV Hungary? Yettel is a new brand, it was Telenor some months ago.

https://tv.yettel.hu/#!/hu-HU/tv/
http://webgrabplus.com/epg-channels#sF7

Thank you.

**Comment by freearhey** [comment]
The guide from tv.yettel.hu is now available at this link:

```
https://iptv-org.github.io/epg/guides/hu/tv.yettel.hu.epg.xml
```
