### ISSUE TITLE
[Argentina] ESPN 1 & ESPN 2 have inverted EPGs

### ISSUE THREAD

**Issue by julianf92** [iptv-org/epg#845]
In the Argentina EPG file, ESPN 1 is showing the programming of ESPN 2, and vice versa.

**Comment by freearhey** [comment]
Could you be more specific about which guide you are talking about?

**Comment by julianf92** [comment]
My bad. I thought it was https://iptv-org.github.io/epg/guides/ar/mi.tv.epg.xml but it seems that file doesn't have ESPN 1 or 2.

Any chance you could source the data from here?

https://www.directv.com.ar/guia/guia.aspx

ESPN 1, 2 and 3 are channels 621, 622 and 623, respectively.

**Comment by freearhey** [comment]
I will look into this later when I have some free time.

But it's better to create a new issue for this request so the rest of the community can also see it and maybe help.
