### ISSUE TITLE
tv.yettel.hu problem

### ISSUE THREAD

**Issue by sirjohn771103** [iptv-org/epg#846]
Hello, thank you for this provider:
[https://iptv-org.github.io/epg/guides/hu/tv.yettel.hu.epg.xml](url)

This is not good:
<channel lang="hu" xmltv_id="NationalGeographicHungaryCzechia.us" site_id="LCH133">National Geographic</channel>

It has Czech language EPG, not Hungarian.
Please, update it. Thank you for your work.

**Comment by freearhey** [comment]
Could you give me a concrete example? I could not find a description in Czech.

**Comment by sirjohn771103** [comment]
[https://cloud.iptveditor.com/channel/epg/](url) shows it in Czech language. In the XML file it is in Hungarian language. Thank you for this nice work. The proble is over there, not here. Thank you.

**Comment by sirjohn771103** [comment]
[image: epg.png]

I would like to use here:
https://cloud.iptveditor.com/channel/epg/



Aleksandr Statciuk ***@***.***> ezt írta (időpont: 2022. jún.
18., Szo, 15:53):

**Comment by sirjohn771103** [comment]
![epg](https://user-images.githubusercontent.com/96374704/174447213-78ec7e8f-683c-4108-8d14-dcea05107d94.png)

**Comment by freearhey** [comment]
I don't know where exactly the epg in this app comes from, but it's not https://iptv-org.github.io/epg/guides/hu/tv.yettel.hu.epg.xml, because everything in it is in Hungarian:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/7253922/174447926-dedccbbc-f900-48d6-9e7f-9213efd25189.png">

**Comment by sirjohn771103** [comment]
Thank you. You're work is the best! I make a ticket for them. I close this.
