### ISSUE TITLE
[ARG] Add EPG for sports channels

### ISSUE THREAD

**Issue by julianf92** [iptv-org/epg#848]
I'd like to request EPG for Argentina's ESPN and DirecTV sports channels. Please note that these are different from Mexican or other versions.

DirecTV Argentina lists their EPG here, maybe it can be used as a source?
https://www.directv.com.ar/guia/guia.aspx

Namely: ESPN 1 (Channel 621), ESPN (622), ESPN 3 (623), DirecTV Sports (1610), DirecTV Sports 2 (1612), and DirecTV Sports+ (1613).

Thank you!

**Comment by freearhey** [comment]
The guide from directv.com.ar is now available at this link:

```
https://iptv-org.github.io/epg/guides/ar/directv.com.ar.epg.xml
```
