### ISSUE TITLE
Brazil Channel Request

### ISSUE THREAD

**Issue by Rferreira2k** [iptv-org/epg#857]
Hi!

The ESNP channels in Brazil are changed again.  Now have two channels "ESPN Plus" with different schedule

ESPN Extra (https://mi.tv/br/canais/espn-plus) exists on EPG with name "ESPNExtraBrazil.br"
ESPN Extra (https://mi.tv/br/canais/espn-extra) not exists on EPG xml

Thanks!

**Comment by PopeyeTheSai10r** [comment]
Hi @Rferreira2k, I think the way to solve this is starting by gathering the channel info for the channel and adding it to the database. {https://github.com/iptv-org/database} once that's done contributors will be able make the changes to {mi.tv_br.channels.xml} and submit a pull request.
