### ISSUE TITLE
Have you stopped using "lang" attribute?

### ISSUE THREAD

**Issue by Chris230291** [iptv-org/epg#860]
Have you decided not to include the "lang" attribute in titles/descriptions anymore?
Is this intentional?

Chris

**Comment by mcastellaneta** [comment]
Should be solved by: dd54b9f0ef4b6778b627e0f050b7941e0a9ef919

**Comment by mcastellaneta** [comment]
Maybe fixed in https://github.com/freearhey/epg-grabber/commit/dd54b9f0ef4b6778b627e0f050b7941e0a9ef919

**Comment by freearhey** [comment]
@Chris230291 Thanks for pointing that out! I updated the code and now the attribute should appear again.
