### ISSUE TITLE
mncvision.id missing some channels

### ISSUE THREAD

**Issue by kraith** [iptv-org/epg#875]
Why some channels epg are missing from mncvision.id and transvision.co.id epg?
eg; hbo, cinemax, natgeo, natgeo wild, discovery, etc
those channels are still exists on https://mncvision.id/schedule and https://www.transvision.co.id/jadwalacara/epg.html
I found this epg and it contains some missing channel epg
https://macan.tv/xmltv.php?username=epg&password=epg

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/b9ce3fe01afad3f44ec57cfe63ea3f57b4bc8390
