### ISSUE TITLE
Dozens of channels disappeared from Brazil's EPG

### ISSUE THREAD

**Issue by Rferreira2k** [iptv-org/epg#876]
dozens of channels disappeared from Brazils EPG (A&E, AMC, Animal Planet, Cinemax, all discovery channels, E!, FX, HGTV, all history channels, Lifetime, paramount, National geographic, sony channel, space, star channel, syfy and many others)

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/b9ce3fe01afad3f44ec57cfe63ea3f57b4bc8390
