### ISSUE TITLE
Missing channels in m.tv.sm.cz EPG

### ISSUE THREAD

**Issue by Dexer125** [iptv-org/epg#877]
Hi, many of channels in m.tv.sms.cz EPG have disappeared. HBO, HBO2, HBO3, Cinemax, Cinemax2, BabyTV, AMC, Paramount Network, History Channel, Discovery Channel, National Geographic, Nate Geo WILD, Animal Planet, TLC, Cartoon Network, Disney Channel, Disney Junior. I don't know where is the problem as those channels are still in channels xml. I checked workflow and they were present in EPG 3 days ago.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/commit/b9ce3fe01afad3f44ec57cfe63ea3f57b4bc8390
