### ISSUE TITLE
[ARG] Flow EPG

### ISSUE THREAD

**Issue by julianf92** [iptv-org/epg#883]
Hi, I was wondering if you could add the EPG for Flow Argentina, which can be found below:

https://entretenimiento.flow.com.ar/tv-cable/programacion

Thanks!

**Comment by freearhey** [comment]
This site just won't load any program for me:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/7253922/186791361-66b75aa7-d521-47be-97e9-971383dc5355.png">

**Comment by LaneSh4d0w** [comment]
It uses this https://buscador.cablevisionfibertel.com.ar/index.aspx.

makes a POST for EPG data : https://buscador.cablevisionfibertel.com.ar/TVGridWS/TvGridWS.asmx/ReloadGrid with daySel as a parameter (equivalent to the day you want the EPG, or the "dia" shown in the picture)

**Comment by freearhey** [comment]
Unfortunately, I was still unable to download the program guide. But maybe someone else will have better luck.

**Comment by nickleby** [comment]
Empty grid for me too. I guess the website is having issues.

**Comment by freearhey** [comment]
Closing for now. If the program appears on the site again we'll revisit this issue.
