### ISSUE TITLE
Source with extra EPG information

### ISSUE THREAD

**Issue by TertoGordez** [iptv-org/epg#893]
Hi,

Im looking to create an .xml file for tv24.se (there is also a UK counterpart tv24.co.uk)  but I'm not elite enough to create the config file etc. I've previously contributed to the XML for tv.nu and allente.se.

I've noticed that the source tv24.se and tv24.co.uk provides a lot of nice extra EPG information. Such as "LIVE", "NEW" and movie logo for movies. There is also a second title row with the IMDB film genre and rating for movies, and for live events it provides teams competing.

Have a look here:
www.tv24.se
or
www.tv24.co.uk

for example Live Event:
Title row: Fotboll: FA-cupen
Secondary title row: Manchester United - Middlesbrough 

for example Movie:
Title row:Wind River
Secondary title row: Kriminaldrama (2017)7.7

Then there is the normal description of the movie or game with the plot or summary as any other epg.

I've found that the " "LIVE", "NEW" and movie logo for movies are possible. At least in Tivimate app.
Here is one user on reddit that has it:
https://www.reddit.com/r/TiviMate/comments/vi7kh6/feature/
(does not include the secondary title row)

I would also like the secondary title row to be included since usually, the tile is "FA-Cup", "Champions League" or similar, which does not state the teams playing the game. This would be really nice to be able to see.

As previously stated, I'm capable to create the XML file with guidelines. 

Anybody with the knowledge to let me know if this is possible, and if so if they are willing to help out with the config file etc.?

**Comment by mcastellaneta** [comment]
You could use the attribute `sub_title` for the secondary title row and `icon` for the image. 

Since the XML is created once each day, there is no point in including the tag LIVE in the programme, as it should be handled later by the IPTV player.

As regards the NEW tag, it could be added since the attribute `new` exist in the xmltv.dtd standard

**Comment by freearhey** [comment]
The guide from tv24.se is now available at:

```
https://iptv-org.github.io/epg/guides/se/tv24.se.epg.xml.gz
```

and tv24.co.uk at:

```
https://iptv-org.github.io/epg/guides/uk/tv24.co.uk.epg.xml.gz
```
