### ISSUE TITLE
tv.trueid.net.epg.xml

### ISSUE THREAD

**Issue by walpak1** [iptv-org/epg#901]
please add truepremierfootballhd1 -5

**Comment by Bebel93** [comment]
http://s1.pixel4k.vision:80 problème de serveur pouvez vous m'aider svp merci

**Comment by PopeyeTheSai10r** [comment]
> please add truepremierfootballhd1 -5

It will be faster for someone to work on this if they have a link to the source.

**Comment by iamnatto** [comment]
please add epg for these channels: TRUE CHINESE MORE, TRUE ASIAN MORE, TRUE KOREAN MORE

ref link for epg
[https://tv.trueid.net/tvguide/trueidtv-movies-series](url)
[http://tvsmagazine.com/schedule.php?category=mov&lang=eng](url)

**Comment by iamnatto** [comment]
> > please add truepremierfootballhd1 -5
> 
> It will be faster for someone to work on this if they have a link to the source.

epg for TRUE sport channels
[https://tv.trueid.net/tvguide/trueidtv-sport](url)
[http://tvsmagazine.com/schedule.php?category=sport&lang=eng](url)

**Comment by freearhey** [comment]
Added in https://github.com/iptv-org/epg/commit/8059748937236ace88a93eb510006eb4eac78c83
