### ISSUE TITLE
Add channels to tvim.tv

### ISSUE THREAD

**Issue by fraudiay79** [iptv-org/epg#903]
Can you add the following channels to tvim.tv?
I have not tested on Webgrabber if it pulls the data.

    <channel update="i" site="tvim.tv" site_id="KLANKOSOVA" xmltv_id="KlanKosova.rs">Klan Kosova</channel>
    <channel update="i" site="tvim.tv" site_id="T7" xmltv_id="RTV21.xk">RTV 21</channel>
    <channel update="i" site="tvim.tv" site_id="RTV21" xmltv_id="T7.rs">T7 News</channel>
    <channel update="i" site="tvim.tv" site_id="KINO1" xmltv_id="ARTKino1.xk">ART Kino 1</channel>
    <channel update="i" site="tvim.tv" site_id="KINO2" xmltv_id="ARTKino2.xk">ART Kino 2</channel>
    <channel update="i" site="tvim.tv" site_id="DOKU1" xmltv_id="ARTDoku1.xk">ART Doku 1</channel>
    <channel update="i" site="tvim.tv" site_id="DOKU2" xmltv_id="ARTDoku2.xk">ART Doku 2</channel>
    <channel update="i" site="tvim.tv" site_id="EPISODE" xmltv_id="Episode.xk">Episode</channel>
    <channel update="i" site="tvim.tv" site_id="PRIMETV" xmltv_id="PrimeTV.xk">Prime TV</channel>
    <channel update="i" site="tvim.tv" site_id="TVARTA" xmltv_id="ArtaNews.xk">Arta News</channel>
    <channel update="i" site="tvim.tv" site_id="SPORT1" xmltv_id="ARTSport1.xk">ART Sport 1</channel>
    <channel update="i" site="tvim.tv" site_id="SPORT2" xmltv_id="ARTSport2.xk">ART Sport 2</channel>
    <channel update="i" site="tvim.tv" site_id="SPORT3" xmltv_id="ARTSport3.xk">ART Sport 3</channel>
    <channel update="i" site="tvim.tv" site_id="SPORT4" xmltv_id="ARTSport4.xk">ART Sport 4</channel>
    <channel update="i" site="tvim.tv" site_id="SPORT5" xmltv_id="ARTSport5.xk">ART Sport 5</channel>
    <channel update="i" site="tvim.tv" site_id="SPORT6" xmltv_id="ARTSport6.xk">ART Sport 6</channel>
    <channel update="i" site="tvim.tv" site_id="KSPORT1" xmltv_id="KSport1.xk">K Sport 1</channel>
    <channel update="i" site="tvim.tv" site_id="KSPORT2" xmltv_id="KSport2.xk">K Sport 2</channel>
    <channel update="i" site="tvim.tv" site_id="KSPORT3" xmltv_id="KSport3.xk">K Sport 3</channel>
    <channel update="i" site="tvim.tv" site_id="KSPORT4" xmltv_id="KSport4.xk">K Sport 4</channel>
    <channel update="i" site="tvim.tv" site_id="KSPORT5" xmltv_id="KSport5.xk">K Sport 5</channel>
    <channel update="i" site="tvim.tv" site_id="ARENASPORT1" xmltv_id="ArenaSport1.rs">Arena Sport 1</channel>
    <channel update="i" site="tvim.tv" site_id="ARENASPORT2" xmltv_id="ArenaSport2.rs">Arena Sport 2</channel>
    <channel update="i" site="tvim.tv" site_id="ARENASPORT3" xmltv_id="ArenaSport3.rs">Arena Sport 3</channel>
    <channel update="i" site="tvim.tv" site_id="ARENASPORT4" xmltv_id="ArenaSport4.rs">Arena Sport 4</channel>
    <channel update="i" site="tvim.tv" site_id="ARENASPORT5" xmltv_id="ArenaSport5.rs">Arena Sport 5</channel>
    <channel update="i" site="tvim.tv" site_id="NBATV" xmltv_id="NBATVInternational.us">NBA TV</channel>

**Comment by PopeyeTheSai10r** [comment]
WIP

**Comment by fraudiay79** [comment]
created the pull request with the changes.  I also added the Iceland channels as well from my other EPG request

**Comment by freearhey** [comment]
The rest of the channels are added via https://github.com/iptv-org/epg/commit/60c539a76df5f610503de2521e2e1849253ee09c
