### ISSUE TITLE
starhubtvplus.com

### ISSUE THREAD

**Issue by Zoom-Adr** [iptv-org/epg#913]
add new channels hub premier 1 to 4

**Comment by PopeyeTheSai10r** [comment]
Hello @Zoom-Adr, The channels requested are not in the database.

You can follow [this guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) and submit a pull request to get those added to the database first. Once added contributors will be able to add the EPG for them.

**Comment by Zoom-Adr** [comment]
Added in database and edit the xml in the sites folder for 1 channel but its not appearing in the epg.
