### ISSUE TITLE
ziggogo.tv ESPN 4

### ISSUE THREAD

**Issue by Chris230291** [iptv-org/epg#920]
Hello. ESPN 4 is missing from ziggogo.tv.
I would have made a pull request but I couldn't figure out where to find the channel ID's.

Thanks,
Chris

**Comment by PopeyeTheSai10r** [comment]
Hello @Chris230291, 

ESPN 4 was added on https://github.com/iptv-org/epg/pull/921. Please way for the PR to be approved, wait for next EPG update and see if you get the program data.
