### ISSUE TITLE
Fix: CosmoteCinema2HD.gr, Cosmote Cinema 2HD [EPG]

### ISSUE THREAD

**Issue by johntaxmi** [iptv-org/epg#941]
### Describe your issue

There are currently 3 Cosmote Cinema Channels 1HD/2HD/3.
Both Cosmote Cinema 1HD and Cosmote Cinema 3 has a working EPG, but the Cosmote Cinema 2HD does not have a working EPG, even though I am able to see it in the database.

[Cosmote Cinema 2HD EPG](https://www.cosmote.gr/cosmotetv/residential/program/epg/programchannel?p_p_id=channelprogram_WAR_OTETVportlet&p_p_lifecycle=0&_channelprogram_WAR_OTETVportlet_platform=DTH&_channelprogram_WAR_OTETVportlet_date=24-07-2022&_channelprogram_WAR_OTETVportlet_articleTitleUrl=ote-cinema-2-hd&_channelprogram_WAR_OTETVportlet_redirect=https%253A%252F%252Fwww.cosmote.gr%252Fportal%252Fresidential%252Fprogram)

Thanks in advanced.

**Comment by PopeyeTheSai10r** [comment]
Hello @johntaxmi , The daily job still picking up the info for CosmoteSport2HD.gr as you can see [from the link](https://github.com/iptv-org/epg/blob/gh-pages/guides/gr/cosmote.gr.epg.xml). 

Can you make sure the channel name in your playlist matches the name in the database "Cosmote Sport 2" (CosmoteSport2HD.gr)?

**Comment by johntaxmi** [comment]
@PopeyeTheSai10r Yep, you are right for Cosmote Sport 2.
But it was a mistake, I wanted to ask about Cosmote **Cinema** 2 and not Sport I had even changed the title of the issue.
Am sorry for the confusion.

**Comment by PopeyeTheSai10r** [comment]
Ok, The EPG info for CosmoteCinema2HD.gr still being pulled but I think I know what that issue is.

The database name is "Cosmote Cinema 2HD" with channel id "CosmoteCinema2HD.gr". 
While the cosmote.gr_gr.channels.xml file have it as "Cosmote Cinema 2 HD".

**Comment by johntaxmi** [comment]
Your first link now actually works.
Sadly I am not able (at least for now) to check if the second one has the EPG or not as my program have cache so even though if the second link does not work I am still able to see the EPG normally.

But like i said before the first link works perfectly for all Cosmote TV channels.
The only Cosmote channel that i am not able to see is **Cosmote Series**, even though you have **Cosmote Series Marathon**, there is a different channel with name **Cosmote Series**, just **without** the word **Marathon**.
Am not sure if you are able to add it aswell.

I also have an other suggestion about adding the NOVA TV channels an other greek multi channel thing.
Here is the program [Nova TV](https://www.novasports.gr/tv-program/)
They have Nova Sports 1/2/3/4/5/6 and also Nova Sports Prime/News/Start

I would really appriciate if you could add them aswell!
Thanks in advanced!
Ask me any other question you may have for your testing about cosmote cinema 2, I would be more than happy to assist you!

**Comment by PopeyeTheSai10r** [comment]
Hello @johntaxmi, I fixed Cosmote Cinema 2HD (CosmoteCinema2HD.gr) #945  and added Cosmote Series (CosmoteSeries.gr) #946. I think we can consider the original request as completed at this point. 

I would recommend opening a new ticket for Nova Sports and others Nova channels since that will be using a different source. Not sure if this will help you or not but the information for some of the Nova channels is already available at https://iptv-org.github.io/epg/guides/cy/novacyprus.com.epg.xml.

**Comment by johntaxmi** [comment]
Appriciate your help for making the pull requests.

Indeed those Nova channels which you mentioned are those that I need but sadly not only there are many channels missing but also they are in a different file (At country Cyprus).
I dont really know why they are like that as they greek channels and not Cyprus.

I will open a new ticket for my suggestion about adding all the Novasports channels.
Thanks again, have a nice day!
