### ISSUE TITLE
Fix: Adult Swim East have the wrong EPG

### ISSUE THREAD

**Issue by K-Lys514** [iptv-org/epg#968]
### Describe your issue

I have the US playlist from your other repo and since the last week, Adult Swim East have the EPG from a Mexican sport channel. I've looked at the playlist and adult swim have the right channel code (AdultSwimEast.us).

**Comment by PopeyeTheSai10r** [comment]
Hello @K-Lys514, It looks like the source no longer have the station listed in the USA channel groups. The station is still available for Canada at this time.

**Comment by K-Lys514** [comment]
Hi, sorry i might have say it in a bad way as english isn't my language. What i want to say is the epg that come in the us playlist from iptv seems to have being mixed with Adrenalina Sports Network, even if i add an epg from an other source like the one from cartoon network it's get stuck with Adrenalina Sports Network programming in Kodi even with a new installation so i ask myself if it's come from here as you seem to provide epg for the us playlist.
