### ISSUE TITLE
Fix: changing for musor.tv (Hungary)

### ISSUE THREAD

**Issue by sirjohn771103** [iptv-org/epg#969]
### Describe your issue

Please, delete these channels. They are out from Hungary.
DigiSport1Hungary.hu
DigiSport2Hungary.hu
DigiSport3Hungary.hu

Please, pick up this new channel: Match4
[https://musor.tv/mai/tvmusor/MATCH4](url)

Thank you.

**Comment by PopeyeTheSai10r** [comment]
Match4 is not in the channels database.

You can follow [this guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md) and submit a pull request to get it added. Once added contributors should be able to add the EPG for it.

**Comment by freearhey** [comment]
> Please, delete these channels. They are out from Hungary.

The guide can contain more than just Hungarian channels.

> Please, pick up this new channel: Match4

Added in https://github.com/iptv-org/epg/commit/5f458f944e97088c3b3095edf99e1a517cceb93f
