### ISSUE TITLE
Optus Sports -  Australia 

### ISSUE THREAD

**Issue by Dr3sdan** [iptv-org/epg#983]
Optus Sports epg seems to have disappeared from the Australian EPG.

Anyway to update it?

**Comment by freearhey** [comment]
Could you be more specific about which guide you're talking about?

**Comment by Dr3sdan** [comment]
The epg guide to Optus Sports (from Australia) was on https://iptv-org.github.io/epg/guides/au/ but has seemingly disappeared.

**Comment by freearhey** [comment]
I'm sorry, but I can't help you until it's clear which [site](https://github.com/iptv-org/epg/tree/master/sites) we're talking about.
