### ISSUE TITLE
Fix: Astro.my.com don't seem to work anymore

### ISSUE THREAD

**Issue by Krozbit** [iptv-org/epg#984]
### Describe your issue

Astro.my.com don't seem to work anymore.
Adding it as an epg xml doesn't create any epg
Many thanks for whoever can look into it

**Comment by RevGear** [comment]
https://iptv-org.github.io/epg/guides/my/astro.com.my.epg.xml
Seems to load ok. Was it a specific channel that was missing?

**Comment by freearhey** [comment]
It works for me too:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/7253922/186520278-5d69ae36-55f3-49c0-ab62-575321b7a314.png">
